function HTMLColors() {
    var colors = [];
colors.push('lightslategrey');
colors.push('darkviolet');
colors.push('cyan');
colors.push('darkslateblue');
colors.push('bisque');
colors.push('lightgrey');
colors.push('khaki');
colors.push('darkgray');
colors.push('saddlebrown');
colors.push('blanchedalmond');
colors.push('darkblue');
colors.push('lightcoral');
colors.push('orangered');
colors.push('moccasin');
colors.push('azure');
colors.push('lightgoldenrodyellow');
colors.push('skyblue');
colors.push('deepskyblue');
colors.push('chartreuse');
colors.push('mediumpurple');
colors.push('lightyellow');
colors.push('violet');
colors.push('palevioletred');
colors.push('dimgrey');
colors.push('rosybrown');
colors.push('honeydew');
colors.push('mediumblue');
colors.push('darkseagreen');
colors.push('limegreen');
colors.push('paleturquoise');
colors.push('mediumorchid');
colors.push('burlywood');
colors.push('silver');
colors.push('papayawhip');
colors.push('chocolate');
colors.push('lightsteelblue');
colors.push('pink');
colors.push('darkgreen');
colors.push('sienna');
colors.push('seashell');
colors.push('thistle');
colors.push('yellow');
colors.push('lightseagreen');
colors.push('cornsilk');
colors.push('blueviolet');
colors.push('tomato');
colors.push('cornflowerblue');
colors.push('sandybrown');
colors.push('gold');
colors.push('springgreen');
colors.push('gray');
colors.push('slategrey');
colors.push('mediumvioletred');
colors.push('crimson');
colors.push('darkcyan');
colors.push('ivory');
colors.push('darkmagenta');
colors.push('wheat');
colors.push('indianred');
colors.push('darkorchid');
colors.push('whitesmoke');
colors.push('mintcream');
colors.push('lightpink');
colors.push('black');
colors.push('teal');
colors.push('cadetblue');
colors.push('beige');
colors.push('darkkhaki');
colors.push('blue');
colors.push('darkslategray');
colors.push('royalblue');
colors.push('seagreen');
colors.push('purple');
colors.push('orchid');
colors.push('forestgreen');
colors.push('darksalmon');
colors.push('palegreen');
colors.push('navy');
colors.push('lightslategray');
colors.push('rebeccapurple');
colors.push('greenyellow');
colors.push('red');
colors.push('aqua');
colors.push('white');
colors.push('dodgerblue');
colors.push('lightblue');
colors.push('olive');
colors.push('coral');
colors.push('peachpuff');
colors.push('darkolivegreen');
colors.push('darkturquoise');
colors.push('darkgrey');
colors.push('lavender');
colors.push('lightgray');
colors.push('gainsboro');
colors.push('tan');
colors.push('plum');
colors.push('midnightblue');
colors.push('powderblue');
colors.push('dimgray');
colors.push('lemonchiffon');
colors.push('salmon');
colors.push('lightgreen');
colors.push('brown');
colors.push('goldenrod');
colors.push('steelblue');
colors.push('lightsalmon');
colors.push('darkred');
colors.push('snow');
colors.push('olivedrab');
colors.push('yellowgreen');
colors.push('indigo');
colors.push('lawngreen');
colors.push('magenta');
colors.push('aquamarine');
colors.push('floralwhite');
colors.push('antiquewhite');
colors.push('hotpink');
colors.push('turquoise');
colors.push('peru');
colors.push('fuchsia');
colors.push('firebrick');
colors.push('aliceblue');
colors.push('darkgoldenrod');
colors.push('navajowhite');
colors.push('lavenderblush');
colors.push('mediumspringgreen');
colors.push('slategray');
colors.push('mistyrose');
colors.push('linen');
colors.push('darkorange');
colors.push('slateblue');
colors.push('lightcyan');
colors.push('lightskyblue');
colors.push('mediumseagreen');
colors.push('mediumturquoise');
colors.push('deeppink');
colors.push('ghostwhite');
colors.push('green');
colors.push('lime');
colors.push('mediumaquamarine');
colors.push('oldlace');
colors.push('grey');
colors.push('orange');
colors.push('darkslategrey');
colors.push('mediumslateblue');
colors.push('maroon');
colors.push('palegoldenrod');
return colors;
}

function HTMLColorsMap() {
    var colors = new Object();
colors.lightslategrey = '#778899';
colors.darkviolet = '#9400D3';
colors.cyan = '#00FFFF';
colors.darkslateblue = '#483D8B';
colors.bisque = '#FFE4C4';
colors.lightgrey = '#D3D3D3';
colors.khaki = '#F0E68C';
colors.darkgray = '#A9A9A9';
colors.saddlebrown = '#8B4513';
colors.blanchedalmond = '#FFEBCD';
colors.darkblue = '#00008B';
colors.lightcoral = '#F08080';
colors.orangered = '#FF4500';
colors.moccasin = '#FFE4B5';
colors.azure = '#F0FFFF';
colors.lightgoldenrodyellow = '#FAFAD2';
colors.skyblue = '#87CEEB';
colors.deepskyblue = '#00BFFF';
colors.chartreuse = '#7FFF00';
colors.mediumpurple = '#9370DB';
colors.lightyellow = '#FFFFE0';
colors.violet = '#EE82EE';
colors.palevioletred = '#DB7093';
colors.dimgrey = '#696969';
colors.rosybrown = '#BC8F8F';
colors.honeydew = '#F0FFF0';
colors.mediumblue = '#0000CD';
colors.darkseagreen = '#8FBC8F';
colors.limegreen = '#32CD32';
colors.paleturquoise = '#AFEEEE';
colors.mediumorchid = '#BA55D3';
colors.burlywood = '#DEB887';
colors.silver = '#C0C0C0';
colors.papayawhip = '#FFEFD5';
colors.chocolate = '#D2691E';
colors.lightsteelblue = '#B0C4DE';
colors.pink = '#FFC0CB';
colors.darkgreen = '#006400';
colors.sienna = '#A0522D';
colors.seashell = '#FFF5EE';
colors.thistle = '#D8BFD8';
colors.yellow = '#FFFF00';
colors.lightseagreen = '#20B2AA';
colors.cornsilk = '#FFF8DC';
colors.blueviolet = '#8A2BE2';
colors.tomato = '#FF6347';
colors.cornflowerblue = '#6495ED';
colors.sandybrown = '#F4A460';
colors.gold = '#FFD700';
colors.springgreen = '#00FF7F';
colors.gray = '#808080';
colors.slategrey = '#708090';
colors.mediumvioletred = '#C71585';
colors.crimson = '#DC143C';
colors.darkcyan = '#008B8B';
colors.ivory = '#FFFFF0';
colors.darkmagenta = '#8B008B';
colors.wheat = '#F5DEB3';
colors.indianred = '#CD5C5C';
colors.darkorchid = '#9932CC';
colors.whitesmoke = '#F5F5F5';
colors.mintcream = '#F5FFFA';
colors.lightpink = '#FFB6C1';
colors.black = '#000000';
colors.teal = '#008080';
colors.cadetblue = '#5F9EA0';
colors.beige = '#F5F5DC';
colors.darkkhaki = '#BDB76B';
colors.blue = '#0000FF';
colors.darkslategray = '#2F4F4F';
colors.royalblue = '#4169E1';
colors.seagreen = '#2E8B57';
colors.purple = '#800080';
colors.orchid = '#DA70D6';
colors.forestgreen = '#228B22';
colors.darksalmon = '#E9967A';
colors.palegreen = '#98FB98';
colors.navy = '#000080';
colors.lightslategray = '#778899';
colors.rebeccapurple = '#663399';
colors.greenyellow = '#ADFF2F';
colors.red = '#FF0000';
colors.aqua = '#00FFFF';
colors.white = '#FFFFFF';
colors.dodgerblue = '#1E90FF';
colors.lightblue = '#ADD8E6';
colors.olive = '#808000';
colors.coral = '#FF7F50';
colors.peachpuff = '#FFDAB9';
colors.darkolivegreen = '#556B2F';
colors.darkturquoise = '#00CED1';
colors.darkgrey = '#A9A9A9';
colors.lavender = '#E6E6FA';
colors.lightgray = '#D3D3D3';
colors.gainsboro = '#DCDCDC';
colors.tan = '#D2B48C';
colors.plum = '#DDA0DD';
colors.midnightblue = '#191970';
colors.powderblue = '#B0E0E6';
colors.dimgray = '#696969';
colors.lemonchiffon = '#FFFACD';
colors.salmon = '#FA8072';
colors.lightgreen = '#90EE90';
colors.brown = '#A52A2A';
colors.goldenrod = '#DAA520';
colors.steelblue = '#4682B4';
colors.lightsalmon = '#FFA07A';
colors.darkred = '#8B0000';
colors.snow = '#FFFAFA';
colors.olivedrab = '#6B8E23';
colors.yellowgreen = '#9ACD32';
colors.indigo = '#4B0082';
colors.lawngreen = '#7CFC00';
colors.magenta = '#FF00FF';
colors.aquamarine = '#7FFFD4';
colors.floralwhite = '#FFFAF0';
colors.antiquewhite = '#FAEBD7';
colors.hotpink = '#FF69B4';
colors.turquoise = '#40E0D0';
colors.peru = '#CD853F';
colors.fuchsia = '#FF00FF';
colors.firebrick = '#B22222';
colors.aliceblue = '#F0F8FF';
colors.darkgoldenrod = '#B8860B';
colors.navajowhite = '#FFDEAD';
colors.lavenderblush = '#FFF0F5';
colors.mediumspringgreen = '#00FA9A';
colors.slategray = '#708090';
colors.mistyrose = '#FFE4E1';
colors.linen = '#FAF0E6';
colors.darkorange = '#FF8C00';
colors.slateblue = '#6A5ACD';
colors.lightcyan = '#E0FFFF';
colors.lightskyblue = '#87CEFA';
colors.mediumseagreen = '#3CB371';
colors.mediumturquoise = '#48D1CC';
colors.deeppink = '#FF1493';
colors.ghostwhite = '#F8F8FF';
colors.green = '#008000';
colors.lime = '#00FF00';
colors.mediumaquamarine = '#66CDAA';
colors.oldlace = '#FDF5E6';
colors.grey = '#808080';
colors.orange = '#FFA500';
colors.darkslategrey = '#2F4F4F';
colors.mediumslateblue = '#7B68EE';
colors.maroon = '#800000';
colors.palegoldenrod = '#EEE8AA';
return colors;
}
