package b4j.example;


import anywheresoftware.b4a.BA;

public class modautocomplete extends Object{
public static modautocomplete mostCurrent = new modautocomplete();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.modautocomplete", null);
		ba.loadHtSubs(modautocomplete.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.modautocomplete", ba);
		}
	}
    public static Class<?> getObject() {
		return modautocomplete.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static int _descriptionlimit = 0;
public static com.ab.banano.BANano _banano = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcalendar _modcalendar = null;
public static b4j.example.modcard _modcard = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatatable _moddatatable = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddesign _moddesign = null;
public static b4j.example.modexpansionpanels _modexpansionpanels = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modgrid _modgrid = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimeline _modtimeline = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modtreeview _modtreeview = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _btnclear_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 213;BA.debugLine="Sub btnClear_click(e As BANanoEvent)";
 //BA.debugLineNum = 214;BA.debugLine="vm.SetStateSingle(\"model\", Null)";
_vm._setstatesingle /*b4j.example.bananovm*/ ("model",anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 215;BA.debugLine="End Sub";
return "";
}
public static String  _btnediting_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 169;BA.debugLine="Sub btnEditing_click(e As BANanoEvent)";
 //BA.debugLineNum = 170;BA.debugLine="vm.ToggleState(\"isEditing\")";
_vm._togglestate /*b4j.example.bananovm*/ ("isEditing");
 //BA.debugLineNum = 171;BA.debugLine="End Sub";
return "";
}
public static String  _btnsaveprofile_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 164;BA.debugLine="Sub btnSaveProfile_click(e As BANanoEvent)";
 //BA.debugLineNum = 165;BA.debugLine="vm.ToggleState(\"isEditing\")";
_vm._togglestate /*b4j.example.bananovm*/ ("isEditing");
 //BA.debugLineNum = 166;BA.debugLine="vm.SetStateSingle(\"hasSaved\", \"True\")";
_vm._setstatesingle /*b4j.example.bananovm*/ ("hasSaved",(Object)("True"));
 //BA.debugLineNum = 167;BA.debugLine="End Sub";
return "";
}
public static b4j.example.vmcard  _card_1() throws Exception{
b4j.example.vmcard _card1 = null;
b4j.example.vmlabel _lblnote = null;
b4j.example.vmselect _ac = null;
b4j.example.vmcardtext _ct = null;
b4j.example.vmdivider _dvd1 = null;
b4j.example.vmexpandtransition _et = null;
b4j.example.vmlist _sl = null;
b4j.example.vmbutton _btnclear = null;
 //BA.debugLineNum = 173;BA.debugLine="Sub Card_1 As VMCard";
 //BA.debugLineNum = 174;BA.debugLine="Dim Card1 As VMCard = vm.CreateCard(\"card1\", Me)";
_card1 = _vm._createcard /*b4j.example.vmcard*/ ("card1",modautocomplete.getObject());
 //BA.debugLineNum = 175;BA.debugLine="Card1.SetColorIntensity(vm.COLOR_RED, vm.INTENSIT";
_card1._setcolorintensity /*b4j.example.vmcard*/ (_vm._color_red /*String*/ ,_vm._intensity_lighten2 /*String*/ )._setdark /*b4j.example.vmcard*/ (anywheresoftware.b4a.keywords.Common.True)._settext /*b4j.example.vmcard*/ ((Object)("Search for Public APIs"))._addclass /*b4j.example.vmcard*/ ("headline");
 //BA.debugLineNum = 177;BA.debugLine="Dim lblNote As VMLabel = vm.CreateLabel(\"\")";
_lblnote = _vm._createlabel /*b4j.example.vmlabel*/ ("");
 //BA.debugLineNum = 178;BA.debugLine="lblNote.SetText(\"Explore hundreds of free API's r";
_lblnote._settext /*b4j.example.vmlabel*/ ("Explore hundreds of free API's ready for consumption! For more information visit{NBSP}");
 //BA.debugLineNum = 179;BA.debugLine="lblNote.AddHyperLink(\"this Github repository\", \"h";
_lblnote._addhyperlink /*b4j.example.vmlabel*/ ("this Github repository","https://github.com/toddmotto/public-apis");
 //BA.debugLineNum = 180;BA.debugLine="Card1.Text.SetText(lblNote.ToString)";
_card1._text /*b4j.example.vmcardtext*/ ._settext /*b4j.example.vmcardtext*/ (_lblnote._tostring /*String*/ ());
 //BA.debugLineNum = 182;BA.debugLine="Dim ac As VMSelect = vm.CreateSelect(\"ac1\", Me)";
_ac = _vm._createselect /*b4j.example.vmselect*/ ("ac1",modautocomplete.getObject());
 //BA.debugLineNum = 183;BA.debugLine="ac.SetVModel(\"model\")";
_ac._setvmodel /*b4j.example.vmselect*/ ("model");
 //BA.debugLineNum = 184;BA.debugLine="ac.SetItems(\"itemsa\")";
_ac._setitems /*b4j.example.vmselect*/ ("itemsa");
 //BA.debugLineNum = 185;BA.debugLine="ac.SetLoading(\"isloading\")";
_ac._setloading /*b4j.example.vmselect*/ (BA.ObjectToBoolean("isloading"));
 //BA.debugLineNum = 186;BA.debugLine="ac.SetSearchInput(\"search\")";
_ac._setsearchinput /*b4j.example.vmselect*/ (BA.ObjectToBoolean("search"));
 //BA.debugLineNum = 187;BA.debugLine="ac.SetColor(\"white\").SetHideNoData(True).SetHideS";
_ac._setcolor /*b4j.example.vmselect*/ ("white")._sethidenodata /*b4j.example.vmselect*/ (anywheresoftware.b4a.keywords.Common.True)._sethideselected /*b4j.example.vmselect*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 188;BA.debugLine="ac.SetItemText(\"Description\").SetItemValue(\"API\")";
_ac._setitemtext /*b4j.example.vmselect*/ ("Description")._setitemvalue /*b4j.example.vmselect*/ ("API")._setlabel /*b4j.example.vmselect*/ ("Public APIs");
 //BA.debugLineNum = 189;BA.debugLine="ac.SetPlaceholder(\"Start typing to search\").SetPr";
_ac._setplaceholder /*b4j.example.vmselect*/ ("Start typing to search")._setprependicon /*b4j.example.vmselect*/ ("mdi-database-search");
 //BA.debugLineNum = 190;BA.debugLine="ac.SetReturnObject(True)";
_ac._setreturnobject /*b4j.example.vmselect*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 192;BA.debugLine="Dim ct As VMCardText = vm.CreateCardText(\"ct1\", M";
_ct = _vm._createcardtext /*b4j.example.vmcardtext*/ ("ct1",modautocomplete.getObject());
 //BA.debugLineNum = 193;BA.debugLine="ct.SetText(ac.ToString)";
_ct._settext /*b4j.example.vmcardtext*/ (_ac._tostring /*String*/ ());
 //BA.debugLineNum = 195;BA.debugLine="Card1.AddStuff(ct.tostring)";
_card1._addstuff /*b4j.example.vmcard*/ (_ct._tostring /*String*/ ());
 //BA.debugLineNum = 196;BA.debugLine="Dim dvd1 As VMDivider = vm.CreateDivider";
_dvd1 = _vm._createdivider /*b4j.example.vmdivider*/ ();
 //BA.debugLineNum = 197;BA.debugLine="Card1.AddStuff(dvd1.ToString)";
_card1._addstuff /*b4j.example.vmcard*/ (_dvd1._tostring /*String*/ ());
 //BA.debugLineNum = 198;BA.debugLine="Dim et As VMExpandTransition = vm.CreateExpandTra";
_et = _vm._createexpandtransition /*b4j.example.vmexpandtransition*/ ("et1",modautocomplete.getObject());
 //BA.debugLineNum = 200;BA.debugLine="Dim sl As VMList = vm.CreateList(\"sl1\", Me).SetVI";
_sl = _vm._createlist /*b4j.example.vmlist*/ ("sl1",modautocomplete.getObject())._setvif /*b4j.example.vmlist*/ ("model")._setcolorintensity /*b4j.example.vmlist*/ (_vm._color_red /*String*/ ,_vm._intensity_lighten3 /*String*/ );
 //BA.debugLineNum = 201;BA.debugLine="sl.SetDataSource(\"fields\", \"\", \"\", \"\", \"key\", \"va";
_sl._setdatasource /*b4j.example.vmlist*/ ("fields","","","","key","value","");
 //BA.debugLineNum = 202;BA.debugLine="sl.Pop(et.ExpandTransition)";
_sl._pop /*String*/ (_et._expandtransition /*b4j.example.vmelement*/ );
 //BA.debugLineNum = 204;BA.debugLine="Card1.AddStuff(et.ToString)";
_card1._addstuff /*b4j.example.vmcard*/ (_et._tostring /*String*/ ());
 //BA.debugLineNum = 206;BA.debugLine="Card1.Actions.AddSpacer";
_card1._actions /*b4j.example.vmcardactions*/ ._addspacer /*b4j.example.vmcardactions*/ ();
 //BA.debugLineNum = 208;BA.debugLine="Dim btnClear As VMButton = vm.CreateButton(\"btnCl";
_btnclear = _vm._createbutton /*b4j.example.vmbutton*/ ("btnClear",modautocomplete.getObject())._setlabel /*b4j.example.vmbutton*/ ("Clear");
 //BA.debugLineNum = 209;BA.debugLine="Card1.Actions.AddButton(btnClear)";
_card1._actions /*b4j.example.vmcardactions*/ ._addbutton /*b4j.example.vmcardactions*/ (_btnclear);
 //BA.debugLineNum = 210;BA.debugLine="Return Card1";
if (true) return _card1;
 //BA.debugLineNum = 211;BA.debugLine="End Sub";
return null;
}
public static b4j.example.vmcard  _card_2() throws Exception{
anywheresoftware.b4a.objects.collections.List _lst = null;
b4j.example.vmcard _card = null;
b4j.example.vmbutton _btn = null;
b4j.example.vmtextfield _txtname = null;
b4j.example.vmselect _txtac = null;
b4j.example.vmbutton _btn1 = null;
b4j.example.vmsnackbar _sb1 = null;
 //BA.debugLineNum = 102;BA.debugLine="Sub Card_2 As VMCard";
 //BA.debugLineNum = 104;BA.debugLine="vm.SetData(\"hasSaved\", False)";
_vm._setdata /*b4j.example.bananovm*/ ("hasSaved",(Object)(anywheresoftware.b4a.keywords.Common.False));
 //BA.debugLineNum = 105;BA.debugLine="vm.SetData(\"isEditing\", Null)";
_vm._setdata /*b4j.example.bananovm*/ ("isEditing",anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 106;BA.debugLine="vm.SetData(\"model1\", \"Null\")";
_vm._setdata /*b4j.example.bananovm*/ ("model1",(Object)("Null"));
 //BA.debugLineNum = 108;BA.debugLine="Dim lst As List";
_lst = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 109;BA.debugLine="lst.Initialize";
_lst.Initialize();
 //BA.debugLineNum = 110;BA.debugLine="lst.Add(CreateMap(\"name\": \"Florida\", \"abbr\": \"FL\"";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("Florida"),(Object)("abbr"),(Object)("FL"),(Object)("id"),(Object)("1")}).getObject()));
 //BA.debugLineNum = 111;BA.debugLine="lst.Add(CreateMap(\"name\": \"Georgia\", \"abbr\": \"GA\"";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("Georgia"),(Object)("abbr"),(Object)("GA"),(Object)("id"),(Object)("2")}).getObject()));
 //BA.debugLineNum = 112;BA.debugLine="lst.Add(CreateMap(\"name\": \"Nebraska\", \"abbr\": \"NE";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("Nebraska"),(Object)("abbr"),(Object)("NE"),(Object)("id"),(Object)("3")}).getObject()));
 //BA.debugLineNum = 113;BA.debugLine="lst.Add(CreateMap(\"name\": \"California\", \"abbr\": \"";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("California"),(Object)("abbr"),(Object)("CA"),(Object)("id"),(Object)("4")}).getObject()));
 //BA.debugLineNum = 114;BA.debugLine="lst.Add(CreateMap(\"name\": \"New York\", \"abbr\": \"NY";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("New York"),(Object)("abbr"),(Object)("NY"),(Object)("id"),(Object)("5")}).getObject()));
 //BA.debugLineNum = 115;BA.debugLine="vm.SetData(\"states1\", lst)";
_vm._setdata /*b4j.example.bananovm*/ ("states1",(Object)(_lst.getObject()));
 //BA.debugLineNum = 117;BA.debugLine="Dim Card As VMCard = vm.CreateCard(\"card2\", Me)";
_card = _vm._createcard /*b4j.example.vmcard*/ ("card2",modautocomplete.getObject());
 //BA.debugLineNum = 118;BA.debugLine="Card.SetColorIntensity(vm.COLOR_PURPLE, vm.INTENS";
_card._setcolorintensity /*b4j.example.vmcard*/ (_vm._color_purple /*String*/ ,_vm._intensity_lighten1 /*String*/ )._setdark /*b4j.example.vmcard*/ (anywheresoftware.b4a.keywords.Common.True)._addclass /*b4j.example.vmcard*/ ("overflow-hidden");
 //BA.debugLineNum = 119;BA.debugLine="Card.ToolBar.SetFlat(True).SetColor(\"purple\")";
_card._toolbar /*b4j.example.vmtoolbar*/ ._setflat /*b4j.example.vmtoolbar*/ (anywheresoftware.b4a.keywords.Common.True)._setcolor /*b4j.example.vmtoolbar*/ ("purple");
 //BA.debugLineNum = 121;BA.debugLine="Card.ToolBar.AddIcon(\"\",\"mdi-account\", \"\", \"\")";
_card._toolbar /*b4j.example.vmtoolbar*/ ._addicon /*b4j.example.vmtoolbar*/ ("","mdi-account","","");
 //BA.debugLineNum = 122;BA.debugLine="Card.ToolBar.AddTitle(\"User Profile\", \"font-weigh";
_card._toolbar /*b4j.example.vmtoolbar*/ ._addtitle /*b4j.example.vmtoolbar*/ ("User Profile","font-weight-light");
 //BA.debugLineNum = 123;BA.debugLine="Card.ToolBar.AddSpacer";
_card._toolbar /*b4j.example.vmtoolbar*/ ._addspacer /*b4j.example.vmtoolbar*/ ();
 //BA.debugLineNum = 125;BA.debugLine="Dim btn As VMButton = vm.CreateButton(\"btnEditing";
_btn = _vm._createbutton /*b4j.example.vmbutton*/ ("btnEditing",modautocomplete.getObject())._setcolorintensity /*b4j.example.vmbutton*/ (_vm._color_purple /*String*/ ,_vm._intensity_darken3 /*String*/ );
 //BA.debugLineNum = 126;BA.debugLine="btn.SetAttributes(Array(\"fab\", \"small\"))";
_btn._setattributes /*b4j.example.vmbutton*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("fab"),(Object)("small")}));
 //BA.debugLineNum = 127;BA.debugLine="btn.SetToggleIcons(\"isEditing\", \"mdi-close\", \"mdi";
_btn._settoggleicons /*b4j.example.vmbutton*/ ("isEditing","mdi-close","mdi-pencil");
 //BA.debugLineNum = 128;BA.debugLine="Card.ToolBar.AddButton(btn)";
_card._toolbar /*b4j.example.vmtoolbar*/ ._addbutton /*b4j.example.vmtoolbar*/ (_btn);
 //BA.debugLineNum = 130;BA.debugLine="Dim txtName As VMTextField = vm.CreateTextField(\"";
_txtname = _vm._createtextfield /*b4j.example.vmtextfield*/ ("txtName",modautocomplete.getObject())._setcolor /*b4j.example.vmtextfield*/ ("white")._setlabel /*b4j.example.vmtextfield*/ ("Name")._bind /*b4j.example.vmtextfield*/ (":disabled","!isEditing");
 //BA.debugLineNum = 131;BA.debugLine="Card.Text.AddContent(txtName.tostring)";
_card._text /*b4j.example.vmcardtext*/ ._addcontent /*b4j.example.vmcardtext*/ (_txtname._tostring /*String*/ ());
 //BA.debugLineNum = 133;BA.debugLine="Dim txtac As VMSelect = vm.CreateSelect(\"txtac\",";
_txtac = _vm._createselect /*b4j.example.vmselect*/ ("txtac",modautocomplete.getObject())._bind /*b4j.example.vmselect*/ (":disabled","!isEditing")._bind /*b4j.example.vmselect*/ (":items","states1");
 //BA.debugLineNum = 135;BA.debugLine="txtac.SetColor(\"white\").SetItemText(\"name\").SetLa";
_txtac._setcolor /*b4j.example.vmselect*/ ("white")._setitemtext /*b4j.example.vmselect*/ ("name")._setlabel /*b4j.example.vmselect*/ ("State");
 //BA.debugLineNum = 136;BA.debugLine="Card.Text.AddContent(txtac.ToString)";
_card._text /*b4j.example.vmcardtext*/ ._addcontent /*b4j.example.vmcardtext*/ (_txtac._tostring /*String*/ ());
 //BA.debugLineNum = 138;BA.debugLine="Card.Actions.AddSpacer";
_card._actions /*b4j.example.vmcardactions*/ ._addspacer /*b4j.example.vmcardactions*/ ();
 //BA.debugLineNum = 140;BA.debugLine="Dim btn1 As VMButton = vm.CreateButton(\"btnSavePr";
_btn1 = _vm._createbutton /*b4j.example.vmbutton*/ ("btnSaveProfile",modautocomplete.getObject())._setlabel /*b4j.example.vmbutton*/ ("Save")._setcolor /*b4j.example.vmbutton*/ ("success")._bind /*b4j.example.vmbutton*/ (":disabled","!isEditing");
 //BA.debugLineNum = 141;BA.debugLine="Card.Actions.AddButton(btn1)";
_card._actions /*b4j.example.vmcardactions*/ ._addbutton /*b4j.example.vmcardactions*/ (_btn1);
 //BA.debugLineNum = 143;BA.debugLine="Dim sb1 As VMSnackBar = vm.CreateSnackBar(\"sb1\",";
_sb1 = _vm._createsnackbar /*b4j.example.vmsnackbar*/ ("sb1",modautocomplete.getObject())._setvmodel /*b4j.example.vmsnackbar*/ ("hasSaved")._bind /*b4j.example.vmsnackbar*/ (":timeout","2000");
 //BA.debugLineNum = 144;BA.debugLine="sb1.SetAttributes(Array(\"absolute\", \"bottom\", \"le";
_sb1._setattributes /*b4j.example.vmsnackbar*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("absolute"),(Object)("bottom"),(Object)("left")}))._settext /*b4j.example.vmsnackbar*/ ("Your profile has been updated!");
 //BA.debugLineNum = 145;BA.debugLine="Card.AddExtraContent(sb1.ToString)";
_card._addextracontent /*b4j.example.vmcard*/ (_sb1._tostring /*String*/ ());
 //BA.debugLineNum = 147;BA.debugLine="Return Card";
if (true) return _card;
 //BA.debugLineNum = 148;BA.debugLine="End Sub";
return null;
}
public static b4j.example.vmcard  _card_3() throws Exception{
b4j.example.vmcard _card = null;
b4j.example.vmselect _ac1 = null;
b4j.example.vmselect _ac2 = null;
b4j.example.vmselect _ac3 = null;
 //BA.debugLineNum = 78;BA.debugLine="Sub Card_3 As VMCard	'";
 //BA.debugLineNum = 79;BA.debugLine="vm.SetData(\"value\", Null)";
_vm._setdata /*b4j.example.bananovm*/ ("value",anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 80;BA.debugLine="vm.SetData(\"items\", Array(\"foo\", \"bar\", \"fizz\", \"";
_vm._setdata /*b4j.example.bananovm*/ ("items",(Object)(new Object[]{(Object)("foo"),(Object)("bar"),(Object)("fizz"),(Object)("buzz")}));
 //BA.debugLineNum = 81;BA.debugLine="vm.SetData(\"values\", Array(\"foo\", \"bar\"))";
_vm._setdata /*b4j.example.bananovm*/ ("values",(Object)(new Object[]{(Object)("foo"),(Object)("bar")}));
 //BA.debugLineNum = 83;BA.debugLine="Dim Card As VMCard = vm.CreateCard(\"card3\", Me)";
_card = _vm._createcard /*b4j.example.vmcard*/ ("card3",modautocomplete.getObject());
 //BA.debugLineNum = 84;BA.debugLine="Card.Container.AddRows(1).AddColumns(3,12,12,12,1";
_card._container /*b4j.example.vmcontainer*/ ._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns /*b4j.example.vmcontainer*/ ((int) (3),(int) (12),(int) (12),(int) (12),(int) (12));
 //BA.debugLineNum = 86;BA.debugLine="Dim ac1 As VMSelect = vm.CreateAutoComplete(\"ac31";
_ac1 = _vm._createautocomplete /*b4j.example.vmselect*/ ("ac31",modautocomplete.getObject())._setvmodel /*b4j.example.vmselect*/ ("values")._bind /*b4j.example.vmselect*/ (":items","items");
 //BA.debugLineNum = 87;BA.debugLine="ac1.SetAttributes(Array(\"outlined\", \"dense\", \"chi";
_ac1._setattributes /*b4j.example.vmselect*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("outlined"),(Object)("dense"),(Object)("chips"),(Object)("small-chips"),(Object)("multiple")}))._setlabel /*b4j.example.vmselect*/ ("Outlined");
 //BA.debugLineNum = 88;BA.debugLine="Card.Container.AddComponent(1, 1, ac1.ToString)";
_card._container /*b4j.example.vmcontainer*/ ._addcomponent /*String*/ ((int) (1),(int) (1),_ac1._tostring /*String*/ ());
 //BA.debugLineNum = 90;BA.debugLine="Dim ac2 As VMSelect = vm.CreateAutoComplete(\"ac32";
_ac2 = _vm._createautocomplete /*b4j.example.vmselect*/ ("ac32",modautocomplete.getObject())._setvmodel /*b4j.example.vmselect*/ ("values")._bind /*b4j.example.vmselect*/ (":items","items");
 //BA.debugLineNum = 91;BA.debugLine="ac2.SetAttributes(Array(\"dense\", \"chips\", \"small-";
_ac2._setattributes /*b4j.example.vmselect*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("dense"),(Object)("chips"),(Object)("small-chips"),(Object)("multiple"),(Object)("solo")}))._setlabel /*b4j.example.vmselect*/ ("Solo");
 //BA.debugLineNum = 92;BA.debugLine="Card.Container.AddComponent(1, 2, ac2.ToString)";
_card._container /*b4j.example.vmcontainer*/ ._addcomponent /*String*/ ((int) (1),(int) (2),_ac2._tostring /*String*/ ());
 //BA.debugLineNum = 94;BA.debugLine="Dim ac3 As VMSelect = vm.CreateAutoComplete(\"ac33";
_ac3 = _vm._createautocomplete /*b4j.example.vmselect*/ ("ac33",modautocomplete.getObject())._setvmodel /*b4j.example.vmselect*/ ("values")._bind /*b4j.example.vmselect*/ (":items","items");
 //BA.debugLineNum = 95;BA.debugLine="ac3.SetAttributes(Array(\"dense\", \"filled\")).SetLa";
_ac3._setattributes /*b4j.example.vmselect*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("dense"),(Object)("filled")}))._setlabel /*b4j.example.vmselect*/ ("Filled");
 //BA.debugLineNum = 96;BA.debugLine="Card.Container.AddComponent(1, 3, ac3.ToString)";
_card._container /*b4j.example.vmcontainer*/ ._addcomponent /*String*/ ((int) (1),(int) (3),_ac3._tostring /*String*/ ());
 //BA.debugLineNum = 98;BA.debugLine="Return Card";
if (true) return _card;
 //BA.debugLineNum = 100;BA.debugLine="End Sub";
return null;
}
public static b4j.example.vmcard  _card_4() throws Exception{
b4j.example.vmcard _card = null;
b4j.example.vmtemplate _tmp = null;
b4j.example.vmprogresslinear _prg = null;
b4j.example.vmimage _img = null;
b4j.example.vmcontainer _cont = null;
b4j.example.vmmenu _mm = null;
b4j.example.vmtemplate _tmp1 = null;
b4j.example.vmbutton _btn = null;
 //BA.debugLineNum = 41;BA.debugLine="Sub Card_4 As VMCard";
 //BA.debugLineNum = 42;BA.debugLine="vm.SetData(\"isupdating\", False)";
_vm._setdata /*b4j.example.bananovm*/ ("isupdating",(Object)(anywheresoftware.b4a.keywords.Common.False));
 //BA.debugLineNum = 44;BA.debugLine="Dim Card As VMCard = vm.CreateCard(\"card4\", Me).S";
_card = _vm._createcard /*b4j.example.vmcard*/ ("card4",modautocomplete.getObject())._setcolorintensity /*b4j.example.vmcard*/ (_vm._color_bluegrey /*String*/ ,_vm._intensity_darken1 /*String*/ );
 //BA.debugLineNum = 45;BA.debugLine="Card.SetDark(True).Bind(\":loading\", \"isupdating\")";
_card._setdark /*b4j.example.vmcard*/ (anywheresoftware.b4a.keywords.Common.True)._bind /*b4j.example.vmcard*/ (":loading","isupdating");
 //BA.debugLineNum = 47;BA.debugLine="Dim tmp As VMTemplate = vm.CreateTemplate(\"t1\", M";
_tmp = _vm._createtemplate /*b4j.example.vmtemplate*/ ("t1",modautocomplete.getObject())._setslotprogress /*b4j.example.vmtemplate*/ ();
 //BA.debugLineNum = 49;BA.debugLine="Dim prg As VMProgressLinear = vm.CreateProgressLi";
_prg = _vm._createprogresslinear /*b4j.example.vmprogresslinear*/ ("prg1",modautocomplete.getObject())._setattributes /*b4j.example.vmprogresslinear*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("absolute"),(Object)("indeterminate")}));
 //BA.debugLineNum = 50;BA.debugLine="prg.SetColorIntensity(vm.COLOR_GREEN, vm.INTENSIT";
_prg._setcolorintensity /*b4j.example.vmprogresslinear*/ (_vm._color_green /*String*/ ,_vm._intensity_lighten3 /*String*/ )._setheight /*b4j.example.vmprogresslinear*/ ("4");
 //BA.debugLineNum = 51;BA.debugLine="prg.Pop(tmp.Template)";
_prg._pop /*String*/ (_tmp._template /*b4j.example.vmelement*/ );
 //BA.debugLineNum = 53;BA.debugLine="Card.AddComponent(tmp.ToString)";
_card._addcomponent /*b4j.example.vmcard*/ (_tmp._tostring /*String*/ ());
 //BA.debugLineNum = 55;BA.debugLine="Dim img As VMImage = vm.CreateImage(\"card4img\", M";
_img = _vm._createimage /*b4j.example.vmimage*/ ("card4img",modautocomplete.getObject())._setheight /*b4j.example.vmimage*/ (BA.NumberToString(200))._setvmodel /*b4j.example.vmimage*/ ("card4img","./assets/dark-beach.jpg");
 //BA.debugLineNum = 56;BA.debugLine="Card.AddComponent(img.tostring)";
_card._addcomponent /*b4j.example.vmcard*/ (_img._tostring /*String*/ ());
 //BA.debugLineNum = 58;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(\"car";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ ("card4cont",modautocomplete.getObject());
 //BA.debugLineNum = 59;BA.debugLine="cont.AddRows(1).AddColumns(1, 12, 12, 12, 12)";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns /*b4j.example.vmcontainer*/ ((int) (1),(int) (12),(int) (12),(int) (12),(int) (12));
 //BA.debugLineNum = 60;BA.debugLine="cont.AddClassRC(1, 1, Array(\"text-right\"))";
_cont._addclassrc /*b4j.example.vmcontainer*/ ((int) (1),(int) (1),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("text-right")}));
 //BA.debugLineNum = 62;BA.debugLine="Dim mm As VMMenu = vm.CreateMenu(\"mm\", Me).SetAtt";
_mm = _vm._createmenu /*b4j.example.vmmenu*/ ("mm",modautocomplete.getObject())._setattributes /*b4j.example.vmmenu*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("bottom"),(Object)("left")}))._setslideytransition /*b4j.example.vmmenu*/ ();
 //BA.debugLineNum = 64;BA.debugLine="Dim tmp1 As VMTemplate = vm.CreateTemplate(\"t2\",";
_tmp1 = _vm._createtemplate /*b4j.example.vmtemplate*/ ("t2",modautocomplete.getObject())._setslotactivatoron /*b4j.example.vmtemplate*/ ();
 //BA.debugLineNum = 65;BA.debugLine="Dim btn As VMButton = vm.CreateButton(\"btn2\", Me)";
_btn = _vm._createbutton /*b4j.example.vmbutton*/ ("btn2",modautocomplete.getObject())._setvon /*b4j.example.vmbutton*/ ("on")._seticonbutton /*b4j.example.vmbutton*/ ("mdi-dots-vertical");
 //BA.debugLineNum = 66;BA.debugLine="tmp1.AddComponent(btn.ToString)";
_tmp1._addcomponent /*b4j.example.vmtemplate*/ (_btn._tostring /*String*/ ());
 //BA.debugLineNum = 67;BA.debugLine="mm.AddComponent(tmp1.ToString)";
_mm._addcomponent /*b4j.example.vmmenu*/ (_tmp1._tostring /*String*/ ());
 //BA.debugLineNum = 68;BA.debugLine="cont.AddComponent(1, 1, mm.ToString)";
_cont._addcomponent /*String*/ ((int) (1),(int) (1),_mm._tostring /*String*/ ());
 //BA.debugLineNum = 70;BA.debugLine="img.AddComponent(cont.ToString)";
_img._addcomponent /*b4j.example.vmimage*/ (_cont._tostring /*String*/ ());
 //BA.debugLineNum = 72;BA.debugLine="Return Card";
if (true) return _card;
 //BA.debugLineNum = 74;BA.debugLine="End Sub";
return null;
}
public static String  _code() throws Exception{
b4j.example.vmcontainer _cont = null;
b4j.example.vmcard _card = null;
b4j.example.vmcard _card2 = null;
b4j.example.vmcard _card3 = null;
 //BA.debugLineNum = 12;BA.debugLine="Sub Code";
 //BA.debugLineNum = 13;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 15;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,modautocomplete.getObject());
 //BA.debugLineNum = 17;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 19;BA.debugLine="cont.addrows(5).AddColumns2x6";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (5))._addcolumns2x6 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 21;BA.debugLine="descriptionlimit = 60";
_descriptionlimit = (int) (60);
 //BA.debugLineNum = 22;BA.debugLine="Reset";
_reset();
 //BA.debugLineNum = 24;BA.debugLine="Dim Card As VMCard = Card_1";
_card = _card_1();
 //BA.debugLineNum = 25;BA.debugLine="Dim card2 As VMCard = Card_2";
_card2 = _card_2();
 //BA.debugLineNum = 26;BA.debugLine="Dim card3 As VMCard = Card_3";
_card3 = _card_3();
 //BA.debugLineNum = 29;BA.debugLine="cont.AddComponent(1, 1, Card.ToString)";
_cont._addcomponent /*String*/ ((int) (1),(int) (1),_card._tostring /*String*/ ());
 //BA.debugLineNum = 30;BA.debugLine="cont.AddComponent(1, 2, card2.ToString)";
_cont._addcomponent /*String*/ ((int) (1),(int) (2),_card2._tostring /*String*/ ());
 //BA.debugLineNum = 31;BA.debugLine="cont.AddComponent(2, 1, card3.ToString)";
_cont._addcomponent /*String*/ ((int) (2),(int) (1),_card3._tostring /*String*/ ());
 //BA.debugLineNum = 34;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 36;BA.debugLine="vm.SetWatch(\"search\", True, True, Me, \"SearchItem";
_vm._setwatch /*b4j.example.bananovm*/ ("search",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,modautocomplete.getObject(),"SearchItems");
 //BA.debugLineNum = 37;BA.debugLine="vm.SetWatch(\"model\", True, True, Me, \"ComputeFiel";
_vm._setwatch /*b4j.example.bananovm*/ ("model",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,modautocomplete.getObject(),"ComputeFields");
 //BA.debugLineNum = 38;BA.debugLine="vm.SetMethod(Me, \"customfilter\")";
_vm._setmethod /*b4j.example.bananovm*/ (modautocomplete.getObject(),"customfilter");
 //BA.debugLineNum = 39;BA.debugLine="End Sub";
return "";
}
public static anywheresoftware.b4a.objects.collections.List  _computefields() throws Exception{
anywheresoftware.b4a.objects.collections.List _fields = null;
anywheresoftware.b4a.objects.collections.Map _model = null;
String _k = "";
Object _v = null;
 //BA.debugLineNum = 226;BA.debugLine="Sub ComputeFields As List";
 //BA.debugLineNum = 227;BA.debugLine="Dim fields As List";
_fields = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 228;BA.debugLine="fields.Initialize";
_fields.Initialize();
 //BA.debugLineNum = 229;BA.debugLine="Dim model As Map = vm.GetState(\"model\",Null)";
_model = new anywheresoftware.b4a.objects.collections.Map();
_model = (anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(_vm._getstate /*Object*/ ("model",anywheresoftware.b4a.keywords.Common.Null)));
 //BA.debugLineNum = 230;BA.debugLine="If model = Null Then Return fields";
if (_model== null) { 
if (true) return _fields;};
 //BA.debugLineNum = 231;BA.debugLine="For Each k As String In model.Keys";
{
final anywheresoftware.b4a.BA.IterableList group5 = _model.Keys();
final int groupLen5 = group5.getSize()
;int index5 = 0;
;
for (; index5 < groupLen5;index5++){
_k = BA.ObjectToString(group5.Get(index5));
 //BA.debugLineNum = 232;BA.debugLine="Dim v As Object = model.Get(k)";
_v = _model.Get((Object)(_k));
 //BA.debugLineNum = 233;BA.debugLine="fields.Add(CreateMap(\"key\": v, \"value\":v))";
_fields.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("key"),_v,(Object)("value"),_v}).getObject()));
 }
};
 //BA.debugLineNum = 235;BA.debugLine="vm.SetStateSingle(\"fields\", fields)";
_vm._setstatesingle /*b4j.example.bananovm*/ ("fields",(Object)(_fields.getObject()));
 //BA.debugLineNum = 236;BA.debugLine="Return fields";
if (true) return _fields;
 //BA.debugLineNum = 237;BA.debugLine="End Sub";
return null;
}
public static boolean  _customfilter(anywheresoftware.b4a.objects.collections.Map _item,String _querytext,String _itemtext) throws Exception{
String _textone = "";
String _texttwo = "";
String _searchtext = "";
int _pos1 = 0;
int _pos2 = 0;
boolean _bres = false;
 //BA.debugLineNum = 150;BA.debugLine="Sub customfilter(item As Map, queryText As String,";
 //BA.debugLineNum = 151;BA.debugLine="Dim textOne As String = item.get(\"name\")";
_textone = BA.ObjectToString(_item.Get((Object)("name")));
 //BA.debugLineNum = 152;BA.debugLine="Dim textTwo As String = item.Get(\"abbr\")";
_texttwo = BA.ObjectToString(_item.Get((Object)("abbr")));
 //BA.debugLineNum = 153;BA.debugLine="Dim searchText As String = queryText.toLowerCase";
_searchtext = _querytext.toLowerCase();
 //BA.debugLineNum = 155;BA.debugLine="textOne = textOne.ToLowerCase";
_textone = _textone.toLowerCase();
 //BA.debugLineNum = 156;BA.debugLine="textTwo = textTwo.ToLowerCase";
_texttwo = _texttwo.toLowerCase();
 //BA.debugLineNum = 158;BA.debugLine="Dim pos1 As Int = textOne.indexof(searchText)";
_pos1 = _textone.indexOf(_searchtext);
 //BA.debugLineNum = 159;BA.debugLine="Dim pos2 As Int = textTwo.IndexOf(searchText)";
_pos2 = _texttwo.indexOf(_searchtext);
 //BA.debugLineNum = 160;BA.debugLine="Dim bres As Boolean = BANano.IIf(pos1 > -1, True,";
_bres = BA.ObjectToBoolean(_banano.IIf((Object)(_pos1>-1),(Object)(anywheresoftware.b4a.keywords.Common.True),(Object)(_pos2>-1)));
 //BA.debugLineNum = 161;BA.debugLine="Return bres";
if (true) return _bres;
 //BA.debugLineNum = 162;BA.debugLine="End Sub";
return false;
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 4;BA.debugLine="Public name As String = \"autocompleteCode\"";
_name = "autocompleteCode";
 //BA.debugLineNum = 5;BA.debugLine="Public title As String = \"Auto Complete\"";
_title = "Auto Complete";
 //BA.debugLineNum = 6;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 7;BA.debugLine="Private descriptionlimit As Int";
_descriptionlimit = 0;
 //BA.debugLineNum = 8;BA.debugLine="Private BANano As BANano 'ignore";
_banano = new com.ab.banano.BANano();
 //BA.debugLineNum = 9;BA.debugLine="End Sub";
return "";
}
public static String  _reset() throws Exception{
 //BA.debugLineNum = 217;BA.debugLine="Sub Reset";
 //BA.debugLineNum = 218;BA.debugLine="vm.SetStateSingle(\"descriptionlimit\", description";
_vm._setstatesingle /*b4j.example.bananovm*/ ("descriptionlimit",(Object)(_descriptionlimit));
 //BA.debugLineNum = 219;BA.debugLine="vm.SetStateSingle(\"isloading\",False)";
_vm._setstatesingle /*b4j.example.bananovm*/ ("isloading",(Object)(anywheresoftware.b4a.keywords.Common.False));
 //BA.debugLineNum = 220;BA.debugLine="vm.SetStateSingle(\"model\", Null)";
_vm._setstatesingle /*b4j.example.bananovm*/ ("model",anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 221;BA.debugLine="vm.SetStateSingle(\"search\", Null)";
_vm._setstatesingle /*b4j.example.bananovm*/ ("search",anywheresoftware.b4a.keywords.Common.Null);
 //BA.debugLineNum = 222;BA.debugLine="vm.SetStateSingle(\"fields\", Array())";
_vm._setstatesingle /*b4j.example.bananovm*/ ("fields",(Object)(new Object[]{}));
 //BA.debugLineNum = 223;BA.debugLine="vm.SetStateSingle(\"itemsa\", Array())";
_vm._setstatesingle /*b4j.example.bananovm*/ ("itemsa",(Object)(new Object[]{}));
 //BA.debugLineNum = 224;BA.debugLine="End Sub";
return "";
}
public static String  _searchitems(String _xval) throws Exception{
boolean _hasiw = false;
anywheresoftware.b4a.objects.collections.List _items = null;
boolean _isloading = false;
com.ab.banano.BANanoFetchResponse _response = null;
com.ab.banano.BANanoJSONParser _data = null;
com.ab.banano.BANanoJSONParser _error = null;
com.ab.banano.BANanoFetch _fetch1 = null;
anywheresoftware.b4a.objects.collections.Map _res = null;
long _count = 0L;
anywheresoftware.b4a.objects.collections.List _entries = null;
int _dl = 0;
anywheresoftware.b4a.objects.collections.Map _entry = null;
String _sdescription = "";
 //BA.debugLineNum = 240;BA.debugLine="Sub SearchItems(xval As String)";
 //BA.debugLineNum = 241;BA.debugLine="Dim hasIW As Boolean = BANano.CheckInternetConnec";
_hasiw = _banano.CheckInternetConnectionWait();
 //BA.debugLineNum = 242;BA.debugLine="If hasIW = False Then Return";
if (_hasiw==anywheresoftware.b4a.keywords.Common.False) { 
if (true) return "";};
 //BA.debugLineNum = 244;BA.debugLine="Dim items As List = vm.GetState(\"itemsa\", Array()";
_items = new anywheresoftware.b4a.objects.collections.List();
_items = (anywheresoftware.b4a.objects.collections.List) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.List(), (java.util.List)(_vm._getstate /*Object*/ ("itemsa",(Object)(new Object[]{}))));
 //BA.debugLineNum = 246;BA.debugLine="Dim isloading As Boolean = vm.GetState(\"isloading";
_isloading = BA.ObjectToBoolean(_vm._getstate /*Object*/ ("isloading",(Object)(anywheresoftware.b4a.keywords.Common.False)));
 //BA.debugLineNum = 248;BA.debugLine="If items.Size > 0 Then Return";
if (_items.getSize()>0) { 
if (true) return "";};
 //BA.debugLineNum = 250;BA.debugLine="If isloading Then Return";
if (_isloading) { 
if (true) return "";};
 //BA.debugLineNum = 252;BA.debugLine="vm.SetStateSingle(\"isloading\", True)";
_vm._setstatesingle /*b4j.example.bananovm*/ ("isloading",(Object)(anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 255;BA.debugLine="Dim Response As BANanoFetchResponse";
_response = new com.ab.banano.BANanoFetchResponse();
 //BA.debugLineNum = 256;BA.debugLine="Dim Data As BANanoJSONParser";
_data = new com.ab.banano.BANanoJSONParser();
 //BA.debugLineNum = 257;BA.debugLine="Dim Error As BANanoJSONParser";
_error = new com.ab.banano.BANanoJSONParser();
 //BA.debugLineNum = 259;BA.debugLine="Dim fetch1 As BANanoFetch";
_fetch1 = new com.ab.banano.BANanoFetch();
 //BA.debugLineNum = 261;BA.debugLine="fetch1.Initialize(\"https://api.publicapis.org/ent";
_fetch1.Initialize("https://api.publicapis.org/entries",(com.ab.banano.BANanoFetchOptions)(anywheresoftware.b4a.keywords.Common.Null));
 //BA.debugLineNum = 263;BA.debugLine="fetch1.Then(Response)";
_fetch1.Then((Object)(_response));
 //BA.debugLineNum = 265;BA.debugLine="fetch1.Return(Response.Json)";
_fetch1.Return(_response.Json());
 //BA.debugLineNum = 266;BA.debugLine="fetch1.Then(Data)";
_fetch1.Then((Object)(_data));
 //BA.debugLineNum = 267;BA.debugLine="Dim res As Map = Data.NextObject";
_res = new anywheresoftware.b4a.objects.collections.Map();
_res = _data.NextObject();
 //BA.debugLineNum = 268;BA.debugLine="Dim count As Long = res.Get(\"count\")";
_count = BA.ObjectToLongNumber(_res.Get((Object)("count")));
 //BA.debugLineNum = 269;BA.debugLine="Dim entries As List = res.Get(\"entries\")";
_entries = new anywheresoftware.b4a.objects.collections.List();
_entries = (anywheresoftware.b4a.objects.collections.List) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.List(), (java.util.List)(_res.Get((Object)("entries"))));
 //BA.debugLineNum = 271;BA.debugLine="Dim items As List";
_items = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 272;BA.debugLine="items.Initialize";
_items.Initialize();
 //BA.debugLineNum = 274;BA.debugLine="Dim dl As Int = vm.GetState(\"descriptionlimit\",d";
_dl = (int)(BA.ObjectToNumber(_vm._getstate /*Object*/ ("descriptionlimit",(Object)(_descriptionlimit))));
 //BA.debugLineNum = 276;BA.debugLine="For Each entry As Map In entries";
_entry = new anywheresoftware.b4a.objects.collections.Map();
{
final anywheresoftware.b4a.BA.IterableList group22 = _entries;
final int groupLen22 = group22.getSize()
;int index22 = 0;
;
for (; index22 < groupLen22;index22++){
_entry = (anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(group22.Get(index22)));
 //BA.debugLineNum = 277;BA.debugLine="Dim sDescription As String = entry.Get(\"Descrip";
_sdescription = BA.ObjectToString(_entry.Get((Object)("Description")));
 //BA.debugLineNum = 278;BA.debugLine="If sDescription.Length > descriptionlimit Then";
if (_sdescription.length()>_descriptionlimit) { 
 //BA.debugLineNum = 279;BA.debugLine="sDescription = vm.LeftString(sDescription, dl)";
_sdescription = _vm._leftstring /*String*/ (_sdescription,(long) (_dl))+"...";
 //BA.debugLineNum = 280;BA.debugLine="entry.Put(\"Description\", sDescription)";
_entry.Put((Object)("Description"),(Object)(_sdescription));
 };
 //BA.debugLineNum = 282;BA.debugLine="items.Add(entry)";
_items.Add((Object)(_entry.getObject()));
 }
};
 //BA.debugLineNum = 285;BA.debugLine="vm.SetStateSingle(\"itemsa\", items)";
_vm._setstatesingle /*b4j.example.bananovm*/ ("itemsa",(Object)(_items.getObject()));
 //BA.debugLineNum = 286;BA.debugLine="fetch1.Else(Error)";
_fetch1.Else((Object)(_error));
 //BA.debugLineNum = 287;BA.debugLine="Log(Error)";
anywheresoftware.b4a.keywords.Common.Log(BA.ObjectToString(_error));
 //BA.debugLineNum = 288;BA.debugLine="fetch1.Finally";
_fetch1.Finally();
 //BA.debugLineNum = 290;BA.debugLine="vm.SetStateSingle(\"isloading\", False)";
_vm._setstatesingle /*b4j.example.bananovm*/ ("isloading",(Object)(anywheresoftware.b4a.keywords.Common.False));
 //BA.debugLineNum = 291;BA.debugLine="fetch1.End";
_fetch1.End();
 //BA.debugLineNum = 292;BA.debugLine="End Sub";
return "";
}
}
