package b4j.example;


import anywheresoftware.b4a.BA;

public class modcard extends Object{
public static modcard mostCurrent = new modcard();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.modcard", null);
		ba.loadHtSubs(modcard.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.modcard", ba);
		}
	}
    public static Class<?> getObject() {
		return modcard.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static b4j.example.bananovue _vue = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcalendar _modcalendar = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modautocomplete _modautocomplete = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatatable _moddatatable = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddesign _moddesign = null;
public static b4j.example.modexpansionpanels _modexpansionpanels = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modgrid _modgrid = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimeline _modtimeline = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modtreeview _modtreeview = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _btna_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 168;BA.debugLine="Private Sub btna_click(e As BANanoEvent)";
 //BA.debugLineNum = 169;BA.debugLine="vm.ShowSnackBar(\"Banner\")";
_vm._showsnackbar /*String*/ ("Banner");
 //BA.debugLineNum = 170;BA.debugLine="End Sub";
return "";
}
public static String  _btnb_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 173;BA.debugLine="Private Sub btnb_click(e As BANanoEvent)";
 //BA.debugLineNum = 174;BA.debugLine="vm.ShowSnackBar(\"Squirrel\")";
_vm._showsnackbar /*String*/ ("Squirrel");
 //BA.debugLineNum = 175;BA.debugLine="End Sub";
return "";
}
public static String  _btnc_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 178;BA.debugLine="Private Sub btnc_click(e As BANanoEvent)";
 //BA.debugLineNum = 179;BA.debugLine="vm.ShowSnackBar(\"Sky\")";
_vm._showsnackbar /*String*/ ("Sky");
 //BA.debugLineNum = 180;BA.debugLine="End Sub";
return "";
}
public static String  _btnd_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 183;BA.debugLine="Private Sub btnd_click(e As BANanoEvent)";
 //BA.debugLineNum = 184;BA.debugLine="vm.ShowSnackBar(\"Planet\")";
_vm._showsnackbar /*String*/ ("Planet");
 //BA.debugLineNum = 185;BA.debugLine="End Sub";
return "";
}
public static String  _btne_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 188;BA.debugLine="Private Sub btne_click(e As BANanoEvent)";
 //BA.debugLineNum = 189;BA.debugLine="vm.ShowSnackBar(\"Bird\")";
_vm._showsnackbar /*String*/ ("Bird");
 //BA.debugLineNum = 190;BA.debugLine="End Sub";
return "";
}
public static String  _carcard1_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 193;BA.debugLine="Private Sub carcard1_click(e As BANanoEvent)";
 //BA.debugLineNum = 194;BA.debugLine="vm.ShowSnackBar(\"Card Clicked!\")";
_vm._showsnackbar /*String*/ ("Card Clicked!");
 //BA.debugLineNum = 195;BA.debugLine="End Sub";
return "";
}
public static String  _cardclickcodecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 152;BA.debugLine="Sub cardclickcodecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 153;BA.debugLine="vue.CopyCode2Clipboard(\"cardclickcode\")";
_vue._copycode2clipboard /*String*/ ("cardclickcode");
 //BA.debugLineNum = 154;BA.debugLine="End Sub";
return "";
}
public static String  _cardclickcodedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 156;BA.debugLine="Sub cardclickcodedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 157;BA.debugLine="vue.DownloadCode(\"cardclickcode\", \"cardclickcode.";
_vue._downloadcode /*String*/ ("cardclickcode","cardclickcode.txt");
 //BA.debugLineNum = 158;BA.debugLine="End Sub";
return "";
}
public static String  _cardcodecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 160;BA.debugLine="Sub cardcodecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 161;BA.debugLine="vue.CopyCode2Clipboard(\"cardcode\")";
_vue._copycode2clipboard /*String*/ ("cardcode");
 //BA.debugLineNum = 162;BA.debugLine="End Sub";
return "";
}
public static String  _cardcodedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 164;BA.debugLine="Sub cardcodedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 165;BA.debugLine="vue.DownloadCode(\"cardcode\", \"cardcode.txt\")";
_vue._downloadcode /*String*/ ("cardcode","cardcode.txt");
 //BA.debugLineNum = 166;BA.debugLine="End Sub";
return "";
}
public static String  _code() throws Exception{
b4j.example.vmcontainer _cont = null;
b4j.example.vmcard _carcard1 = null;
b4j.example.vmprism _codeit = null;
b4j.example.vmprism _codeit1 = null;
b4j.example.vmelement _profilecard = null;
b4j.example.vmelement _cardtitle = null;
b4j.example.vmelement _avatar = null;
b4j.example.vmelement _img = null;
b4j.example.vmelement _cardtext = null;
b4j.example.vmelement _h6 = null;
b4j.example.vmelement _h4 = null;
b4j.example.vmelement _p = null;
b4j.example.vmelement _btn = null;
b4j.example.vmcard _cardsheet = null;
b4j.example.vmsparkline _sl = null;
String _scard = "";
b4j.example.vmelement _div = null;
 //BA.debugLineNum = 10;BA.debugLine="Sub Code";
 //BA.debugLineNum = 11;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 12;BA.debugLine="vue = vm.vue";
_vue = _vm._vue /*b4j.example.bananovue*/ ;
 //BA.debugLineNum = 14;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,modcard.getObject());
 //BA.debugLineNum = 16;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 18;BA.debugLine="Dim carcard1 As VMCard";
_carcard1 = new b4j.example.vmcard();
 //BA.debugLineNum = 19;BA.debugLine="carcard1.Initialize(vue, \"carcard1\", Me)";
_carcard1._initialize /*b4j.example.vmcard*/ (ba,_vue,"carcard1",modcard.getObject());
 //BA.debugLineNum = 20;BA.debugLine="carcard1.SetTitle(\"card1\")";
_carcard1._settitle /*b4j.example.vmcard*/ ("card1");
 //BA.debugLineNum = 21;BA.debugLine="carcard1.SetSubTitle(\"card1 SubTitle\")";
_carcard1._setsubtitle /*b4j.example.vmcard*/ ("card1 SubTitle");
 //BA.debugLineNum = 22;BA.debugLine="carcard1.Image.SetHeight(200)";
_carcard1._image /*b4j.example.vmimage*/ ._setheight /*b4j.example.vmimage*/ (BA.NumberToString(200));
 //BA.debugLineNum = 23;BA.debugLine="carcard1.Image.SetValue(\"./assets/sky.jpg\")";
_carcard1._image /*b4j.example.vmimage*/ ._setvalue /*b4j.example.vmimage*/ ("./assets/sky.jpg");
 //BA.debugLineNum = 24;BA.debugLine="carcard1.Text.AddContent(\"This is card1card conte";
_carcard1._text /*b4j.example.vmcardtext*/ ._addcontent /*b4j.example.vmcardtext*/ ("This is card1card content");
 //BA.debugLineNum = 25;BA.debugLine="carcard1.SetHover(True)";
_carcard1._sethover /*b4j.example.vmcard*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 26;BA.debugLine="carcard1.SetLoaderheight(\"4\")";
_carcard1._setloaderheight /*b4j.example.vmcard*/ ("4");
 //BA.debugLineNum = 27;BA.debugLine="carcard1.SetMaxwidth(\"450\")";
_carcard1._setmaxwidth /*b4j.example.vmcard*/ ("450");
 //BA.debugLineNum = 28;BA.debugLine="carcard1.SetRaised(True)";
_carcard1._setraised /*b4j.example.vmcard*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 29;BA.debugLine="carcard1.SetShaped(True)";
_carcard1._setshaped /*b4j.example.vmcard*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 30;BA.debugLine="carcard1.SetVisible(True)";
_carcard1._setvisible /*b4j.example.vmcard*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 31;BA.debugLine="carcard1.AddDivider";
_carcard1._adddivider /*b4j.example.vmcard*/ ();
 //BA.debugLineNum = 32;BA.debugLine="carcard1.Actions.AddSpacer";
_carcard1._actions /*b4j.example.vmcardactions*/ ._addspacer /*b4j.example.vmcardactions*/ ();
 //BA.debugLineNum = 33;BA.debugLine="carcard1.Actions.AddButton1(\"btna\", \"dashboard\",";
_carcard1._actions /*b4j.example.vmcardactions*/ ._addbutton1 /*b4j.example.vmcardactions*/ ("btna","dashboard","red","Banner","A business banner","");
 //BA.debugLineNum = 34;BA.debugLine="carcard1.Actions.AddIcon(\"btnb\", \"account_box\", \"";
_carcard1._actions /*b4j.example.vmcardactions*/ ._addicon /*b4j.example.vmcardactions*/ ("btnb","account_box","indigo","","Another squirrel","");
 //BA.debugLineNum = 35;BA.debugLine="carcard1.Actions.AddIcon(\"btnc\", \"gavel\", \"green\"";
_carcard1._actions /*b4j.example.vmcardactions*/ ._addicon /*b4j.example.vmcardactions*/ ("btnc","gavel","green","","Heavens","");
 //BA.debugLineNum = 36;BA.debugLine="carcard1.Actions.AddIcon(\"btnd\", \"question_answer";
_carcard1._actions /*b4j.example.vmcardactions*/ ._addicon /*b4j.example.vmcardactions*/ ("btnd","question_answer","purple","","Planets of the world","");
 //BA.debugLineNum = 37;BA.debugLine="carcard1.Actions.AddIcon(\"btne\", \"mdi-account\", \"";
_carcard1._actions /*b4j.example.vmcardactions*/ ._addicon /*b4j.example.vmcardactions*/ ("btne","mdi-account","yellow","","This is a beautiful bird","");
 //BA.debugLineNum = 38;BA.debugLine="cont.AddControl(carcard1.Card, carcard1.tostring,";
_cont._addcontrol /*String*/ (_carcard1._card /*b4j.example.vmelement*/ ,_carcard1._tostring /*String*/ (),BA.NumberToString(1),BA.NumberToString(1),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12));
 //BA.debugLineNum = 41;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 42;BA.debugLine="vue.AddCode($\"Dim carcard1 As VMCard\"$)";
_vue._addcode /*String*/ (("Dim carcard1 As VMCard"));
 //BA.debugLineNum = 43;BA.debugLine="vue.AddCode($\"carcard1.Initialize(vue, \"carcard1\",";
_vue._addcode /*String*/ (("carcard1.Initialize(vue, \"carcard1\", Me)"));
 //BA.debugLineNum = 44;BA.debugLine="vue.AddCode($\"carcard1.SetTitle(\"card1\")\"$)";
_vue._addcode /*String*/ (("carcard1.SetTitle(\"card1\")"));
 //BA.debugLineNum = 45;BA.debugLine="vue.AddCode($\"carcard1.SetSubTitle(\"card1 SubTitle";
_vue._addcode /*String*/ (("carcard1.SetSubTitle(\"card1 SubTitle\")"));
 //BA.debugLineNum = 46;BA.debugLine="vue.AddCode($\"carcard1.Image.SetHeight(200)\"$)";
_vue._addcode /*String*/ (("carcard1.Image.SetHeight(200)"));
 //BA.debugLineNum = 47;BA.debugLine="vue.AddCode($\"carcard1.Image.SetValue(\"./assets/sk";
_vue._addcode /*String*/ (("carcard1.Image.SetValue(\"./assets/sky.jpg\")"));
 //BA.debugLineNum = 48;BA.debugLine="vue.AddCode($\"carcard1.Text.AddContent(\"This is ca";
_vue._addcode /*String*/ (("carcard1.Text.AddContent(\"This is card1card content\")"));
 //BA.debugLineNum = 49;BA.debugLine="vue.AddCode($\"carcard1.SetHover(True)\"$)";
_vue._addcode /*String*/ (("carcard1.SetHover(True)"));
 //BA.debugLineNum = 50;BA.debugLine="vue.AddCode($\"carcard1.SetLoaderheight(\"4\")\"$)";
_vue._addcode /*String*/ (("carcard1.SetLoaderheight(\"4\")"));
 //BA.debugLineNum = 51;BA.debugLine="vue.AddCode($\"carcard1.SetMaxwidth(\"450\")\"$)";
_vue._addcode /*String*/ (("carcard1.SetMaxwidth(\"450\")"));
 //BA.debugLineNum = 52;BA.debugLine="vue.AddCode($\"carcard1.SetRaised(True)\"$)";
_vue._addcode /*String*/ (("carcard1.SetRaised(True)"));
 //BA.debugLineNum = 53;BA.debugLine="vue.AddCode($\"carcard1.SetShaped(True)\"$)";
_vue._addcode /*String*/ (("carcard1.SetShaped(True)"));
 //BA.debugLineNum = 54;BA.debugLine="vue.AddCode($\"carcard1.SetVisible(True)\"$)";
_vue._addcode /*String*/ (("carcard1.SetVisible(True)"));
 //BA.debugLineNum = 55;BA.debugLine="vue.AddCode($\"carcard1.AddDivider\"$)";
_vue._addcode /*String*/ (("carcard1.AddDivider"));
 //BA.debugLineNum = 56;BA.debugLine="vue.AddCode($\"carcard1.Actions.AddSpacer\"$)";
_vue._addcode /*String*/ (("carcard1.Actions.AddSpacer"));
 //BA.debugLineNum = 57;BA.debugLine="vue.AddCode($\"carcard1.Actions.AddButton1(\"btna\",";
_vue._addcode /*String*/ (("carcard1.Actions.AddButton1(\"btna\", \"dashboard\", \"red\", \"Banner\", \"A business banner\", \"\")"));
 //BA.debugLineNum = 58;BA.debugLine="vue.AddCode($\"carcard1.Actions.AddIcon(\"btnb\", \"ac";
_vue._addcode /*String*/ (("carcard1.Actions.AddIcon(\"btnb\", \"account_box\", \"indigo\", \"\", \"Another squirrel\", \"\")"));
 //BA.debugLineNum = 59;BA.debugLine="vue.AddCode($\"carcard1.Actions.AddIcon(\"btnc\", \"ga";
_vue._addcode /*String*/ (("carcard1.Actions.AddIcon(\"btnc\", \"gavel\", \"green\", \"\", \"Heavens\", \"\")"));
 //BA.debugLineNum = 60;BA.debugLine="vue.AddCode($\"carcard1.Actions.AddIcon(\"btnd\", \"qu";
_vue._addcode /*String*/ (("carcard1.Actions.AddIcon(\"btnd\", \"question_answer\", \"purple\", \"\", \"Planets of the world\", \"\")"));
 //BA.debugLineNum = 61;BA.debugLine="vue.AddCode($\"carcard1.Actions.AddIcon(\"btne\", \"md";
_vue._addcode /*String*/ (("carcard1.Actions.AddIcon(\"btne\", \"mdi-account\", \"yellow\", \"\", \"This is a beautiful bird\", \"\")"));
 //BA.debugLineNum = 62;BA.debugLine="vue.AddCode($\"cont.AddControl(carcard1.Card, carca";
_vue._addcode /*String*/ (("cont.AddControl(carcard1.Card, carcard1.tostring, 1, 1, 0, 0, 0, 0, 12, 12, 12, 12)"));
 //BA.debugLineNum = 63;BA.debugLine="Dim codeit As VMPrism = pgIndex.CreateVBCode(vue,";
_codeit = _pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modcard.getObject(),"cardcode","Card",_vue._getsourcecode /*String*/ ());
 //BA.debugLineNum = 64;BA.debugLine="cont.AddControl(codeit.PrismComponent, codeit.ToS";
_cont._addcontrol /*String*/ (_codeit._prismcomponent /*b4j.example.vmelement*/ ,_codeit._tostring /*String*/ (),BA.NumberToString(2),BA.NumberToString(1),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12));
 //BA.debugLineNum = 67;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 68;BA.debugLine="vue.AddCode($\"Private Sub btna_click(e As BANanoEv";
_vue._addcode /*String*/ (("Private Sub btna_click(e As BANanoEvent)"));
 //BA.debugLineNum = 69;BA.debugLine="vue.AddCode($\"vm.ShowSnackBar(\"Banner\")\"$)";
_vue._addcode /*String*/ (("vm.ShowSnackBar(\"Banner\")"));
 //BA.debugLineNum = 70;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 71;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 72;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 73;BA.debugLine="vue.AddCode($\"Private Sub btnb_click(e As BANanoEv";
_vue._addcode /*String*/ (("Private Sub btnb_click(e As BANanoEvent)"));
 //BA.debugLineNum = 74;BA.debugLine="vue.AddCode($\"vm.ShowSnackBar(\"Squirrel\")\"$)";
_vue._addcode /*String*/ (("vm.ShowSnackBar(\"Squirrel\")"));
 //BA.debugLineNum = 75;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 76;BA.debugLine="Dim codeit1 As VMPrism = pgIndex.CreateVBCode(vue";
_codeit1 = _pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modcard.getObject(),"cardclickcode","Card Button Click",_vue._getsourcecode /*String*/ ());
 //BA.debugLineNum = 77;BA.debugLine="cont.AddControl(codeit1.PrismComponent, codeit1.T";
_cont._addcontrol /*String*/ (_codeit1._prismcomponent /*b4j.example.vmelement*/ ,_codeit1._tostring /*String*/ (),BA.NumberToString(2),BA.NumberToString(1),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12));
 //BA.debugLineNum = 81;BA.debugLine="Dim profileCard As VMElement = vm.VCard(\"profilec";
_profilecard = _vm._vcard /*b4j.example.vmelement*/ ("profilecard");
 //BA.debugLineNum = 82;BA.debugLine="profileCard.setvisible(True)";
_profilecard._setvisible /*b4j.example.vmelement*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 83;BA.debugLine="Dim cardTitle As VMElement = vm.VCardTitle(\"\").Ad";
_cardtitle = _vm._vcardtitle /*b4j.example.vmelement*/ ("")._addstyle /*b4j.example.vmelement*/ ("top","-40px !important");
 //BA.debugLineNum = 85;BA.debugLine="Dim avatar As VMElement = vm.VAvatar(\"\")";
_avatar = _vm._vavatar /*b4j.example.vmelement*/ ("");
 //BA.debugLineNum = 86;BA.debugLine="avatar.AddAttributes(CreateMap(\"size\":\"128\"))";
_avatar._addattributes /*b4j.example.vmelement*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("size"),(Object)("128")}));
 //BA.debugLineNum = 87;BA.debugLine="avatar.AddStyles(CreateMap(\"top\": \"-64px\", \"margi";
_avatar._addstyles /*b4j.example.vmelement*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("top"),(Object)("-64px"),(Object)("margin-bottom"),(Object)("-32px"),(Object)("border-radius"),(Object)("50% !important"),(Object)("position"),(Object)("relative")}));
 //BA.debugLineNum = 88;BA.debugLine="avatar.AddClass(\"text-center mx-auto elevation-6\"";
_avatar._addclass /*b4j.example.vmelement*/ ("text-center mx-auto elevation-6");
 //BA.debugLineNum = 89;BA.debugLine="Dim img As VMElement = vm.VImg(\"\").AddAttr(\"src\",";
_img = _vm._vimg /*b4j.example.vmelement*/ ("")._addattr /*b4j.example.vmelement*/ ("src","./assets/sponge.png");
 //BA.debugLineNum = 90;BA.debugLine="avatar.AddElement(img)";
_avatar._addelement /*b4j.example.vmelement*/ (_img);
 //BA.debugLineNum = 92;BA.debugLine="cardTitle.AddElement(avatar)";
_cardtitle._addelement /*b4j.example.vmelement*/ (_avatar);
 //BA.debugLineNum = 94;BA.debugLine="profileCard.AddElement(cardTitle)";
_profilecard._addelement /*b4j.example.vmelement*/ (_cardtitle);
 //BA.debugLineNum = 96;BA.debugLine="Dim cardText As VMElement = vm.VCardText(\"profile";
_cardtext = _vm._vcardtext /*b4j.example.vmelement*/ ("profiletext")._addclass /*b4j.example.vmelement*/ ("text-center");
 //BA.debugLineNum = 97;BA.debugLine="Dim h6 As VMElement = vm.H6(\"\").AddClass(\"mb-1 gr";
_h6 = _vm._h6 /*b4j.example.vmelement*/ ("")._addclass /*b4j.example.vmelement*/ ("mb-1 grey--text")._settext /*b4j.example.vmelement*/ ("CEO / CO-FOUNDER");
 //BA.debugLineNum = 98;BA.debugLine="cardText.AddElement(h6)";
_cardtext._addelement /*b4j.example.vmelement*/ (_h6);
 //BA.debugLineNum = 99;BA.debugLine="Dim h4 As VMElement = vm.H4(\"\").AddClass(\"font-we";
_h4 = _vm._h4 /*b4j.example.vmelement*/ ("")._addclass /*b4j.example.vmelement*/ ("font-weight-light mb-3 black--text")._settext /*b4j.example.vmelement*/ ("Anele Mbanga (Mashy)");
 //BA.debugLineNum = 100;BA.debugLine="cardText.AddElement(h4)";
_cardtext._addelement /*b4j.example.vmelement*/ (_h4);
 //BA.debugLineNum = 101;BA.debugLine="Dim p As VMElement = vm.P(\"\").AddClass(\"font-weig";
_p = _vm._p /*b4j.example.vmelement*/ ("")._addclass /*b4j.example.vmelement*/ ("font-weight-light grey--text");
 //BA.debugLineNum = 102;BA.debugLine="p.SetText(\"Don't be scared of the truth because w";
_p._settext /*b4j.example.vmelement*/ ("Don't be scared of the truth because we need to restart the human foundation in truth and I love you like Kanye loves Kanye, I love Rick Owens’ bed design but the back is...");
 //BA.debugLineNum = 103;BA.debugLine="cardText.AddElement(p)";
_cardtext._addelement /*b4j.example.vmelement*/ (_p);
 //BA.debugLineNum = 104;BA.debugLine="Dim btn As VMElement = vm.VBtn(\"\").AddAttr(\"color";
_btn = _vm._vbtn /*b4j.example.vmelement*/ ("")._addattr /*b4j.example.vmelement*/ ("color","success")._addattr /*b4j.example.vmelement*/ ("rounded",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.True))._addclass /*b4j.example.vmelement*/ ("mr-0")._settext /*b4j.example.vmelement*/ ("Follow");
 //BA.debugLineNum = 105;BA.debugLine="cardText.AddElement(btn)";
_cardtext._addelement /*b4j.example.vmelement*/ (_btn);
 //BA.debugLineNum = 106;BA.debugLine="profileCard.AddElement(cardText)";
_profilecard._addelement /*b4j.example.vmelement*/ (_cardtext);
 //BA.debugLineNum = 107;BA.debugLine="cont.AddControl(profileCard, profileCard.ToString";
_cont._addcontrol /*String*/ (_profilecard,_profilecard._tostring /*String*/ (),BA.NumberToString(3),BA.NumberToString(1),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(12),BA.NumberToString(4),BA.NumberToString(4),BA.NumberToString(4));
 //BA.debugLineNum = 110;BA.debugLine="Dim cardsheet As VMCard = vm.createcard(\"cardshee";
_cardsheet = _vm._createcard /*b4j.example.vmcard*/ ("cardsheet",modcard.getObject());
 //BA.debugLineNum = 111;BA.debugLine="cardsheet.addclass(\"mt-4 mx-auto\")";
_cardsheet._addclass /*b4j.example.vmcard*/ ("mt-4 mx-auto");
 //BA.debugLineNum = 112;BA.debugLine="cardsheet.setmaxwidth(\"400\")";
_cardsheet._setmaxwidth /*b4j.example.vmcard*/ ("400");
 //BA.debugLineNum = 113;BA.debugLine="cardsheet.SetVisible(True)";
_cardsheet._setvisible /*b4j.example.vmcard*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 114;BA.debugLine="cardsheet.TopSheet.SetColor(vm.COLOR_CYAN)";
_cardsheet._topsheet /*b4j.example.vmsheet*/ ._setcolor /*b4j.example.vmsheet*/ (_vm._color_cyan /*String*/ );
 //BA.debugLineNum = 115;BA.debugLine="cardsheet.topsheet.setelevation(12)";
_cardsheet._topsheet /*b4j.example.vmsheet*/ ._setelevation /*b4j.example.vmsheet*/ (BA.NumberToString(12));
 //BA.debugLineNum = 117;BA.debugLine="Dim sl As VMSparkLine = vm.CreateSparkLine(\"sl\",";
_sl = _vm._createsparkline /*b4j.example.vmsparkline*/ ("sl",modcard.getObject());
 //BA.debugLineNum = 118;BA.debugLine="sl.setcolor(vm.color_white)";
_sl._setcolor /*b4j.example.vmsparkline*/ (_vm._color_white /*String*/ );
 //BA.debugLineNum = 119;BA.debugLine="sl.setlinewidth(\"2\")";
_sl._setlinewidth /*b4j.example.vmsparkline*/ ("2");
 //BA.debugLineNum = 120;BA.debugLine="sl.setpadding(\"16\")";
_sl._setpadding /*b4j.example.vmsparkline*/ ("16");
 //BA.debugLineNum = 121;BA.debugLine="sl.addxy(\"12am\", 200)";
_sl._addxy /*b4j.example.vmsparkline*/ ("12am",(int) (200));
 //BA.debugLineNum = 122;BA.debugLine="sl.addxy(\"3am\", 675)";
_sl._addxy /*b4j.example.vmsparkline*/ ("3am",(int) (675));
 //BA.debugLineNum = 123;BA.debugLine="sl.addxy(\"6am\", 410)";
_sl._addxy /*b4j.example.vmsparkline*/ ("6am",(int) (410));
 //BA.debugLineNum = 124;BA.debugLine="sl.addxy(\"9am\", 390)";
_sl._addxy /*b4j.example.vmsparkline*/ ("9am",(int) (390));
 //BA.debugLineNum = 125;BA.debugLine="sl.addxy(\"12pm\", 310)";
_sl._addxy /*b4j.example.vmsparkline*/ ("12pm",(int) (310));
 //BA.debugLineNum = 126;BA.debugLine="sl.addxy(\"3pm\", 460)";
_sl._addxy /*b4j.example.vmsparkline*/ ("3pm",(int) (460));
 //BA.debugLineNum = 127;BA.debugLine="sl.addxy(\"6pm\", 250)";
_sl._addxy /*b4j.example.vmsparkline*/ ("6pm",(int) (250));
 //BA.debugLineNum = 128;BA.debugLine="sl.addxy(\"9pm\", 240)";
_sl._addxy /*b4j.example.vmsparkline*/ ("9pm",(int) (240));
 //BA.debugLineNum = 131;BA.debugLine="cardsheet.topsheet.AddComponent(sl.tostring)";
_cardsheet._topsheet /*b4j.example.vmsheet*/ ._addcomponent /*b4j.example.vmsheet*/ (_sl._tostring /*String*/ ());
 //BA.debugLineNum = 133;BA.debugLine="cardsheet.Text.AddElement(\"\", \"div\", \"User Regist";
_cardsheet._text /*b4j.example.vmcardtext*/ ._addelement /*b4j.example.vmcardtext*/ ("","div","User Registration",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("title font-weight-light mb-2")}));
 //BA.debugLineNum = 134;BA.debugLine="cardsheet.Text.AddElement(\"\", \"div\", \"Last Campai";
_cardsheet._text /*b4j.example.vmcardtext*/ ._addelement /*b4j.example.vmcardtext*/ ("","div","Last Campaign Performance",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("subheading font-weight-light grey--text")}));
 //BA.debugLineNum = 135;BA.debugLine="cardsheet.Text.AddDivider";
_cardsheet._text /*b4j.example.vmcardtext*/ ._adddivider /*b4j.example.vmcardtext*/ ();
 //BA.debugLineNum = 136;BA.debugLine="cardsheet.Text.AddElement(\"\", \"v-icon\", \"mdi-cloc";
_cardsheet._text /*b4j.example.vmcardtext*/ ._addelement /*b4j.example.vmcardtext*/ ("","v-icon","mdi-clock",anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("small"),(Object)(anywheresoftware.b4a.keywords.Common.True)}),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("mr-2")}));
 //BA.debugLineNum = 137;BA.debugLine="cardsheet.Text.AddElement(\"\", \"span\", \"last regis";
_cardsheet._text /*b4j.example.vmcardtext*/ ._addelement /*b4j.example.vmcardtext*/ ("","span","last registration 26 minutes ago",anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("small"),(Object)(anywheresoftware.b4a.keywords.Common.True)}),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("caption grey--text font-weight-light")}));
 //BA.debugLineNum = 141;BA.debugLine="Dim scard As String = cardsheet.tostring";
_scard = _cardsheet._tostring /*String*/ ();
 //BA.debugLineNum = 142;BA.debugLine="Dim div As VMElement = vm.Div(\"divcard\")";
_div = _vm._div /*b4j.example.vmelement*/ ("divcard");
 //BA.debugLineNum = 143;BA.debugLine="div.setvisible(True)";
_div._setvisible /*b4j.example.vmelement*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 144;BA.debugLine="div.AddComponent(scard)";
_div._addcomponent /*b4j.example.vmelement*/ (_scard);
 //BA.debugLineNum = 146;BA.debugLine="cont.AddControl(div, div.ToString, 4 ,1, 0, 0, 0,";
_cont._addcontrol /*String*/ (_div,_div._tostring /*String*/ (),BA.NumberToString(4),BA.NumberToString(1),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(0),BA.NumberToString(12),BA.NumberToString(4),BA.NumberToString(4),BA.NumberToString(4));
 //BA.debugLineNum = 148;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 149;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Public name As String = \"cardCode\"";
_name = "cardCode";
 //BA.debugLineNum = 4;BA.debugLine="Public title As String = \"Card\"";
_title = "Card";
 //BA.debugLineNum = 5;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 6;BA.debugLine="Private vue As BANanoVue";
_vue = new b4j.example.bananovue();
 //BA.debugLineNum = 7;BA.debugLine="End Sub";
return "";
}
}
