package b4j.example;


import anywheresoftware.b4a.BA;

public class modcalendar extends Object{
public static modcalendar mostCurrent = new modcalendar();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.modcalendar", null);
		ba.loadHtSubs(modcalendar.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.modcalendar", ba);
		}
	}
    public static Class<?> getObject() {
		return modcalendar.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static b4j.example.bananovue _vue = null;
public static b4j.example.vmmenu _calmenu = null;
public static b4j.example.vmcalendar _cal = null;
public static b4j.example.vmcard _calcard = null;
public static com.ab.banano.BANano _banano = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcard _modcard = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modautocomplete _modautocomplete = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatatable _moddatatable = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddesign _moddesign = null;
public static b4j.example.modexpansionpanels _modexpansionpanels = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modgrid _modgrid = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimeline _modtimeline = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modtreeview _modtreeview = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _cal_change(Object _obj) throws Exception{
 //BA.debugLineNum = 238;BA.debugLine="Sub cal_change(obj As Object)";
 //BA.debugLineNum = 240;BA.debugLine="End Sub";
return "";
}
public static String  _cal_clickdate(Object _obj) throws Exception{
 //BA.debugLineNum = 234;BA.debugLine="Sub cal_clickdate(obj As Object)";
 //BA.debugLineNum = 236;BA.debugLine="End Sub";
return "";
}
public static String  _cal_clickevent(anywheresoftware.b4a.objects.collections.Map _obj) throws Exception{
String _sevent = "";
 //BA.debugLineNum = 225;BA.debugLine="Sub cal_clickevent(obj As Map)";
 //BA.debugLineNum = 226;BA.debugLine="Dim sevent As String = BANano.tojson(obj)";
_sevent = BA.ObjectToString(_banano.ToJson((Object)(_obj.getObject())));
 //BA.debugLineNum = 227;BA.debugLine="vm.ShowSnackBar(sevent)";
_vm._showsnackbar /*String*/ (_sevent);
 //BA.debugLineNum = 228;BA.debugLine="End Sub";
return "";
}
public static String  _cal_clickmore(Object _obj) throws Exception{
 //BA.debugLineNum = 230;BA.debugLine="Sub cal_clickmore(obj As Object)";
 //BA.debugLineNum = 232;BA.debugLine="End Sub";
return "";
}
public static String  _caldefcopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 284;BA.debugLine="Sub caldefcopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 285;BA.debugLine="vue.CopyCode2Clipboard(\"caldef\")";
_vue._copycode2clipboard /*String*/ ("caldef");
 //BA.debugLineNum = 286;BA.debugLine="End Sub";
return "";
}
public static String  _caldefdownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 288;BA.debugLine="Sub caldefdownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 289;BA.debugLine="vue.DownloadCode(\"caldef\", \"caldef.txt\")";
_vue._downloadcode /*String*/ ("caldef","caldef.txt");
 //BA.debugLineNum = 290;BA.debugLine="End Sub";
return "";
}
public static String  _caleventscopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 302;BA.debugLine="Sub caleventscopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 303;BA.debugLine="vue.CopyCode2Clipboard(\"calevents\")";
_vue._copycode2clipboard /*String*/ ("calevents");
 //BA.debugLineNum = 304;BA.debugLine="End Sub";
return "";
}
public static String  _caleventsdownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 306;BA.debugLine="Sub caleventsdownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 307;BA.debugLine="vue.DownloadCode(\"calevents\", \"calevents.txt\")";
_vue._downloadcode /*String*/ ("calevents","calevents.txt");
 //BA.debugLineNum = 308;BA.debugLine="End Sub";
return "";
}
public static String  _calmenuitems_click(com.ab.banano.BANanoEvent _e) throws Exception{
String _calitem = "";
String _caltitle = "";
 //BA.debugLineNum = 243;BA.debugLine="Sub calmenuitems_click(e As BANanoEvent)";
 //BA.debugLineNum = 244;BA.debugLine="Dim calitem As String = vm.GetIDFromEvent(e)";
_calitem = _vm._getidfromevent /*String*/ (_e);
 //BA.debugLineNum = 245;BA.debugLine="Dim caltitle As String = cal.GetTitle";
_caltitle = _cal._gettitle /*String*/ ();
 //BA.debugLineNum = 246;BA.debugLine="Select Case calitem";
switch (BA.switchObjectToInt(_calitem,"day","week","month")) {
case 0: {
 //BA.debugLineNum = 248;BA.debugLine="calmenu.UpdateButtonLabel(\"Day\")";
_calmenu._updatebuttonlabel /*String*/ ("Day");
 //BA.debugLineNum = 249;BA.debugLine="cal.dayview";
_cal._dayview /*String*/ ();
 //BA.debugLineNum = 250;BA.debugLine="calcard.UpdateTitle(caltitle)";
_calcard._updatetitle /*b4j.example.vmcard*/ (_caltitle);
 break; }
case 1: {
 //BA.debugLineNum = 252;BA.debugLine="calmenu.UpdateButtonLabel(\"Week\")";
_calmenu._updatebuttonlabel /*String*/ ("Week");
 //BA.debugLineNum = 253;BA.debugLine="cal.weekview";
_cal._weekview /*String*/ ();
 //BA.debugLineNum = 254;BA.debugLine="calcard.UpdateTitle(caltitle)";
_calcard._updatetitle /*b4j.example.vmcard*/ (_caltitle);
 break; }
case 2: {
 //BA.debugLineNum = 256;BA.debugLine="calmenu.UpdateButtonLabel(\"Month\")";
_calmenu._updatebuttonlabel /*String*/ ("Month");
 //BA.debugLineNum = 257;BA.debugLine="cal.monthview";
_cal._monthview /*String*/ ();
 //BA.debugLineNum = 258;BA.debugLine="calcard.UpdateTitle(caltitle)";
_calcard._updatetitle /*b4j.example.vmcard*/ (_caltitle);
 break; }
}
;
 //BA.debugLineNum = 260;BA.debugLine="End Sub";
return "";
}
public static String  _calnext_click(com.ab.banano.BANanoEvent _e) throws Exception{
String _caltitle = "";
 //BA.debugLineNum = 277;BA.debugLine="Sub calnext_click(e As BANanoEvent)";
 //BA.debugLineNum = 278;BA.debugLine="cal.ShowNext";
_cal._shownext /*String*/ ();
 //BA.debugLineNum = 279;BA.debugLine="Dim caltitle As String = cal.GetTitle";
_caltitle = _cal._gettitle /*String*/ ();
 //BA.debugLineNum = 280;BA.debugLine="calcard.UpdateTitle(caltitle)";
_calcard._updatetitle /*b4j.example.vmcard*/ (_caltitle);
 //BA.debugLineNum = 281;BA.debugLine="End Sub";
return "";
}
public static String  _calprev_click(com.ab.banano.BANanoEvent _e) throws Exception{
String _caltitle = "";
 //BA.debugLineNum = 270;BA.debugLine="Sub calprev_click(e As BANanoEvent)";
 //BA.debugLineNum = 271;BA.debugLine="cal.ShowPrevious";
_cal._showprevious /*String*/ ();
 //BA.debugLineNum = 272;BA.debugLine="Dim caltitle As String = cal.GetTitle";
_caltitle = _cal._gettitle /*String*/ ();
 //BA.debugLineNum = 273;BA.debugLine="calcard.UpdateTitle(caltitle)";
_calcard._updatetitle /*b4j.example.vmcard*/ (_caltitle);
 //BA.debugLineNum = 274;BA.debugLine="End Sub";
return "";
}
public static String  _caltoday_click(com.ab.banano.BANanoEvent _e) throws Exception{
String _caltitle = "";
 //BA.debugLineNum = 263;BA.debugLine="Sub caltoday_click(e As BANanoEvent)";
 //BA.debugLineNum = 264;BA.debugLine="cal.SelectToday";
_cal._selecttoday /*String*/ ();
 //BA.debugLineNum = 265;BA.debugLine="Dim caltitle As String = cal.GetTitle";
_caltitle = _cal._gettitle /*String*/ ();
 //BA.debugLineNum = 266;BA.debugLine="calcard.UpdateTitle(caltitle)";
_calcard._updatetitle /*b4j.example.vmcard*/ (_caltitle);
 //BA.debugLineNum = 267;BA.debugLine="End Sub";
return "";
}
public static String  _caluxcopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 293;BA.debugLine="Sub caluxcopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 294;BA.debugLine="vue.CopyCode2Clipboard(\"calux\")";
_vue._copycode2clipboard /*String*/ ("calux");
 //BA.debugLineNum = 295;BA.debugLine="End Sub";
return "";
}
public static String  _caluxdownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 297;BA.debugLine="Sub caluxdownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 298;BA.debugLine="vue.DownloadCode(\"calux\", \"calux.txt\")";
_vue._downloadcode /*String*/ ("calux","calux.txt");
 //BA.debugLineNum = 299;BA.debugLine="End Sub";
return "";
}
public static String  _code() throws Exception{
b4j.example.vmcontainer _cont = null;
b4j.example.vmsheet _calsheet = null;
String _snow = "";
String _snow1 = "";
String _snow2 = "";
 //BA.debugLineNum = 13;BA.debugLine="Sub Code";
 //BA.debugLineNum = 14;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 15;BA.debugLine="vue = vm.vue";
_vue = _vm._vue /*b4j.example.bananovue*/ ;
 //BA.debugLineNum = 17;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,modcalendar.getObject());
 //BA.debugLineNum = 19;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 21;BA.debugLine="cont.AddRows(10).AddColumns12";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (10))._addcolumns12 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 24;BA.debugLine="calcard = vm.CreateCard(\"calcard\", Me)";
_calcard = _vm._createcard /*b4j.example.vmcard*/ ("calcard",modcalendar.getObject());
 //BA.debugLineNum = 26;BA.debugLine="calcard.SetTitle(\"My Calendar\")";
_calcard._settitle /*b4j.example.vmcard*/ ("My Calendar");
 //BA.debugLineNum = 28;BA.debugLine="calcard.Title.AddSpacer";
_calcard._title /*b4j.example.vmcardtitle*/ ._addspacer /*b4j.example.vmcardtitle*/ ();
 //BA.debugLineNum = 30;BA.debugLine="calcard.Title.AddButton3(\"caltoday\", \"\", \"\", \"\",";
_calcard._title /*b4j.example.vmcardtitle*/ ._addbutton3 /*b4j.example.vmcardtitle*/ ("caltoday","","","","Today",anywheresoftware.b4a.keywords.Common.True,"","");
 //BA.debugLineNum = 31;BA.debugLine="calcard.Title.AddIcon2(\"calprev\", \"mdi-chevron-le";
_calcard._title /*b4j.example.vmcardtitle*/ ._addicon2 /*b4j.example.vmcardtitle*/ ("calprev","mdi-chevron-left","","small","","","mx-1");
 //BA.debugLineNum = 32;BA.debugLine="calcard.Title.AddIcon2(\"calnext\", \"mdi-chevron-ri";
_calcard._title /*b4j.example.vmcardtitle*/ ._addicon2 /*b4j.example.vmcardtitle*/ ("calnext","mdi-chevron-right","","small","","","mx-1");
 //BA.debugLineNum = 34;BA.debugLine="calmenu = vm.CreateMenu(\"calmenu\", Me)";
_calmenu = _vm._createmenu /*b4j.example.vmmenu*/ ("calmenu",modcalendar.getObject());
 //BA.debugLineNum = 35;BA.debugLine="calmenu.SetButton1(\"mdi-menu-down\", \"right\", \"Typ";
_calmenu._setbutton1 /*b4j.example.vmmenu*/ ("mdi-menu-down","right","Type",anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 36;BA.debugLine="calmenu.AddKeyValue(\"day\", \"Day\")";
_calmenu._addkeyvalue /*String*/ ("day","Day");
 //BA.debugLineNum = 37;BA.debugLine="calmenu.AddKeyValue(\"week\", \"Week\")";
_calmenu._addkeyvalue /*String*/ ("week","Week");
 //BA.debugLineNum = 38;BA.debugLine="calmenu.AddKeyValue(\"month\", \"Month\")";
_calmenu._addkeyvalue /*String*/ ("month","Month");
 //BA.debugLineNum = 39;BA.debugLine="calcard.Title.AddMenu(calmenu)";
_calcard._title /*b4j.example.vmcardtitle*/ ._addmenu /*b4j.example.vmcardtitle*/ (_calmenu);
 //BA.debugLineNum = 41;BA.debugLine="Dim calsheet As VMSheet = vm.CreateSheet(\"calshee";
_calsheet = _vm._createsheet /*b4j.example.vmsheet*/ ("calsheet",modcalendar.getObject());
 //BA.debugLineNum = 42;BA.debugLine="calsheet.SetHeight(\"600\")";
_calsheet._setheight /*b4j.example.vmsheet*/ ("600");
 //BA.debugLineNum = 45;BA.debugLine="cal = vm.CreateCalendar(\"cal\", Me)";
_cal = _vm._createcalendar /*b4j.example.vmcalendar*/ ("cal",modcalendar.getObject());
 //BA.debugLineNum = 46;BA.debugLine="cal.SetCOlor(vm.COLOR_PRIMARY)";
_cal._setcolor /*b4j.example.vmcalendar*/ (_vm._color_primary /*String*/ );
 //BA.debugLineNum = 47;BA.debugLine="cal.SetEventOverlapMode(\"column\")";
_cal._seteventoverlapmode /*b4j.example.vmcalendar*/ ("column");
 //BA.debugLineNum = 48;BA.debugLine="cal.SetEventOverlapThreshold(\"45\")";
_cal._seteventoverlapthreshold /*b4j.example.vmcalendar*/ ("45");
 //BA.debugLineNum = 50;BA.debugLine="calsheet.SetText(cal.tostring)";
_calsheet._settext /*String*/ (_cal._tostring /*String*/ ());
 //BA.debugLineNum = 52;BA.debugLine="calcard.Text.SetText(calsheet.ToString)";
_calcard._text /*b4j.example.vmcardtext*/ ._settext /*b4j.example.vmcardtext*/ (_calsheet._tostring /*String*/ ());
 //BA.debugLineNum = 54;BA.debugLine="calcard.AddToContainer(cont,1,1)";
_calcard._addtocontainer /*String*/ (_cont,(int) (1),(int) (1));
 //BA.debugLineNum = 58;BA.debugLine="cal.ClearEvents";
_cal._clearevents /*String*/ ();
 //BA.debugLineNum = 59;BA.debugLine="cal.ClearCategories";
_cal._clearcategories /*String*/ ();
 //BA.debugLineNum = 60;BA.debugLine="cal.AddCategory(\"b4a\", vm.COLOR_ORANGE)";
_cal._addcategory /*String*/ ("b4a",_vm._color_orange /*String*/ );
 //BA.debugLineNum = 61;BA.debugLine="cal.AddCategory(\"b4i\", vm.COLOR_PINK)";
_cal._addcategory /*String*/ ("b4i",_vm._color_pink /*String*/ );
 //BA.debugLineNum = 62;BA.debugLine="cal.AddCategory(\"b4j\", vm.COLOR_CYAN)";
_cal._addcategory /*String*/ ("b4j",_vm._color_cyan /*String*/ );
 //BA.debugLineNum = 64;BA.debugLine="Dim sNow As String = BANanoShared.DateNow & \"T10:";
_snow = _bananoshared._datenow /*String*/ ()+"T10:00";
 //BA.debugLineNum = 65;BA.debugLine="Dim sNow1 As String = BANanoShared.DateNow & \"T12";
_snow1 = _bananoshared._datenow /*String*/ ()+"T12:00";
 //BA.debugLineNum = 66;BA.debugLine="Dim sNow2 As String = BANanoShared.DateNow & \"T13";
_snow2 = _bananoshared._datenow /*String*/ ()+"T13:05";
 //BA.debugLineNum = 68;BA.debugLine="cal.AddEvent(\"1\", \"b4a\", \"Develop B4A App\", sNow,";
_cal._addevent /*String*/ ("1","b4a","Develop B4A App",_snow,_snow,anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 69;BA.debugLine="cal.AddEvent(\"2\", \"b4i\", \"Develop B4i App\", sNow1";
_cal._addevent /*String*/ ("2","b4i","Develop B4i App",_snow1,_snow1,anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 70;BA.debugLine="cal.AddEvent(\"3\", \"b4j\", \"Develop B4J App\", sNow2";
_cal._addevent /*String*/ ("3","b4j","Develop B4J App",_snow2,_snow2,anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 71;BA.debugLine="cal.Update";
_cal._update /*String*/ ();
 //BA.debugLineNum = 73;BA.debugLine="vue.SetMounted(Me, \"MoundCalendar\")";
_vue._setmounted /*b4j.example.bananovue*/ (modcalendar.getObject(),"MoundCalendar");
 //BA.debugLineNum = 77;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 78;BA.debugLine="vue.AddCode($\"Private calmenu As VMMenu\"$)";
_vue._addcode /*String*/ (("Private calmenu As VMMenu"));
 //BA.debugLineNum = 79;BA.debugLine="vue.AddCode($\"Private cal As VMCalendar\"$)";
_vue._addcode /*String*/ (("Private cal As VMCalendar"));
 //BA.debugLineNum = 80;BA.debugLine="vue.AddCode($\"Private calcard As VMCard\"$)";
_vue._addcode /*String*/ (("Private calcard As VMCard"));
 //BA.debugLineNum = 81;BA.debugLine="vue.AddCode($\"Private BANano As BANano\"$)";
_vue._addcode /*String*/ (("Private BANano As BANano"));
 //BA.debugLineNum = 82;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"caldef\", \"Calendar";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modcalendar.getObject(),"caldef","Calendar Definition",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (2),(int) (1));
 //BA.debugLineNum = 85;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 86;BA.debugLine="vue.AddCode($\"'create a card to hold the calendar\"";
_vue._addcode /*String*/ (("'create a card to hold the calendar"));
 //BA.debugLineNum = 87;BA.debugLine="vue.AddCode($\"calcard = vm.CreateCard(\"calcard\", M";
_vue._addcode /*String*/ (("calcard = vm.CreateCard(\"calcard\", Me)"));
 //BA.debugLineNum = 88;BA.debugLine="vue.AddCode($\"'set title of card, dynamic\"$)";
_vue._addcode /*String*/ (("'set title of card, dynamic"));
 //BA.debugLineNum = 89;BA.debugLine="vue.AddCode($\"calcard.SetTitle(\"My Calendar\")\"$)";
_vue._addcode /*String*/ (("calcard.SetTitle(\"My Calendar\")"));
 //BA.debugLineNum = 90;BA.debugLine="vue.AddCode($\"'add a spacer\"$)";
_vue._addcode /*String*/ (("'add a spacer"));
 //BA.debugLineNum = 91;BA.debugLine="vue.AddCode($\"calcard.Title.AddSpacer\"$)";
_vue._addcode /*String*/ (("calcard.Title.AddSpacer"));
 //BA.debugLineNum = 92;BA.debugLine="vue.AddCode($\"'add buttons\"$)";
_vue._addcode /*String*/ (("'add buttons"));
 //BA.debugLineNum = 93;BA.debugLine="vue.AddCode($\"calcard.Title.AddButton3(\"caltoday\",";
_vue._addcode /*String*/ (("calcard.Title.AddButton3(\"caltoday\", \"\", \"\", \"\", \"Today\", True, \"\", \"\")"));
 //BA.debugLineNum = 94;BA.debugLine="vue.AddCode($\"calcard.Title.AddIcon2(\"calprev\", \"m";
_vue._addcode /*String*/ (("calcard.Title.AddIcon2(\"calprev\", \"mdi-chevron-left\", \"\", \"small\", \"\",\"\",\"mx-1\")"));
 //BA.debugLineNum = 95;BA.debugLine="vue.AddCode($\"calcard.Title.AddIcon2(\"calnext\", \"m";
_vue._addcode /*String*/ (("calcard.Title.AddIcon2(\"calnext\", \"mdi-chevron-right\", \"\", \"small\", \"\", \"\", \"mx-1\")"));
 //BA.debugLineNum = 96;BA.debugLine="vue.AddCode($\"'create a menu to change calendar vi";
_vue._addcode /*String*/ (("'create a menu to change calendar view"));
 //BA.debugLineNum = 97;BA.debugLine="vue.AddCode($\"calmenu = vm.CreateMenu(\"calmenu\", M";
_vue._addcode /*String*/ (("calmenu = vm.CreateMenu(\"calmenu\", Me)"));
 //BA.debugLineNum = 98;BA.debugLine="vue.AddCode($\"calmenu.SetButton1(\"mdi-menu-down\",";
_vue._addcode /*String*/ (("calmenu.SetButton1(\"mdi-menu-down\", \"right\", \"Type\", True)"));
 //BA.debugLineNum = 99;BA.debugLine="vue.AddCode($\"calmenu.AddKeyValue(\"day\", \"Day\")\"$)";
_vue._addcode /*String*/ (("calmenu.AddKeyValue(\"day\", \"Day\")"));
 //BA.debugLineNum = 100;BA.debugLine="vue.AddCode($\"calmenu.AddKeyValue(\"week\", \"Week\")\"";
_vue._addcode /*String*/ (("calmenu.AddKeyValue(\"week\", \"Week\")"));
 //BA.debugLineNum = 101;BA.debugLine="vue.AddCode($\"calmenu.AddKeyValue(\"month\", \"Month\"";
_vue._addcode /*String*/ (("calmenu.AddKeyValue(\"month\", \"Month\")"));
 //BA.debugLineNum = 102;BA.debugLine="vue.AddCode($\"calcard.Title.AddMenu(calmenu)\"$)";
_vue._addcode /*String*/ (("calcard.Title.AddMenu(calmenu)"));
 //BA.debugLineNum = 103;BA.debugLine="vue.AddCode($\"'we will add calendar to sheet\"$)";
_vue._addcode /*String*/ (("'we will add calendar to sheet"));
 //BA.debugLineNum = 104;BA.debugLine="vue.AddCode($\"Dim calsheet As VMSheet = vm.CreateS";
_vue._addcode /*String*/ (("Dim calsheet As VMSheet = vm.CreateSheet(\"calsheet\", Me)"));
 //BA.debugLineNum = 105;BA.debugLine="vue.AddCode($\"calsheet.SetHeight(\"600\")\"$)";
_vue._addcode /*String*/ (("calsheet.SetHeight(\"600\")"));
 //BA.debugLineNum = 106;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 107;BA.debugLine="vue.AddCode($\"'create the calendar\"$)";
_vue._addcode /*String*/ (("'create the calendar"));
 //BA.debugLineNum = 108;BA.debugLine="vue.AddCode($\"cal = vm.CreateCalendar(\"cal\", Me)\"$";
_vue._addcode /*String*/ (("cal = vm.CreateCalendar(\"cal\", Me)"));
 //BA.debugLineNum = 109;BA.debugLine="vue.AddCode($\"cal.SetCOlor(vm.COLOR_PRIMARY)\"$)";
_vue._addcode /*String*/ (("cal.SetCOlor(vm.COLOR_PRIMARY)"));
 //BA.debugLineNum = 110;BA.debugLine="vue.AddCode($\"cal.SetEventOverlapMode(\"column\")\"$)";
_vue._addcode /*String*/ (("cal.SetEventOverlapMode(\"column\")"));
 //BA.debugLineNum = 111;BA.debugLine="vue.AddCode($\"cal.SetEventOverlapThreshold(\"45\")\"$";
_vue._addcode /*String*/ (("cal.SetEventOverlapThreshold(\"45\")"));
 //BA.debugLineNum = 112;BA.debugLine="vue.AddCode($\"'add calender to sheet\"$)";
_vue._addcode /*String*/ (("'add calender to sheet"));
 //BA.debugLineNum = 113;BA.debugLine="vue.AddCode($\"calsheet.SetText(cal.tostring)\"$)";
_vue._addcode /*String*/ (("calsheet.SetText(cal.tostring)"));
 //BA.debugLineNum = 114;BA.debugLine="vue.AddCode($\"'add sheet to card\"$)";
_vue._addcode /*String*/ (("'add sheet to card"));
 //BA.debugLineNum = 115;BA.debugLine="vue.AddCode($\"calcard.Text.SetText(calsheet.ToStri";
_vue._addcode /*String*/ (("calcard.Text.SetText(calsheet.ToString)"));
 //BA.debugLineNum = 116;BA.debugLine="vue.AddCode($\"'add card to container\"$)";
_vue._addcode /*String*/ (("'add card to container"));
 //BA.debugLineNum = 117;BA.debugLine="vue.AddCode($\"calcard.AddToContainer(cont,1,1)\"$)";
_vue._addcode /*String*/ (("calcard.AddToContainer(cont,1,1)"));
 //BA.debugLineNum = 118;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 119;BA.debugLine="vue.AddCode($\"'add container to page\"$)";
_vue._addcode /*String*/ (("'add container to page"));
 //BA.debugLineNum = 120;BA.debugLine="vue.AddCode($\"vm.AddContainer(cont)\"$)";
_vue._addcode /*String*/ (("vm.AddContainer(cont)"));
 //BA.debugLineNum = 121;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 122;BA.debugLine="vue.AddCode($\"'add some events\"$)";
_vue._addcode /*String*/ (("'add some events"));
 //BA.debugLineNum = 123;BA.debugLine="vue.AddCode($\"cal.ClearEvents\"$)";
_vue._addcode /*String*/ (("cal.ClearEvents"));
 //BA.debugLineNum = 124;BA.debugLine="vue.AddCode($\"cal.ClearCategories\"$)";
_vue._addcode /*String*/ (("cal.ClearCategories"));
 //BA.debugLineNum = 125;BA.debugLine="vue.AddCode($\"cal.AddCategory(\"b4a\", vm.COLOR_ORAN";
_vue._addcode /*String*/ (("cal.AddCategory(\"b4a\", vm.COLOR_ORANGE)"));
 //BA.debugLineNum = 126;BA.debugLine="vue.AddCode($\"cal.AddCategory(\"b4i\", vm.COLOR_PINK";
_vue._addcode /*String*/ (("cal.AddCategory(\"b4i\", vm.COLOR_PINK)"));
 //BA.debugLineNum = 127;BA.debugLine="vue.AddCode($\"cal.AddCategory(\"b4j\", vm.COLOR_CYAN";
_vue._addcode /*String*/ (("cal.AddCategory(\"b4j\", vm.COLOR_CYAN)"));
 //BA.debugLineNum = 128;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 129;BA.debugLine="vue.AddCode($\"Dim sNow As String = BANanoShared.Da";
_vue._addcode /*String*/ (("Dim sNow As String = BANanoShared.DateNow & \"T10:00\""));
 //BA.debugLineNum = 130;BA.debugLine="vue.AddCode($\"Dim sNow1 As String = BANanoShared.D";
_vue._addcode /*String*/ (("Dim sNow1 As String = BANanoShared.DateNow & \"T12:00\""));
 //BA.debugLineNum = 131;BA.debugLine="vue.AddCode($\"Dim sNow2 As String = BANanoShared.D";
_vue._addcode /*String*/ (("Dim sNow2 As String = BANanoShared.DateNow & \"T13:05\""));
 //BA.debugLineNum = 132;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 133;BA.debugLine="vue.AddCode($\"cal.AddEvent(\"1\", \"b4a\", \"Develop B4";
_vue._addcode /*String*/ (("cal.AddEvent(\"1\", \"b4a\", \"Develop B4A App\", sNow, sNow, False)"));
 //BA.debugLineNum = 134;BA.debugLine="vue.AddCode($\"cal.AddEvent(\"2\", \"b4i\", \"Develop B4";
_vue._addcode /*String*/ (("cal.AddEvent(\"2\", \"b4i\", \"Develop B4i App\", sNow1, sNow1, False)"));
 //BA.debugLineNum = 135;BA.debugLine="vue.AddCode($\"cal.AddEvent(\"3\", \"b4j\", \"Develop B4";
_vue._addcode /*String*/ (("cal.AddEvent(\"3\", \"b4j\", \"Develop B4J App\", sNow2, sNow2, True)"));
 //BA.debugLineNum = 136;BA.debugLine="vue.AddCode($\"cal.Update\"$)";
_vue._addcode /*String*/ (("cal.Update"));
 //BA.debugLineNum = 137;BA.debugLine="vue.AddCode($\"'run when app is mounded\"$)";
_vue._addcode /*String*/ (("'run when app is mounded"));
 //BA.debugLineNum = 138;BA.debugLine="vue.AddCode($\"vue.SetMounted(Me, \"MoundCalendar\")\"";
_vue._addcode /*String*/ (("vue.SetMounted(Me, \"MoundCalendar\")"));
 //BA.debugLineNum = 139;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 140;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"calux\", \"Calendar U";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modcalendar.getObject(),"calux","Calendar User Interface",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (3),(int) (1));
 //BA.debugLineNum = 143;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 144;BA.debugLine="vue.AddCode($\"'when calendar is mounted\"$)";
_vue._addcode /*String*/ (("'when calendar is mounted"));
 //BA.debugLineNum = 145;BA.debugLine="vue.AddCode($\"Sub MoundCalendar\"$)";
_vue._addcode /*String*/ (("Sub MoundCalendar"));
 //BA.debugLineNum = 146;BA.debugLine="vue.AddCode($\"cal.CheckChange\"$)";
_vue._addcode /*String*/ (("cal.CheckChange"));
 //BA.debugLineNum = 147;BA.debugLine="vue.AddCode($\"Dim caltitle As String = cal.GetTitl";
_vue._addcode /*String*/ (("Dim caltitle As String = cal.GetTitle"));
 //BA.debugLineNum = 148;BA.debugLine="vue.AddCode($\"calcard.UpdateTitle(caltitle)\"$)";
_vue._addcode /*String*/ (("calcard.UpdateTitle(caltitle)"));
 //BA.debugLineNum = 149;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 150;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 151;BA.debugLine="vue.AddCode($\"'an event is clicked\"$)";
_vue._addcode /*String*/ (("'an event is clicked"));
 //BA.debugLineNum = 152;BA.debugLine="vue.AddCode($\"Sub cal_clickevent(obj As Map)\"$)";
_vue._addcode /*String*/ (("Sub cal_clickevent(obj As Map)"));
 //BA.debugLineNum = 153;BA.debugLine="vue.AddCode($\"Dim sevent As String = BANano.tojson";
_vue._addcode /*String*/ (("Dim sevent As String = BANano.tojson(obj)"));
 //BA.debugLineNum = 154;BA.debugLine="vue.AddCode($\"vm.ShowSnackBar(sevent)\"$)";
_vue._addcode /*String*/ (("vm.ShowSnackBar(sevent)"));
 //BA.debugLineNum = 155;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 156;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 157;BA.debugLine="vue.AddCode($\"Sub cal_clickmore(obj As Object)\"$)";
_vue._addcode /*String*/ (("Sub cal_clickmore(obj As Object)"));
 //BA.debugLineNum = 158;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 159;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 160;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 161;BA.debugLine="vue.AddCode($\"Sub cal_clickdate(obj As Object)\"$)";
_vue._addcode /*String*/ (("Sub cal_clickdate(obj As Object)"));
 //BA.debugLineNum = 162;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 163;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 164;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 165;BA.debugLine="vue.AddCode($\"Sub cal_change(obj As Object)\"$)";
_vue._addcode /*String*/ (("Sub cal_change(obj As Object)"));
 //BA.debugLineNum = 166;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 167;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 168;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 169;BA.debugLine="vue.AddCode($\"'change calendar view\"$)";
_vue._addcode /*String*/ (("'change calendar view"));
 //BA.debugLineNum = 170;BA.debugLine="vue.AddCode($\"Sub calmenuitems_click(e As BANanoEv";
_vue._addcode /*String*/ (("Sub calmenuitems_click(e As BANanoEvent)"));
 //BA.debugLineNum = 171;BA.debugLine="vue.AddCode($\"Dim calitem As String = vm.GetIDFrom";
_vue._addcode /*String*/ (("Dim calitem As String = vm.GetIDFromEvent(e)"));
 //BA.debugLineNum = 172;BA.debugLine="vue.AddCode($\"Dim caltitle As String = cal.GetTitl";
_vue._addcode /*String*/ (("Dim caltitle As String = cal.GetTitle"));
 //BA.debugLineNum = 173;BA.debugLine="vue.AddCode($\"Select Case calitem\"$)";
_vue._addcode /*String*/ (("Select Case calitem"));
 //BA.debugLineNum = 174;BA.debugLine="vue.AddCode($\"Case \"day\"\"$)";
_vue._addcode /*String*/ (("Case \"day\""));
 //BA.debugLineNum = 175;BA.debugLine="vue.AddCode($\"calmenu.UpdateButtonLabel(\"Day\")\"$)";
_vue._addcode /*String*/ (("calmenu.UpdateButtonLabel(\"Day\")"));
 //BA.debugLineNum = 176;BA.debugLine="vue.AddCode($\"cal.dayview\"$)";
_vue._addcode /*String*/ (("cal.dayview"));
 //BA.debugLineNum = 177;BA.debugLine="vue.AddCode($\"calcard.UpdateTitle(caltitle)\"$)";
_vue._addcode /*String*/ (("calcard.UpdateTitle(caltitle)"));
 //BA.debugLineNum = 178;BA.debugLine="vue.AddCode($\"Case \"week\"\"$)";
_vue._addcode /*String*/ (("Case \"week\""));
 //BA.debugLineNum = 179;BA.debugLine="vue.AddCode($\"calmenu.UpdateButtonLabel(\"Week\")\"$)";
_vue._addcode /*String*/ (("calmenu.UpdateButtonLabel(\"Week\")"));
 //BA.debugLineNum = 180;BA.debugLine="vue.AddCode($\"cal.weekview\"$)";
_vue._addcode /*String*/ (("cal.weekview"));
 //BA.debugLineNum = 181;BA.debugLine="vue.AddCode($\"calcard.UpdateTitle(caltitle)\"$)";
_vue._addcode /*String*/ (("calcard.UpdateTitle(caltitle)"));
 //BA.debugLineNum = 182;BA.debugLine="vue.AddCode($\"Case \"month\"\"$)";
_vue._addcode /*String*/ (("Case \"month\""));
 //BA.debugLineNum = 183;BA.debugLine="vue.AddCode($\"calmenu.UpdateButtonLabel(\"Month\")\"$";
_vue._addcode /*String*/ (("calmenu.UpdateButtonLabel(\"Month\")"));
 //BA.debugLineNum = 184;BA.debugLine="vue.AddCode($\"cal.monthview\"$)";
_vue._addcode /*String*/ (("cal.monthview"));
 //BA.debugLineNum = 185;BA.debugLine="vue.AddCode($\"calcard.UpdateTitle(caltitle)\"$)";
_vue._addcode /*String*/ (("calcard.UpdateTitle(caltitle)"));
 //BA.debugLineNum = 186;BA.debugLine="vue.AddCode($\"End Select\"$)";
_vue._addcode /*String*/ (("End Select"));
 //BA.debugLineNum = 187;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 188;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 189;BA.debugLine="vue.AddCode($\"'today is clicked\"$)";
_vue._addcode /*String*/ (("'today is clicked"));
 //BA.debugLineNum = 190;BA.debugLine="vue.AddCode($\"Sub caltoday_click(e As BANanoEvent)";
_vue._addcode /*String*/ (("Sub caltoday_click(e As BANanoEvent)"));
 //BA.debugLineNum = 191;BA.debugLine="vue.AddCode($\"cal.SelectToday\"$)";
_vue._addcode /*String*/ (("cal.SelectToday"));
 //BA.debugLineNum = 192;BA.debugLine="vue.AddCode($\"Dim caltitle As String = cal.GetTitl";
_vue._addcode /*String*/ (("Dim caltitle As String = cal.GetTitle"));
 //BA.debugLineNum = 193;BA.debugLine="vue.AddCode($\"calcard.UpdateTitle(caltitle)\"$)";
_vue._addcode /*String*/ (("calcard.UpdateTitle(caltitle)"));
 //BA.debugLineNum = 194;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 195;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 196;BA.debugLine="vue.AddCode($\"'prev is clicked\"$)";
_vue._addcode /*String*/ (("'prev is clicked"));
 //BA.debugLineNum = 197;BA.debugLine="vue.AddCode($\"Sub calprev_click(e As BANanoEvent)\"";
_vue._addcode /*String*/ (("Sub calprev_click(e As BANanoEvent)"));
 //BA.debugLineNum = 198;BA.debugLine="vue.AddCode($\"cal.ShowPrevious\"$)";
_vue._addcode /*String*/ (("cal.ShowPrevious"));
 //BA.debugLineNum = 199;BA.debugLine="vue.AddCode($\"Dim caltitle As String = cal.GetTitl";
_vue._addcode /*String*/ (("Dim caltitle As String = cal.GetTitle"));
 //BA.debugLineNum = 200;BA.debugLine="vue.AddCode($\"calcard.UpdateTitle(caltitle)\"$)";
_vue._addcode /*String*/ (("calcard.UpdateTitle(caltitle)"));
 //BA.debugLineNum = 201;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 202;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 203;BA.debugLine="vue.AddCode($\"'next is clicked\"$)";
_vue._addcode /*String*/ (("'next is clicked"));
 //BA.debugLineNum = 204;BA.debugLine="vue.AddCode($\"Sub calnext_click(e As BANanoEvent)\"";
_vue._addcode /*String*/ (("Sub calnext_click(e As BANanoEvent)"));
 //BA.debugLineNum = 205;BA.debugLine="vue.AddCode($\"cal.ShowNext\"$)";
_vue._addcode /*String*/ (("cal.ShowNext"));
 //BA.debugLineNum = 206;BA.debugLine="vue.AddCode($\"Dim caltitle As String = cal.GetTitl";
_vue._addcode /*String*/ (("Dim caltitle As String = cal.GetTitle"));
 //BA.debugLineNum = 207;BA.debugLine="vue.AddCode($\"calcard.UpdateTitle(caltitle)\"$)";
_vue._addcode /*String*/ (("calcard.UpdateTitle(caltitle)"));
 //BA.debugLineNum = 208;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 209;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"calevents\", \"Calen";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modcalendar.getObject(),"calevents","Calendar Events & Methods",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (4),(int) (1));
 //BA.debugLineNum = 213;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 215;BA.debugLine="End Sub";
return "";
}
public static String  _moundcalendar() throws Exception{
String _caltitle = "";
 //BA.debugLineNum = 218;BA.debugLine="Sub MoundCalendar";
 //BA.debugLineNum = 219;BA.debugLine="cal.CheckChange";
_cal._checkchange /*String*/ ();
 //BA.debugLineNum = 220;BA.debugLine="Dim caltitle As String = cal.GetTitle";
_caltitle = _cal._gettitle /*String*/ ();
 //BA.debugLineNum = 221;BA.debugLine="calcard.UpdateTitle(caltitle)";
_calcard._updatetitle /*b4j.example.vmcard*/ (_caltitle);
 //BA.debugLineNum = 222;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Public name As String = \"calendarCode\"";
_name = "calendarCode";
 //BA.debugLineNum = 4;BA.debugLine="Public title As String = \"Calendar\"";
_title = "Calendar";
 //BA.debugLineNum = 5;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 6;BA.debugLine="Private vue As BANanoVue";
_vue = new b4j.example.bananovue();
 //BA.debugLineNum = 7;BA.debugLine="Private calmenu As VMMenu";
_calmenu = new b4j.example.vmmenu();
 //BA.debugLineNum = 8;BA.debugLine="Private cal As VMCalendar";
_cal = new b4j.example.vmcalendar();
 //BA.debugLineNum = 9;BA.debugLine="Private calcard As VMCard";
_calcard = new b4j.example.vmcard();
 //BA.debugLineNum = 10;BA.debugLine="Private BANano As BANano";
_banano = new com.ab.banano.BANano();
 //BA.debugLineNum = 11;BA.debugLine="End Sub";
return "";
}
}
