package b4j.example;


import anywheresoftware.b4a.BA;

public class modchips extends Object{
public static modchips mostCurrent = new modchips();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.modchips", null);
		ba.loadHtSubs(modchips.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.modchips", ba);
		}
	}
    public static Class<?> getObject() {
		return modchips.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static com.ab.banano.BANano _banano = null;
public static b4j.example.bananovue _vue = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcalendar _modcalendar = null;
public static b4j.example.modcard _modcard = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modautocomplete _modautocomplete = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatatable _moddatatable = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddesign _moddesign = null;
public static b4j.example.modexpansionpanels _modexpansionpanels = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modgrid _modgrid = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimeline _modtimeline = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modtreeview _modtreeview = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _c10_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 396;BA.debugLine="Sub c10_click(e As BANanoEvent)";
 //BA.debugLineNum = 397;BA.debugLine="vm.ShowSnackBar(\"Server status check!\")";
_vm._showsnackbar /*String*/ ("Server status check!");
 //BA.debugLineNum = 398;BA.debugLine="End Sub";
return "";
}
public static String  _c12_close(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 400;BA.debugLine="Sub c12_close(e As BANanoEvent)";
 //BA.debugLineNum = 401;BA.debugLine="vm.SetData(\"c12\", False)";
_vm._setdata /*b4j.example.bananovm*/ ("c12",(Object)(anywheresoftware.b4a.keywords.Common.False));
 //BA.debugLineNum = 402;BA.debugLine="End Sub";
return "";
}
public static String  _c8_close(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 405;BA.debugLine="Sub c8_close(e As BANanoEvent)";
 //BA.debugLineNum = 406;BA.debugLine="BANano.Window.Alert(\"Close!\")";
_banano.Window().Alert("Close!");
 //BA.debugLineNum = 407;BA.debugLine="End Sub";
return "";
}
public static String  _cg_change(String _value) throws Exception{
 //BA.debugLineNum = 328;BA.debugLine="Sub cg_change(value As String)";
 //BA.debugLineNum = 329;BA.debugLine="vm.ShowSnackBarSuccess(value)";
_vm._showsnackbarsuccess /*String*/ (_value);
 //BA.debugLineNum = 330;BA.debugLine="End Sub";
return "";
}
public static String  _cg1_change(String _value) throws Exception{
 //BA.debugLineNum = 332;BA.debugLine="Sub cg1_change(value As String)";
 //BA.debugLineNum = 333;BA.debugLine="vm.ShowSnackBarSuccess(value)";
_vm._showsnackbarsuccess /*String*/ (_value);
 //BA.debugLineNum = 334;BA.debugLine="End Sub";
return "";
}
public static String  _cg2_change(String _value) throws Exception{
 //BA.debugLineNum = 336;BA.debugLine="Sub cg2_change(value As String)";
 //BA.debugLineNum = 337;BA.debugLine="vm.ShowSnackBarSuccess(value)";
_vm._showsnackbarsuccess /*String*/ (_value);
 //BA.debugLineNum = 338;BA.debugLine="End Sub";
return "";
}
public static String  _cg4_change(anywheresoftware.b4a.objects.collections.List _value) throws Exception{
 //BA.debugLineNum = 340;BA.debugLine="Sub cg4_change(value As List)";
 //BA.debugLineNum = 341;BA.debugLine="vm.ShowSnackBarSUccess(BANano.ToJson(value))";
_vm._showsnackbarsuccess /*String*/ (BA.ObjectToString(_banano.ToJson((Object)(_value.getObject()))));
 //BA.debugLineNum = 342;BA.debugLine="End Sub";
return "";
}
public static String  _cg5_change(anywheresoftware.b4a.objects.collections.List _value) throws Exception{
 //BA.debugLineNum = 344;BA.debugLine="Sub cg5_change(value As List)";
 //BA.debugLineNum = 345;BA.debugLine="vm.ShowSnackBarSUccess(BANano.ToJson(value))";
_vm._showsnackbarsuccess /*String*/ (BA.ObjectToString(_banano.ToJson((Object)(_value.getObject()))));
 //BA.debugLineNum = 346;BA.debugLine="End Sub";
return "";
}
public static String  _chipfiltercopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 348;BA.debugLine="Sub chipfiltercopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 349;BA.debugLine="vue.CopyCode2Clipboard(\"chipfilter\")";
_vue._copycode2clipboard /*String*/ ("chipfilter");
 //BA.debugLineNum = 350;BA.debugLine="End Sub";
return "";
}
public static String  _chipfilterdownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 352;BA.debugLine="Sub chipfilterdownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 353;BA.debugLine="vue.DownloadCode(\"chipfilter\", \"chipfilter.txt\")";
_vue._downloadcode /*String*/ ("chipfilter","chipfilter.txt");
 //BA.debugLineNum = 354;BA.debugLine="End Sub";
return "";
}
public static String  _chipgroupcopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 376;BA.debugLine="Sub chipgroupcopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 377;BA.debugLine="vue.CopyCode2Clipboard(\"chipgroup\")";
_vue._copycode2clipboard /*String*/ ("chipgroup");
 //BA.debugLineNum = 378;BA.debugLine="End Sub";
return "";
}
public static String  _chipgroupdownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 380;BA.debugLine="Sub chipgroupdownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 381;BA.debugLine="vue.DownloadCode(\"chipgroup\", \"chipgroup.txt\")";
_vue._downloadcode /*String*/ ("chipgroup","chipgroup.txt");
 //BA.debugLineNum = 382;BA.debugLine="End Sub";
return "";
}
public static String  _chipscodecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 386;BA.debugLine="Sub chipscodecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 387;BA.debugLine="vue.CopyCode2Clipboard(\"chipscode\")";
_vue._copycode2clipboard /*String*/ ("chipscode");
 //BA.debugLineNum = 388;BA.debugLine="End Sub";
return "";
}
public static String  _chipscodedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 390;BA.debugLine="Sub chipscodedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 391;BA.debugLine="vue.DownloadCode(\"chipscode\", \"chipscode.txt\")";
_vue._downloadcode /*String*/ ("chipscode","chipscode.txt");
 //BA.debugLineNum = 392;BA.debugLine="End Sub";
return "";
}
public static String  _code() throws Exception{
b4j.example.vmcontainer _cont = null;
b4j.example.vmcontainer _chipsx = null;
b4j.example.vmchipgroup _cg = null;
b4j.example.vmcontainer _xcont = null;
b4j.example.vmcard _product1 = null;
b4j.example.vmcardtext _vcardtext = null;
b4j.example.vmchipgroup _cg1 = null;
b4j.example.vmbutton _btnadd2cart = null;
b4j.example.vmcard _shirtblouse = null;
b4j.example.vmcardtext _cardtext1 = null;
b4j.example.vmchipgroup _cg2 = null;
b4j.example.vmbutton _btnadd2cart1 = null;
b4j.example.vmelement _card3 = null;
b4j.example.vmelement _tbl1 = null;
b4j.example.vmelement _btn1 = null;
b4j.example.vmelement _icn = null;
b4j.example.vmelement _tt = null;
b4j.example.vmelement _c3t1 = null;
b4j.example.vmelement _c3t2 = null;
b4j.example.vmelement _h2 = null;
b4j.example.vmchipgroup _cg4 = null;
anywheresoftware.b4a.objects.collections.List _amenities = null;
b4j.example.vmelement _h2a = null;
b4j.example.vmchipgroup _cg5 = null;
anywheresoftware.b4a.objects.collections.List _neighborhoods = null;
 //BA.debugLineNum = 11;BA.debugLine="Sub Code";
 //BA.debugLineNum = 12;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 13;BA.debugLine="vue = vm.vue";
_vue = _vm._vue /*b4j.example.bananovue*/ ;
 //BA.debugLineNum = 15;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,modchips.getObject());
 //BA.debugLineNum = 17;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 18;BA.debugLine="cont.AddRows(10).AddColumns12";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (10))._addcolumns12 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 20;BA.debugLine="Dim chipsx As VMContainer = vm.CreateContainer(\"c";
_chipsx = _vm._createcontainer /*b4j.example.vmcontainer*/ ("chips",modchips.getObject())._settextcenter /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 22;BA.debugLine="vm.CreateChip(\"c1\", Me).AddClass(\"ma-2\").SetText(";
_vm._createchip /*b4j.example.vmchip*/ ("c1",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._settext /*b4j.example.vmchip*/ ("Default")._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 23;BA.debugLine="vm.CreateChip(\"c2\", Me).AddClass(\"ma-2\").SetText(";
_vm._createchip /*b4j.example.vmchip*/ ("c2",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._settext /*b4j.example.vmchip*/ ("Primary")._setcolor /*b4j.example.vmchip*/ ("primary")._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 24;BA.debugLine="vm.CreateChip(\"c3\", Me).AddClass(\"ma-2\").SetText(";
_vm._createchip /*b4j.example.vmchip*/ ("c3",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._settext /*b4j.example.vmchip*/ ("Secondary")._setcolor /*b4j.example.vmchip*/ ("secondary")._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 25;BA.debugLine="vm.CreateChip(\"c4\", Me).AddClass(\"ma-2\").SetText(";
_vm._createchip /*b4j.example.vmchip*/ ("c4",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._settext /*b4j.example.vmchip*/ ("Red Chip")._settextcolor /*b4j.example.vmchip*/ ("white")._setcolor /*b4j.example.vmchip*/ ("red")._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 26;BA.debugLine="vm.CreateChip(\"c5\", Me).AddClass(\"ma-2\").SetText(";
_vm._createchip /*b4j.example.vmchip*/ ("c5",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._settext /*b4j.example.vmchip*/ ("Green Chip")._settextcolor /*b4j.example.vmchip*/ ("white")._setcolor /*b4j.example.vmchip*/ ("green")._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 28;BA.debugLine="vm.createchip(\"c6\", Me).AddClass(\"ma-2\").SetColor";
_vm._createchip /*b4j.example.vmchip*/ ("c6",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._setcolor /*b4j.example.vmchip*/ (_vm._color_indigo /*String*/ )._settextcolor /*b4j.example.vmchip*/ (_vm._color_white /*String*/ )._seticon /*b4j.example.vmchip*/ ("mdi-account-circle","left")._settext /*b4j.example.vmchip*/ ("Ranee")._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 29;BA.debugLine="vm.createchip(\"c7\", Me).AddClass(\"ma-2\").SetColor";
_vm._createchip /*b4j.example.vmchip*/ ("c7",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._setcolor /*b4j.example.vmchip*/ (_vm._color_indigo /*String*/ )._settextcolor /*b4j.example.vmchip*/ (_vm._color_white /*String*/ )._settext /*b4j.example.vmchip*/ ("Premium")._seticon /*b4j.example.vmchip*/ ("mdi-star","right")._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 30;BA.debugLine="vm.createchip(\"c8\", Me).AddClass(\"ma-2\").SetColor";
_vm._createchip /*b4j.example.vmchip*/ ("c8",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._setcolor /*b4j.example.vmchip*/ (_vm._color_teal /*String*/ )._settextcolor /*b4j.example.vmchip*/ (_vm._color_white /*String*/ )._seticon /*b4j.example.vmchip*/ ("mdi-checkbox-marked-circle","left")._settext /*b4j.example.vmchip*/ ("Confirm")._setclose /*b4j.example.vmchip*/ (anywheresoftware.b4a.keywords.Common.True)._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 31;BA.debugLine="vm.createchip(\"c9\", Me).AddClass(\"ma-2\").SetColor";
_vm._createchip /*b4j.example.vmchip*/ ("c9",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._setcolor /*b4j.example.vmchip*/ (_vm._color_teal /*String*/ )._setcloseicon /*b4j.example.vmchip*/ ("mdi-delete")._settextcolor /*b4j.example.vmchip*/ (_vm._color_white /*String*/ )._seticon /*b4j.example.vmchip*/ ("mdi-checkbox-marked-circle","left")._settext /*b4j.example.vmchip*/ ("TheMash")._setclose /*b4j.example.vmchip*/ (anywheresoftware.b4a.keywords.Common.True)._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 32;BA.debugLine="vm.createchip(\"c10\", Me).AddClass(\"ma-2\").SetColo";
_vm._createchip /*b4j.example.vmchip*/ ("c10",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._setcolor /*b4j.example.vmchip*/ ("success")._seticon /*b4j.example.vmchip*/ ("mdi-server-plus","left")._setoutlined /*b4j.example.vmchip*/ (anywheresoftware.b4a.keywords.Common.True)._settext /*b4j.example.vmchip*/ ("Server Status")._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 33;BA.debugLine="vm.createchip(\"c11\", Me).AddClass(\"ma-2\").SetColo";
_vm._createchip /*b4j.example.vmchip*/ ("c11",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._setcolor /*b4j.example.vmchip*/ (_vm._color_pink /*String*/ )._settextcolor /*b4j.example.vmchip*/ (_vm._color_white /*String*/ )._seticon /*b4j.example.vmchip*/ ("mdi-label","left")._setlabel /*b4j.example.vmchip*/ (anywheresoftware.b4a.keywords.Common.True)._settext /*b4j.example.vmchip*/ ("Tags")._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 34;BA.debugLine="vm.createchip(\"c12\", Me).AddClass(\"ma-2\").SetColo";
_vm._createchip /*b4j.example.vmchip*/ ("c12",modchips.getObject())._addclass /*b4j.example.vmchip*/ ("ma-2")._setcolor /*b4j.example.vmchip*/ (_vm._color_red /*String*/ )._settextcolor /*b4j.example.vmchip*/ (_vm._color_white /*String*/ )._settext /*b4j.example.vmchip*/ ("Remove")._setclose /*b4j.example.vmchip*/ (anywheresoftware.b4a.keywords.Common.True)._addtocontainer /*String*/ (_chipsx,(int) (0),(int) (0));
 //BA.debugLineNum = 35;BA.debugLine="cont.AddComponent(1, 1, chipsx.ToString)";
_cont._addcomponent /*String*/ ((int) (1),(int) (1),_chipsx._tostring /*String*/ ());
 //BA.debugLineNum = 38;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 39;BA.debugLine="vue.AddCode($\"vm.CreateChip(\"c1\", Me).AddClass(\"ma";
_vue._addcode /*String*/ (("vm.CreateChip(\"c1\", Me).AddClass(\"ma-2\").SetText(\"Default\").AddToContainer(chipsx, 0 , 0)"));
 //BA.debugLineNum = 40;BA.debugLine="vue.AddCode($\"vm.CreateChip(\"c2\", Me).AddClass(\"ma";
_vue._addcode /*String*/ (("vm.CreateChip(\"c2\", Me).AddClass(\"ma-2\").SetText(\"Primary\").SetColor(\"primary\").AddToContainer(chipsx, 0 , 0)"));
 //BA.debugLineNum = 41;BA.debugLine="vue.AddCode($\"vm.CreateChip(\"c3\", Me).AddClass(\"ma";
_vue._addcode /*String*/ (("vm.CreateChip(\"c3\", Me).AddClass(\"ma-2\").SetText(\"Secondary\").SetColor(\"secondary\").AddToContainer(chipsx, 0 , 0)"));
 //BA.debugLineNum = 42;BA.debugLine="vue.AddCode($\"vm.CreateChip(\"c4\", Me).AddClass(\"ma";
_vue._addcode /*String*/ (("vm.CreateChip(\"c4\", Me).AddClass(\"ma-2\").SetText(\"Red Chip\").SetTextColor(\"white\").SetColor(\"red\").AddToContainer(chipsx, 0 , 0)"));
 //BA.debugLineNum = 43;BA.debugLine="vue.AddCode($\"vm.CreateChip(\"c5\", Me).AddClass(\"ma";
_vue._addcode /*String*/ (("vm.CreateChip(\"c5\", Me).AddClass(\"ma-2\").SetText(\"Green Chip\").SetTextColor(\"white\").SetColor(\"green\").AddToContainer(chipsx, 0 , 0)"));
 //BA.debugLineNum = 44;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 45;BA.debugLine="vue.AddCode($\"vm.createchip(\"c6\", Me).AddClass(\"ma";
_vue._addcode /*String*/ (("vm.createchip(\"c6\", Me).AddClass(\"ma-2\").SetColor(vm.COLOR_INDIGO).SetTextColor(vm.COLOR_WHITE).SetIcon(\"mdi-account-circle\", \"left\").SetText(\"Ranee\").AddToContainer(chipsx, 0, 0)"));
 //BA.debugLineNum = 46;BA.debugLine="vue.AddCode($\"vm.createchip(\"c7\", Me).AddClass(\"ma";
_vue._addcode /*String*/ (("vm.createchip(\"c7\", Me).AddClass(\"ma-2\").SetColor(vm.COLOR_INDIGO).SetTextColor(vm.COLOR_WHITE).SetText(\"Premium\").SetIcon(\"mdi-star\", \"right\").AddToContainer(chipsx, 0, 0)"));
 //BA.debugLineNum = 47;BA.debugLine="vue.AddCode($\"vm.createchip(\"c8\", Me).AddClass(\"ma";
_vue._addcode /*String*/ (("vm.createchip(\"c8\", Me).AddClass(\"ma-2\").SetColor(vm.COLOR_TEAL).SetTextColor(vm.COLOR_WHITE).SetIcon(\"mdi-checkbox-marked-circle\", \"left\").SetText(\"Confirm\").SetClose(True).AddToContainer(chipsx, 0, 0)"));
 //BA.debugLineNum = 48;BA.debugLine="vue.AddCode($\"vm.createchip(\"c9\", Me).AddClass(\"ma";
_vue._addcode /*String*/ (("vm.createchip(\"c9\", Me).AddClass(\"ma-2\").SetColor(vm.COLOR_TEAL).SetCloseIcon(\"mdi-delete\").SetTextColor(vm.COLOR_WHITE).SetIcon(\"mdi-checkbox-marked-circle\", \"left\").SetText(\"TheMash\").SetClose(True).AddToContainer(chipsx, 0, 0)"));
 //BA.debugLineNum = 49;BA.debugLine="vue.AddCode($\"vm.createchip(\"c10\", Me).AddClass(\"m";
_vue._addcode /*String*/ (("vm.createchip(\"c10\", Me).AddClass(\"ma-2\").SetColor(\"success\").SetIcon(\"mdi-server-plus\", \"left\").SetOutlined(True).SetText(\"Server Status\").AddToContainer(chipsx, 0, 0)"));
 //BA.debugLineNum = 50;BA.debugLine="vue.AddCode($\"vm.createchip(\"c11\", Me).AddClass(\"m";
_vue._addcode /*String*/ (("vm.createchip(\"c11\", Me).AddClass(\"ma-2\").SetColor(vm.COLOR_PINK).SetTextColor(vm.COLOR_WHITE).SetIcon(\"mdi-label\", \"left\").SetLabel(True).SetText(\"Tags\").AddToContainer(chipsx, 0, 0)"));
 //BA.debugLineNum = 51;BA.debugLine="vue.AddCode($\"vm.createchip(\"c12\", Me).AddClass(\"m";
_vue._addcode /*String*/ (("vm.createchip(\"c12\", Me).AddClass(\"ma-2\").SetColor(vm.COLOR_RED).SetTextColor(vm.COLOR_WHITE).SetText(\"Remove\").SetClose(True).AddToContainer(chipsx, 0, 0)"));
 //BA.debugLineNum = 52;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 53;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"chipscode\", \"Chips\"";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modchips.getObject(),"chipscode","Chips",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (2),(int) (1));
 //BA.debugLineNum = 56;BA.debugLine="Dim cg As VMChipGroup = vm.CreateChipGroup(\"cg\",";
_cg = _vm._createchipgroup /*b4j.example.vmchipgroup*/ ("cg",modchips.getObject())._setcolumn /*b4j.example.vmchipgroup*/ ((Object)(anywheresoftware.b4a.keywords.Common.True))._setactiveclass /*b4j.example.vmchipgroup*/ ((Object)(_vm._color_primary_text /*String*/ ));
 //BA.debugLineNum = 57;BA.debugLine="cg.AddItems(Array(\"Work\", \"Home Improvement\", \"Va";
_cg._additems /*b4j.example.vmchipgroup*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("Work"),(Object)("Home Improvement"),(Object)("Vacation"),(Object)("Food"),(Object)("Drawers")}));
 //BA.debugLineNum = 58;BA.debugLine="cg.AddItems(Array(\"Shopping\", \"Art\", \"Tech\", \"Cre";
_cg._additems /*b4j.example.vmchipgroup*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("Shopping"),(Object)("Art"),(Object)("Tech"),(Object)("Creative Writing")}));
 //BA.debugLineNum = 59;BA.debugLine="cg.AddToContainer(cont, 3, 1)";
_cg._addtocontainer /*String*/ (_cont,(int) (3),(int) (1));
 //BA.debugLineNum = 62;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 63;BA.debugLine="vue.AddCode($\"'chip groups\"$)";
_vue._addcode /*String*/ (("'chip groups"));
 //BA.debugLineNum = 64;BA.debugLine="vue.AddCode($\"Dim cg As VMChipGroup = vm.CreateChi";
_vue._addcode /*String*/ (("Dim cg As VMChipGroup = vm.CreateChipGroup(\"cg\", Me).SetColumn(True).SetActiveClass(vm.COLOR_PRIMARY_TEXT)"));
 //BA.debugLineNum = 65;BA.debugLine="vue.AddCode($\"cg.AddItems(Array(\"Work\", \"Home Impr";
_vue._addcode /*String*/ (("cg.AddItems(Array(\"Work\", \"Home Improvement\", \"Vacation\", \"Food\", \"Drawers\"))"));
 //BA.debugLineNum = 66;BA.debugLine="vue.AddCode($\"cg.AddItems(Array(\"Shopping\", \"Art\",";
_vue._addcode /*String*/ (("cg.AddItems(Array(\"Shopping\", \"Art\", \"Tech\", \"Creative Writing\"))"));
 //BA.debugLineNum = 67;BA.debugLine="vue.AddCode($\"cg.AddToContainer(cont, 3, 1)\"$)";
_vue._addcode /*String*/ (("cg.AddToContainer(cont, 3, 1)"));
 //BA.debugLineNum = 68;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"chipgroup\", \"Chip";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modchips.getObject(),"chipgroup","Chip Group",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (4),(int) (1));
 //BA.debugLineNum = 70;BA.debugLine="Dim xcont As VMContainer = vm.CreateContainer(\"xc";
_xcont = _vm._createcontainer /*b4j.example.vmcontainer*/ ("xcont",modchips.getObject());
 //BA.debugLineNum = 71;BA.debugLine="xcont.AddRows(1).AddColumns4x3";
_xcont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns4x3 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 73;BA.debugLine="Dim product1 As VMCard = vm.CreateCard(\"product1\"";
_product1 = _vm._createcard /*b4j.example.vmcard*/ ("product1",modchips.getObject())._addclass /*b4j.example.vmcard*/ ("mx-auto")._setmaxwidth /*b4j.example.vmcard*/ ("auto");
 //BA.debugLineNum = 75;BA.debugLine="product1.Title.AddElement(\"\", \"h2\", \"Toothbrush\",";
_product1._title /*b4j.example.vmcardtitle*/ ._addelement /*b4j.example.vmcardtitle*/ ("","h2","Toothbrush",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("display-1")}));
 //BA.debugLineNum = 76;BA.debugLine="product1.Title.AddSpacer";
_product1._title /*b4j.example.vmcardtitle*/ ._addspacer /*b4j.example.vmcardtitle*/ ();
 //BA.debugLineNum = 77;BA.debugLine="product1.Title.AddElement(\"\", \"span\", \"$4.99\", Nu";
_product1._title /*b4j.example.vmcardtitle*/ ._addelement /*b4j.example.vmcardtitle*/ ("","span","$4.99",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("title")}));
 //BA.debugLineNum = 79;BA.debugLine="product1.Text.SetText(\"Our company takes pride in";
_product1._text /*b4j.example.vmcardtext*/ ._settext /*b4j.example.vmcardtext*/ ("Our company takes pride in making handmade brushes.");
 //BA.debugLineNum = 80;BA.debugLine="product1.Text.SetText(\"Our toothbrushes are avail";
_product1._text /*b4j.example.vmcardtext*/ ._settext /*b4j.example.vmcardtext*/ ("Our toothbrushes are available in 4 different bristel types, from extra soft To hard.");
 //BA.debugLineNum = 82;BA.debugLine="product1.SetTextAfterDivider(\"mx-4\")";
_product1._settextafterdivider /*b4j.example.vmcard*/ ("mx-4");
 //BA.debugLineNum = 84;BA.debugLine="Dim vcardtext As VMCardText = vm.CreateCardText(\"";
_vcardtext = _vm._createcardtext /*b4j.example.vmcardtext*/ ("",modchips.getObject());
 //BA.debugLineNum = 86;BA.debugLine="vcardtext.AddElement(\"\", \"span\", \"Select Type\", N";
_vcardtext._addelement /*b4j.example.vmcardtext*/ ("","span","Select Type",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("subheading")}));
 //BA.debugLineNum = 88;BA.debugLine="Dim cg1 As VMChipGroup = vm.CreateChipGroup(\"cg1\"";
_cg1 = _vm._createchipgroup /*b4j.example.vmchipgroup*/ ("cg1",modchips.getObject());
 //BA.debugLineNum = 89;BA.debugLine="cg1.SetVModel(\"selection\").SetData(\"selection\", 2";
_cg1._setvmodel /*b4j.example.vmchipgroup*/ ("selection")._setdata /*b4j.example.vmchipgroup*/ ("selection",(Object)(2))._setactiveclass /*b4j.example.vmchipgroup*/ ((Object)("deep-purple--text text--accent-4"))._setmandatory /*b4j.example.vmchipgroup*/ ((Object)(anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 90;BA.debugLine="cg1.AddItems(Array(\"Extra Soft\", \"Soft\", \"Medium\"";
_cg1._additems /*b4j.example.vmchipgroup*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("Extra Soft"),(Object)("Soft"),(Object)("Medium"),(Object)("Hard")}));
 //BA.debugLineNum = 92;BA.debugLine="vcardtext.SetText(cg1.ToString)";
_vcardtext._settext /*b4j.example.vmcardtext*/ (_cg1._tostring /*String*/ ());
 //BA.debugLineNum = 93;BA.debugLine="product1.SetTextAfter(vcardtext.tostring)";
_product1._settextafter /*b4j.example.vmcard*/ (_vcardtext._tostring /*String*/ ());
 //BA.debugLineNum = 95;BA.debugLine="Dim btnAdd2Cart As VMButton = vm.CreateButton(\"\",";
_btnadd2cart = _vm._createbutton /*b4j.example.vmbutton*/ ("",modchips.getObject());
 //BA.debugLineNum = 96;BA.debugLine="btnAdd2Cart.SetBlock(True)";
_btnadd2cart._setblock /*b4j.example.vmbutton*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 97;BA.debugLine="btnAdd2Cart.SetTextColor(vm.COLOR_WHITE)";
_btnadd2cart._settextcolor /*b4j.example.vmbutton*/ (_vm._color_white /*String*/ );
 //BA.debugLineNum = 98;BA.debugLine="btnAdd2Cart.SetColorIntensity(vm.COLOR_DEEPPURPLE";
_btnadd2cart._setcolorintensity /*b4j.example.vmbutton*/ (_vm._color_deeppurple /*String*/ ,_vm._intensity_accent4 /*String*/ );
 //BA.debugLineNum = 99;BA.debugLine="btnAdd2Cart.SetLabel(\"Add to Cart\")";
_btnadd2cart._setlabel /*b4j.example.vmbutton*/ ("Add to Cart");
 //BA.debugLineNum = 101;BA.debugLine="product1.Actions.AddButton(btnAdd2Cart)";
_product1._actions /*b4j.example.vmcardactions*/ ._addbutton /*b4j.example.vmcardactions*/ (_btnadd2cart);
 //BA.debugLineNum = 102;BA.debugLine="product1.AddToContainer(xcont, 1, 1)";
_product1._addtocontainer /*String*/ (_xcont,(int) (1),(int) (1));
 //BA.debugLineNum = 105;BA.debugLine="Dim shirtBlouse As VMCard = vm.CreateCard(\"shirtB";
_shirtblouse = _vm._createcard /*b4j.example.vmcard*/ ("shirtBlouse",modchips.getObject())._addclass /*b4j.example.vmcard*/ ("mx-auto")._setmaxwidth /*b4j.example.vmcard*/ ("400");
 //BA.debugLineNum = 106;BA.debugLine="shirtBlouse.Title.AddElement(\"\", \"h2\", \"Shirt Blo";
_shirtblouse._title /*b4j.example.vmcardtitle*/ ._addelement /*b4j.example.vmcardtitle*/ ("","h2","Shirt Blouse",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("display-1")}));
 //BA.debugLineNum = 107;BA.debugLine="shirtBlouse.Title.AddSpacer";
_shirtblouse._title /*b4j.example.vmcardtitle*/ ._addspacer /*b4j.example.vmcardtitle*/ ();
 //BA.debugLineNum = 108;BA.debugLine="shirtBlouse.Title.AddElement(\"\", \"span\", \"$44.50\"";
_shirtblouse._title /*b4j.example.vmcardtitle*/ ._addelement /*b4j.example.vmcardtitle*/ ("","span","$44.50",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("title")}));
 //BA.debugLineNum = 109;BA.debugLine="shirtBlouse.Text.SetText(\"Our blouses are availab";
_shirtblouse._text /*b4j.example.vmcardtext*/ ._settext /*b4j.example.vmcardtext*/ ("Our blouses are available in 8 colors. You can custom order a built-in arch support For any of the models.");
 //BA.debugLineNum = 110;BA.debugLine="shirtBlouse.SetTextAfterDivider(\"mx-4\")";
_shirtblouse._settextafterdivider /*b4j.example.vmcard*/ ("mx-4");
 //BA.debugLineNum = 112;BA.debugLine="Dim cardText1 As VMCardText = vm.CreateCardText(\"";
_cardtext1 = _vm._createcardtext /*b4j.example.vmcardtext*/ ("",modchips.getObject());
 //BA.debugLineNum = 113;BA.debugLine="cardText1.AddElement(\"\", \"span\", \"Select Size\", N";
_cardtext1._addelement /*b4j.example.vmcardtext*/ ("","span","Select Size",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("subheading")}));
 //BA.debugLineNum = 115;BA.debugLine="Dim cg2 As VMChipGroup = vm.CreateChipGroup(\"cg2\"";
_cg2 = _vm._createchipgroup /*b4j.example.vmchipgroup*/ ("cg2",modchips.getObject())._setvmodel /*b4j.example.vmchipgroup*/ ("cg2selection")._setdata /*b4j.example.vmchipgroup*/ ("cg2selection",(Object)("08"))._setmandatory /*b4j.example.vmchipgroup*/ ((Object)(anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 116;BA.debugLine="cg2.SetActiveClass(\"deep-purple--text text--accen";
_cg2._setactiveclass /*b4j.example.vmchipgroup*/ ((Object)("deep-purple--text text--accent-4"));
 //BA.debugLineNum = 117;BA.debugLine="cg2.AddItems(Array(\"04\", \"06\", \"08\", \"10\", \"12\",";
_cg2._additems /*b4j.example.vmchipgroup*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("04"),(Object)("06"),(Object)("08"),(Object)("10"),(Object)("12"),(Object)("14")}));
 //BA.debugLineNum = 119;BA.debugLine="cardText1.SetText(cg2.ToString)";
_cardtext1._settext /*b4j.example.vmcardtext*/ (_cg2._tostring /*String*/ ());
 //BA.debugLineNum = 120;BA.debugLine="shirtBlouse.SetTextAfter(cardText1.ToString)";
_shirtblouse._settextafter /*b4j.example.vmcard*/ (_cardtext1._tostring /*String*/ ());
 //BA.debugLineNum = 122;BA.debugLine="Dim btnAdd2Cart1 As VMButton = vm.CreateButton(\"\"";
_btnadd2cart1 = _vm._createbutton /*b4j.example.vmbutton*/ ("",modchips.getObject());
 //BA.debugLineNum = 123;BA.debugLine="btnAdd2Cart1.SetBlock(True)";
_btnadd2cart1._setblock /*b4j.example.vmbutton*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 124;BA.debugLine="btnAdd2Cart1.SetTextColor(vm.COLOR_WHITE)";
_btnadd2cart1._settextcolor /*b4j.example.vmbutton*/ (_vm._color_white /*String*/ );
 //BA.debugLineNum = 125;BA.debugLine="btnAdd2Cart1.SetColorIntensity(vm.COLOR_DEEPPURPL";
_btnadd2cart1._setcolorintensity /*b4j.example.vmbutton*/ (_vm._color_deeppurple /*String*/ ,_vm._intensity_accent4 /*String*/ );
 //BA.debugLineNum = 126;BA.debugLine="btnAdd2Cart1.SetLabel(\"Add to Cart\")";
_btnadd2cart1._setlabel /*b4j.example.vmbutton*/ ("Add to Cart");
 //BA.debugLineNum = 128;BA.debugLine="shirtBlouse.Actions.AddButton(btnAdd2Cart1)";
_shirtblouse._actions /*b4j.example.vmcardactions*/ ._addbutton /*b4j.example.vmcardactions*/ (_btnadd2cart1);
 //BA.debugLineNum = 129;BA.debugLine="shirtBlouse.AddToContainer(xcont, 1, 2)";
_shirtblouse._addtocontainer /*String*/ (_xcont,(int) (1),(int) (2));
 //BA.debugLineNum = 132;BA.debugLine="Dim card3 As VMElement = vm.VCard(\"card3\").AddCla";
_card3 = _vm._vcard /*b4j.example.vmelement*/ ("card3")._addclass /*b4j.example.vmelement*/ ("mx-auto")._setmaxwidth /*b4j.example.vmelement*/ ("400");
 //BA.debugLineNum = 134;BA.debugLine="Dim tbl1 As VMElement = vm.VToolBar(\"card2tbl1\")";
_tbl1 = _vm._vtoolbar /*b4j.example.vmelement*/ ("card2tbl1");
 //BA.debugLineNum = 135;BA.debugLine="tbl1.SetAttr(CreateMap(\"flat\":True, \"color\":\"deep";
_tbl1._setattr /*b4j.example.vmelement*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("flat"),(Object)(anywheresoftware.b4a.keywords.Common.True),(Object)("color"),(Object)("deep-purple accent-4"),(Object)("dark"),(Object)(anywheresoftware.b4a.keywords.Common.True)}));
 //BA.debugLineNum = 137;BA.debugLine="Dim btn1 As VMElement = vm.VBtn(\"\").SetAttrSingle";
_btn1 = _vm._vbtn /*b4j.example.vmelement*/ ("")._setattrsingle /*b4j.example.vmelement*/ ("icon",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.True))._settextcolor /*b4j.example.vmelement*/ (_vm._color_white /*String*/ );
 //BA.debugLineNum = 138;BA.debugLine="Dim icn As VMElement = vm.VIcon(\"\").SetText(\"mdi-";
_icn = _vm._vicon /*b4j.example.vmelement*/ ("")._settext /*b4j.example.vmelement*/ ("mdi-close");
 //BA.debugLineNum = 139;BA.debugLine="btn1.AddElement(icn)";
_btn1._addelement /*b4j.example.vmelement*/ (_icn);
 //BA.debugLineNum = 140;BA.debugLine="tbl1.AddElement(btn1)";
_tbl1._addelement /*b4j.example.vmelement*/ (_btn1);
 //BA.debugLineNum = 142;BA.debugLine="Dim tt As VMElement = vm.VToolbarTitle(\"\").SetTex";
_tt = _vm._vtoolbartitle /*b4j.example.vmelement*/ ("")._settext /*b4j.example.vmelement*/ ("Filter Results")._settextcolor /*b4j.example.vmelement*/ (_vm._color_white /*String*/ );
 //BA.debugLineNum = 143;BA.debugLine="tbl1.AddElement(tt)";
_tbl1._addelement /*b4j.example.vmelement*/ (_tt);
 //BA.debugLineNum = 144;BA.debugLine="card3.AddElement(tbl1)";
_card3._addelement /*b4j.example.vmelement*/ (_tbl1);
 //BA.debugLineNum = 146;BA.debugLine="Dim c3t1 As VMElement = vm.VCardText(\"\")";
_c3t1 = _vm._vcardtext /*b4j.example.vmelement*/ ("");
 //BA.debugLineNum = 147;BA.debugLine="Dim c3t2 As VMElement = vm.VCardText(\"\")";
_c3t2 = _vm._vcardtext /*b4j.example.vmelement*/ ("");
 //BA.debugLineNum = 149;BA.debugLine="Dim h2 As VMElement = vm.H2(\"\").AddClass(\"title m";
_h2 = _vm._h2 /*b4j.example.vmelement*/ ("")._addclass /*b4j.example.vmelement*/ ("title mb-2")._settext /*b4j.example.vmelement*/ ("Choose amenities");
 //BA.debugLineNum = 150;BA.debugLine="c3t1.AddElement(h2)";
_c3t1._addelement /*b4j.example.vmelement*/ (_h2);
 //BA.debugLineNum = 153;BA.debugLine="Dim cg4 As VMChipGroup = vm.CreateChipGroup(\"cg4\"";
_cg4 = _vm._createchipgroup /*b4j.example.vmchipgroup*/ ("cg4",modchips.getObject())._setvmodel /*b4j.example.vmchipgroup*/ ("amenities");
 //BA.debugLineNum = 154;BA.debugLine="cg4.SetMultiple(True)";
_cg4._setmultiple /*b4j.example.vmchipgroup*/ ((Object)(anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 155;BA.debugLine="cg4.SetColumn(True)";
_cg4._setcolumn /*b4j.example.vmchipgroup*/ ((Object)(anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 156;BA.debugLine="Dim amenities As List = vm.NewList1(Array As Stri";
_amenities = new anywheresoftware.b4a.objects.collections.List();
_amenities = _vm._newlist1 /*anywheresoftware.b4a.objects.collections.List*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"washer","dogs"}));
 //BA.debugLineNum = 157;BA.debugLine="cg4.SetData(\"amenities\", amenities)";
_cg4._setdata /*b4j.example.vmchipgroup*/ ("amenities",(Object)(_amenities.getObject()));
 //BA.debugLineNum = 158;BA.debugLine="cg4.AddItem(\"elevator\", True, True, \"Elevator\")";
_cg4._additem /*String*/ ("elevator",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Elevator");
 //BA.debugLineNum = 159;BA.debugLine="cg4.AddItem(\"washer\", True, True, \"Washer\")";
_cg4._additem /*String*/ ("washer",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Washer");
 //BA.debugLineNum = 160;BA.debugLine="cg4.AddItem(\"fireplace\", True, True, \"Fireplace\")";
_cg4._additem /*String*/ ("fireplace",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Fireplace");
 //BA.debugLineNum = 161;BA.debugLine="cg4.AddItem(\"wheelchair\", True, True,  \"Wheelchai";
_cg4._additem /*String*/ ("wheelchair",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Wheelchair");
 //BA.debugLineNum = 162;BA.debugLine="cg4.AddItem(\"dogs\", True, True,  \"Dogs ok\")";
_cg4._additem /*String*/ ("dogs",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Dogs ok");
 //BA.debugLineNum = 163;BA.debugLine="cg4.AddItem(\"cats\", True, True, \"Cats ok\")";
_cg4._additem /*String*/ ("cats",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Cats ok");
 //BA.debugLineNum = 164;BA.debugLine="c3t1.SetText(cg4.tostring)";
_c3t1._settext /*b4j.example.vmelement*/ (_cg4._tostring /*String*/ ());
 //BA.debugLineNum = 166;BA.debugLine="card3.AddElement(c3t1)";
_card3._addelement /*b4j.example.vmelement*/ (_c3t1);
 //BA.debugLineNum = 168;BA.debugLine="Dim h2a As VMElement = vm.H2(\"\").AddClass(\"title";
_h2a = _vm._h2 /*b4j.example.vmelement*/ ("")._addclass /*b4j.example.vmelement*/ ("title mb-2")._settext /*b4j.example.vmelement*/ ("Choose neighborhoods");
 //BA.debugLineNum = 169;BA.debugLine="c3t2.AddElement(h2a)";
_c3t2._addelement /*b4j.example.vmelement*/ (_h2a);
 //BA.debugLineNum = 171;BA.debugLine="Dim cg5 As VMChipGroup = vm.CreateChipGroup(\"cg5\"";
_cg5 = _vm._createchipgroup /*b4j.example.vmchipgroup*/ ("cg5",modchips.getObject())._setvmodel /*b4j.example.vmchipgroup*/ ("neighborhoods");
 //BA.debugLineNum = 172;BA.debugLine="cg5.SetMultiple(True)";
_cg5._setmultiple /*b4j.example.vmchipgroup*/ ((Object)(anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 173;BA.debugLine="cg5.SetColumn(True)";
_cg5._setcolumn /*b4j.example.vmchipgroup*/ ((Object)(anywheresoftware.b4a.keywords.Common.True));
 //BA.debugLineNum = 174;BA.debugLine="Dim neighborhoods As List = vm.NewList1(Array As";
_neighborhoods = new anywheresoftware.b4a.objects.collections.List();
_neighborhoods = _vm._newlist1 /*anywheresoftware.b4a.objects.collections.List*/ (anywheresoftware.b4a.keywords.Common.ArrayToList(new String[]{"3","4"}));
 //BA.debugLineNum = 175;BA.debugLine="cg5.SetData(\"neighborhoods\", neighborhoods)";
_cg5._setdata /*b4j.example.vmchipgroup*/ ("neighborhoods",(Object)(_neighborhoods.getObject()));
 //BA.debugLineNum = 176;BA.debugLine="cg5.AddItem(\"1\", True, True,  \"Snowy Rock Place\")";
_cg5._additem /*String*/ ("1",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Snowy Rock Place");
 //BA.debugLineNum = 177;BA.debugLine="cg5.AddItem(\"2\", True, True,  \"Honeylane Circle\")";
_cg5._additem /*String*/ ("2",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Honeylane Circle");
 //BA.debugLineNum = 178;BA.debugLine="cg5.AddItem(\"3\", True, True,  \"Donna Drive\")";
_cg5._additem /*String*/ ("3",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Donna Drive");
 //BA.debugLineNum = 179;BA.debugLine="cg5.AddItem(\"4\", True, True,  \"Elaine Street\")";
_cg5._additem /*String*/ ("4",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Elaine Street");
 //BA.debugLineNum = 180;BA.debugLine="cg5.AddItem(\"5\", True, True,  \"Court Street\")";
_cg5._additem /*String*/ ("5",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Court Street");
 //BA.debugLineNum = 181;BA.debugLine="cg5.AddItem(\"6\", True, True,  \"Kennedy Park\")";
_cg5._additem /*String*/ ("6",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"Kennedy Park");
 //BA.debugLineNum = 182;BA.debugLine="c3t2.SetText(cg5.tostring)";
_c3t2._settext /*b4j.example.vmelement*/ (_cg5._tostring /*String*/ ());
 //BA.debugLineNum = 184;BA.debugLine="card3.AddElement(c3t2)";
_card3._addelement /*b4j.example.vmelement*/ (_c3t2);
 //BA.debugLineNum = 187;BA.debugLine="card3.AddToContainer(xcont, 1, 3)";
_card3._addtocontainer /*String*/ (_xcont,(int) (1),(int) (3));
 //BA.debugLineNum = 189;BA.debugLine="cont.AddComponent(5,1, xcont.tostring)";
_cont._addcomponent /*String*/ ((int) (5),(int) (1),_xcont._tostring /*String*/ ());
 //BA.debugLineNum = 195;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 196;BA.debugLine="vue.AddCode($\"Dim xcont As VMContainer = vm.Create";
_vue._addcode /*String*/ (("Dim xcont As VMContainer = vm.CreateContainer(\"xcont\", Me)"));
 //BA.debugLineNum = 197;BA.debugLine="vue.AddCode($\"xcont.AddRows(1).AddColumns4x3\"$)";
_vue._addcode /*String*/ (("xcont.AddRows(1).AddColumns4x3"));
 //BA.debugLineNum = 198;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 199;BA.debugLine="vue.AddCode($\"Dim product1 As VMCard = vm.CreateCa";
_vue._addcode /*String*/ (("Dim product1 As VMCard = vm.CreateCard(\"product1\", Me).AddClass(\"mx-auto\").SetMaxWidth(\"auto\")"));
 //BA.debugLineNum = 200;BA.debugLine="vue.AddCode($\"'** title add own heading\"$)";
_vue._addcode /*String*/ (("'** title add own heading"));
 //BA.debugLineNum = 201;BA.debugLine="vue.AddCode($\"product1.Title.AddElement(\"\", \"h2\",";
_vue._addcode /*String*/ (("product1.Title.AddElement(\"\", \"h2\", \"Toothbrush\", Null, Null, Array(\"display-1\"))"));
 //BA.debugLineNum = 202;BA.debugLine="vue.AddCode($\"product1.Title.AddSpacer\"$)";
_vue._addcode /*String*/ (("product1.Title.AddSpacer"));
 //BA.debugLineNum = 203;BA.debugLine="vue.AddCode($\"product1.Title.AddElement(\"\", \"span\"";
_vue._addcode /*String*/ (("product1.Title.AddElement(\"\", \"span\", \"~4.99\", Null, Null, Array(\"title\"))"));
 //BA.debugLineNum = 204;BA.debugLine="vue.AddCode($\"'** text\"$)";
_vue._addcode /*String*/ (("'** text"));
 //BA.debugLineNum = 205;BA.debugLine="vue.AddCode($\"product1.Text.SetText(\"Our company t";
_vue._addcode /*String*/ (("product1.Text.SetText(\"Our company takes pride in making handmade brushes.\")"));
 //BA.debugLineNum = 206;BA.debugLine="vue.AddCode($\"product1.Text.SetText(\"Our toothbrus";
_vue._addcode /*String*/ (("product1.Text.SetText(\"Our toothbrushes are available in 4 different bristel types, from extra soft To hard.\")"));
 //BA.debugLineNum = 207;BA.debugLine="vue.AddCode($\"'** text after\"$)";
_vue._addcode /*String*/ (("'** text after"));
 //BA.debugLineNum = 208;BA.debugLine="vue.AddCode($\"product1.SetTextAfterDivider(\"mx-4\")";
_vue._addcode /*String*/ (("product1.SetTextAfterDivider(\"mx-4\")"));
 //BA.debugLineNum = 209;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 210;BA.debugLine="vue.AddCode($\"Dim vcardtext As VMCardText = vm.Cre";
_vue._addcode /*String*/ (("Dim vcardtext As VMCardText = vm.CreateCardText(\"\", Me)"));
 //BA.debugLineNum = 211;BA.debugLine="vue.AddCode($\"'add a span\"$)";
_vue._addcode /*String*/ (("'add a span"));
 //BA.debugLineNum = 212;BA.debugLine="vue.AddCode($\"vcardtext.AddElement(\"\", \"span\", \"Se";
_vue._addcode /*String*/ (("vcardtext.AddElement(\"\", \"span\", \"Select Type\", Null, Null, Array(\"subheading\"))"));
 //BA.debugLineNum = 213;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 214;BA.debugLine="vue.AddCode($\"Dim cg1 As VMChipGroup = vm.CreateCh";
_vue._addcode /*String*/ (("Dim cg1 As VMChipGroup = vm.CreateChipGroup(\"\", Me)"));
 //BA.debugLineNum = 215;BA.debugLine="vue.AddCode($\"cg1.SetVModel(\"selection\").SetData(\"";
_vue._addcode /*String*/ (("cg1.SetVModel(\"selection\").SetData(\"selection\", 2).SetActiveClass(\"deep-purple--text text--accent-4\").SetMandatory(True)"));
 //BA.debugLineNum = 216;BA.debugLine="vue.AddCode($\"cg1.AddItems(Array(\"Extra Soft\", \"So";
_vue._addcode /*String*/ (("cg1.AddItems(Array(\"Extra Soft\", \"Soft\", \"Medium\", \"Hard\"))"));
 //BA.debugLineNum = 217;BA.debugLine="vue.AddCode($\"'add chip group to text\"$)";
_vue._addcode /*String*/ (("'add chip group to text"));
 //BA.debugLineNum = 218;BA.debugLine="vue.AddCode($\"vcardtext.SetText(cg1.ToString)\"$)";
_vue._addcode /*String*/ (("vcardtext.SetText(cg1.ToString)"));
 //BA.debugLineNum = 219;BA.debugLine="vue.AddCode($\"product1.SetTextAfter(vcardtext.tost";
_vue._addcode /*String*/ (("product1.SetTextAfter(vcardtext.tostring)"));
 //BA.debugLineNum = 220;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 221;BA.debugLine="vue.AddCode($\"Dim btnAdd2Cart As VMButton = vm.Cre";
_vue._addcode /*String*/ (("Dim btnAdd2Cart As VMButton = vm.CreateButton(\"\", Me)"));
 //BA.debugLineNum = 222;BA.debugLine="vue.AddCode($\"btnAdd2Cart.SetBlock(True)\"$)";
_vue._addcode /*String*/ (("btnAdd2Cart.SetBlock(True)"));
 //BA.debugLineNum = 223;BA.debugLine="vue.AddCode($\"btnAdd2Cart.SetTextColor(vm.COLOR_WH";
_vue._addcode /*String*/ (("btnAdd2Cart.SetTextColor(vm.COLOR_WHITE)"));
 //BA.debugLineNum = 224;BA.debugLine="vue.AddCode($\"btnAdd2Cart.SetColorIntensity(vm.COL";
_vue._addcode /*String*/ (("btnAdd2Cart.SetColorIntensity(vm.COLOR_DEEPPURPLE, vm.INTENSITY_ACCENT4)"));
 //BA.debugLineNum = 225;BA.debugLine="vue.AddCode($\"btnAdd2Cart.SetLabel(\"Add to Cart\")\"";
_vue._addcode /*String*/ (("btnAdd2Cart.SetLabel(\"Add to Cart\")"));
 //BA.debugLineNum = 226;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 227;BA.debugLine="vue.AddCode($\"product1.Actions.AddButton(btnAdd2Ca";
_vue._addcode /*String*/ (("product1.Actions.AddButton(btnAdd2Cart)"));
 //BA.debugLineNum = 228;BA.debugLine="vue.AddCode($\"product1.AddToContainer(xcont, 1, 1)";
_vue._addcode /*String*/ (("product1.AddToContainer(xcont, 1, 1)"));
 //BA.debugLineNum = 229;BA.debugLine="vue.AddCode($\"cont.AddComponent(5,1, xcont.tostrin";
_vue._addcode /*String*/ (("cont.AddComponent(5,1, xcont.tostring)"));
 //BA.debugLineNum = 230;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"toothbrush\", \"Tooth";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modchips.getObject(),"toothbrush","Tooth Brush",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (6),(int) (1));
 //BA.debugLineNum = 234;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 235;BA.debugLine="vue.AddCode($\"Dim shirtBlouse As VMCard = vm.Creat";
_vue._addcode /*String*/ (("Dim shirtBlouse As VMCard = vm.CreateCard(\"shirtBlouse\", Me).AddClass(\"mx-auto\").SetMaxWidth(\"400\")"));
 //BA.debugLineNum = 236;BA.debugLine="vue.AddCode($\"shirtBlouse.Title.AddElement(\"\", \"h2";
_vue._addcode /*String*/ (("shirtBlouse.Title.AddElement(\"\", \"h2\", \"Shirt Blouse\", Null, Null, Array(\"display-1\"))"));
 //BA.debugLineNum = 237;BA.debugLine="vue.AddCode($\"shirtBlouse.Title.AddSpacer\"$)";
_vue._addcode /*String*/ (("shirtBlouse.Title.AddSpacer"));
 //BA.debugLineNum = 238;BA.debugLine="vue.AddCode($\"shirtBlouse.Title.AddElement(\"\", \"sp";
_vue._addcode /*String*/ (("shirtBlouse.Title.AddElement(\"\", \"span\", \"~44.50\", Null, Null, Array(\"title\"))"));
 //BA.debugLineNum = 239;BA.debugLine="vue.AddCode($\"shirtBlouse.Text.SetText(\"Our blouse";
_vue._addcode /*String*/ (("shirtBlouse.Text.SetText(\"Our blouses are available in 8 colors. You can custom order a built-in arch support For any of the models.\")"));
 //BA.debugLineNum = 240;BA.debugLine="vue.AddCode($\"shirtBlouse.SetTextAfterDivider(\"mx-";
_vue._addcode /*String*/ (("shirtBlouse.SetTextAfterDivider(\"mx-4\")"));
 //BA.debugLineNum = 241;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 242;BA.debugLine="vue.AddCode($\"Dim cardText1 As VMCardText = vm.Cre";
_vue._addcode /*String*/ (("Dim cardText1 As VMCardText = vm.CreateCardText(\"\", Me)"));
 //BA.debugLineNum = 243;BA.debugLine="vue.AddCode($\"cardText1.AddElement(\"\", \"span\", \"Se";
_vue._addcode /*String*/ (("cardText1.AddElement(\"\", \"span\", \"Select Size\", Null, Null, Array(\"subheading\"))"));
 //BA.debugLineNum = 244;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 245;BA.debugLine="vue.AddCode($\"Dim cg2 As VMChipGroup = vm.CreateCh";
_vue._addcode /*String*/ (("Dim cg2 As VMChipGroup = vm.CreateChipGroup(\"cg2\", Me).SetVmodel(\"cg2selection\").SetData(\"cg2selection\", \"08\").SetMandatory(True)"));
 //BA.debugLineNum = 246;BA.debugLine="vue.AddCode($\"cg2.SetActiveClass(\"deep-purple--tex";
_vue._addcode /*String*/ (("cg2.SetActiveClass(\"deep-purple--text text--accent-4\")"));
 //BA.debugLineNum = 247;BA.debugLine="vue.AddCode($\"cg2.AddItems(Array(\"04\", \"06\", \"08\",";
_vue._addcode /*String*/ (("cg2.AddItems(Array(\"04\", \"06\", \"08\", \"10\", \"12\", \"14\"))"));
 //BA.debugLineNum = 248;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 249;BA.debugLine="vue.AddCode($\"cardText1.SetText(cg2.ToString)\"$)";
_vue._addcode /*String*/ (("cardText1.SetText(cg2.ToString)"));
 //BA.debugLineNum = 250;BA.debugLine="vue.AddCode($\"shirtBlouse.SetTextAfter(cardText1.T";
_vue._addcode /*String*/ (("shirtBlouse.SetTextAfter(cardText1.ToString)"));
 //BA.debugLineNum = 251;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 252;BA.debugLine="vue.AddCode($\"Dim btnAdd2Cart1 As VMButton = vm.Cr";
_vue._addcode /*String*/ (("Dim btnAdd2Cart1 As VMButton = vm.CreateButton(\"\", Me)"));
 //BA.debugLineNum = 253;BA.debugLine="vue.AddCode($\"btnAdd2Cart1.SetBlock(True)\"$)";
_vue._addcode /*String*/ (("btnAdd2Cart1.SetBlock(True)"));
 //BA.debugLineNum = 254;BA.debugLine="vue.AddCode($\"btnAdd2Cart1.SetTextColor(vm.COLOR_W";
_vue._addcode /*String*/ (("btnAdd2Cart1.SetTextColor(vm.COLOR_WHITE)"));
 //BA.debugLineNum = 255;BA.debugLine="vue.AddCode($\"btnAdd2Cart1.SetColorIntensity(vm.CO";
_vue._addcode /*String*/ (("btnAdd2Cart1.SetColorIntensity(vm.COLOR_DEEPPURPLE, vm.INTENSITY_ACCENT4)"));
 //BA.debugLineNum = 256;BA.debugLine="vue.AddCode($\"btnAdd2Cart1.SetLabel(\"Add to Cart\")";
_vue._addcode /*String*/ (("btnAdd2Cart1.SetLabel(\"Add to Cart\")"));
 //BA.debugLineNum = 257;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 258;BA.debugLine="vue.AddCode($\"shirtBlouse.Actions.AddButton(btnAdd";
_vue._addcode /*String*/ (("shirtBlouse.Actions.AddButton(btnAdd2Cart1)"));
 //BA.debugLineNum = 259;BA.debugLine="vue.AddCode($\"shirtBlouse.AddToContainer(xcont, 1,";
_vue._addcode /*String*/ (("shirtBlouse.AddToContainer(xcont, 1, 2)"));
 //BA.debugLineNum = 260;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 261;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"shblouse\", \"Shirt B";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modchips.getObject(),"shblouse","Shirt Blouse",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (7),(int) (1));
 //BA.debugLineNum = 265;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 266;BA.debugLine="vue.AddCode($\"'3rd card\"$)";
_vue._addcode /*String*/ (("'3rd card"));
 //BA.debugLineNum = 267;BA.debugLine="vue.AddCode($\"Dim card3 As VMElement = vm.VCard(\"c";
_vue._addcode /*String*/ (("Dim card3 As VMElement = vm.VCard(\"card3\").AddClass(\"mx-auto\").SetMaxWidth(\"400\")"));
 //BA.debugLineNum = 268;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 269;BA.debugLine="vue.AddCode($\"Dim tbl1 As VMElement = vm.VToolBar(";
_vue._addcode /*String*/ (("Dim tbl1 As VMElement = vm.VToolBar(\"card2tbl1\")"));
 //BA.debugLineNum = 270;BA.debugLine="vue.AddCode($\"tbl1.SetAttr(CreateMap(\"flat\":True,";
_vue._addcode /*String*/ (("tbl1.SetAttr(CreateMap(\"flat\":True, \"color\":\"deep-purple accent-4\", \"dark\":True))"));
 //BA.debugLineNum = 271;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 272;BA.debugLine="vue.AddCode($\"Dim btn1 As VMElement = vm.VBtn(\"\").";
_vue._addcode /*String*/ (("Dim btn1 As VMElement = vm.VBtn(\"\").SetAttrSingle(\"icon\", True).SetTextColor(vm.COLOR_WHITE)"));
 //BA.debugLineNum = 273;BA.debugLine="vue.AddCode($\"Dim icn As VMElement = vm.VIcon(\"\").";
_vue._addcode /*String*/ (("Dim icn As VMElement = vm.VIcon(\"\").SetText(\"mdi-close\")"));
 //BA.debugLineNum = 274;BA.debugLine="vue.AddCode($\"btn1.AddElement(icn)\"$)";
_vue._addcode /*String*/ (("btn1.AddElement(icn)"));
 //BA.debugLineNum = 275;BA.debugLine="vue.AddCode($\"tbl1.AddElement(btn1)\"$)";
_vue._addcode /*String*/ (("tbl1.AddElement(btn1)"));
 //BA.debugLineNum = 276;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 277;BA.debugLine="vue.AddCode($\"Dim tt As VMElement = vm.VToolbarTit";
_vue._addcode /*String*/ (("Dim tt As VMElement = vm.VToolbarTitle(\"\").SetText(\"Filter Results\").SetTextColor(vm.COLOR_white)"));
 //BA.debugLineNum = 278;BA.debugLine="vue.AddCode($\"tbl1.AddElement(tt)\"$)";
_vue._addcode /*String*/ (("tbl1.AddElement(tt)"));
 //BA.debugLineNum = 279;BA.debugLine="vue.AddCode($\"card3.AddElement(tbl1)\"$)";
_vue._addcode /*String*/ (("card3.AddElement(tbl1)"));
 //BA.debugLineNum = 280;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 281;BA.debugLine="vue.AddCode($\"Dim c3t1 As VMElement = vm.VCardText";
_vue._addcode /*String*/ (("Dim c3t1 As VMElement = vm.VCardText(\"\")"));
 //BA.debugLineNum = 282;BA.debugLine="vue.AddCode($\"Dim c3t2 As VMElement = vm.VCardText";
_vue._addcode /*String*/ (("Dim c3t2 As VMElement = vm.VCardText(\"\")"));
 //BA.debugLineNum = 283;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 284;BA.debugLine="vue.AddCode($\"Dim h2 As VMElement = vm.H2(\"\").AddC";
_vue._addcode /*String*/ (("Dim h2 As VMElement = vm.H2(\"\").AddClass(\"title mb-2\").SetText(\"Choose amenities\")"));
 //BA.debugLineNum = 285;BA.debugLine="vue.AddCode($\"c3t1.AddElement(h2)\"$)";
_vue._addcode /*String*/ (("c3t1.AddElement(h2)"));
 //BA.debugLineNum = 286;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 287;BA.debugLine="vue.AddCode($\"Dim cg4 As VMChipGroup = vm.CreateC";
_vue._addcode /*String*/ (("Dim cg4 As VMChipGroup = vm.CreateChipGroup(\"cg4\", Me).SetVmodel(\"amenities\")"));
 //BA.debugLineNum = 288;BA.debugLine="vue.AddCode($\"cg4.SetMultiple(True)\"$)";
_vue._addcode /*String*/ (("cg4.SetMultiple(True)"));
 //BA.debugLineNum = 289;BA.debugLine="vue.AddCode($\"cg4.SetColumn(True)\"$)";
_vue._addcode /*String*/ (("cg4.SetColumn(True)"));
 //BA.debugLineNum = 290;BA.debugLine="vue.AddCode($\"Dim amenities As List = vm.NewList1";
_vue._addcode /*String*/ (("Dim amenities As List = vm.NewList1(Array As String(\"washer\", \"dogs\"))"));
 //BA.debugLineNum = 291;BA.debugLine="vue.AddCode($\"cg4.SetData(\"amenities\", amenities)";
_vue._addcode /*String*/ (("cg4.SetData(\"amenities\", amenities)"));
 //BA.debugLineNum = 292;BA.debugLine="vue.AddCode($\"cg4.AddItem(\"elevator\", True, True,";
_vue._addcode /*String*/ (("cg4.AddItem(\"elevator\", True, True, \"Elevator\")"));
 //BA.debugLineNum = 293;BA.debugLine="vue.AddCode($\"cg4.AddItem(\"washer\", True, True, \"";
_vue._addcode /*String*/ (("cg4.AddItem(\"washer\", True, True, \"Washer\")"));
 //BA.debugLineNum = 294;BA.debugLine="vue.AddCode($\"cg4.AddItem(\"fireplace\", True, True";
_vue._addcode /*String*/ (("cg4.AddItem(\"fireplace\", True, True, \"Fireplace\")"));
 //BA.debugLineNum = 295;BA.debugLine="vue.AddCode($\"cg4.AddItem(\"wheelchair\", True, Tru";
_vue._addcode /*String*/ (("cg4.AddItem(\"wheelchair\", True, True,  \"Wheelchair\")"));
 //BA.debugLineNum = 296;BA.debugLine="vue.AddCode($\"cg4.AddItem(\"dogs\", True, True,  \"D";
_vue._addcode /*String*/ (("cg4.AddItem(\"dogs\", True, True,  \"Dogs ok\")"));
 //BA.debugLineNum = 297;BA.debugLine="vue.AddCode($\"cg4.AddItem(\"cats\", True, True, \"Ca";
_vue._addcode /*String*/ (("cg4.AddItem(\"cats\", True, True, \"Cats ok\")"));
 //BA.debugLineNum = 298;BA.debugLine="vue.AddCode($\"c3t1.SetText(cg4.tostring)\"$)";
_vue._addcode /*String*/ (("c3t1.SetText(cg4.tostring)"));
 //BA.debugLineNum = 299;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 300;BA.debugLine="vue.AddCode($\"card3.AddElement(c3t1)\"$)";
_vue._addcode /*String*/ (("card3.AddElement(c3t1)"));
 //BA.debugLineNum = 301;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 302;BA.debugLine="vue.AddCode($\"Dim h2a As VMElement = vm.H2(\"\").Add";
_vue._addcode /*String*/ (("Dim h2a As VMElement = vm.H2(\"\").AddClass(\"title mb-2\").SetText(\"Choose neighborhoods\")"));
 //BA.debugLineNum = 303;BA.debugLine="vue.AddCode($\"c3t2.AddElement(h2a)\"$)";
_vue._addcode /*String*/ (("c3t2.AddElement(h2a)"));
 //BA.debugLineNum = 304;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 305;BA.debugLine="vue.AddCode($\"Dim cg5 As VMChipGroup = vm.CreateC";
_vue._addcode /*String*/ (("Dim cg5 As VMChipGroup = vm.CreateChipGroup(\"cg5\", Me).SetVmodel(\"neighborhoods\")"));
 //BA.debugLineNum = 306;BA.debugLine="vue.AddCode($\"cg5.SetMultiple(True)\"$)";
_vue._addcode /*String*/ (("cg5.SetMultiple(True)"));
 //BA.debugLineNum = 307;BA.debugLine="vue.AddCode($\"cg5.SetColumn(True)\"$)";
_vue._addcode /*String*/ (("cg5.SetColumn(True)"));
 //BA.debugLineNum = 308;BA.debugLine="vue.AddCode($\"Dim neighborhoods As List = vm.NewL";
_vue._addcode /*String*/ (("Dim neighborhoods As List = vm.NewList1(Array As String(\"3\", \"4\"))"));
 //BA.debugLineNum = 309;BA.debugLine="vue.AddCode($\"cg5.SetData(\"neighborhoods\", neighb";
_vue._addcode /*String*/ (("cg5.SetData(\"neighborhoods\", neighborhoods)"));
 //BA.debugLineNum = 310;BA.debugLine="vue.AddCode($\"cg5.AddItem(\"1\", True, True,  \"Snow";
_vue._addcode /*String*/ (("cg5.AddItem(\"1\", True, True,  \"Snowy Rock Place\")"));
 //BA.debugLineNum = 311;BA.debugLine="vue.AddCode($\"cg5.AddItem(\"2\", True, True,  \"Hone";
_vue._addcode /*String*/ (("cg5.AddItem(\"2\", True, True,  \"Honeylane Circle\")"));
 //BA.debugLineNum = 312;BA.debugLine="vue.AddCode($\"cg5.AddItem(\"3\", True, True,  \"Donn";
_vue._addcode /*String*/ (("cg5.AddItem(\"3\", True, True,  \"Donna Drive\")"));
 //BA.debugLineNum = 313;BA.debugLine="vue.AddCode($\"cg5.AddItem(\"4\", True, True,  \"Elai";
_vue._addcode /*String*/ (("cg5.AddItem(\"4\", True, True,  \"Elaine Street\")"));
 //BA.debugLineNum = 314;BA.debugLine="vue.AddCode($\"cg5.AddItem(\"5\", True, True,  \"Cour";
_vue._addcode /*String*/ (("cg5.AddItem(\"5\", True, True,  \"Court Street\")"));
 //BA.debugLineNum = 315;BA.debugLine="vue.AddCode($\"cg5.AddItem(\"6\", True, True,  \"Kenn";
_vue._addcode /*String*/ (("cg5.AddItem(\"6\", True, True,  \"Kennedy Park\")"));
 //BA.debugLineNum = 316;BA.debugLine="vue.AddCode($\"c3t2.SetText(cg5.tostring)\"$)";
_vue._addcode /*String*/ (("c3t2.SetText(cg5.tostring)"));
 //BA.debugLineNum = 317;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 318;BA.debugLine="vue.AddCode($\"card3.AddElement(c3t2)\"$)";
_vue._addcode /*String*/ (("card3.AddElement(c3t2)"));
 //BA.debugLineNum = 319;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 320;BA.debugLine="vue.AddCode($\"'add card to container\"$)";
_vue._addcode /*String*/ (("'add card to container"));
 //BA.debugLineNum = 321;BA.debugLine="vue.AddCode($\"card3.AddToContainer(xcont, 1, 3)\"$)";
_vue._addcode /*String*/ (("card3.AddToContainer(xcont, 1, 3)"));
 //BA.debugLineNum = 322;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"chipfilter\", \"Chip";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modchips.getObject(),"chipfilter","Chip Group Filter ",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (8),(int) (1));
 //BA.debugLineNum = 324;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 325;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Public name As String = \"chipsCode\"";
_name = "chipsCode";
 //BA.debugLineNum = 4;BA.debugLine="Public title As String = \"Chips\"";
_title = "Chips";
 //BA.debugLineNum = 5;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 6;BA.debugLine="Private BANano As BANano  'ignore";
_banano = new com.ab.banano.BANano();
 //BA.debugLineNum = 7;BA.debugLine="Private vue As BANanoVue";
_vue = new b4j.example.bananovue();
 //BA.debugLineNum = 8;BA.debugLine="End Sub";
return "";
}
public static String  _shblousecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 357;BA.debugLine="Sub shblousecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 358;BA.debugLine="vue.CopyCode2Clipboard(\"shblouse\")";
_vue._copycode2clipboard /*String*/ ("shblouse");
 //BA.debugLineNum = 359;BA.debugLine="End Sub";
return "";
}
public static String  _shblousedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 361;BA.debugLine="Sub shblousedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 362;BA.debugLine="vue.DownloadCode(\"shblouse\", \"shblouse.txt\")";
_vue._downloadcode /*String*/ ("shblouse","shblouse.txt");
 //BA.debugLineNum = 363;BA.debugLine="End Sub";
return "";
}
public static String  _toothbrushcopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 366;BA.debugLine="Sub toothbrushcopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 367;BA.debugLine="vue.CopyCode2Clipboard(\"toothbrush\")";
_vue._copycode2clipboard /*String*/ ("toothbrush");
 //BA.debugLineNum = 368;BA.debugLine="End Sub";
return "";
}
public static String  _toothbrushdownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 370;BA.debugLine="Sub toothbrushdownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 371;BA.debugLine="vue.DownloadCode(\"toothbrush\", \"toothbrush.txt\")";
_vue._downloadcode /*String*/ ("toothbrush","toothbrush.txt");
 //BA.debugLineNum = 372;BA.debugLine="End Sub";
return "";
}
}
