package b4j.example;


import anywheresoftware.b4a.BA;

public class moddesign extends Object{
public static moddesign mostCurrent = new moddesign();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.moddesign", null);
		ba.loadHtSubs(moddesign.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.moddesign", ba);
		}
	}
    public static Class<?> getObject() {
		return moddesign.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static com.ab.banano.BANano _banano = null;
public static b4j.example.vmcontainer _cont = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcalendar _modcalendar = null;
public static b4j.example.modcard _modcard = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modautocomplete _modautocomplete = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatatable _moddatatable = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.modexpansionpanels _modexpansionpanels = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modgrid _modgrid = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimeline _modtimeline = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modtreeview _modtreeview = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _btnicony_click(com.ab.banano.BANanoEvent _e) throws Exception{
anywheresoftware.b4a.objects.collections.Map _rec = null;
 //BA.debugLineNum = 98;BA.debugLine="Sub btnicony_click(e As BANanoEvent)";
 //BA.debugLineNum = 99;BA.debugLine="Dim rec As Map = cont.getdata";
_rec = new anywheresoftware.b4a.objects.collections.Map();
_rec = _cont._getdata /*anywheresoftware.b4a.objects.collections.Map*/ ();
 //BA.debugLineNum = 100;BA.debugLine="vm.ShowAlert(\"inform\",\"Data\", BANano.tojson(rec),";
_vm._showalert /*String*/ ("inform","Data",BA.ObjectToString(_banano.ToJson((Object)(_rec.getObject()))),"Data");
 //BA.debugLineNum = 101;BA.debugLine="End Sub";
return "";
}
public static String  _code() throws Exception{
b4j.example.vmcheckbox _switch = null;
b4j.example.vmradiogroup _radiogroup = null;
b4j.example.vmcheckbox _checkbox = null;
b4j.example.vmdatetimepicker _datepicker = null;
b4j.example.vmdatetimepicker _timepicker = null;
b4j.example.vmslider _slider = null;
b4j.example.vmtextfield _txtname = null;
anywheresoftware.b4a.objects.collections.List _lst = null;
anywheresoftware.b4a.objects.collections.Map _genderlist = null;
b4j.example.vmselect _ac1 = null;
b4j.example.vmselect _ac2 = null;
b4j.example.vmtextfield _txta = null;
b4j.example.vmtextfield _pwd = null;
b4j.example.vmfileinput _fi = null;
b4j.example.vmimage _img = null;
b4j.example.vmlabel _lbl = null;
b4j.example.vmicon _icon = null;
b4j.example.vmbutton _btn = null;
b4j.example.vmselect _mysel = null;
b4j.example.vmselect _mysel1 = null;
b4j.example.vmbutton _btnx = null;
b4j.example.vmbutton _btnxy = null;
 //BA.debugLineNum = 11;BA.debugLine="Sub Code";
 //BA.debugLineNum = 12;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 14;BA.debugLine="cont = vm.CreateContainer(name, Me)";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,moddesign.getObject());
 //BA.debugLineNum = 16;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 18;BA.debugLine="Dim switch As VMCheckBox = vm.NewSwitch(Me, True,";
_switch = _vm._newswitch /*b4j.example.vmcheckbox*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"switch1","switch1","Radio",(Object)("Yes"),(Object)("No"),anywheresoftware.b4a.keywords.Common.True,(int) (0))._setdevicepositions /*b4j.example.vmcheckbox*/ (BA.NumberToString(1),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 19;BA.debugLine="cont.AddControl1(switch.CheckBox, switch.ToString";
_cont._addcontrol1 /*String*/ (_switch._checkbox /*b4j.example.vmelement*/ ,_switch._tostring /*String*/ ());
 //BA.debugLineNum = 21;BA.debugLine="Dim radiogroup As VMRadioGroup = vm.NewRadioGroup";
_radiogroup = _vm._newradiogroup /*b4j.example.vmradiogroup*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"radiogroup","radiogroup","Gender",(Object)("female"),anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("male"),(Object)("Male"),(Object)("female"),(Object)("Female")}),anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,(int) (0))._setdevicepositions /*b4j.example.vmradiogroup*/ (BA.NumberToString(1),BA.NumberToString(2),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 22;BA.debugLine="radiogroup.SetHorizontal(True)";
_radiogroup._sethorizontal /*b4j.example.vmradiogroup*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 23;BA.debugLine="cont.AddControl1(radiogroup.RadioGroup, radiogrou";
_cont._addcontrol1 /*String*/ (_radiogroup._radiogroup /*b4j.example.vmelement*/ ,_radiogroup._tostring /*String*/ ());
 //BA.debugLineNum = 25;BA.debugLine="Dim checkbox As VMCheckBox = vm.NewCheckBox(Me, T";
_checkbox = _vm._newcheckbox /*b4j.example.vmcheckbox*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"checkbox","checkbox","I concur!",(Object)("Yes"),(Object)("No"),anywheresoftware.b4a.keywords.Common.True,(int) (0))._setdevicepositions /*b4j.example.vmcheckbox*/ (BA.NumberToString(1),BA.NumberToString(3),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 26;BA.debugLine="cont.AddControl1(checkbox.CheckBox, checkbox.ToSt";
_cont._addcontrol1 /*String*/ (_checkbox._checkbox /*b4j.example.vmelement*/ ,_checkbox._tostring /*String*/ ());
 //BA.debugLineNum = 28;BA.debugLine="Dim datepicker As VMDateTimePicker = vm.NewDatePi";
_datepicker = _vm._newdatepicker /*b4j.example.vmdatetimepicker*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"datepicker","datepicker","Date Picker",anywheresoftware.b4a.keywords.Common.True,"Select a Date Picker","This date","",(int) (0))._setdevicepositions /*b4j.example.vmdatetimepicker*/ (BA.NumberToString(1),BA.NumberToString(4),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 29;BA.debugLine="cont.AddControl1(datepicker.DateTimePicker, datep";
_cont._addcontrol1 /*String*/ (_datepicker._datetimepicker /*b4j.example.vmelement*/ ,_datepicker._tostring /*String*/ ());
 //BA.debugLineNum = 31;BA.debugLine="Dim timepicker As VMDateTimePicker = vm.NewTimePi";
_timepicker = _vm._newtimepicker /*b4j.example.vmdatetimepicker*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"timepicker","timepicker","Time Picker",anywheresoftware.b4a.keywords.Common.True,"Select a time Picker","This time","",(int) (0))._setdevicepositions /*b4j.example.vmdatetimepicker*/ (BA.NumberToString(2),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 32;BA.debugLine="cont.AddControl1(timepicker.DateTimePicker, timep";
_cont._addcontrol1 /*String*/ (_timepicker._datetimepicker /*b4j.example.vmelement*/ ,_timepicker._tostring /*String*/ ());
 //BA.debugLineNum = 34;BA.debugLine="Dim slider As VMSlider = vm.NewSlider(Me, True, \"";
_slider = _vm._newslider /*b4j.example.vmslider*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"slider","slider","Slider",BA.NumberToString(0),BA.NumberToString(100),(int) (0))._setdevicepositions /*b4j.example.vmslider*/ (BA.NumberToString(2),BA.NumberToString(2),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 35;BA.debugLine="cont.AddControl1(slider.Slider, slider.ToString)";
_cont._addcontrol1 /*String*/ (_slider._slider /*b4j.example.vmelement*/ ,_slider._tostring /*String*/ ());
 //BA.debugLineNum = 37;BA.debugLine="Dim txtName As VMTextField = vm.NewTextField(Me,";
_txtname = _vm._newtextfield /*b4j.example.vmtextfield*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"firstname","firstname","First Name","Enter your first name",anywheresoftware.b4a.keywords.Common.True,"",(int) (50),"First Name","",(int) (0))._setdevicepositions /*b4j.example.vmtextfield*/ (BA.NumberToString(3),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 38;BA.debugLine="cont.AddControl1(txtName.Textfield, txtName.ToStr";
_cont._addcontrol1 /*String*/ (_txtname._textfield /*b4j.example.vmelement*/ ,_txtname._tostring /*String*/ ());
 //BA.debugLineNum = 40;BA.debugLine="Dim lst As List";
_lst = new anywheresoftware.b4a.objects.collections.List();
 //BA.debugLineNum = 41;BA.debugLine="lst.Initialize";
_lst.Initialize();
 //BA.debugLineNum = 42;BA.debugLine="lst.Add(CreateMap(\"name\": \"Florida\", \"abbr\": \"FL\"";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("Florida"),(Object)("abbr"),(Object)("FL"),(Object)("id"),(Object)("1")}).getObject()));
 //BA.debugLineNum = 43;BA.debugLine="lst.Add(CreateMap(\"name\": \"Georgia\", \"abbr\": \"GA\"";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("Georgia"),(Object)("abbr"),(Object)("GA"),(Object)("id"),(Object)("2")}).getObject()));
 //BA.debugLineNum = 44;BA.debugLine="lst.Add(CreateMap(\"name\": \"Nebraska\", \"abbr\": \"NE";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("Nebraska"),(Object)("abbr"),(Object)("NE"),(Object)("id"),(Object)("3")}).getObject()));
 //BA.debugLineNum = 45;BA.debugLine="lst.Add(CreateMap(\"name\": \"California\", \"abbr\": \"";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("California"),(Object)("abbr"),(Object)("CA"),(Object)("id"),(Object)("4")}).getObject()));
 //BA.debugLineNum = 46;BA.debugLine="lst.Add(CreateMap(\"name\": \"New York\", \"abbr\": \"NY";
_lst.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("name"),(Object)("New York"),(Object)("abbr"),(Object)("NY"),(Object)("id"),(Object)("5")}).getObject()));
 //BA.debugLineNum = 47;BA.debugLine="vm.SetData(\"states2\", lst)";
_vm._setdata /*b4j.example.bananovm*/ ("states2",(Object)(_lst.getObject()));
 //BA.debugLineNum = 49;BA.debugLine="Dim genderlist As Map = CreateMap(\"f\":\"Female\", \"";
_genderlist = new anywheresoftware.b4a.objects.collections.Map();
_genderlist = anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("f"),(Object)("Female"),(Object)("m"),(Object)("Male")});
 //BA.debugLineNum = 51;BA.debugLine="Dim ac1 As VMSelect = vm.NewAutoCompleteDataSourc";
_ac1 = _vm._newautocompletedatasource /*b4j.example.vmselect*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"acx1","acx1","States",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.False,"States","states2","id","name",anywheresoftware.b4a.keywords.Common.False,"This is it!","",(int) (0))._setdevicepositions /*b4j.example.vmselect*/ (BA.NumberToString(3),BA.NumberToString(2),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 52;BA.debugLine="cont.AddControl1(ac1.Combo, ac1.ToString)";
_cont._addcontrol1 /*String*/ (_ac1._combo /*b4j.example.vmelement*/ ,_ac1._tostring /*String*/ ());
 //BA.debugLineNum = 54;BA.debugLine="Dim ac2 As VMSelect = vm.NewAutoCompleteOptions(M";
_ac2 = _vm._newautocompleteoptions /*b4j.example.vmselect*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"acx2","acx2","Gender",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.False,"Gender",_genderlist,"id","text",anywheresoftware.b4a.keywords.Common.False,"This is it!","",(int) (0))._setdevicepositions /*b4j.example.vmselect*/ (BA.NumberToString(3),BA.NumberToString(2),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 55;BA.debugLine="cont.AddControl1(ac2.Combo, ac2.ToString)";
_cont._addcontrol1 /*String*/ (_ac2._combo /*b4j.example.vmelement*/ ,_ac2._tostring /*String*/ ());
 //BA.debugLineNum = 57;BA.debugLine="Dim txta As VMTextField = vm.NewTextArea(Me, True";
_txta = _vm._newtextarea /*b4j.example.vmtextfield*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"txtarea","textarea","Text Area","A placeholder",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.False,"",(int) (255),"Helper Text","",(int) (0))._setdevicepositions /*b4j.example.vmtextfield*/ (BA.NumberToString(4),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12));
 //BA.debugLineNum = 58;BA.debugLine="cont.AddControl1(txta.TextField, txta.ToString)";
_cont._addcontrol1 /*String*/ (_txta._textfield /*b4j.example.vmelement*/ ,_txta._tostring /*String*/ ());
 //BA.debugLineNum = 60;BA.debugLine="Dim pwd As VMTextField = vm.NewPassword(Me, True,";
_pwd = _vm._newpassword /*b4j.example.vmtextfield*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"pwd1","pwd1","Password","Enter your password!",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"mdi-lock",(int) (10),"Password","",(int) (0))._setdevicepositions /*b4j.example.vmtextfield*/ (BA.NumberToString(5),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 61;BA.debugLine="cont.AddControl1(pwd.TextFIeld, pwd.ToString)";
_cont._addcontrol1 /*String*/ (_pwd._textfield /*b4j.example.vmelement*/ ,_pwd._tostring /*String*/ ());
 //BA.debugLineNum = 63;BA.debugLine="Dim fi As VMFileInput = vm.NewFileInput(Me, True,";
_fi = _vm._newfileinput /*b4j.example.vmfileinput*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.False,"fileinput","fileinput","Select your file!","Enter a file",anywheresoftware.b4a.keywords.Common.True,"This is a file!","",(int) (0))._setdevicepositions /*b4j.example.vmfileinput*/ (BA.NumberToString(5),BA.NumberToString(2),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 64;BA.debugLine="cont.AddControl1(fi.FileInput, fi.ToString)";
_cont._addcontrol1 /*String*/ (_fi._fileinput /*b4j.example.vmelement*/ ,_fi._tostring /*String*/ ());
 //BA.debugLineNum = 66;BA.debugLine="Dim img As VMImage = vm.NewImage(Me, True, \"image";
_img = _vm._newimage /*b4j.example.vmimage*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"image","image","./assets/sponge.png","Sponge","100","100")._setdevicepositions /*b4j.example.vmimage*/ (BA.NumberToString(6),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 67;BA.debugLine="img.SetBorderRadius(\"10px\")";
_img._setborderradius /*b4j.example.vmimage*/ ("10px");
 //BA.debugLineNum = 68;BA.debugLine="img.SetBorder(\"1px\", vm.COLOR_BLACK, vm.BORDER_DO";
_img._setborder /*b4j.example.vmimage*/ ("1px",_vm._color_black /*String*/ ,_vm._border_double /*String*/ );
 //BA.debugLineNum = 69;BA.debugLine="cont.AddControl1(img.Image, img.ToString)";
_cont._addcontrol1 /*String*/ (_img._image /*b4j.example.vmelement*/ ,_img._tostring /*String*/ ());
 //BA.debugLineNum = 71;BA.debugLine="Dim lbl As VMLabel = vm.NewLabel(True, \"labelz\",";
_lbl = _vm._newlabel /*b4j.example.vmlabel*/ (anywheresoftware.b4a.keywords.Common.True,"labelz","labelz",_vm._size_h1 /*String*/ ,"This is H1")._setdevicepositions /*b4j.example.vmlabel*/ (BA.NumberToString(6),BA.NumberToString(2),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 72;BA.debugLine="cont.AddControl1(lbl.Label, lbl.ToString)";
_cont._addcontrol1 /*String*/ (_lbl._label /*b4j.example.vmelement*/ ,_lbl._tostring /*String*/ ());
 //BA.debugLineNum = 74;BA.debugLine="Dim icon As VMIcon = vm.NewIcon(Me, True, \"icon\",";
_icon = _vm._newicon /*b4j.example.vmicon*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"icon","mdi-chevron-right",_vm._icon_large /*String*/ ,_vm._color_amber /*String*/ ,"")._setdevicepositions /*b4j.example.vmicon*/ (BA.NumberToString(7),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 75;BA.debugLine="icon.SetDark(True)";
_icon._setdark /*b4j.example.vmicon*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 76;BA.debugLine="cont.AddControl1(icon.Icon, icon.ToString)";
_cont._addcontrol1 /*String*/ (_icon._icon /*b4j.example.vmelement*/ ,_icon._tostring /*String*/ ());
 //BA.debugLineNum = 78;BA.debugLine="Dim btn As VMButton = vm.NewButton(Me, True, \"but";
_btn = _vm._newbutton /*b4j.example.vmbutton*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"buttonx","TheMash Block",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.False,anywheresoftware.b4a.keywords.Common.True)._setdevicepositions /*b4j.example.vmbutton*/ (BA.NumberToString(7),BA.NumberToString(2),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 79;BA.debugLine="cont.AddControl1(btn.Button, btn.ToString)";
_cont._addcontrol1 /*String*/ (_btn._button /*b4j.example.vmelement*/ ,_btn._tostring /*String*/ ());
 //BA.debugLineNum = 81;BA.debugLine="Dim mysel As VMSelect = vm.NewSelectDataSource(Me";
_mysel = _vm._newselectdatasource /*b4j.example.vmselect*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"myselect","myselect","Select States",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.True,"States","states2","id","name",anywheresoftware.b4a.keywords.Common.False,"My thingo","",(int) (0))._setdevicepositions /*b4j.example.vmselect*/ (BA.NumberToString(8),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 82;BA.debugLine="cont.AddControl1(mysel.Combo, mysel.ToString)";
_cont._addcontrol1 /*String*/ (_mysel._combo /*b4j.example.vmelement*/ ,_mysel._tostring /*String*/ ());
 //BA.debugLineNum = 84;BA.debugLine="Dim mysel1 As VMSelect = vm.NewSelectOptions(Me,";
_mysel1 = _vm._newselectoptions /*b4j.example.vmselect*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"myselect1","myselect1","Select Gender",anywheresoftware.b4a.keywords.Common.True,anywheresoftware.b4a.keywords.Common.False,"Gender",_genderlist,"id","text",anywheresoftware.b4a.keywords.Common.False,"My thingo","",(int) (0))._setdevicepositions /*b4j.example.vmselect*/ (BA.NumberToString(8),BA.NumberToString(2),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 85;BA.debugLine="cont.AddControl1(mysel1.Combo, mysel1.ToString)";
_cont._addcontrol1 /*String*/ (_mysel1._combo /*b4j.example.vmelement*/ ,_mysel1._tostring /*String*/ ());
 //BA.debugLineNum = 87;BA.debugLine="Dim btnx As VMButton = vm.NewIconButton(Me, True,";
_btnx = _vm._newiconbutton /*b4j.example.vmbutton*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"btnicon","mdi-dots-vertical",_vm._color_brown /*String*/ ,"Account details")._setdevicepositions /*b4j.example.vmbutton*/ (BA.NumberToString(9),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 88;BA.debugLine="cont.AddControl1(btnx.Button, btnx.ToString)";
_cont._addcontrol1 /*String*/ (_btnx._button /*b4j.example.vmelement*/ ,_btnx._tostring /*String*/ ());
 //BA.debugLineNum = 90;BA.debugLine="Dim btnxy As VMButton = vm.NewFabButton(Me, True,";
_btnxy = _vm._newfabbutton /*b4j.example.vmbutton*/ (moddesign.getObject(),anywheresoftware.b4a.keywords.Common.True,"btnicony","mdi-pencil",_vm._color_deeporange /*String*/ ,"Fab Button")._setdevicepositions /*b4j.example.vmbutton*/ (BA.NumberToString(9),BA.NumberToString(2),BA.NumberToString(12),BA.NumberToString(6),BA.NumberToString(6),BA.NumberToString(6));
 //BA.debugLineNum = 91;BA.debugLine="btnxy.SetLarge(True)";
_btnxy._setlarge /*b4j.example.vmbutton*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 92;BA.debugLine="cont.AddControl1(btnxy.Button, btnxy.ToString)";
_cont._addcontrol1 /*String*/ (_btnxy._button /*b4j.example.vmelement*/ ,_btnxy._tostring /*String*/ ());
 //BA.debugLineNum = 95;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 96;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Public name As String = \"designCode\"";
_name = "designCode";
 //BA.debugLineNum = 4;BA.debugLine="Public title As String = \"Design\"";
_title = "Design";
 //BA.debugLineNum = 5;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 6;BA.debugLine="Private BANano As BANano   'ignore";
_banano = new com.ab.banano.BANano();
 //BA.debugLineNum = 7;BA.debugLine="Private cont As VMContainer";
_cont = new b4j.example.vmcontainer();
 //BA.debugLineNum = 8;BA.debugLine="End Sub";
return "";
}
}
