package b4j.example;


import anywheresoftware.b4a.BA;

public class moddatatable extends Object{
public static moddatatable mostCurrent = new moddatatable();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.moddatatable", null);
		ba.loadHtSubs(moddatatable.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.moddatatable", ba);
		}
	}
    public static Class<?> getObject() {
		return moddatatable.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static com.ab.banano.BANano _banano = null;
public static b4j.example.vmdatatable _dt1 = null;
public static b4j.example.vmdatatable _dtusers = null;
public static b4j.example.vmdatatable _dtimages = null;
public static b4j.example.bananovue _vue = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcalendar _modcalendar = null;
public static b4j.example.modcard _modcard = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modautocomplete _modautocomplete = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddesign _moddesign = null;
public static b4j.example.modexpansionpanels _modexpansionpanels = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modgrid _modgrid = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimeline _modtimeline = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modtreeview _modtreeview = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _btnnew_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 562;BA.debugLine="Sub btnNew_click(e As BANanoEvent)";
 //BA.debugLineNum = 563;BA.debugLine="vm.ShowSnackBar(\"Add record!\")";
_vm._showsnackbar /*String*/ ("Add record!");
 //BA.debugLineNum = 564;BA.debugLine="End Sub";
return "";
}
public static String  _code() throws Exception{
b4j.example.vmcontainer _cont = null;
anywheresoftware.b4a.objects.collections.List _recs = null;
b4j.example.vmlabel _lblsel = null;
anywheresoftware.b4a.objects.collections.List _users = null;
anywheresoftware.b4a.objects.collections.List _images = null;
 //BA.debugLineNum = 15;BA.debugLine="Sub Code";
 //BA.debugLineNum = 16;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 17;BA.debugLine="vue = vm.vue";
_vue = _vm._vue /*b4j.example.bananovue*/ ;
 //BA.debugLineNum = 19;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,moddatatable.getObject());
 //BA.debugLineNum = 21;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 23;BA.debugLine="cont.AddRows(5).AddColumns12";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (5))._addcolumns12 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 25;BA.debugLine="Dim recs As List = vm.Json2List($\"[     {";
_recs = new anywheresoftware.b4a.objects.collections.List();
_recs = _vm._json2list /*anywheresoftware.b4a.objects.collections.List*/ (("[\n"+"    {\n"+"        \"name\": \"Frozen Yogurt\",\n"+"        \"calories\": 159,\n"+"        \"fat\": 6,\n"+"        \"carbs\": 24,\n"+"        \"protein\": 4,\n"+"        \"iron\": \"1%\",\n"+"        \"glutenfree\": \"Yes\"\n"+"    },\n"+"    {\n"+"        \"name\": \"Ice cream sandwich\",\n"+"        \"calories\": 237,\n"+"        \"fat\": 9,\n"+"        \"carbs\": 37,\n"+"        \"protein\": 4.3,\n"+"        \"iron\": \"1%\",\n"+"        \"glutenfree\": \"No\"\n"+"    },\n"+"    {\n"+"        \"name\": \"Eclair\",\n"+"        \"calories\": 262,\n"+"        \"fat\": 16,\n"+"        \"carbs\": 23,\n"+"        \"protein\": 6,\n"+"        \"iron\": \"7%\",\n"+"        \"glutenfree\": \"No\"\n"+"    },\n"+"    {\n"+"        \"name\": \"Jelly bean\",\n"+"        \"calories\": 375,\n"+"        \"fat\": 0,\n"+"        \"carbs\": 94,\n"+"        \"protein\": 0,\n"+"        \"iron\": \"0%\",\n"+"        \"glutenfree\": \"Yes\"\n"+"    },\n"+"    {\n"+"        \"name\": \"Lollipop\",\n"+"        \"calories\": 392,\n"+"        \"fat\": 0.2,\n"+"        \"carbs\": 98,\n"+"        \"protein\": 0,\n"+"        \"iron\": \"2%\",\n"+"        \"glutenfree\": \"Yes\"\n"+"    },\n"+"    {\n"+"        \"name\": \"KitKat\",\n"+"        \"calories\": 518,\n"+"        \"fat\": 26,\n"+"        \"carbs\": 65,\n"+"        \"protein\": 7,\n"+"        \"iron\": \"6%\",\n"+"        \"glutenfree\": \"False\"\n"+"    }\n"+"]"));
 //BA.debugLineNum = 81;BA.debugLine="dt1 = vm.CreateDataTable(\"dt1\", \"name\", Me)";
_dt1 = _vm._createdatatable /*b4j.example.vmdatatable*/ ("dt1","name",moddatatable.getObject());
 //BA.debugLineNum = 82;BA.debugLine="dt1.SetTitle(\"Food Intake\")";
_dt1._settitle /*b4j.example.vmdatatable*/ ("Food Intake");
 //BA.debugLineNum = 83;BA.debugLine="dt1.AddSearch";
_dt1._addsearch /*String*/ ();
 //BA.debugLineNum = 84;BA.debugLine="dt1.AddDivider";
_dt1._adddivider /*String*/ ();
 //BA.debugLineNum = 85;BA.debugLine="dt1.AddNew(\"btnNew\", \"mdi-plus\", \"Add a new recor";
_dt1._addnew /*b4j.example.vmdatatable*/ ("btnNew","mdi-plus","Add a new record");
 //BA.debugLineNum = 86;BA.debugLine="dt1.SetDataSource(recs)";
_dt1._setdatasource /*b4j.example.vmdatatable*/ (_recs);
 //BA.debugLineNum = 87;BA.debugLine="dt1.AddColumn1(\"name\", \"Desset (100g serving)\", d";
_dt1._addcolumn1 /*b4j.example.vmdatatable*/ ("name","Desset (100g serving)",_dt1._column_text /*String*/ ,(int) (0),anywheresoftware.b4a.keywords.Common.False,_dt1._align_left /*String*/ );
 //BA.debugLineNum = 88;BA.debugLine="dt1.AddColumns(CreateMap(\"calories\": \"Calories\",";
_dt1._addcolumns /*b4j.example.vmdatatable*/ (anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("calories"),(Object)("Calories"),(Object)("fat"),(Object)("Fat (g)"),(Object)("carbs"),(Object)("Carbs (g)"),(Object)("protein"),(Object)("Protein (g)"),(Object)("iron"),(Object)("Iron (%)")}));
 //BA.debugLineNum = 89;BA.debugLine="dt1.AddColumn(\"glutenfree\", \"Gluten-Free\")";
_dt1._addcolumn /*b4j.example.vmdatatable*/ ("glutenfree","Gluten-Free");
 //BA.debugLineNum = 90;BA.debugLine="dt1.AddEditThrash";
_dt1._addeditthrash /*String*/ ();
 //BA.debugLineNum = 91;BA.debugLine="dt1.AddDownload";
_dt1._adddownload /*String*/ ();
 //BA.debugLineNum = 92;BA.debugLine="dt1.AddMenuV";
_dt1._addmenuv /*String*/ ();
 //BA.debugLineNum = 93;BA.debugLine="dt1.AddClone";
_dt1._addclone /*String*/ ();
 //BA.debugLineNum = 94;BA.debugLine="dt1.AddPrint";
_dt1._addprint /*String*/ ();
 //BA.debugLineNum = 95;BA.debugLine="dt1.SetItemKey(\"name\")";
_dt1._setitemkey /*b4j.example.vmdatatable*/ ("name");
 //BA.debugLineNum = 96;BA.debugLine="dt1.SetColumnTotal(\"calories\", \"sumfield('calorie";
_dt1._setcolumntotal /*b4j.example.vmdatatable*/ ("calories","sumfield('calories')");
 //BA.debugLineNum = 98;BA.debugLine="vue.SetMethod(Me, \"sumfield\")";
_vue._setmethod /*b4j.example.bananovue*/ (moddatatable.getObject(),"sumfield");
 //BA.debugLineNum = 100;BA.debugLine="dt1.SetColumnType(\"glutenfree\", dt1.COLUMN_CHECKB";
_dt1._setcolumntype /*b4j.example.vmdatatable*/ ("glutenfree",_dt1._column_checkbox /*String*/ );
 //BA.debugLineNum = 101;BA.debugLine="dt1.SetColumnType(\"calories\", dt1.COLUMN_CHIP)";
_dt1._setcolumntype /*b4j.example.vmdatatable*/ ("calories",_dt1._column_chip /*String*/ );
 //BA.debugLineNum = 102;BA.debugLine="dt1.SetColumnExtra(\"calories\", $\":color=\"getcolor";
_dt1._setcolumnextra /*b4j.example.vmdatatable*/ ("calories",(":color=\"getcolor(item.calories)\""));
 //BA.debugLineNum = 105;BA.debugLine="dt1.SetShowSelect(True)";
_dt1._setshowselect /*b4j.example.vmdatatable*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 108;BA.debugLine="dt1.SetOnInput(\"dt1_input\")";
_dt1._setoninput /*b4j.example.vmdatatable*/ ("dt1_input");
 //BA.debugLineNum = 110;BA.debugLine="dt1.SetExternalPagination";
_dt1._setexternalpagination /*b4j.example.vmdatatable*/ ();
 //BA.debugLineNum = 111;BA.debugLine="dt1.AddDivider";
_dt1._adddivider /*String*/ ();
 //BA.debugLineNum = 112;BA.debugLine="dt1.SetClearSort";
_dt1._setclearsort /*String*/ ();
 //BA.debugLineNum = 113;BA.debugLine="dt1.AddDivider";
_dt1._adddivider /*String*/ ();
 //BA.debugLineNum = 114;BA.debugLine="dt1.SetColumnChooser(True)";
_dt1._setcolumnchooser /*String*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 115;BA.debugLine="dt1.AddToContainer(cont, 1, 1)";
_dt1._addtocontainer /*String*/ (_cont,(int) (1),(int) (1));
 //BA.debugLineNum = 117;BA.debugLine="Dim lblSel As VMLabel = vm.CreateLabel(\"lblSelect";
_lblsel = _vm._createlabel /*b4j.example.vmlabel*/ ("lblSelected")._setparagraph /*b4j.example.vmlabel*/ ()._settext /*b4j.example.vmlabel*/ ("Selected: {{ dt1selected }}")._addclass /*b4j.example.vmlabel*/ ("ma-2");
 //BA.debugLineNum = 118;BA.debugLine="lblSel.AddToContainer(cont, 1,1)";
_lblsel._addtocontainer /*String*/ (_cont,(int) (1),(int) (1));
 //BA.debugLineNum = 121;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 122;BA.debugLine="vue.AddCode($\"Dim recs As List = vm.Json2List($\"[\"";
_vue._addcode /*String*/ (("Dim recs As List = vm.Json2List($\"["));
 //BA.debugLineNum = 123;BA.debugLine="vue.AddCode($\"{\"$)";
_vue._addcode /*String*/ (("{"));
 //BA.debugLineNum = 124;BA.debugLine="vue.AddCode($\"\"name\": \"Frozen Yogurt\",\"$)";
_vue._addcode /*String*/ (("\"name\": \"Frozen Yogurt\","));
 //BA.debugLineNum = 125;BA.debugLine="vue.AddCode($\"\"calories\": 159,\"$)";
_vue._addcode /*String*/ (("\"calories\": 159,"));
 //BA.debugLineNum = 126;BA.debugLine="vue.AddCode($\"\"fat\": 6,\"$)";
_vue._addcode /*String*/ (("\"fat\": 6,"));
 //BA.debugLineNum = 127;BA.debugLine="vue.AddCode($\"\"carbs\": 24,\"$)";
_vue._addcode /*String*/ (("\"carbs\": 24,"));
 //BA.debugLineNum = 128;BA.debugLine="vue.AddCode($\"\"protein\": 4,\"$)";
_vue._addcode /*String*/ (("\"protein\": 4,"));
 //BA.debugLineNum = 129;BA.debugLine="vue.AddCode($\"\"iron\": \"1%\",\"$)";
_vue._addcode /*String*/ (("\"iron\": \"1%\","));
 //BA.debugLineNum = 130;BA.debugLine="vue.AddCode($\"\"glutenfree\": \"Yes\"\"$)";
_vue._addcode /*String*/ (("\"glutenfree\": \"Yes\""));
 //BA.debugLineNum = 131;BA.debugLine="vue.AddCode($\"},\"$)";
_vue._addcode /*String*/ (("},"));
 //BA.debugLineNum = 132;BA.debugLine="vue.AddCode($\"{\"$)";
_vue._addcode /*String*/ (("{"));
 //BA.debugLineNum = 133;BA.debugLine="vue.AddCode($\"\"name\": \"Ice cream sandwich\",\"$)";
_vue._addcode /*String*/ (("\"name\": \"Ice cream sandwich\","));
 //BA.debugLineNum = 134;BA.debugLine="vue.AddCode($\"\"calories\": 237,\"$)";
_vue._addcode /*String*/ (("\"calories\": 237,"));
 //BA.debugLineNum = 135;BA.debugLine="vue.AddCode($\"\"fat\": 9,\"$)";
_vue._addcode /*String*/ (("\"fat\": 9,"));
 //BA.debugLineNum = 136;BA.debugLine="vue.AddCode($\"\"carbs\": 37,\"$)";
_vue._addcode /*String*/ (("\"carbs\": 37,"));
 //BA.debugLineNum = 137;BA.debugLine="vue.AddCode($\"\"protein\": 4.3,\"$)";
_vue._addcode /*String*/ (("\"protein\": 4.3,"));
 //BA.debugLineNum = 138;BA.debugLine="vue.AddCode($\"\"iron\": \"1%\",\"$)";
_vue._addcode /*String*/ (("\"iron\": \"1%\","));
 //BA.debugLineNum = 139;BA.debugLine="vue.AddCode($\"\"glutenfree\": \"No\"\"$)";
_vue._addcode /*String*/ (("\"glutenfree\": \"No\""));
 //BA.debugLineNum = 140;BA.debugLine="vue.AddCode($\"},\"$)";
_vue._addcode /*String*/ (("},"));
 //BA.debugLineNum = 141;BA.debugLine="vue.AddCode($\"{\"$)";
_vue._addcode /*String*/ (("{"));
 //BA.debugLineNum = 142;BA.debugLine="vue.AddCode($\"\"name\": \"Eclair\",\"$)";
_vue._addcode /*String*/ (("\"name\": \"Eclair\","));
 //BA.debugLineNum = 143;BA.debugLine="vue.AddCode($\"\"calories\": 262,\"$)";
_vue._addcode /*String*/ (("\"calories\": 262,"));
 //BA.debugLineNum = 144;BA.debugLine="vue.AddCode($\"\"fat\": 16,\"$)";
_vue._addcode /*String*/ (("\"fat\": 16,"));
 //BA.debugLineNum = 145;BA.debugLine="vue.AddCode($\"\"carbs\": 23,\"$)";
_vue._addcode /*String*/ (("\"carbs\": 23,"));
 //BA.debugLineNum = 146;BA.debugLine="vue.AddCode($\"\"protein\": 6,\"$)";
_vue._addcode /*String*/ (("\"protein\": 6,"));
 //BA.debugLineNum = 147;BA.debugLine="vue.AddCode($\"\"iron\": \"7%\",\"$)";
_vue._addcode /*String*/ (("\"iron\": \"7%\","));
 //BA.debugLineNum = 148;BA.debugLine="vue.AddCode($\"\"glutenfree\": \"No\"\"$)";
_vue._addcode /*String*/ (("\"glutenfree\": \"No\""));
 //BA.debugLineNum = 149;BA.debugLine="vue.AddCode($\"},\"$)";
_vue._addcode /*String*/ (("},"));
 //BA.debugLineNum = 150;BA.debugLine="vue.AddCode($\"{\"$)";
_vue._addcode /*String*/ (("{"));
 //BA.debugLineNum = 151;BA.debugLine="vue.AddCode($\"\"name\": \"Jelly bean\",\"$)";
_vue._addcode /*String*/ (("\"name\": \"Jelly bean\","));
 //BA.debugLineNum = 152;BA.debugLine="vue.AddCode($\"\"calories\": 375,\"$)";
_vue._addcode /*String*/ (("\"calories\": 375,"));
 //BA.debugLineNum = 153;BA.debugLine="vue.AddCode($\"\"fat\": 0,\"$)";
_vue._addcode /*String*/ (("\"fat\": 0,"));
 //BA.debugLineNum = 154;BA.debugLine="vue.AddCode($\"\"carbs\": 94,\"$)";
_vue._addcode /*String*/ (("\"carbs\": 94,"));
 //BA.debugLineNum = 155;BA.debugLine="vue.AddCode($\"\"protein\": 0,\"$)";
_vue._addcode /*String*/ (("\"protein\": 0,"));
 //BA.debugLineNum = 156;BA.debugLine="vue.AddCode($\"\"iron\": \"0%\",\"$)";
_vue._addcode /*String*/ (("\"iron\": \"0%\","));
 //BA.debugLineNum = 157;BA.debugLine="vue.AddCode($\"\"glutenfree\": \"Yes\"\"$)";
_vue._addcode /*String*/ (("\"glutenfree\": \"Yes\""));
 //BA.debugLineNum = 158;BA.debugLine="vue.AddCode($\"},\"$)";
_vue._addcode /*String*/ (("},"));
 //BA.debugLineNum = 159;BA.debugLine="vue.AddCode($\"{\"$)";
_vue._addcode /*String*/ (("{"));
 //BA.debugLineNum = 160;BA.debugLine="vue.AddCode($\"\"name\": \"Lollipop\",\"$)";
_vue._addcode /*String*/ (("\"name\": \"Lollipop\","));
 //BA.debugLineNum = 161;BA.debugLine="vue.AddCode($\"\"calories\": 392,\"$)";
_vue._addcode /*String*/ (("\"calories\": 392,"));
 //BA.debugLineNum = 162;BA.debugLine="vue.AddCode($\"\"fat\": 0.2,\"$)";
_vue._addcode /*String*/ (("\"fat\": 0.2,"));
 //BA.debugLineNum = 163;BA.debugLine="vue.AddCode($\"\"carbs\": 98,\"$)";
_vue._addcode /*String*/ (("\"carbs\": 98,"));
 //BA.debugLineNum = 164;BA.debugLine="vue.AddCode($\"\"protein\": 0,\"$)";
_vue._addcode /*String*/ (("\"protein\": 0,"));
 //BA.debugLineNum = 165;BA.debugLine="vue.AddCode($\"\"iron\": \"2%\",\"$)";
_vue._addcode /*String*/ (("\"iron\": \"2%\","));
 //BA.debugLineNum = 166;BA.debugLine="vue.AddCode($\"\"glutenfree\": \"Yes\"\"$)";
_vue._addcode /*String*/ (("\"glutenfree\": \"Yes\""));
 //BA.debugLineNum = 167;BA.debugLine="vue.AddCode($\"},\"$)";
_vue._addcode /*String*/ (("},"));
 //BA.debugLineNum = 168;BA.debugLine="vue.AddCode($\"{\"$)";
_vue._addcode /*String*/ (("{"));
 //BA.debugLineNum = 169;BA.debugLine="vue.AddCode($\"\"name\": \"KitKat\",\"$)";
_vue._addcode /*String*/ (("\"name\": \"KitKat\","));
 //BA.debugLineNum = 170;BA.debugLine="vue.AddCode($\"\"calories\": 518,\"$)";
_vue._addcode /*String*/ (("\"calories\": 518,"));
 //BA.debugLineNum = 171;BA.debugLine="vue.AddCode($\"\"fat\": 26,\"$)";
_vue._addcode /*String*/ (("\"fat\": 26,"));
 //BA.debugLineNum = 172;BA.debugLine="vue.AddCode($\"\"carbs\": 65,\"$)";
_vue._addcode /*String*/ (("\"carbs\": 65,"));
 //BA.debugLineNum = 173;BA.debugLine="vue.AddCode($\"\"protein\": 7,\"$)";
_vue._addcode /*String*/ (("\"protein\": 7,"));
 //BA.debugLineNum = 174;BA.debugLine="vue.AddCode($\"\"iron\": \"6%\",\"$)";
_vue._addcode /*String*/ (("\"iron\": \"6%\","));
 //BA.debugLineNum = 175;BA.debugLine="vue.AddCode($\"\"glutenfree\": \"False\"\"$)";
_vue._addcode /*String*/ (("\"glutenfree\": \"False\""));
 //BA.debugLineNum = 176;BA.debugLine="vue.AddCode($\"}\"$)";
_vue._addcode /*String*/ (("}"));
 //BA.debugLineNum = 177;BA.debugLine="vue.AddCode($\"]\"~)\"$)";
_vue._addcode /*String*/ (("]\"~)"));
 //BA.debugLineNum = 178;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"datDataCode\", \"Defi";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,moddatatable.getObject(),"datDataCode","Define DataTable Data - JSON Arrray",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (2),(int) (1));
 //BA.debugLineNum = 181;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 182;BA.debugLine="vue.AddCode($\"dt1 = vm.CreateDataTable(\"dt1\", \"nam";
_vue._addcode /*String*/ (("dt1 = vm.CreateDataTable(\"dt1\", \"name\", Me)"));
 //BA.debugLineNum = 183;BA.debugLine="vue.AddCode($\"dt1.SetTitle(\"Food Intake\")\"$)";
_vue._addcode /*String*/ (("dt1.SetTitle(\"Food Intake\")"));
 //BA.debugLineNum = 184;BA.debugLine="vue.AddCode($\"dt1.AddSearch\"$)";
_vue._addcode /*String*/ (("dt1.AddSearch"));
 //BA.debugLineNum = 185;BA.debugLine="vue.AddCode($\"dt1.AddDivider\"$)";
_vue._addcode /*String*/ (("dt1.AddDivider"));
 //BA.debugLineNum = 186;BA.debugLine="vue.AddCode($\"dt1.AddNew(\"btnNew\", \"mdi-plus\", \"Ad";
_vue._addcode /*String*/ (("dt1.AddNew(\"btnNew\", \"mdi-plus\", \"Add a new record\")"));
 //BA.debugLineNum = 187;BA.debugLine="vue.AddCode($\"dt1.SetDataSource(recs)\"$)";
_vue._addcode /*String*/ (("dt1.SetDataSource(recs)"));
 //BA.debugLineNum = 188;BA.debugLine="vue.AddCode($\"dt1.AddColumn1(\"name\", \"Desset (100g";
_vue._addcode /*String*/ (("dt1.AddColumn1(\"name\", \"Desset (100g serving)\", dt1.COLUMN_TEXT, 0, False, dt1.ALIGN_LEFT)"));
 //BA.debugLineNum = 189;BA.debugLine="vue.AddCode($\"dt1.AddColumns(CreateMap(\"calories\":";
_vue._addcode /*String*/ (("dt1.AddColumns(CreateMap(\"calories\": \"Calories\", \"fat\": \"Fat (g)\", \"carbs\": \"Carbs (g)\", \"protein\": \"Protein (g)\", \"iron\": \"Iron (%)\"))"));
 //BA.debugLineNum = 190;BA.debugLine="vue.AddCode($\"dt1.AddColumn(\"glutenfree\", \"Gluten-";
_vue._addcode /*String*/ (("dt1.AddColumn(\"glutenfree\", \"Gluten-Free\")"));
 //BA.debugLineNum = 191;BA.debugLine="vue.AddCode($\"dt1.AddEditThrash\"$)";
_vue._addcode /*String*/ (("dt1.AddEditThrash"));
 //BA.debugLineNum = 192;BA.debugLine="vue.AddCode($\"dt1.AddDownload\"$)";
_vue._addcode /*String*/ (("dt1.AddDownload"));
 //BA.debugLineNum = 193;BA.debugLine="vue.AddCode($\"dt1.AddMenuV\"$)";
_vue._addcode /*String*/ (("dt1.AddMenuV"));
 //BA.debugLineNum = 194;BA.debugLine="vue.AddCode($\"dt1.AddClone\"$)";
_vue._addcode /*String*/ (("dt1.AddClone"));
 //BA.debugLineNum = 195;BA.debugLine="vue.AddCode($\"dt1.AddPrint\"$)";
_vue._addcode /*String*/ (("dt1.AddPrint"));
 //BA.debugLineNum = 196;BA.debugLine="vue.AddCode($\"dt1.SetItemKey(\"name\")\"$)";
_vue._addcode /*String*/ (("dt1.SetItemKey(\"name\")"));
 //BA.debugLineNum = 197;BA.debugLine="vue.AddCode($\"dt1.SetColumnTotal(\"calories\", \"sumf";
_vue._addcode /*String*/ (("dt1.SetColumnTotal(\"calories\", \"sumfield('calories')\")"));
 //BA.debugLineNum = 198;BA.debugLine="vue.AddCode($\"'register the method\"$)";
_vue._addcode /*String*/ (("'register the method"));
 //BA.debugLineNum = 199;BA.debugLine="vue.AddCode($\"vue.SetMethod(Me, \"sumfield\")\"$)";
_vue._addcode /*String*/ (("vue.SetMethod(Me, \"sumfield\")"));
 //BA.debugLineNum = 200;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 201;BA.debugLine="vue.AddCode($\"dt1.SetColumnType(\"glutenfree\", dt1.";
_vue._addcode /*String*/ (("dt1.SetColumnType(\"glutenfree\", dt1.COLUMN_CHECKBOX)"));
 //BA.debugLineNum = 202;BA.debugLine="vue.AddCode($\"dt1.SetColumnType(\"calories\", dt1.CO";
_vue._addcode /*String*/ (("dt1.SetColumnType(\"calories\", dt1.COLUMN_CHIP)"));
 //BA.debugLineNum = 203;BA.debugLine="vue.AddCode($\"dt1.SetColumnExtra(\"calories\", ~\":co";
_vue._addcode /*String*/ (("dt1.SetColumnExtra(\"calories\", ~\":color=\"getcolor(item.calories)\"\"~)"));
 //BA.debugLineNum = 204;BA.debugLine="vue.AddCode($\"'dt1.SetColumnDisabled(\"calories\", T";
_vue._addcode /*String*/ (("'dt1.SetColumnDisabled(\"calories\", True)"));
 //BA.debugLineNum = 205;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 206;BA.debugLine="vue.AddCode($\"dt1.SetShowSelect(True)\"$)";
_vue._addcode /*String*/ (("dt1.SetShowSelect(True)"));
 //BA.debugLineNum = 207;BA.debugLine="vue.AddCode($\"'dt1.SetOnToggleSelectAll(\"dt1_selec";
_vue._addcode /*String*/ (("'dt1.SetOnToggleSelectAll(\"dt1_selectall\")"));
 //BA.debugLineNum = 208;BA.debugLine="vue.AddCode($\"'dt1.SetOnItemSelected(\"dt1_itemsele";
_vue._addcode /*String*/ (("'dt1.SetOnItemSelected(\"dt1_itemselected\")"));
 //BA.debugLineNum = 209;BA.debugLine="vue.AddCode($\"dt1.SetOnInput(\"dt1_input\")\"$)";
_vue._addcode /*String*/ (("dt1.SetOnInput(\"dt1_input\")"));
 //BA.debugLineNum = 210;BA.debugLine="vue.AddCode($\"'add an external pagination\"$)";
_vue._addcode /*String*/ (("'add an external pagination"));
 //BA.debugLineNum = 211;BA.debugLine="vue.AddCode($\"dt1.SetExternalPagination\"$)";
_vue._addcode /*String*/ (("dt1.SetExternalPagination"));
 //BA.debugLineNum = 212;BA.debugLine="vue.AddCode($\"dt1.AddDivider\"$)";
_vue._addcode /*String*/ (("dt1.AddDivider"));
 //BA.debugLineNum = 213;BA.debugLine="vue.AddCode($\"dt1.SetClearSort\"$)";
_vue._addcode /*String*/ (("dt1.SetClearSort"));
 //BA.debugLineNum = 214;BA.debugLine="vue.AddCode($\"dt1.AddDivider\"$)";
_vue._addcode /*String*/ (("dt1.AddDivider"));
 //BA.debugLineNum = 215;BA.debugLine="vue.AddCode($\"dt1.SetColumnChooser(True)\"$)";
_vue._addcode /*String*/ (("dt1.SetColumnChooser(True)"));
 //BA.debugLineNum = 216;BA.debugLine="vue.AddCode($\"dt1.AddToContainer(cont, 1, 1)\"$)";
_vue._addcode /*String*/ (("dt1.AddToContainer(cont, 1, 1)"));
 //BA.debugLineNum = 217;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"dt1code\", \"Data Tab";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,moddatatable.getObject(),"dt1code","Data Table",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (2),(int) (1));
 //BA.debugLineNum = 220;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 221;BA.debugLine="vue.AddCode($\"vm.SetMethod(Me,\"getcolor\")\"$)";
_vue._addcode /*String*/ (("vm.SetMethod(Me,\"getcolor\")"));
 //BA.debugLineNum = 222;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 223;BA.debugLine="vue.AddCode($\"'sum any column passed\"$)";
_vue._addcode /*String*/ (("'sum any column passed"));
 //BA.debugLineNum = 224;BA.debugLine="vue.AddCode($\"Sub sumfield(fld As String) As Strin";
_vue._addcode /*String*/ (("Sub sumfield(fld As String) As String"));
 //BA.debugLineNum = 225;BA.debugLine="vue.AddCode($\"'get all the records\"$)";
_vue._addcode /*String*/ (("'get all the records"));
 //BA.debugLineNum = 226;BA.debugLine="vue.AddCode($\"Dim totSum As Int = 0\"$)";
_vue._addcode /*String*/ (("Dim totSum As Int = 0"));
 //BA.debugLineNum = 227;BA.debugLine="vue.AddCode($\"Dim recs As List = dt1.GetData\"$)";
_vue._addcode /*String*/ (("Dim recs As List = dt1.GetData"));
 //BA.debugLineNum = 228;BA.debugLine="vue.AddCode($\"For Each rec As Map In recs\"$)";
_vue._addcode /*String*/ (("For Each rec As Map In recs"));
 //BA.debugLineNum = 229;BA.debugLine="vue.AddCode($\"Dim fldNum As String = rec.get(fld)\"";
_vue._addcode /*String*/ (("Dim fldNum As String = rec.get(fld)"));
 //BA.debugLineNum = 230;BA.debugLine="vue.AddCode($\"totSum = totSum + BANano.parseInt(fl";
_vue._addcode /*String*/ (("totSum = totSum + BANano.parseInt(fldNum)"));
 //BA.debugLineNum = 231;BA.debugLine="vue.AddCode($\"Next\"$)";
_vue._addcode /*String*/ (("Next"));
 //BA.debugLineNum = 232;BA.debugLine="vue.AddCode($\"totSum = vue.makemoney(totSum)\"$)";
_vue._addcode /*String*/ (("totSum = vue.makemoney(totSum)"));
 //BA.debugLineNum = 233;BA.debugLine="vue.AddCode($\"Return totSum\"$)";
_vue._addcode /*String*/ (("Return totSum"));
 //BA.debugLineNum = 234;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 235;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 236;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 237;BA.debugLine="vue.AddCode($\"Sub dtuserssave(e As BANanoEvent)\"$)";
_vue._addcode /*String*/ (("Sub dtuserssave(e As BANanoEvent)"));
 //BA.debugLineNum = 238;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 239;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 240;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 241;BA.debugLine="vue.AddCode($\"Sub dtuserscancel(e As BANanoEvent)\"";
_vue._addcode /*String*/ (("Sub dtuserscancel(e As BANanoEvent)"));
 //BA.debugLineNum = 242;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 243;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 244;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 245;BA.debugLine="vue.AddCode($\"Sub dtusersopen(e As BANanoEvent)\"$)";
_vue._addcode /*String*/ (("Sub dtusersopen(e As BANanoEvent)"));
 //BA.debugLineNum = 246;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 247;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 248;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 249;BA.debugLine="vue.AddCode($\"Sub dtusersclose(e As BANanoEvent)\"$";
_vue._addcode /*String*/ (("Sub dtusersclose(e As BANanoEvent)"));
 //BA.debugLineNum = 250;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 251;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 252;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 253;BA.debugLine="vue.AddCode($\"Sub dt1_input(items As List)\"$)";
_vue._addcode /*String*/ (("Sub dt1_input(items As List)"));
 //BA.debugLineNum = 254;BA.debugLine="vue.AddCode($\"Log(\"selected items\")\"$)";
_vue._addcode /*String*/ (("Log(\"selected items\")"));
 //BA.debugLineNum = 255;BA.debugLine="vue.AddCode($\"Dim selKeys As List = dt1.GetItemKey";
_vue._addcode /*String*/ (("Dim selKeys As List = dt1.GetItemKeys(items)"));
 //BA.debugLineNum = 256;BA.debugLine="vue.AddCode($\"Log(selKeys)\"$)";
_vue._addcode /*String*/ (("Log(selKeys)"));
 //BA.debugLineNum = 257;BA.debugLine="vue.AddCode($\"'join the items\"$)";
_vue._addcode /*String*/ (("'join the items"));
 //BA.debugLineNum = 258;BA.debugLine="vue.AddCode($\"Log(\"String Join\")\"$)";
_vue._addcode /*String*/ (("Log(\"String Join\")"));
 //BA.debugLineNum = 259;BA.debugLine="vue.AddCode($\"Dim selItems As String = vm.JoinItem";
_vue._addcode /*String*/ (("Dim selItems As String = vm.JoinItems(\",\", \"'\", selKeys)"));
 //BA.debugLineNum = 260;BA.debugLine="vue.AddCode($\"Log(selItems)\"$)";
_vue._addcode /*String*/ (("Log(selItems)"));
 //BA.debugLineNum = 261;BA.debugLine="vue.AddCode($\"'normal join\"$)";
_vue._addcode /*String*/ (("'normal join"));
 //BA.debugLineNum = 262;BA.debugLine="vue.AddCode($\"Log(\"Normal Join\")\"$)";
_vue._addcode /*String*/ (("Log(\"Normal Join\")"));
 //BA.debugLineNum = 263;BA.debugLine="vue.AddCode($\"Dim selNormal As String = vm.Join(\",";
_vue._addcode /*String*/ (("Dim selNormal As String = vm.Join(\",\", selKeys)"));
 //BA.debugLineNum = 264;BA.debugLine="vue.AddCode($\"Log(selNormal)\"$)";
_vue._addcode /*String*/ (("Log(selNormal)"));
 //BA.debugLineNum = 265;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 266;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 267;BA.debugLine="vue.AddCode($\"Sub dt1_itemselected(item As Map)\"$)";
_vue._addcode /*String*/ (("Sub dt1_itemselected(item As Map)"));
 //BA.debugLineNum = 268;BA.debugLine="vue.AddCode($\"Log(\"item selected\")\"$)";
_vue._addcode /*String*/ (("Log(\"item selected\")"));
 //BA.debugLineNum = 269;BA.debugLine="vue.AddCode($\"Log(item)\"$)";
_vue._addcode /*String*/ (("Log(item)"));
 //BA.debugLineNum = 270;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 271;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 272;BA.debugLine="vue.AddCode($\"Sub dt1_selectall(items As List)\"$)";
_vue._addcode /*String*/ (("Sub dt1_selectall(items As List)"));
 //BA.debugLineNum = 273;BA.debugLine="vue.AddCode($\"Log(items)\"$)";
_vue._addcode /*String*/ (("Log(items)"));
 //BA.debugLineNum = 274;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 275;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 276;BA.debugLine="vue.AddCode($\"Sub dt1_edit(item As Map)\"$)";
_vue._addcode /*String*/ (("Sub dt1_edit(item As Map)"));
 //BA.debugLineNum = 277;BA.debugLine="vue.AddCode($\"vm.ShowSnackBar(\"Edit: \" & BANano.to";
_vue._addcode /*String*/ (("vm.ShowSnackBar(\"Edit: \" & BANano.tojson(item))"));
 //BA.debugLineNum = 278;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 279;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 280;BA.debugLine="vue.AddCode($\"Sub dt1_delete(item As Map)\"$)";
_vue._addcode /*String*/ (("Sub dt1_delete(item As Map)"));
 //BA.debugLineNum = 281;BA.debugLine="vue.AddCode($\"vm.ShowSnackBar(\"Delete: \" & BANano.";
_vue._addcode /*String*/ (("vm.ShowSnackBar(\"Delete: \" & BANano.tojson(item))"));
 //BA.debugLineNum = 282;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 283;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 284;BA.debugLine="vue.AddCode($\"Sub dt1_download(item As Map)\"$)";
_vue._addcode /*String*/ (("Sub dt1_download(item As Map)"));
 //BA.debugLineNum = 285;BA.debugLine="vue.AddCode($\"vm.ShowSnackBar(\"Download: \" & BANan";
_vue._addcode /*String*/ (("vm.ShowSnackBar(\"Download: \" & BANano.tojson(item))"));
 //BA.debugLineNum = 286;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 287;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 288;BA.debugLine="vue.AddCode($\"Sub dt1_menu(item As Map)\"$)";
_vue._addcode /*String*/ (("Sub dt1_menu(item As Map)"));
 //BA.debugLineNum = 289;BA.debugLine="vue.AddCode($\"vm.ShowSnackBar(\"Menu: \" & BANano.to";
_vue._addcode /*String*/ (("vm.ShowSnackBar(\"Menu: \" & BANano.tojson(item))"));
 //BA.debugLineNum = 290;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 291;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 292;BA.debugLine="vue.AddCode($\"Sub dt1_clone(item As Map)\"$)";
_vue._addcode /*String*/ (("Sub dt1_clone(item As Map)"));
 //BA.debugLineNum = 293;BA.debugLine="vue.AddCode($\"vm.ShowSnackBar(\"Clone: \" & BANano.t";
_vue._addcode /*String*/ (("vm.ShowSnackBar(\"Clone: \" & BANano.tojson(item))"));
 //BA.debugLineNum = 294;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 295;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 296;BA.debugLine="vue.AddCode($\"Sub dt1_print(item As Map)\"$)";
_vue._addcode /*String*/ (("Sub dt1_print(item As Map)"));
 //BA.debugLineNum = 297;BA.debugLine="vue.AddCode($\"vm.ShowSnackBar(\"Print: \" & BANano.t";
_vue._addcode /*String*/ (("vm.ShowSnackBar(\"Print: \" & BANano.tojson(item))"));
 //BA.debugLineNum = 298;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 299;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 300;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 301;BA.debugLine="vue.AddCode($\"Sub getcolor(calories As Int) As Str";
_vue._addcode /*String*/ (("Sub getcolor(calories As Int) As String"));
 //BA.debugLineNum = 302;BA.debugLine="vue.AddCode($\"If calories > 400 Then\"$)";
_vue._addcode /*String*/ (("If calories > 400 Then"));
 //BA.debugLineNum = 303;BA.debugLine="vue.AddCode($\"Return \"red\"\"$)";
_vue._addcode /*String*/ (("Return \"red\""));
 //BA.debugLineNum = 304;BA.debugLine="vue.AddCode($\"else if calories > 200 Then\"$)";
_vue._addcode /*String*/ (("else if calories > 200 Then"));
 //BA.debugLineNum = 305;BA.debugLine="vue.AddCode($\"Return \"orange\"\"$)";
_vue._addcode /*String*/ (("Return \"orange\""));
 //BA.debugLineNum = 306;BA.debugLine="vue.AddCode($\"Else\"$)";
_vue._addcode /*String*/ (("Else"));
 //BA.debugLineNum = 307;BA.debugLine="vue.AddCode($\"Return \"green\"\"$)";
_vue._addcode /*String*/ (("Return \"green\""));
 //BA.debugLineNum = 308;BA.debugLine="vue.AddCode($\"End If\"$)";
_vue._addcode /*String*/ (("End If"));
 //BA.debugLineNum = 309;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 310;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"dt1codex\", \"Data Ta";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,moddatatable.getObject(),"dt1codex","Data Table Methods",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (2),(int) (1));
 //BA.debugLineNum = 315;BA.debugLine="Dim users As List = vm.NewList";
_users = new anywheresoftware.b4a.objects.collections.List();
_users = _vm._newlist /*anywheresoftware.b4a.objects.collections.List*/ ();
 //BA.debugLineNum = 316;BA.debugLine="users.add(CreateMap(\"avatar\": \"./assets/1.jpg\", \"";
_users.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("avatar"),(Object)("./assets/1.jpg"),(Object)("firstname"),(Object)("Him"),(Object)("lastname"),(Object)("One"),(Object)("active"),(Object)("Yes"),(Object)("rating"),(Object)(5),(Object)("tasks"),(Object)(9)}).getObject()));
 //BA.debugLineNum = 317;BA.debugLine="users.add(CreateMap(\"avatar\": \"./assets/2.jpg\", \"";
_users.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("avatar"),(Object)("./assets/2.jpg"),(Object)("firstname"),(Object)("Him 2"),(Object)("lastname"),(Object)("One"),(Object)("active"),(Object)("No"),(Object)("rating"),(Object)(4),(Object)("tasks"),(Object)(8)}).getObject()));
 //BA.debugLineNum = 318;BA.debugLine="users.add(CreateMap(\"avatar\": \"./assets/3.jpg\", \"";
_users.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("avatar"),(Object)("./assets/3.jpg"),(Object)("firstname"),(Object)("Her "),(Object)("lastname"),(Object)("One"),(Object)("active"),(Object)("Yes"),(Object)("rating"),(Object)(3),(Object)("tasks"),(Object)(5)}).getObject()));
 //BA.debugLineNum = 319;BA.debugLine="users.add(CreateMap(\"avatar\": \"./assets/4.jpg\", \"";
_users.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("avatar"),(Object)("./assets/4.jpg"),(Object)("firstname"),(Object)("Her 1"),(Object)("lastname"),(Object)("One"),(Object)("active"),(Object)("Yes"),(Object)("rating"),(Object)(2),(Object)("tasks"),(Object)(3)}).getObject()));
 //BA.debugLineNum = 320;BA.debugLine="users.add(CreateMap(\"avatar\": \"./assets/5.jpg\", \"";
_users.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("avatar"),(Object)("./assets/5.jpg"),(Object)("firstname"),(Object)("Her 2"),(Object)("lastname"),(Object)("One"),(Object)("active"),(Object)("No"),(Object)("rating"),(Object)(1),(Object)("tasks"),(Object)(1)}).getObject()));
 //BA.debugLineNum = 322;BA.debugLine="dtUsers = vm.CreateDataTable(\"dtUsers\", \"firstnam";
_dtusers = _vm._createdatatable /*b4j.example.vmdatatable*/ ("dtUsers","firstname",moddatatable.getObject());
 //BA.debugLineNum = 323;BA.debugLine="dtUsers.SetTitle(\"Users\")";
_dtusers._settitle /*b4j.example.vmdatatable*/ ("Users");
 //BA.debugLineNum = 324;BA.debugLine="dtUsers.AddAvatarImg(\"avatar\", \"Profile\")";
_dtusers._addavatarimg /*String*/ ("avatar","Profile");
 //BA.debugLineNum = 325;BA.debugLine="dtUsers.AddColumn(\"firstname\", \"First Name\")";
_dtusers._addcolumn /*b4j.example.vmdatatable*/ ("firstname","First Name");
 //BA.debugLineNum = 326;BA.debugLine="dtUsers.AddColumn(\"lastname\", \"Last Name\")";
_dtusers._addcolumn /*b4j.example.vmdatatable*/ ("lastname","Last Name");
 //BA.debugLineNum = 327;BA.debugLine="dtUsers.AddSwitch(\"active\", \"Active\")";
_dtusers._addswitch /*String*/ ("active","Active");
 //BA.debugLineNum = 328;BA.debugLine="dtUsers.AddRating(\"rating\", \"Performance\")";
_dtusers._addrating /*String*/ ("rating","Performance");
 //BA.debugLineNum = 329;BA.debugLine="dtUsers.AddEditDialog(\"firstname\",False)";
_dtusers._addeditdialog /*String*/ ("firstname",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 330;BA.debugLine="dtUsers.AddEditDialog(\"lastname\",False)";
_dtusers._addeditdialog /*String*/ ("lastname",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 333;BA.debugLine="dtUsers.AddProgressLinear(\"tasks\", \"Progress\")";
_dtusers._addprogresslinear /*String*/ ("tasks","Progress");
 //BA.debugLineNum = 334;BA.debugLine="dtUsers.SetProgressLinearDimensions(\"tasks\", \"ora";
_dtusers._setprogresslineardimensions /*b4j.example.vmdatatable*/ ("tasks","orange","25",anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 336;BA.debugLine="dtUsers.AddEditThrash";
_dtusers._addeditthrash /*String*/ ();
 //BA.debugLineNum = 337;BA.debugLine="dtUsers.SetIconDimensions(\"edit\", \"32px\", \"succes";
_dtusers._seticondimensions /*b4j.example.vmdatatable*/ ("edit","32px","success");
 //BA.debugLineNum = 338;BA.debugLine="dtUsers.SetIconDimensions(\"delete\", \"32p\", \"error";
_dtusers._seticondimensions /*b4j.example.vmdatatable*/ ("delete","32p","error");
 //BA.debugLineNum = 339;BA.debugLine="dtUsers.SetDataSource(users)";
_dtusers._setdatasource /*b4j.example.vmdatatable*/ (_users);
 //BA.debugLineNum = 340;BA.debugLine="dtUsers.SetExternalPagination";
_dtusers._setexternalpagination /*b4j.example.vmdatatable*/ ();
 //BA.debugLineNum = 341;BA.debugLine="dtUsers.AddToContainer(cont, 3, 1)";
_dtusers._addtocontainer /*String*/ (_cont,(int) (3),(int) (1));
 //BA.debugLineNum = 344;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 345;BA.debugLine="vue.AddCode($\"Dim users As List = vm.NewList\"$)";
_vue._addcode /*String*/ (("Dim users As List = vm.NewList"));
 //BA.debugLineNum = 346;BA.debugLine="vue.AddCode($\"users.add(CreateMap(\"avatar\": \"./ass";
_vue._addcode /*String*/ (("users.add(CreateMap(\"avatar\": \"./assets/1.jpg\", \"firstname\":\"Him\", \"lastname\":\"One\", \"active\":\"Yes\", \"rating\":5, \"tasks\":9))"));
 //BA.debugLineNum = 347;BA.debugLine="vue.AddCode($\"users.add(CreateMap(\"avatar\": \"./ass";
_vue._addcode /*String*/ (("users.add(CreateMap(\"avatar\": \"./assets/2.jpg\", \"firstname\":\"Him 2\", \"lastname\":\"One\", \"active\":\"No\", \"rating\":4, \"tasks\": 8))"));
 //BA.debugLineNum = 348;BA.debugLine="vue.AddCode($\"users.add(CreateMap(\"avatar\": \"./ass";
_vue._addcode /*String*/ (("users.add(CreateMap(\"avatar\": \"./assets/3.jpg\", \"firstname\":\"Her \", \"lastname\":\"One\", \"active\":\"Yes\", \"rating\":3, \"tasks\": 5))"));
 //BA.debugLineNum = 349;BA.debugLine="vue.AddCode($\"users.add(CreateMap(\"avatar\": \"./ass";
_vue._addcode /*String*/ (("users.add(CreateMap(\"avatar\": \"./assets/4.jpg\", \"firstname\":\"Her 1\", \"lastname\":\"One\", \"active\":\"Yes\", \"rating\":2, \"tasks\": 3))"));
 //BA.debugLineNum = 350;BA.debugLine="vue.AddCode($\"users.add(CreateMap(\"avatar\": \"./ass";
_vue._addcode /*String*/ (("users.add(CreateMap(\"avatar\": \"./assets/5.jpg\", \"firstname\":\"Her 2\", \"lastname\":\"One\", \"active\":\"No\", \"rating\":1, \"tasks\": 1))"));
 //BA.debugLineNum = 351;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 352;BA.debugLine="vue.AddCode($\"dtUsers = vm.CreateDataTable(\"dtUser";
_vue._addcode /*String*/ (("dtUsers = vm.CreateDataTable(\"dtUsers\", \"firstname\", Me)"));
 //BA.debugLineNum = 353;BA.debugLine="vue.AddCode($\"dtUsers.SetTitle(\"Users\")\"$)";
_vue._addcode /*String*/ (("dtUsers.SetTitle(\"Users\")"));
 //BA.debugLineNum = 354;BA.debugLine="vue.AddCode($\"dtUsers.AddAvatarImg(\"avatar\", \"Prof";
_vue._addcode /*String*/ (("dtUsers.AddAvatarImg(\"avatar\", \"Profile\")"));
 //BA.debugLineNum = 355;BA.debugLine="vue.AddCode($\"dtUsers.AddColumn(\"firstname\", \"Firs";
_vue._addcode /*String*/ (("dtUsers.AddColumn(\"firstname\", \"First Name\")"));
 //BA.debugLineNum = 356;BA.debugLine="vue.AddCode($\"dtUsers.AddColumn(\"lastname\", \"Last";
_vue._addcode /*String*/ (("dtUsers.AddColumn(\"lastname\", \"Last Name\")"));
 //BA.debugLineNum = 357;BA.debugLine="vue.AddCode($\"dtUsers.AddSwitch(\"active\", \"Active\"";
_vue._addcode /*String*/ (("dtUsers.AddSwitch(\"active\", \"Active\")"));
 //BA.debugLineNum = 358;BA.debugLine="vue.AddCode($\"dtUsers.AddRating(\"rating\", \"Perform";
_vue._addcode /*String*/ (("dtUsers.AddRating(\"rating\", \"Performance\")"));
 //BA.debugLineNum = 359;BA.debugLine="vue.AddCode($\"dtUsers.AddEditDialog(\"firstname\",Fa";
_vue._addcode /*String*/ (("dtUsers.AddEditDialog(\"firstname\",False)"));
 //BA.debugLineNum = 360;BA.debugLine="vue.AddCode($\"dtUsers.AddEditDialog(\"lastname\",Fal";
_vue._addcode /*String*/ (("dtUsers.AddEditDialog(\"lastname\",False)"));
 //BA.debugLineNum = 361;BA.debugLine="vue.AddCode($\"'dtUsers.AddProgressCircular(\"tasks\"";
_vue._addcode /*String*/ (("'dtUsers.AddProgressCircular(\"tasks\", \"Completed\")"));
 //BA.debugLineNum = 362;BA.debugLine="vue.AddCode($\"'dtUsers.SetProgressCircularDimensio";
_vue._addcode /*String*/ (("'dtUsers.SetProgressCircularDimensions(\"tasks\", \"green\", \"-90\", \"46\", \"6\")"));
 //BA.debugLineNum = 363;BA.debugLine="vue.AddCode($\"dtUsers.AddProgressLinear(\"tasks\", \"";
_vue._addcode /*String*/ (("dtUsers.AddProgressLinear(\"tasks\", \"Progress\")"));
 //BA.debugLineNum = 364;BA.debugLine="vue.AddCode($\"dtUsers.SetProgressLinearDimensions(";
_vue._addcode /*String*/ (("dtUsers.SetProgressLinearDimensions(\"tasks\", \"orange\", \"25\", True)"));
 //BA.debugLineNum = 365;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 366;BA.debugLine="vue.AddCode($\"dtUsers.AddEditThrash\"$)";
_vue._addcode /*String*/ (("dtUsers.AddEditThrash"));
 //BA.debugLineNum = 367;BA.debugLine="vue.AddCode($\"dtUsers.SetIconDimensions(\"edit\", \"3";
_vue._addcode /*String*/ (("dtUsers.SetIconDimensions(\"edit\", \"32px\", \"success\")"));
 //BA.debugLineNum = 368;BA.debugLine="vue.AddCode($\"dtUsers.SetIconDimensions(\"delete\",";
_vue._addcode /*String*/ (("dtUsers.SetIconDimensions(\"delete\", \"32p\", \"error\")"));
 //BA.debugLineNum = 369;BA.debugLine="vue.AddCode($\"dtUsers.SetDataSource(users)\"$)";
_vue._addcode /*String*/ (("dtUsers.SetDataSource(users)"));
 //BA.debugLineNum = 370;BA.debugLine="vue.AddCode($\"dtUsers.SetExternalPagination\"$)";
_vue._addcode /*String*/ (("dtUsers.SetExternalPagination"));
 //BA.debugLineNum = 371;BA.debugLine="vue.AddCode($\"dtUsers.AddToContainer(cont, 3, 1)\"$";
_vue._addcode /*String*/ (("dtUsers.AddToContainer(cont, 3, 1)"));
 //BA.debugLineNum = 372;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"usrdtcode\", \"Users";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,moddatatable.getObject(),"usrdtcode","Users Data Table",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (3),(int) (1));
 //BA.debugLineNum = 376;BA.debugLine="Dim images As List = vm.newlist";
_images = new anywheresoftware.b4a.objects.collections.List();
_images = _vm._newlist /*anywheresoftware.b4a.objects.collections.List*/ ();
 //BA.debugLineNum = 377;BA.debugLine="images.add(CreateMap(\"image\": \"./assets/bird.jpg\"";
_images.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("image"),(Object)("./assets/bird.jpg"),(Object)("comment"),(Object)("A bird seen from above"),(Object)("lat"),(Object)("16.0"),(Object)("lng"),(Object)("20.1")}).getObject()));
 //BA.debugLineNum = 378;BA.debugLine="images.add(CreateMap(\"image\": \"./assets/dark-beac";
_images.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("image"),(Object)("./assets/dark-beach.jpg"),(Object)("comment"),(Object)("Seen whilst walking"),(Object)("lat"),(Object)("36.0"),(Object)("lng"),(Object)("24.8")}).getObject()));
 //BA.debugLineNum = 379;BA.debugLine="images.add(CreateMap(\"image\": \"./assets/planet.jp";
_images.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("image"),(Object)("./assets/planet.jpg"),(Object)("comment"),(Object)("A need to visit planets"),(Object)("lat"),(Object)("1.0"),(Object)("lng"),(Object)("1.1")}).getObject()));
 //BA.debugLineNum = 380;BA.debugLine="images.add(CreateMap(\"image\": \"./assets/sky.jpg\",";
_images.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("image"),(Object)("./assets/sky.jpg"),(Object)("comment"),(Object)("A beautiful skyline"),(Object)("lat"),(Object)("0"),(Object)("lng"),(Object)("0")}).getObject()));
 //BA.debugLineNum = 381;BA.debugLine="images.add(CreateMap(\"image\": \"./assets/squirrel.";
_images.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("image"),(Object)("./assets/squirrel.jpg"),(Object)("comment"),(Object)("Nutting around"),(Object)("lat"),(Object)("45"),(Object)("lng"),(Object)("30")}).getObject()));
 //BA.debugLineNum = 383;BA.debugLine="dtImages = vm.CreateDataTable(\"dtImages\", \"image\"";
_dtimages = _vm._createdatatable /*b4j.example.vmdatatable*/ ("dtImages","image",moddatatable.getObject());
 //BA.debugLineNum = 384;BA.debugLine="dtImages.SetTitle(\"Presentation\")";
_dtimages._settitle /*b4j.example.vmdatatable*/ ("Presentation");
 //BA.debugLineNum = 385;BA.debugLine="dtImages.AddImage(\"image\", \"Image\")";
_dtimages._addimage /*String*/ ("image","Image");
 //BA.debugLineNum = 386;BA.debugLine="dtImages.SetImageDimensions(\"image\", \"80px\", \"80p";
_dtimages._setimagedimensions /*b4j.example.vmdatatable*/ ("image","80px","80px");
 //BA.debugLineNum = 387;BA.debugLine="dtImages.AddColumn(\"comment\", \"Comment\")";
_dtimages._addcolumn /*b4j.example.vmdatatable*/ ("comment","Comment");
 //BA.debugLineNum = 388;BA.debugLine="dtImages.AddColumn(\"datetaken\", \"Date Taken\")";
_dtimages._addcolumn /*b4j.example.vmdatatable*/ ("datetaken","Date Taken");
 //BA.debugLineNum = 389;BA.debugLine="dtImages.AddColumn(\"lat\", \"Latitude\")";
_dtimages._addcolumn /*b4j.example.vmdatatable*/ ("lat","Latitude");
 //BA.debugLineNum = 390;BA.debugLine="dtImages.AddColumn(\"lng\", \"Longitude\")";
_dtimages._addcolumn /*b4j.example.vmdatatable*/ ("lng","Longitude");
 //BA.debugLineNum = 391;BA.debugLine="dtImages.SetDataSource(images)";
_dtimages._setdatasource /*b4j.example.vmdatatable*/ (_images);
 //BA.debugLineNum = 392;BA.debugLine="dtImages.SetExternalPagination";
_dtimages._setexternalpagination /*b4j.example.vmdatatable*/ ();
 //BA.debugLineNum = 393;BA.debugLine="dtImages.AddToContainer(cont, 4, 1)";
_dtimages._addtocontainer /*String*/ (_cont,(int) (4),(int) (1));
 //BA.debugLineNum = 396;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 397;BA.debugLine="vue.AddCode($\"Dim images As List = vm.newlist\"$)";
_vue._addcode /*String*/ (("Dim images As List = vm.newlist"));
 //BA.debugLineNum = 398;BA.debugLine="vue.AddCode($\"images.add(CreateMap(\"image\": \"./ass";
_vue._addcode /*String*/ (("images.add(CreateMap(\"image\": \"./assets/bird.jpg\", \"comment\":\"A bird seen from above\", \"lat\":\"16.0\", \"lng\":\"20.1\"))"));
 //BA.debugLineNum = 399;BA.debugLine="vue.AddCode($\"images.add(CreateMap(\"image\": \"./ass";
_vue._addcode /*String*/ (("images.add(CreateMap(\"image\": \"./assets/dark-beach.jpg\", \"comment\":\"Seen whilst walking\", \"lat\":\"36.0\", \"lng\":\"24.8\"))"));
 //BA.debugLineNum = 400;BA.debugLine="vue.AddCode($\"images.add(CreateMap(\"image\": \"./ass";
_vue._addcode /*String*/ (("images.add(CreateMap(\"image\": \"./assets/planet.jpg\", \"comment\":\"A need to visit planets\", \"lat\":\"1.0\", \"lng\":\"1.1\"))"));
 //BA.debugLineNum = 401;BA.debugLine="vue.AddCode($\"images.add(CreateMap(\"image\": \"./ass";
_vue._addcode /*String*/ (("images.add(CreateMap(\"image\": \"./assets/sky.jpg\", \"comment\":\"A beautiful skyline\", \"lat\":\"0\", \"lng\":\"0\"))"));
 //BA.debugLineNum = 402;BA.debugLine="vue.AddCode($\"images.add(CreateMap(\"image\": \"./ass";
_vue._addcode /*String*/ (("images.add(CreateMap(\"image\": \"./assets/squirrel.jpg\", \"comment\":\"Nutting around\", \"lat\":\"45\", \"lng\":\"30\"))"));
 //BA.debugLineNum = 403;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 404;BA.debugLine="vue.AddCode($\"dtImages = vm.CreateDataTable(\"dtIma";
_vue._addcode /*String*/ (("dtImages = vm.CreateDataTable(\"dtImages\", \"image\", Me)"));
 //BA.debugLineNum = 405;BA.debugLine="vue.AddCode($\"dtImages.SetTitle(\"Presentation\")\"$)";
_vue._addcode /*String*/ (("dtImages.SetTitle(\"Presentation\")"));
 //BA.debugLineNum = 406;BA.debugLine="vue.AddCode($\"dtImages.AddImage(\"image\", \"Image\")\"";
_vue._addcode /*String*/ (("dtImages.AddImage(\"image\", \"Image\")"));
 //BA.debugLineNum = 407;BA.debugLine="vue.AddCode($\"dtImages.SetImageDimensions(\"image\",";
_vue._addcode /*String*/ (("dtImages.SetImageDimensions(\"image\", \"80px\", \"80px\")"));
 //BA.debugLineNum = 408;BA.debugLine="vue.AddCode($\"dtImages.AddColumn(\"comment\", \"Comme";
_vue._addcode /*String*/ (("dtImages.AddColumn(\"comment\", \"Comment\")"));
 //BA.debugLineNum = 409;BA.debugLine="vue.AddCode($\"dtImages.AddColumn(\"datetaken\", \"Dat";
_vue._addcode /*String*/ (("dtImages.AddColumn(\"datetaken\", \"Date Taken\")"));
 //BA.debugLineNum = 410;BA.debugLine="vue.AddCode($\"dtImages.AddColumn(\"lat\", \"Latitude\"";
_vue._addcode /*String*/ (("dtImages.AddColumn(\"lat\", \"Latitude\")"));
 //BA.debugLineNum = 411;BA.debugLine="vue.AddCode($\"dtImages.AddColumn(\"lng\", \"Longitude";
_vue._addcode /*String*/ (("dtImages.AddColumn(\"lng\", \"Longitude\")"));
 //BA.debugLineNum = 412;BA.debugLine="vue.AddCode($\"dtImages.SetDataSource(images)\"$)";
_vue._addcode /*String*/ (("dtImages.SetDataSource(images)"));
 //BA.debugLineNum = 413;BA.debugLine="vue.AddCode($\"dtImages.SetExternalPagination\"$)";
_vue._addcode /*String*/ (("dtImages.SetExternalPagination"));
 //BA.debugLineNum = 414;BA.debugLine="vue.AddCode($\"dtImages.AddToContainer(cont, 4, 1)\"";
_vue._addcode /*String*/ (("dtImages.AddToContainer(cont, 4, 1)"));
 //BA.debugLineNum = 415;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 416;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"imgdtcode\", \"Images";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,moddatatable.getObject(),"imgdtcode","Images Data Table",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (4),(int) (1));
 //BA.debugLineNum = 419;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 421;BA.debugLine="vm.SetMethod(Me,\"getcolor\")";
_vm._setmethod /*b4j.example.bananovm*/ (moddatatable.getObject(),"getcolor");
 //BA.debugLineNum = 422;BA.debugLine="End Sub";
return "";
}
public static String  _datdatacodecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 464;BA.debugLine="Sub datDataCodecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 465;BA.debugLine="vue.CopyCode2Clipboard(\"datDataCode\")";
_vue._copycode2clipboard /*String*/ ("datDataCode");
 //BA.debugLineNum = 466;BA.debugLine="End Sub";
return "";
}
public static String  _datdatacodedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 468;BA.debugLine="Sub datDataCodedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 469;BA.debugLine="vue.DownloadCode(\"datDataCode\", \"datDataCode.txt\"";
_vue._downloadcode /*String*/ ("datDataCode","datDataCode.txt");
 //BA.debugLineNum = 470;BA.debugLine="End Sub";
return "";
}
public static String  _dt1_clone(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 542;BA.debugLine="Sub dt1_clone(item As Map)";
 //BA.debugLineNum = 543;BA.debugLine="vm.ShowSnackBar(\"Clone: \" & BANano.tojson(item))";
_vm._showsnackbar /*String*/ ("Clone: "+BA.ObjectToString(_banano.ToJson((Object)(_item.getObject()))));
 //BA.debugLineNum = 544;BA.debugLine="End Sub";
return "";
}
public static String  _dt1_delete(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 530;BA.debugLine="Sub dt1_delete(item As Map)";
 //BA.debugLineNum = 531;BA.debugLine="vm.ShowSnackBar(\"Delete: \" & BANano.tojson(item))";
_vm._showsnackbar /*String*/ ("Delete: "+BA.ObjectToString(_banano.ToJson((Object)(_item.getObject()))));
 //BA.debugLineNum = 532;BA.debugLine="End Sub";
return "";
}
public static String  _dt1_download(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 534;BA.debugLine="Sub dt1_download(item As Map)";
 //BA.debugLineNum = 535;BA.debugLine="vm.ShowSnackBar(\"Download: \" & BANano.tojson(item";
_vm._showsnackbar /*String*/ ("Download: "+BA.ObjectToString(_banano.ToJson((Object)(_item.getObject()))));
 //BA.debugLineNum = 536;BA.debugLine="End Sub";
return "";
}
public static String  _dt1_edit(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 526;BA.debugLine="Sub dt1_edit(item As Map)";
 //BA.debugLineNum = 527;BA.debugLine="vm.ShowSnackBar(\"Edit: \" & BANano.tojson(item))";
_vm._showsnackbar /*String*/ ("Edit: "+BA.ObjectToString(_banano.ToJson((Object)(_item.getObject()))));
 //BA.debugLineNum = 528;BA.debugLine="End Sub";
return "";
}
public static String  _dt1_input(anywheresoftware.b4a.objects.collections.List _items) throws Exception{
anywheresoftware.b4a.objects.collections.List _selkeys = null;
String _selitems = "";
String _selnormal = "";
 //BA.debugLineNum = 503;BA.debugLine="Sub dt1_input(items As List)";
 //BA.debugLineNum = 504;BA.debugLine="Log(\"selected items\")";
anywheresoftware.b4a.keywords.Common.Log("selected items");
 //BA.debugLineNum = 505;BA.debugLine="Dim selKeys As List = dt1.GetItemKeys(items)";
_selkeys = new anywheresoftware.b4a.objects.collections.List();
_selkeys = _dt1._getitemkeys /*anywheresoftware.b4a.objects.collections.List*/ (_items);
 //BA.debugLineNum = 506;BA.debugLine="Log(selKeys)";
anywheresoftware.b4a.keywords.Common.Log(BA.ObjectToString(_selkeys));
 //BA.debugLineNum = 508;BA.debugLine="Log(\"String Join\")";
anywheresoftware.b4a.keywords.Common.Log("String Join");
 //BA.debugLineNum = 509;BA.debugLine="Dim selItems As String = vm.JoinItems(\",\", \"'\", s";
_selitems = _vm._joinitems /*String*/ (",","'",_selkeys);
 //BA.debugLineNum = 510;BA.debugLine="Log(selItems)";
anywheresoftware.b4a.keywords.Common.Log(_selitems);
 //BA.debugLineNum = 512;BA.debugLine="Log(\"Normal Join\")";
anywheresoftware.b4a.keywords.Common.Log("Normal Join");
 //BA.debugLineNum = 513;BA.debugLine="Dim selNormal As String = vm.Join(\",\", selKeys)";
_selnormal = _vm._join /*String*/ (",",_selkeys);
 //BA.debugLineNum = 514;BA.debugLine="Log(selNormal)";
anywheresoftware.b4a.keywords.Common.Log(_selnormal);
 //BA.debugLineNum = 515;BA.debugLine="End Sub";
return "";
}
public static String  _dt1_itemselected(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 517;BA.debugLine="Sub dt1_itemselected(item As Map)";
 //BA.debugLineNum = 518;BA.debugLine="Log(\"item selected\")";
anywheresoftware.b4a.keywords.Common.Log("item selected");
 //BA.debugLineNum = 519;BA.debugLine="Log(item)";
anywheresoftware.b4a.keywords.Common.Log(BA.ObjectToString(_item));
 //BA.debugLineNum = 520;BA.debugLine="End Sub";
return "";
}
public static String  _dt1_menu(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 538;BA.debugLine="Sub dt1_menu(item As Map)";
 //BA.debugLineNum = 539;BA.debugLine="vm.ShowSnackBar(\"Menu: \" & BANano.tojson(item))";
_vm._showsnackbar /*String*/ ("Menu: "+BA.ObjectToString(_banano.ToJson((Object)(_item.getObject()))));
 //BA.debugLineNum = 540;BA.debugLine="End Sub";
return "";
}
public static String  _dt1_print(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 546;BA.debugLine="Sub dt1_print(item As Map)";
 //BA.debugLineNum = 547;BA.debugLine="vm.ShowSnackBar(\"Print: \" & BANano.tojson(item))";
_vm._showsnackbar /*String*/ ("Print: "+BA.ObjectToString(_banano.ToJson((Object)(_item.getObject()))));
 //BA.debugLineNum = 548;BA.debugLine="End Sub";
return "";
}
public static String  _dt1_selectall(anywheresoftware.b4a.objects.collections.List _items) throws Exception{
 //BA.debugLineNum = 522;BA.debugLine="Sub dt1_selectall(items As List)";
 //BA.debugLineNum = 523;BA.debugLine="Log(items)";
anywheresoftware.b4a.keywords.Common.Log(BA.ObjectToString(_items));
 //BA.debugLineNum = 524;BA.debugLine="End Sub";
return "";
}
public static String  _dt1codecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 455;BA.debugLine="Sub dt1codecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 456;BA.debugLine="vue.CopyCode2Clipboard(\"dt1code\")";
_vue._copycode2clipboard /*String*/ ("dt1code");
 //BA.debugLineNum = 457;BA.debugLine="End Sub";
return "";
}
public static String  _dt1codedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 459;BA.debugLine="Sub dt1codedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 460;BA.debugLine="vue.DownloadCode(\"dt1code\", \"dt1code.txt\")";
_vue._downloadcode /*String*/ ("dt1code","dt1code.txt");
 //BA.debugLineNum = 461;BA.debugLine="End Sub";
return "";
}
public static String  _dt1codexcopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 444;BA.debugLine="Sub dt1codexcopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 445;BA.debugLine="vue.CopyCode2Clipboard(\"dt1codex\")";
_vue._copycode2clipboard /*String*/ ("dt1codex");
 //BA.debugLineNum = 446;BA.debugLine="End Sub";
return "";
}
public static String  _dt1codexdownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 448;BA.debugLine="Sub dt1codexdownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 449;BA.debugLine="vue.DownloadCode(\"dt1codex\", \"dt1codex.txt\")";
_vue._downloadcode /*String*/ ("dt1codex","dt1codex.txt");
 //BA.debugLineNum = 450;BA.debugLine="End Sub";
return "";
}
public static String  _dtusers_active(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 550;BA.debugLine="Sub dtusers_active(item As Map)";
 //BA.debugLineNum = 551;BA.debugLine="vm.ShowSnackBar(\"Active: \" & BANano.tojson(item))";
_vm._showsnackbar /*String*/ ("Active: "+BA.ObjectToString(_banano.ToJson((Object)(_item.getObject()))));
 //BA.debugLineNum = 552;BA.debugLine="End Sub";
return "";
}
public static String  _dtusers_firstname(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 558;BA.debugLine="Sub dtusers_firstname(item As Map)";
 //BA.debugLineNum = 559;BA.debugLine="vm.ShowSnackBar(\"FirstName: \" & BANano.tojson(ite";
_vm._showsnackbar /*String*/ ("FirstName: "+BA.ObjectToString(_banano.ToJson((Object)(_item.getObject()))));
 //BA.debugLineNum = 560;BA.debugLine="End Sub";
return "";
}
public static String  _dtusers_rating(anywheresoftware.b4a.objects.collections.Map _item) throws Exception{
 //BA.debugLineNum = 554;BA.debugLine="Sub dtusers_rating(item As Map)";
 //BA.debugLineNum = 555;BA.debugLine="vm.ShowSnackBar(\"Rating: \" & BANano.tojson(item))";
_vm._showsnackbar /*String*/ ("Rating: "+BA.ObjectToString(_banano.ToJson((Object)(_item.getObject()))));
 //BA.debugLineNum = 556;BA.debugLine="End Sub";
return "";
}
public static String  _dtuserscancel(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 491;BA.debugLine="Sub dtuserscancel(e As BANanoEvent)";
 //BA.debugLineNum = 493;BA.debugLine="End Sub";
return "";
}
public static String  _dtusersclose(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 499;BA.debugLine="Sub dtusersclose(e As BANanoEvent)";
 //BA.debugLineNum = 501;BA.debugLine="End Sub";
return "";
}
public static String  _dtusersopen(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 495;BA.debugLine="Sub dtusersopen(e As BANanoEvent)";
 //BA.debugLineNum = 497;BA.debugLine="End Sub";
return "";
}
public static String  _dtuserssave(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 487;BA.debugLine="Sub dtuserssave(e As BANanoEvent)";
 //BA.debugLineNum = 489;BA.debugLine="End Sub";
return "";
}
public static String  _getcolor(int _calories) throws Exception{
 //BA.debugLineNum = 566;BA.debugLine="Sub getcolor(calories As Int) As String";
 //BA.debugLineNum = 567;BA.debugLine="If calories > 400 Then";
if (_calories>400) { 
 //BA.debugLineNum = 568;BA.debugLine="Return \"red\"";
if (true) return "red";
 }else if(_calories>200) { 
 //BA.debugLineNum = 570;BA.debugLine="Return \"orange\"";
if (true) return "orange";
 }else {
 //BA.debugLineNum = 572;BA.debugLine="Return \"green\"";
if (true) return "green";
 };
 //BA.debugLineNum = 574;BA.debugLine="End Sub";
return "";
}
public static String  _imgdtcodecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 425;BA.debugLine="Sub imgdtcodecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 426;BA.debugLine="vue.CopyCode2Clipboard(\"imgdtcode\")";
_vue._copycode2clipboard /*String*/ ("imgdtcode");
 //BA.debugLineNum = 427;BA.debugLine="End Sub";
return "";
}
public static String  _imgdtcodedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 429;BA.debugLine="Sub imgdtcodedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 430;BA.debugLine="vue.DownloadCode(\"imgdtcode\", \"imgdtcode.txt\")";
_vue._downloadcode /*String*/ ("imgdtcode","imgdtcode.txt");
 //BA.debugLineNum = 431;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 3;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 4;BA.debugLine="Public name As String = \"dataTableCode\"";
_name = "dataTableCode";
 //BA.debugLineNum = 5;BA.debugLine="Public title As String = \"Data Table\"";
_title = "Data Table";
 //BA.debugLineNum = 6;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 7;BA.debugLine="Private BANano As BANano  'ignore";
_banano = new com.ab.banano.BANano();
 //BA.debugLineNum = 8;BA.debugLine="Private dt1 As VMDataTable";
_dt1 = new b4j.example.vmdatatable();
 //BA.debugLineNum = 9;BA.debugLine="Private dtUsers As VMDataTable";
_dtusers = new b4j.example.vmdatatable();
 //BA.debugLineNum = 10;BA.debugLine="Private dtImages As VMDataTable";
_dtimages = new b4j.example.vmdatatable();
 //BA.debugLineNum = 11;BA.debugLine="Private vue As BANanoVue";
_vue = new b4j.example.bananovue();
 //BA.debugLineNum = 12;BA.debugLine="End Sub";
return "";
}
public static String  _sumfield(String _fld) throws Exception{
int _totsum = 0;
anywheresoftware.b4a.objects.collections.List _recs = null;
anywheresoftware.b4a.objects.collections.Map _rec = null;
String _fldnum = "";
 //BA.debugLineNum = 475;BA.debugLine="Sub sumfield(fld As String) As String";
 //BA.debugLineNum = 477;BA.debugLine="Dim totSum As Int = 0";
_totsum = (int) (0);
 //BA.debugLineNum = 478;BA.debugLine="Dim recs As List = dt1.GetData";
_recs = new anywheresoftware.b4a.objects.collections.List();
_recs = _dt1._getdata /*anywheresoftware.b4a.objects.collections.List*/ ();
 //BA.debugLineNum = 479;BA.debugLine="For Each rec As Map In recs";
_rec = new anywheresoftware.b4a.objects.collections.Map();
{
final anywheresoftware.b4a.BA.IterableList group3 = _recs;
final int groupLen3 = group3.getSize()
;int index3 = 0;
;
for (; index3 < groupLen3;index3++){
_rec = (anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(group3.Get(index3)));
 //BA.debugLineNum = 480;BA.debugLine="Dim fldNum As String = rec.get(fld)";
_fldnum = BA.ObjectToString(_rec.Get((Object)(_fld)));
 //BA.debugLineNum = 481;BA.debugLine="totSum = totSum + BANano.parseInt(fldNum)";
_totsum = (int) (_totsum+_banano.parseInt((Object)(_fldnum)));
 }
};
 //BA.debugLineNum = 483;BA.debugLine="totSum = vue.makemoney(totSum)";
_totsum = (int)(Double.parseDouble(_vue._makemoney /*String*/ (BA.NumberToString(_totsum))));
 //BA.debugLineNum = 484;BA.debugLine="Return totSum";
if (true) return BA.NumberToString(_totsum);
 //BA.debugLineNum = 485;BA.debugLine="End Sub";
return "";
}
public static String  _usrdtcodecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 435;BA.debugLine="Sub usrdtcodecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 436;BA.debugLine="vue.CopyCode2Clipboard(\"usrdtcode\")";
_vue._copycode2clipboard /*String*/ ("usrdtcode");
 //BA.debugLineNum = 437;BA.debugLine="End Sub";
return "";
}
public static String  _usrdtcodedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 439;BA.debugLine="Sub usrdtcodedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 440;BA.debugLine="vue.DownloadCode(\"usrdtcode\", \"usrdtcode.txt\")";
_vue._downloadcode /*String*/ ("usrdtcode","usrdtcode.txt");
 //BA.debugLineNum = 441;BA.debugLine="End Sub";
return "";
}
}
