package b4j.example;


import anywheresoftware.b4a.BA;

public class modexpansionpanels extends Object{
public static modexpansionpanels mostCurrent = new modexpansionpanels();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.modexpansionpanels", null);
		ba.loadHtSubs(modexpansionpanels.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.modexpansionpanels", ba);
		}
	}
    public static Class<?> getObject() {
		return modexpansionpanels.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static b4j.example.bananovue _vue = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcalendar _modcalendar = null;
public static b4j.example.modcard _modcard = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modautocomplete _modautocomplete = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatatable _moddatatable = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddesign _moddesign = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modgrid _modgrid = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimeline _modtimeline = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modtreeview _modtreeview = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _code() throws Exception{
b4j.example.vmcontainer _cont = null;
b4j.example.vmexpansionpanels _ep = null;
b4j.example.vmexpansionpanel _expx = null;
b4j.example.vmlabel _lbl1 = null;
b4j.example.vmcontainer _contbtna = null;
b4j.example.vmcontainer _contbtnb = null;
b4j.example.vmcontainer _contbtnc = null;
b4j.example.vmcontainer _contbtnd = null;
b4j.example.vmcontainer _contbtne = null;
b4j.example.vmexpansionpanels _exppanel1 = null;
 //BA.debugLineNum = 10;BA.debugLine="Sub Code";
 //BA.debugLineNum = 11;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 12;BA.debugLine="vue = vm.vue";
_vue = _vm._vue /*b4j.example.bananovue*/ ;
 //BA.debugLineNum = 14;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,modexpansionpanels.getObject());
 //BA.debugLineNum = 16;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 17;BA.debugLine="cont.AddRows(2).AddColumns12";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (2))._addcolumns12 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 19;BA.debugLine="Dim ep As VMExpansionPanels = vm.CreateExpansionP";
_ep = _vm._createexpansionpanels /*b4j.example.vmexpansionpanels*/ ("ep",modexpansionpanels.getObject())._setaccordion /*b4j.example.vmexpansionpanels*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 20;BA.debugLine="Dim expx As VMExpansionPanel = vm.CreateExpansion";
_expx = _vm._createexpansionpanel /*b4j.example.vmexpansionpanel*/ ("ep1","ep",modexpansionpanels.getObject());
 //BA.debugLineNum = 21;BA.debugLine="expx.SetVFor(\"(item, i)\", \"5\")";
_expx._setvfor /*b4j.example.vmexpansionpanel*/ ("(item, i)","5");
 //BA.debugLineNum = 22;BA.debugLine="expx.Bind(\":key\", \"i\")";
_expx._bind /*b4j.example.vmexpansionpanel*/ (":key","i");
 //BA.debugLineNum = 23;BA.debugLine="expx.Bind(\":id\", \"i\")";
_expx._bind /*b4j.example.vmexpansionpanel*/ (":id","i");
 //BA.debugLineNum = 24;BA.debugLine="expx.Header.SetText(\"Item\")";
_expx._header /*b4j.example.vmexpansionpanelheader*/ ._settext /*b4j.example.vmexpansionpanelheader*/ ("Item");
 //BA.debugLineNum = 25;BA.debugLine="expx.Content.SetText(vm.Rand_LoremIpsum(1))";
_expx._content /*b4j.example.vmexpansionpanelcontent*/ ._settext /*b4j.example.vmexpansionpanelcontent*/ ((Object)(_vm._rand_loremipsum /*String*/ ((int) (1))));
 //BA.debugLineNum = 26;BA.debugLine="ep.AddPanel(expx)";
_ep._addpanel /*b4j.example.vmexpansionpanels*/ (_expx);
 //BA.debugLineNum = 27;BA.debugLine="cont.AddComponent(1, 1, ep.tostring)";
_cont._addcomponent /*String*/ ((int) (1),(int) (1),_ep._tostring /*String*/ ());
 //BA.debugLineNum = 30;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 31;BA.debugLine="vue.AddCode($\"' make accordion\"$)";
_vue._addcode /*String*/ (("' make accordion"));
 //BA.debugLineNum = 32;BA.debugLine="vue.AddCode($\"Dim ep As VMExpansionPanels = vm.Cre";
_vue._addcode /*String*/ (("Dim ep As VMExpansionPanels = vm.CreateExpansionPanels(\"ep\", Me).SetAccordion(True)"));
 //BA.debugLineNum = 33;BA.debugLine="vue.AddCode($\"Dim expx As VMExpansionPanel = vm.Cr";
_vue._addcode /*String*/ (("Dim expx As VMExpansionPanel = vm.CreateExpansionPanel(\"ep1\", \"ep\", Me)"));
 //BA.debugLineNum = 34;BA.debugLine="vue.AddCode($\"expx.SetVFor(\"(item, i)\", \"5\")\"$)";
_vue._addcode /*String*/ (("expx.SetVFor(\"(item, i)\", \"5\")"));
 //BA.debugLineNum = 35;BA.debugLine="vue.AddCode($\"expx.Bind(\":key\", \"i\")\"$)";
_vue._addcode /*String*/ (("expx.Bind(\":key\", \"i\")"));
 //BA.debugLineNum = 36;BA.debugLine="vue.AddCode($\"expx.Bind(\":id\", \"i\")\"$)";
_vue._addcode /*String*/ (("expx.Bind(\":id\", \"i\")"));
 //BA.debugLineNum = 37;BA.debugLine="vue.AddCode($\"expx.Header.SetText(\"Item\")\"$)";
_vue._addcode /*String*/ (("expx.Header.SetText(\"Item\")"));
 //BA.debugLineNum = 38;BA.debugLine="vue.AddCode($\"expx.Content.SetText(vm.Rand_LoremIp";
_vue._addcode /*String*/ (("expx.Content.SetText(vm.Rand_LoremIpsum(1))"));
 //BA.debugLineNum = 39;BA.debugLine="vue.AddCode($\"ep.AddPanel(expx)\"$)";
_vue._addcode /*String*/ (("ep.AddPanel(expx)"));
 //BA.debugLineNum = 40;BA.debugLine="vue.AddCode($\"cont.AddComponent(1, 1, ep.tostring)";
_vue._addcode /*String*/ (("cont.AddComponent(1, 1, ep.tostring)"));
 //BA.debugLineNum = 41;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"exp1code\", \"Accordi";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modexpansionpanels.getObject(),"exp1code","Accordion v-for",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (1),(int) (1));
 //BA.debugLineNum = 44;BA.debugLine="Dim lbl1 As VMLabel = vm.CreateLabel(\"\").SetH1";
_lbl1 = _vm._createlabel /*b4j.example.vmlabel*/ ("")._seth1 /*b4j.example.vmlabel*/ ();
 //BA.debugLineNum = 45;BA.debugLine="lbl1.SetText(vm.Rand_LoremIpsum(1))";
_lbl1._settext /*b4j.example.vmlabel*/ (_vm._rand_loremipsum /*String*/ ((int) (1)));
 //BA.debugLineNum = 47;BA.debugLine="Dim contbtna As VMContainer";
_contbtna = new b4j.example.vmcontainer();
 //BA.debugLineNum = 48;BA.debugLine="contbtna = vm.CreateContainer(\"contbtna\", Me)";
_contbtna = _vm._createcontainer /*b4j.example.vmcontainer*/ ("contbtna",modexpansionpanels.getObject());
 //BA.debugLineNum = 49;BA.debugLine="contbtna.AddControlS(lbl1.Label, lbl1.tostring, 1";
_contbtna._addcontrols /*String*/ (_lbl1._label /*b4j.example.vmelement*/ ,_lbl1._tostring /*String*/ (),BA.NumberToString(1),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12));
 //BA.debugLineNum = 51;BA.debugLine="Dim contbtnb As VMContainer";
_contbtnb = new b4j.example.vmcontainer();
 //BA.debugLineNum = 52;BA.debugLine="contbtnb = vm.CreateContainer(\"contbtnb\", Me)";
_contbtnb = _vm._createcontainer /*b4j.example.vmcontainer*/ ("contbtnb",modexpansionpanels.getObject());
 //BA.debugLineNum = 53;BA.debugLine="contbtnb.AddControlS(lbl1.Label, lbl1.tostring, 1";
_contbtnb._addcontrols /*String*/ (_lbl1._label /*b4j.example.vmelement*/ ,_lbl1._tostring /*String*/ (),BA.NumberToString(1),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12));
 //BA.debugLineNum = 56;BA.debugLine="Dim contbtnc As VMContainer";
_contbtnc = new b4j.example.vmcontainer();
 //BA.debugLineNum = 57;BA.debugLine="contbtnc = vm.CreateContainer(\"contbtnc\", Me)";
_contbtnc = _vm._createcontainer /*b4j.example.vmcontainer*/ ("contbtnc",modexpansionpanels.getObject());
 //BA.debugLineNum = 58;BA.debugLine="contbtnc.AddControlS(lbl1.Label, lbl1.tostring, 1";
_contbtnc._addcontrols /*String*/ (_lbl1._label /*b4j.example.vmelement*/ ,_lbl1._tostring /*String*/ (),BA.NumberToString(1),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12));
 //BA.debugLineNum = 61;BA.debugLine="Dim contbtnd As VMContainer";
_contbtnd = new b4j.example.vmcontainer();
 //BA.debugLineNum = 62;BA.debugLine="contbtnd = vm.CreateContainer(\"contbtnd\", Me)";
_contbtnd = _vm._createcontainer /*b4j.example.vmcontainer*/ ("contbtnd",modexpansionpanels.getObject());
 //BA.debugLineNum = 63;BA.debugLine="contbtnd.AddControlS(lbl1.Label, lbl1.tostring, 1";
_contbtnd._addcontrols /*String*/ (_lbl1._label /*b4j.example.vmelement*/ ,_lbl1._tostring /*String*/ (),BA.NumberToString(1),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12));
 //BA.debugLineNum = 66;BA.debugLine="Dim contbtne As VMContainer";
_contbtne = new b4j.example.vmcontainer();
 //BA.debugLineNum = 67;BA.debugLine="contbtne = vm.CreateContainer(\"contbtne\", Me)";
_contbtne = _vm._createcontainer /*b4j.example.vmcontainer*/ ("contbtne",modexpansionpanels.getObject());
 //BA.debugLineNum = 68;BA.debugLine="contbtne.AddControlS(lbl1.Label, lbl1.tostring, 1";
_contbtne._addcontrols /*String*/ (_lbl1._label /*b4j.example.vmelement*/ ,_lbl1._tostring /*String*/ (),BA.NumberToString(1),BA.NumberToString(1),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12),BA.NumberToString(12));
 //BA.debugLineNum = 71;BA.debugLine="Dim exppanel1 As VMExpansionPanels = vm.CreateExpa";
_exppanel1 = _vm._createexpansionpanels /*b4j.example.vmexpansionpanels*/ ("exppanel1",modexpansionpanels.getObject());
 //BA.debugLineNum = 72;BA.debugLine="exppanel1.SetAccordion(True)";
_exppanel1._setaccordion /*b4j.example.vmexpansionpanels*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 73;BA.debugLine="exppanel1.SetActivepanel(\"1\")";
_exppanel1._setactivepanel /*b4j.example.vmexpansionpanels*/ ("1");
 //BA.debugLineNum = 74;BA.debugLine="exppanel1.SetTile(True)";
_exppanel1._settile /*b4j.example.vmexpansionpanels*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 75;BA.debugLine="exppanel1.SetVisible(True)";
_exppanel1._setvisible /*b4j.example.vmexpansionpanels*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 76;BA.debugLine="exppanel1.AddPanel1(\"btna\", \"Banner\", contbtna)";
_exppanel1._addpanel1 /*String*/ ("btna","Banner",_contbtna);
 //BA.debugLineNum = 77;BA.debugLine="exppanel1.AddPanel1(\"btnb\", \"Squirrel\", contbtnb)";
_exppanel1._addpanel1 /*String*/ ("btnb","Squirrel",_contbtnb);
 //BA.debugLineNum = 78;BA.debugLine="exppanel1.AddPanel1(\"btnc\", \"Sky\", contbtnc)";
_exppanel1._addpanel1 /*String*/ ("btnc","Sky",_contbtnc);
 //BA.debugLineNum = 79;BA.debugLine="exppanel1.AddPanel1(\"btnd\", \"Planet\", contbtnd)";
_exppanel1._addpanel1 /*String*/ ("btnd","Planet",_contbtnd);
 //BA.debugLineNum = 80;BA.debugLine="exppanel1.AddPanel1(\"btne\", \"Bird\", contbtne)";
_exppanel1._addpanel1 /*String*/ ("btne","Bird",_contbtne);
 //BA.debugLineNum = 81;BA.debugLine="cont.AddComponent(2, 1, exppanel1.tostring)";
_cont._addcomponent /*String*/ ((int) (2),(int) (1),_exppanel1._tostring /*String*/ ());
 //BA.debugLineNum = 84;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 85;BA.debugLine="vue.AddCode($\"Dim lbl1 As VMLabel = vm.CreateLabel";
_vue._addcode /*String*/ (("Dim lbl1 As VMLabel = vm.CreateLabel(\"\").SetH1"));
 //BA.debugLineNum = 86;BA.debugLine="vue.AddCode($\"lbl1.SetText(vm.Rand_LoremIpsum(1))\"";
_vue._addcode /*String*/ (("lbl1.SetText(vm.Rand_LoremIpsum(1))"));
 //BA.debugLineNum = 87;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 88;BA.debugLine="vue.AddCode($\"Dim contbtna As VMContainer\"$)";
_vue._addcode /*String*/ (("Dim contbtna As VMContainer"));
 //BA.debugLineNum = 89;BA.debugLine="vue.AddCode($\"contbtna = vm.CreateContainer(\"contb";
_vue._addcode /*String*/ (("contbtna = vm.CreateContainer(\"contbtna\", Me)"));
 //BA.debugLineNum = 90;BA.debugLine="vue.AddCode($\"contbtna.AddControlS(lbl1.Label, lbl";
_vue._addcode /*String*/ (("contbtna.AddControlS(lbl1.Label, lbl1.tostring, 1, 1, 12, 12, 12, 12)"));
 //BA.debugLineNum = 91;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 92;BA.debugLine="vue.AddCode($\"Dim contbtnb As VMContainer\"$)";
_vue._addcode /*String*/ (("Dim contbtnb As VMContainer"));
 //BA.debugLineNum = 93;BA.debugLine="vue.AddCode($\"contbtnb = vm.CreateContainer(\"contb";
_vue._addcode /*String*/ (("contbtnb = vm.CreateContainer(\"contbtnb\", Me)"));
 //BA.debugLineNum = 94;BA.debugLine="vue.AddCode($\"contbtnb.AddControlS(lbl1.Label, lbl";
_vue._addcode /*String*/ (("contbtnb.AddControlS(lbl1.Label, lbl1.tostring, 1, 1, 12, 12, 12, 12)"));
 //BA.debugLineNum = 95;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 96;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 97;BA.debugLine="vue.AddCode($\"Dim contbtnc As VMContainer\"$)";
_vue._addcode /*String*/ (("Dim contbtnc As VMContainer"));
 //BA.debugLineNum = 98;BA.debugLine="vue.AddCode($\"contbtnc = vm.CreateContainer(\"contb";
_vue._addcode /*String*/ (("contbtnc = vm.CreateContainer(\"contbtnc\", Me)"));
 //BA.debugLineNum = 99;BA.debugLine="vue.AddCode($\"contbtnc.AddControlS(lbl1.Label, lbl";
_vue._addcode /*String*/ (("contbtnc.AddControlS(lbl1.Label, lbl1.tostring, 1, 1, 12, 12, 12, 12)"));
 //BA.debugLineNum = 100;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 101;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 102;BA.debugLine="vue.AddCode($\"Dim contbtnd As VMContainer\"$)";
_vue._addcode /*String*/ (("Dim contbtnd As VMContainer"));
 //BA.debugLineNum = 103;BA.debugLine="vue.AddCode($\"contbtnd = vm.CreateContainer(\"contb";
_vue._addcode /*String*/ (("contbtnd = vm.CreateContainer(\"contbtnd\", Me)"));
 //BA.debugLineNum = 104;BA.debugLine="vue.AddCode($\"contbtnd.AddControlS(lbl1.Label, lbl";
_vue._addcode /*String*/ (("contbtnd.AddControlS(lbl1.Label, lbl1.tostring, 1, 1, 12, 12, 12, 12)"));
 //BA.debugLineNum = 105;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 106;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 107;BA.debugLine="vue.AddCode($\"Dim contbtne As VMContainer\"$)";
_vue._addcode /*String*/ (("Dim contbtne As VMContainer"));
 //BA.debugLineNum = 108;BA.debugLine="vue.AddCode($\"contbtne = vm.CreateContainer(\"contb";
_vue._addcode /*String*/ (("contbtne = vm.CreateContainer(\"contbtne\", Me)"));
 //BA.debugLineNum = 109;BA.debugLine="vue.AddCode($\"contbtne.AddControlS(lbl1.Label, lbl";
_vue._addcode /*String*/ (("contbtne.AddControlS(lbl1.Label, lbl1.tostring, 1, 1, 12, 12, 12, 12)"));
 //BA.debugLineNum = 110;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 111;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 112;BA.debugLine="vue.AddCode($\"Dim exppanel1 As VMExpansionPanels =";
_vue._addcode /*String*/ (("Dim exppanel1 As VMExpansionPanels = vm.CreateExpansionPanels(\"exppanel1\", Me)"));
 //BA.debugLineNum = 113;BA.debugLine="vue.AddCode($\"exppanel1.SetAccordion(True)\"$)";
_vue._addcode /*String*/ (("exppanel1.SetAccordion(True)"));
 //BA.debugLineNum = 114;BA.debugLine="vue.AddCode($\"exppanel1.SetActivepanel(\"1\")\"$)";
_vue._addcode /*String*/ (("exppanel1.SetActivepanel(\"1\")"));
 //BA.debugLineNum = 115;BA.debugLine="vue.AddCode($\"exppanel1.SetTile(True)\"$)";
_vue._addcode /*String*/ (("exppanel1.SetTile(True)"));
 //BA.debugLineNum = 116;BA.debugLine="vue.AddCode($\"exppanel1.SetVisible(True)\"$)";
_vue._addcode /*String*/ (("exppanel1.SetVisible(True)"));
 //BA.debugLineNum = 117;BA.debugLine="vue.AddCode($\"exppanel1.AddPanel1(\"btna\", \"Banner\"";
_vue._addcode /*String*/ (("exppanel1.AddPanel1(\"btna\", \"Banner\", contbtna)"));
 //BA.debugLineNum = 118;BA.debugLine="vue.AddCode($\"exppanel1.AddPanel1(\"btnb\", \"Squirre";
_vue._addcode /*String*/ (("exppanel1.AddPanel1(\"btnb\", \"Squirrel\", contbtnb)"));
 //BA.debugLineNum = 119;BA.debugLine="vue.AddCode($\"exppanel1.AddPanel1(\"btnc\", \"Sky\", c";
_vue._addcode /*String*/ (("exppanel1.AddPanel1(\"btnc\", \"Sky\", contbtnc)"));
 //BA.debugLineNum = 120;BA.debugLine="vue.AddCode($\"exppanel1.AddPanel1(\"btnd\", \"Planet\"";
_vue._addcode /*String*/ (("exppanel1.AddPanel1(\"btnd\", \"Planet\", contbtnd)"));
 //BA.debugLineNum = 121;BA.debugLine="vue.AddCode($\"exppanel1.AddPanel1(\"btne\", \"Bird\",";
_vue._addcode /*String*/ (("exppanel1.AddPanel1(\"btne\", \"Bird\", contbtne)"));
 //BA.debugLineNum = 122;BA.debugLine="vue.AddCode($\"cont.AddComponent(2, 1, exppanel1.to";
_vue._addcode /*String*/ (("cont.AddComponent(2, 1, exppanel1.tostring)"));
 //BA.debugLineNum = 123;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"exp2code\", \"Accordi";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modexpansionpanels.getObject(),"exp2code","Accordion using Containers",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (2),(int) (1));
 //BA.debugLineNum = 126;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 127;BA.debugLine="End Sub";
return "";
}
public static String  _ep_click(com.ab.banano.BANanoEvent _e) throws Exception{
String _eid = "";
 //BA.debugLineNum = 152;BA.debugLine="Sub ep_click(e As BANanoEvent)";
 //BA.debugLineNum = 153;BA.debugLine="Dim eID As String = vm.GetIDFromEvent(e)";
_eid = _vm._getidfromevent /*String*/ (_e);
 //BA.debugLineNum = 154;BA.debugLine="vm.ShowSnackBar(eID)";
_vm._showsnackbar /*String*/ (_eid);
 //BA.debugLineNum = 155;BA.debugLine="End Sub";
return "";
}
public static String  _exp1codecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 139;BA.debugLine="Sub exp1codecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 140;BA.debugLine="vue.CopyCode2Clipboard(\"exp1code\")";
_vue._copycode2clipboard /*String*/ ("exp1code");
 //BA.debugLineNum = 141;BA.debugLine="End Sub";
return "";
}
public static String  _exp1codedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 143;BA.debugLine="Sub exp1codedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 144;BA.debugLine="vue.DownloadCode(\"exp1code\", \"exp1code.txt\")";
_vue._downloadcode /*String*/ ("exp1code","exp1code.txt");
 //BA.debugLineNum = 145;BA.debugLine="End Sub";
return "";
}
public static String  _exp2codecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 130;BA.debugLine="Sub exp2codecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 131;BA.debugLine="vue.CopyCode2Clipboard(\"exp2code\")";
_vue._copycode2clipboard /*String*/ ("exp2code");
 //BA.debugLineNum = 132;BA.debugLine="End Sub";
return "";
}
public static String  _exp2codedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 134;BA.debugLine="Sub exp2codedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 135;BA.debugLine="vue.DownloadCode(\"exp2code\", \"exp2code.txt\")";
_vue._downloadcode /*String*/ ("exp2code","exp2code.txt");
 //BA.debugLineNum = 136;BA.debugLine="End Sub";
return "";
}
public static String  _exppanel1_click(com.ab.banano.BANanoEvent _e) throws Exception{
String _expid = "";
 //BA.debugLineNum = 147;BA.debugLine="Private Sub exppanel1_click(e As BANanoEvent)";
 //BA.debugLineNum = 148;BA.debugLine="Dim expid As String = vm.GetIDFromEvent(e)";
_expid = _vm._getidfromevent /*String*/ (_e);
 //BA.debugLineNum = 149;BA.debugLine="vm.ShowSnackBar(expid)";
_vm._showsnackbar /*String*/ (_expid);
 //BA.debugLineNum = 150;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Public name As String = \"expansionPanelCode\"";
_name = "expansionPanelCode";
 //BA.debugLineNum = 4;BA.debugLine="Public title As String = \"Expansion Panels\"";
_title = "Expansion Panels";
 //BA.debugLineNum = 5;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 6;BA.debugLine="Private vue As BANanoVue";
_vue = new b4j.example.bananovue();
 //BA.debugLineNum = 7;BA.debugLine="End Sub";
return "";
}
}
