package b4j.example;


import anywheresoftware.b4a.BA;

public class modgrid extends Object{
public static modgrid mostCurrent = new modgrid();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.modgrid", null);
		ba.loadHtSubs(modgrid.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.modgrid", ba);
		}
	}
    public static Class<?> getObject() {
		return modgrid.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcalendar _modcalendar = null;
public static b4j.example.modcard _modcard = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modautocomplete _modautocomplete = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatatable _moddatatable = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddesign _moddesign = null;
public static b4j.example.modexpansionpanels _modexpansionpanels = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimeline _modtimeline = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modtreeview _modtreeview = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _code() throws Exception{
b4j.example.vmcontainer _cont = null;
 //BA.debugLineNum = 9;BA.debugLine="Sub Code";
 //BA.debugLineNum = 10;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 12;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,modgrid.getObject());
 //BA.debugLineNum = 14;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 16;BA.debugLine="cont.AddRows(1).AddColumns12";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns12 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 17;BA.debugLine="cont.SetBorderRC(1,1, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (1),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 18;BA.debugLine="cont.AddLabel(1, 1, \"\", \"p\", \"R1C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (1),(int) (1),"","p","R1C1");
 //BA.debugLineNum = 20;BA.debugLine="cont.AddRows(1).AddColumns11p1";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns11p1 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 21;BA.debugLine="cont.SetBorderRC(2,1, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (2),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 22;BA.debugLine="cont.SetBorderRC(2,2, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (2),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 23;BA.debugLine="cont.AddLabel(2, 1, \"\", \"p\", \"R2C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (2),(int) (1),"","p","R2C1");
 //BA.debugLineNum = 24;BA.debugLine="cont.AddLabel(2, 2, \"\", \"p\", \"R2C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (2),(int) (2),"","p","R2C2");
 //BA.debugLineNum = 26;BA.debugLine="cont.AddRows(1).AddColumns10p2";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns10p2 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 27;BA.debugLine="cont.SetBorderRC(3,1, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (3),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 28;BA.debugLine="cont.SetBorderRC(3,2, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (3),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 29;BA.debugLine="cont.AddLabel(3, 1, \"\", \"p\", \"R3C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (3),(int) (1),"","p","R3C1");
 //BA.debugLineNum = 30;BA.debugLine="cont.AddLabel(3, 2, \"\", \"p\", \"R3C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (3),(int) (2),"","p","R3C2");
 //BA.debugLineNum = 33;BA.debugLine="cont.AddRows(1).AddColumns9p3";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns9p3 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 34;BA.debugLine="cont.SetBorderRC(4,1, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (4),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 35;BA.debugLine="cont.SetBorderRC(4,2, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (4),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 36;BA.debugLine="cont.AddLabel(4, 1, \"\", \"p\", \"R4C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (4),(int) (1),"","p","R4C1");
 //BA.debugLineNum = 37;BA.debugLine="cont.AddLabel(4, 2, \"\", \"p\", \"R4C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (4),(int) (2),"","p","R4C2");
 //BA.debugLineNum = 39;BA.debugLine="cont.AddRows(1).AddColumns8p4";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns8p4 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 40;BA.debugLine="cont.SetBorderRC(5,1, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (5),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 41;BA.debugLine="cont.SetBorderRC(5,2, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (5),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 42;BA.debugLine="cont.AddLabel(5, 1, \"\", \"p\", \"R5C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (5),(int) (1),"","p","R5C1");
 //BA.debugLineNum = 43;BA.debugLine="cont.AddLabel(5, 2, \"\", \"p\", \"R5C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (5),(int) (2),"","p","R5C2");
 //BA.debugLineNum = 46;BA.debugLine="cont.AddRows(1).AddColumns7p5";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns7p5 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 47;BA.debugLine="cont.SetBorderRC(6,1, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (6),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 48;BA.debugLine="cont.SetBorderRC(6,2, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (6),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 49;BA.debugLine="cont.AddLabel(6, 1, \"\", \"p\", \"R6C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (6),(int) (1),"","p","R6C1");
 //BA.debugLineNum = 50;BA.debugLine="cont.AddLabel(6, 2, \"\", \"p\", \"R6C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (6),(int) (2),"","p","R6C2");
 //BA.debugLineNum = 52;BA.debugLine="cont.AddRows(1).AddColumns2x6";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns2x6 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 53;BA.debugLine="cont.SetBorderRC(7,1, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (7),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 54;BA.debugLine="cont.SetBorderRC(7,2, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (7),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 55;BA.debugLine="cont.AddLabel(7, 1, \"\", \"p\", \"R8C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (7),(int) (1),"","p","R8C1");
 //BA.debugLineNum = 56;BA.debugLine="cont.AddLabel(7, 2, \"\", \"p\", \"R8C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (7),(int) (2),"","p","R8C2");
 //BA.debugLineNum = 59;BA.debugLine="cont.AddRows(1).AddColumns5p7";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns5p7 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 60;BA.debugLine="cont.SetBorderRC(8,1, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (8),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 61;BA.debugLine="cont.SetBorderRC(8,2, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (8),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 62;BA.debugLine="cont.AddLabel(8, 1, \"\", \"p\", \"R8C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (8),(int) (1),"","p","R8C1");
 //BA.debugLineNum = 63;BA.debugLine="cont.AddLabel(8, 2, \"\", \"p\", \"R8C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (8),(int) (2),"","p","R8C2");
 //BA.debugLineNum = 66;BA.debugLine="cont.AddRows(1).AddColumns4p8";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns4p8 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 67;BA.debugLine="cont.SetBorderRC(9,1, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (9),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 68;BA.debugLine="cont.SetBorderRC(9,2, \"1px\", vm.vue.COLOR_BLUE, v";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (9),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 69;BA.debugLine="cont.AddLabel(9, 1, \"\", \"p\", \"R9C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (9),(int) (1),"","p","R9C1");
 //BA.debugLineNum = 70;BA.debugLine="cont.AddLabel(9, 2, \"\", \"p\", \"R9C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (9),(int) (2),"","p","R9C2");
 //BA.debugLineNum = 73;BA.debugLine="cont.AddRows(1).AddColumns3p9";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns3p9 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 74;BA.debugLine="cont.SetBorderRC(10,1, \"1px\", vm.vue.COLOR_BLUE,";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (10),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 75;BA.debugLine="cont.SetBorderRC(10,2, \"1px\", vm.vue.COLOR_BLUE,";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (10),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 76;BA.debugLine="cont.AddLabel(10, 1, \"\", \"p\", \"R10C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (10),(int) (1),"","p","R10C1");
 //BA.debugLineNum = 77;BA.debugLine="cont.AddLabel(10, 2, \"\", \"p\", \"R10C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (10),(int) (2),"","p","R10C2");
 //BA.debugLineNum = 80;BA.debugLine="cont.AddRows(1).AddColumns2p10";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns2p10 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 81;BA.debugLine="cont.SetBorderRC(11,1, \"1px\", vm.vue.COLOR_BLUE,";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (11),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 82;BA.debugLine="cont.SetBorderRC(11,2, \"1px\", vm.vue.COLOR_BLUE,";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (11),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 83;BA.debugLine="cont.AddLabel(11, 1, \"\", \"p\", \"R11C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (11),(int) (1),"","p","R11C1");
 //BA.debugLineNum = 84;BA.debugLine="cont.AddLabel(11, 2, \"\", \"p\", \"R11C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (11),(int) (2),"","p","R11C2");
 //BA.debugLineNum = 87;BA.debugLine="cont.AddRows(1).AddColumns1p11";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns1p11 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 88;BA.debugLine="cont.SetBorderRC(12,1, \"1px\", vm.vue.COLOR_BLUE,";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (12),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 89;BA.debugLine="cont.SetBorderRC(12,2, \"1px\", vm.vue.COLOR_BLUE,";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (12),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 90;BA.debugLine="cont.AddLabel(12, 1, \"\", \"p\", \"R12C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (12),(int) (1),"","p","R12C1");
 //BA.debugLineNum = 91;BA.debugLine="cont.AddLabel(12, 2, \"\", \"p\", \"R12C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (12),(int) (2),"","p","R12C2");
 //BA.debugLineNum = 96;BA.debugLine="cont.AddRows(1).AddColumns(1,2,2,2,2).AddColumns(";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns /*b4j.example.vmcontainer*/ ((int) (1),(int) (2),(int) (2),(int) (2),(int) (2))._addcolumns /*b4j.example.vmcontainer*/ ((int) (1),(int) (8),(int) (8),(int) (8),(int) (8))._addcolumns /*b4j.example.vmcontainer*/ ((int) (1),(int) (2),(int) (2),(int) (2),(int) (2));
 //BA.debugLineNum = 97;BA.debugLine="cont.SetBorderRC(13,1, \"1px\", vm.vue.COLOR_BLUE,";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (13),(int) (1),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 98;BA.debugLine="cont.SetBorderRC(13,2, \"1px\", vm.vue.COLOR_BLUE,";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (13),(int) (2),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 99;BA.debugLine="cont.SetBorderRC(13,3, \"1px\", vm.vue.COLOR_BLUE,";
_cont._setborderrc /*b4j.example.vmcontainer*/ ((int) (13),(int) (3),"1px",_vm._vue /*b4j.example.bananovue*/ ._color_blue /*String*/ ,_vm._vue /*b4j.example.bananovue*/ ._border_dashed /*String*/ );
 //BA.debugLineNum = 100;BA.debugLine="cont.AddLabel(13, 1, \"\", \"p\", \"R13C1\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (13),(int) (1),"","p","R13C1");
 //BA.debugLineNum = 101;BA.debugLine="cont.AddLabel(13, 2, \"\", \"p\", \"R13C2\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (13),(int) (2),"","p","R13C2");
 //BA.debugLineNum = 102;BA.debugLine="cont.AddLabel(13, 3, \"\", \"p\", \"R13C3\")";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (13),(int) (3),"","p","R13C3");
 //BA.debugLineNum = 105;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 106;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Public name As String = \"introCode\"";
_name = "introCode";
 //BA.debugLineNum = 4;BA.debugLine="Public title As String = \"Grid\"";
_title = "Grid";
 //BA.debugLineNum = 5;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 6;BA.debugLine="End Sub";
return "";
}
}
