package b4j.example;


import anywheresoftware.b4a.BA;

public class modtreeview extends Object{
public static modtreeview mostCurrent = new modtreeview();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.modtreeview", null);
		ba.loadHtSubs(modtreeview.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.modtreeview", ba);
		}
	}
    public static Class<?> getObject() {
		return modtreeview.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static b4j.example.vmtreeview _tv = null;
public static com.ab.banano.BANano _banano = null;
public static b4j.example.bananovue _vue = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcalendar _modcalendar = null;
public static b4j.example.modcard _modcard = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modautocomplete _modautocomplete = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatatable _moddatatable = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddesign _moddesign = null;
public static b4j.example.modexpansionpanels _modexpansionpanels = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modgrid _modgrid = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimeline _modtimeline = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _code() throws Exception{
b4j.example.vmcontainer _cont = null;
b4j.example.vmtreeview _tv2 = null;
 //BA.debugLineNum = 12;BA.debugLine="Sub Code";
 //BA.debugLineNum = 13;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 14;BA.debugLine="vue = vm.vue";
_vue = _vm._vue /*b4j.example.bananovue*/ ;
 //BA.debugLineNum = 16;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,modtreeview.getObject());
 //BA.debugLineNum = 18;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 20;BA.debugLine="cont.AddRows(10).AddColumns12";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (10))._addcolumns12 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 22;BA.debugLine="Dim tv As VMTreeView = vm.CreateTreeView(\"tv1\", M";
_tv = _vm._createtreeview /*b4j.example.vmtreeview*/ ("tv1",modtreeview.getObject());
 //BA.debugLineNum = 24;BA.debugLine="tv.SetSelectable(True)";
_tv._setselectable /*b4j.example.vmtreeview*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 25;BA.debugLine="tv.AddItem(\"\", \"1\", \"Applications\", \"\", Null, Fal";
_tv._additem /*b4j.example.vmtreeview*/ ("","1","Applications","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 26;BA.debugLine="tv.AddItem(\"1\", \"2\", \"Calendar\", \"\", Null, False)";
_tv._additem /*b4j.example.vmtreeview*/ ("1","2","Calendar","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 27;BA.debugLine="tv.AddItem(\"1\", \"3\", \"Chrome\", \"\", Null, False)";
_tv._additem /*b4j.example.vmtreeview*/ ("1","3","Chrome","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 28;BA.debugLine="tv.AddItem(\"1\", \"4\", \"Webstorm\", \"\", Null, False)";
_tv._additem /*b4j.example.vmtreeview*/ ("1","4","Webstorm","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 29;BA.debugLine="tv.AddItem(\"\", \"5\", \"Documents\", \"\", Null, False)";
_tv._additem /*b4j.example.vmtreeview*/ ("","5","Documents","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 30;BA.debugLine="tv.AddItem(\"5\", \"6\", \"vuetify\", \"\", Null, False)";
_tv._additem /*b4j.example.vmtreeview*/ ("5","6","vuetify","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 31;BA.debugLine="tv.AddItem(\"6\", \"7\", \"src\", \"\", Null, False)";
_tv._additem /*b4j.example.vmtreeview*/ ("6","7","src","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 32;BA.debugLine="tv.AddItem(\"7\", \"8\", \"index.html\", \"\", \"html\", Fa";
_tv._additem /*b4j.example.vmtreeview*/ ("7","8","index.html","","html",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 33;BA.debugLine="tv.AddItem(\"7\", \"9\", \"bootstrap.ts\", \"\", \"ts\", Fa";
_tv._additem /*b4j.example.vmtreeview*/ ("7","9","bootstrap.ts","","ts",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 34;BA.debugLine="tv.AddItem(\"7\", \"15\", \"logo.png\", \"\", \"png\", Fals";
_tv._additem /*b4j.example.vmtreeview*/ ("7","15","logo.png","","png",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 35;BA.debugLine="tv.AddItem(\"7\", \"16\", \".gitignore.txt\", \"\", \"txt\"";
_tv._additem /*b4j.example.vmtreeview*/ ("7","16",".gitignore.txt","","txt",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 36;BA.debugLine="tv.AddItem(\"7\", \"17\", \"babel.config.js\", \"\", \"js\"";
_tv._additem /*b4j.example.vmtreeview*/ ("7","17","babel.config.js","","js",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 37;BA.debugLine="tv.AddItem(\"7\", \"18\", \"package.json\", \"\", \"json\",";
_tv._additem /*b4j.example.vmtreeview*/ ("7","18","package.json","","json",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 38;BA.debugLine="tv.AddItem(\"5\", \"10\", \"material2 : \", \"\", Null, F";
_tv._additem /*b4j.example.vmtreeview*/ ("5","10","material2 : ","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 39;BA.debugLine="tv.AddItem(\"10\", \"11\", \"src : \", \"\", Null, False)";
_tv._additem /*b4j.example.vmtreeview*/ ("10","11","src : ","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 40;BA.debugLine="tv.AddItem(\"11\", \"12\", \"v-btn.ts\", \"\", \"ts\", Fals";
_tv._additem /*b4j.example.vmtreeview*/ ("11","12","v-btn.ts","","ts",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 41;BA.debugLine="tv.AddItem(\"11\", \"13\", \"v-card.ts\", \"\", \"ts\", Fal";
_tv._additem /*b4j.example.vmtreeview*/ ("11","13","v-card.ts","","ts",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 42;BA.debugLine="tv.AddItem(\"11\", \"14\", \"v-window.ts\", \"\", \"ts\", F";
_tv._additem /*b4j.example.vmtreeview*/ ("11","14","v-window.ts","","ts",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 43;BA.debugLine="tv.AddToContainer(cont, 1, 1)";
_tv._addtocontainer /*String*/ (_cont,(int) (1),(int) (1));
 //BA.debugLineNum = 45;BA.debugLine="cont.AddLabel(2, 1, \"lblx2\",\"p\", $\"Selected: {{ t";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (2),(int) (1),"lblx2","p",("Selected: {{ tv1selected }}"));
 //BA.debugLineNum = 48;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 49;BA.debugLine="vue.AddCode($\"Dim tv As VMTreeView = vm.CreateTree";
_vue._addcode /*String*/ (("Dim tv As VMTreeView = vm.CreateTreeView(\"tv1\", Me)"));
 //BA.debugLineNum = 50;BA.debugLine="vue.AddCode($\"'has checkboxes\"$)";
_vue._addcode /*String*/ (("'has checkboxes"));
 //BA.debugLineNum = 51;BA.debugLine="vue.AddCode($\"tv.SetSelectable(True)\"$)";
_vue._addcode /*String*/ (("tv.SetSelectable(True)"));
 //BA.debugLineNum = 52;BA.debugLine="vue.AddCode($\"tv.AddItem(\"\", \"1\", \"Applications\",";
_vue._addcode /*String*/ (("tv.AddItem(\"\", \"1\", \"Applications\", \"\", Null, False)"));
 //BA.debugLineNum = 53;BA.debugLine="vue.AddCode($\"tv.AddItem(\"1\", \"2\", \"Calendar\", \"\",";
_vue._addcode /*String*/ (("tv.AddItem(\"1\", \"2\", \"Calendar\", \"\", Null, False)"));
 //BA.debugLineNum = 54;BA.debugLine="vue.AddCode($\"tv.AddItem(\"1\", \"3\", \"Chrome\", \"\", N";
_vue._addcode /*String*/ (("tv.AddItem(\"1\", \"3\", \"Chrome\", \"\", Null, False)"));
 //BA.debugLineNum = 55;BA.debugLine="vue.AddCode($\"tv.AddItem(\"1\", \"4\", \"Webstorm\", \"\",";
_vue._addcode /*String*/ (("tv.AddItem(\"1\", \"4\", \"Webstorm\", \"\", Null, False)"));
 //BA.debugLineNum = 56;BA.debugLine="vue.AddCode($\"tv.AddItem(\"\", \"5\", \"Documents\", \"\",";
_vue._addcode /*String*/ (("tv.AddItem(\"\", \"5\", \"Documents\", \"\", Null, False)"));
 //BA.debugLineNum = 57;BA.debugLine="vue.AddCode($\"tv.AddItem(\"5\", \"6\", \"vuetify\", \"\",";
_vue._addcode /*String*/ (("tv.AddItem(\"5\", \"6\", \"vuetify\", \"\", Null, False)"));
 //BA.debugLineNum = 58;BA.debugLine="vue.AddCode($\"tv.AddItem(\"6\", \"7\", \"src\", \"\", Null";
_vue._addcode /*String*/ (("tv.AddItem(\"6\", \"7\", \"src\", \"\", Null, False)"));
 //BA.debugLineNum = 59;BA.debugLine="vue.AddCode($\"tv.AddItem(\"7\", \"8\", \"index.html\", \"";
_vue._addcode /*String*/ (("tv.AddItem(\"7\", \"8\", \"index.html\", \"\", \"html\", False)"));
 //BA.debugLineNum = 60;BA.debugLine="vue.AddCode($\"tv.AddItem(\"7\", \"9\", \"bootstrap.ts\",";
_vue._addcode /*String*/ (("tv.AddItem(\"7\", \"9\", \"bootstrap.ts\", \"\", \"ts\", False)"));
 //BA.debugLineNum = 61;BA.debugLine="vue.AddCode($\"tv.AddItem(\"7\", \"15\", \"logo.png\", \"\"";
_vue._addcode /*String*/ (("tv.AddItem(\"7\", \"15\", \"logo.png\", \"\", \"png\", False)"));
 //BA.debugLineNum = 62;BA.debugLine="vue.AddCode($\"tv.AddItem(\"7\", \"16\", \".gitignore.tx";
_vue._addcode /*String*/ (("tv.AddItem(\"7\", \"16\", \".gitignore.txt\", \"\", \"txt\", False)"));
 //BA.debugLineNum = 63;BA.debugLine="vue.AddCode($\"tv.AddItem(\"7\", \"17\", \"babel.config.";
_vue._addcode /*String*/ (("tv.AddItem(\"7\", \"17\", \"babel.config.js\", \"\", \"js\", False)"));
 //BA.debugLineNum = 64;BA.debugLine="vue.AddCode($\"tv.AddItem(\"7\", \"18\", \"package.json\"";
_vue._addcode /*String*/ (("tv.AddItem(\"7\", \"18\", \"package.json\", \"\", \"json\", False)"));
 //BA.debugLineNum = 65;BA.debugLine="vue.AddCode($\"tv.AddItem(\"5\", \"10\", \"material2 : \"";
_vue._addcode /*String*/ (("tv.AddItem(\"5\", \"10\", \"material2 : \", \"\", Null, False)"));
 //BA.debugLineNum = 66;BA.debugLine="vue.AddCode($\"tv.AddItem(\"10\", \"11\", \"src : \", \"\",";
_vue._addcode /*String*/ (("tv.AddItem(\"10\", \"11\", \"src : \", \"\", Null, False)"));
 //BA.debugLineNum = 67;BA.debugLine="vue.AddCode($\"tv.AddItem(\"11\", \"12\", \"v-btn.ts\", \"";
_vue._addcode /*String*/ (("tv.AddItem(\"11\", \"12\", \"v-btn.ts\", \"\", \"ts\", False)"));
 //BA.debugLineNum = 68;BA.debugLine="vue.AddCode($\"tv.AddItem(\"11\", \"13\", \"v-card.ts\",";
_vue._addcode /*String*/ (("tv.AddItem(\"11\", \"13\", \"v-card.ts\", \"\", \"ts\", False)"));
 //BA.debugLineNum = 69;BA.debugLine="vue.AddCode($\"tv.AddItem(\"11\", \"14\", \"v-window.ts\"";
_vue._addcode /*String*/ (("tv.AddItem(\"11\", \"14\", \"v-window.ts\", \"\", \"ts\", False)"));
 //BA.debugLineNum = 70;BA.debugLine="vue.AddCode($\"tv.AddToContainer(cont, 1, 1)\"$)";
_vue._addcode /*String*/ (("tv.AddToContainer(cont, 1, 1)"));
 //BA.debugLineNum = 71;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 72;BA.debugLine="vue.AddCode($\"cont.AddLabel(2, 1, \"lblx2\",\"p\", ~\"S";
_vue._addcode /*String*/ (("cont.AddLabel(2, 1, \"lblx2\",\"p\", ~\"Selected: {{ tv1selected }}\"~)"));
 //BA.debugLineNum = 73;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"tv1code\", \"Treeview";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modtreeview.getObject(),"tv1code","Treeview with Checkboxes",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (3),(int) (1));
 //BA.debugLineNum = 76;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 77;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 78;BA.debugLine="vue.AddCode($\"'selected\"$)";
_vue._addcode /*String*/ (("'selected"));
 //BA.debugLineNum = 79;BA.debugLine="vue.AddCode($\"Sub tv1_oninput(items As List)\"$)";
_vue._addcode /*String*/ (("Sub tv1_oninput(items As List)"));
 //BA.debugLineNum = 80;BA.debugLine="vue.AddCode($\"Dim sCode As String = BANano.tojson(";
_vue._addcode /*String*/ (("Dim sCode As String = BANano.tojson(items)"));
 //BA.debugLineNum = 81;BA.debugLine="vue.AddCode($\"vm.showsnackbar(\"Selected: \" & sCode";
_vue._addcode /*String*/ (("vm.showsnackbar(\"Selected: \" & sCode)"));
 //BA.debugLineNum = 82;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 83;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"tv1codechecked\", \"T";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modtreeview.getObject(),"tv1codechecked","TreeView Get Checked",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (4),(int) (1));
 //BA.debugLineNum = 85;BA.debugLine="Dim tv2 As VMTreeView = vm.CreateTreeView(\"tv2\",";
_tv2 = _vm._createtreeview /*b4j.example.vmtreeview*/ ("tv2",modtreeview.getObject());
 //BA.debugLineNum = 86;BA.debugLine="tv2.SetActivatable(True)";
_tv2._setactivatable /*b4j.example.vmtreeview*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 87;BA.debugLine="tv2.AddItem(\"\", \"1\", \"Applications\", \"\", Null, Fa";
_tv2._additem /*b4j.example.vmtreeview*/ ("","1","Applications","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 88;BA.debugLine="tv2.AddItem(\"1\", \"2\", \"Calendar\", \"\", Null, False";
_tv2._additem /*b4j.example.vmtreeview*/ ("1","2","Calendar","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 89;BA.debugLine="tv2.AddItem(\"1\", \"3\", \"Chrome\", \"\", Null, False)";
_tv2._additem /*b4j.example.vmtreeview*/ ("1","3","Chrome","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 90;BA.debugLine="tv2.AddItem(\"1\", \"4\", \"Webstorm\", \"\", Null, False";
_tv2._additem /*b4j.example.vmtreeview*/ ("1","4","Webstorm","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 91;BA.debugLine="tv2.AddItem(\"\", \"5\", \"Documents\", \"\", Null, False";
_tv2._additem /*b4j.example.vmtreeview*/ ("","5","Documents","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 92;BA.debugLine="tv2.AddItem(\"5\", \"6\", \"vuetify\", \"\", Null, False)";
_tv2._additem /*b4j.example.vmtreeview*/ ("5","6","vuetify","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 93;BA.debugLine="tv2.AddItem(\"6\", \"7\", \"src\", \"\", Null, False)";
_tv2._additem /*b4j.example.vmtreeview*/ ("6","7","src","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 94;BA.debugLine="tv2.AddItem(\"7\", \"8\", \"index.html\", \"\", \"html\", F";
_tv2._additem /*b4j.example.vmtreeview*/ ("7","8","index.html","","html",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 95;BA.debugLine="tv2.AddItem(\"7\", \"9\", \"bootstrap.ts\", \"\", \"ts\", F";
_tv2._additem /*b4j.example.vmtreeview*/ ("7","9","bootstrap.ts","","ts",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 96;BA.debugLine="tv2.AddItem(\"7\", \"15\", \"logo.png\", \"\", \"png\", Fal";
_tv2._additem /*b4j.example.vmtreeview*/ ("7","15","logo.png","","png",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 97;BA.debugLine="tv2.AddItem(\"7\", \"16\", \".gitignore.txt\", \"\", \"txt";
_tv2._additem /*b4j.example.vmtreeview*/ ("7","16",".gitignore.txt","","txt",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 98;BA.debugLine="tv2.AddItem(\"7\", \"17\", \"babel.config.js\", \"\", \"js";
_tv2._additem /*b4j.example.vmtreeview*/ ("7","17","babel.config.js","","js",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 99;BA.debugLine="tv2.AddItem(\"7\", \"18\", \"package.json\", \"\", \"json\"";
_tv2._additem /*b4j.example.vmtreeview*/ ("7","18","package.json","","json",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 100;BA.debugLine="tv2.AddItem(\"5\", \"10\", \"material2 : \", \"\", Null,";
_tv2._additem /*b4j.example.vmtreeview*/ ("5","10","material2 : ","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 101;BA.debugLine="tv2.AddItem(\"10\", \"11\", \"src : \", \"\", Null, False";
_tv2._additem /*b4j.example.vmtreeview*/ ("10","11","src : ","",BA.ObjectToString(anywheresoftware.b4a.keywords.Common.Null),anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 102;BA.debugLine="tv2.AddItem(\"11\", \"12\", \"v-btn.ts\", \"\", \"ts\", Fal";
_tv2._additem /*b4j.example.vmtreeview*/ ("11","12","v-btn.ts","","ts",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 103;BA.debugLine="tv2.AddItem(\"11\", \"13\", \"v-card.ts\", \"\", \"ts\", Fa";
_tv2._additem /*b4j.example.vmtreeview*/ ("11","13","v-card.ts","","ts",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 104;BA.debugLine="tv2.AddItem(\"11\", \"14\", \"v-window.ts\", \"\", \"ts\",";
_tv2._additem /*b4j.example.vmtreeview*/ ("11","14","v-window.ts","","ts",anywheresoftware.b4a.keywords.Common.False);
 //BA.debugLineNum = 105;BA.debugLine="tv2.AddToContainer(cont, 5, 1)";
_tv2._addtocontainer /*String*/ (_cont,(int) (5),(int) (1));
 //BA.debugLineNum = 107;BA.debugLine="cont.AddLabel(6, 1, \"lblxx3\",\"p\", $\"Active: {{ tv";
_cont._addlabel /*b4j.example.vmcontainer*/ ((int) (6),(int) (1),"lblxx3","p",("Active: {{ tv2active }}"));
 //BA.debugLineNum = 110;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 111;BA.debugLine="vue.AddCode($\"Dim tv2 As VMTreeView = vm.CreateTre";
_vue._addcode /*String*/ (("Dim tv2 As VMTreeView = vm.CreateTreeView(\"tv2\", Me)"));
 //BA.debugLineNum = 112;BA.debugLine="vue.AddCode($\"tv2.SetActivatable(True)\"$)";
_vue._addcode /*String*/ (("tv2.SetActivatable(True)"));
 //BA.debugLineNum = 113;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"\", \"1\", \"Applications\",";
_vue._addcode /*String*/ (("tv2.AddItem(\"\", \"1\", \"Applications\", \"\", Null, False)"));
 //BA.debugLineNum = 114;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"1\", \"2\", \"Calendar\", \"\"";
_vue._addcode /*String*/ (("tv2.AddItem(\"1\", \"2\", \"Calendar\", \"\", Null, False)"));
 //BA.debugLineNum = 115;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"1\", \"3\", \"Chrome\", \"\",";
_vue._addcode /*String*/ (("tv2.AddItem(\"1\", \"3\", \"Chrome\", \"\", Null, False)"));
 //BA.debugLineNum = 116;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"1\", \"4\", \"Webstorm\", \"\"";
_vue._addcode /*String*/ (("tv2.AddItem(\"1\", \"4\", \"Webstorm\", \"\", Null, False)"));
 //BA.debugLineNum = 117;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"\", \"5\", \"Documents\", \"\"";
_vue._addcode /*String*/ (("tv2.AddItem(\"\", \"5\", \"Documents\", \"\", Null, False)"));
 //BA.debugLineNum = 118;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"5\", \"6\", \"vuetify\", \"\",";
_vue._addcode /*String*/ (("tv2.AddItem(\"5\", \"6\", \"vuetify\", \"\", Null, False)"));
 //BA.debugLineNum = 119;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"6\", \"7\", \"src\", \"\", Nul";
_vue._addcode /*String*/ (("tv2.AddItem(\"6\", \"7\", \"src\", \"\", Null, False)"));
 //BA.debugLineNum = 120;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"7\", \"8\", \"index.html\",";
_vue._addcode /*String*/ (("tv2.AddItem(\"7\", \"8\", \"index.html\", \"\", \"html\", False)"));
 //BA.debugLineNum = 121;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"7\", \"9\", \"bootstrap.ts\"";
_vue._addcode /*String*/ (("tv2.AddItem(\"7\", \"9\", \"bootstrap.ts\", \"\", \"ts\", False)"));
 //BA.debugLineNum = 122;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"7\", \"15\", \"logo.png\", \"";
_vue._addcode /*String*/ (("tv2.AddItem(\"7\", \"15\", \"logo.png\", \"\", \"png\", False)"));
 //BA.debugLineNum = 123;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"7\", \"16\", \".gitignore.t";
_vue._addcode /*String*/ (("tv2.AddItem(\"7\", \"16\", \".gitignore.txt\", \"\", \"txt\", False)"));
 //BA.debugLineNum = 124;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"7\", \"17\", \"babel.config";
_vue._addcode /*String*/ (("tv2.AddItem(\"7\", \"17\", \"babel.config.js\", \"\", \"js\", False)"));
 //BA.debugLineNum = 125;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"7\", \"18\", \"package.json";
_vue._addcode /*String*/ (("tv2.AddItem(\"7\", \"18\", \"package.json\", \"\", \"json\", False)"));
 //BA.debugLineNum = 126;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"5\", \"10\", \"material2 :";
_vue._addcode /*String*/ (("tv2.AddItem(\"5\", \"10\", \"material2 : \", \"\", Null, False)"));
 //BA.debugLineNum = 127;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"10\", \"11\", \"src : \", \"\"";
_vue._addcode /*String*/ (("tv2.AddItem(\"10\", \"11\", \"src : \", \"\", Null, False)"));
 //BA.debugLineNum = 128;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"11\", \"12\", \"v-btn.ts\",";
_vue._addcode /*String*/ (("tv2.AddItem(\"11\", \"12\", \"v-btn.ts\", \"\", \"ts\", False)"));
 //BA.debugLineNum = 129;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"11\", \"13\", \"v-card.ts\",";
_vue._addcode /*String*/ (("tv2.AddItem(\"11\", \"13\", \"v-card.ts\", \"\", \"ts\", False)"));
 //BA.debugLineNum = 130;BA.debugLine="vue.AddCode($\"tv2.AddItem(\"11\", \"14\", \"v-window.ts";
_vue._addcode /*String*/ (("tv2.AddItem(\"11\", \"14\", \"v-window.ts\", \"\", \"ts\", False)"));
 //BA.debugLineNum = 131;BA.debugLine="vue.AddCode($\"tv2.AddToContainer(cont, 5, 1)\"$)";
_vue._addcode /*String*/ (("tv2.AddToContainer(cont, 5, 1)"));
 //BA.debugLineNum = 132;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 133;BA.debugLine="vue.AddCode($\"cont.AddLabel(6, 1, \"lblxx3\",\"p\", ~\"";
_vue._addcode /*String*/ (("cont.AddLabel(6, 1, \"lblxx3\",\"p\", ~\"Active: {{ tv2active }}\"~)"));
 //BA.debugLineNum = 134;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 135;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"tv2code\", \"TreeView";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modtreeview.getObject(),"tv2code","TreeView Node Click",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (7),(int) (1));
 //BA.debugLineNum = 138;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 139;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 140;BA.debugLine="vue.AddCode($\"'active\"$)";
_vue._addcode /*String*/ (("'active"));
 //BA.debugLineNum = 141;BA.debugLine="vue.AddCode($\"Sub tv2_updateactive(items As List)\"";
_vue._addcode /*String*/ (("Sub tv2_updateactive(items As List)"));
 //BA.debugLineNum = 142;BA.debugLine="vue.AddCode($\"Dim sCode As String = BANano.tojson(";
_vue._addcode /*String*/ (("Dim sCode As String = BANano.tojson(items)"));
 //BA.debugLineNum = 143;BA.debugLine="vue.AddCode($\"vm.showsnackbar(\"Active: \" & sCode)\"";
_vue._addcode /*String*/ (("vm.showsnackbar(\"Active: \" & sCode)"));
 //BA.debugLineNum = 144;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 145;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"tv2codeclick\", \"Tre";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modtreeview.getObject(),"tv2codeclick","TreeView Node Click Event",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (8),(int) (1));
 //BA.debugLineNum = 149;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 150;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Public name As String = \"treeCode\"";
_name = "treeCode";
 //BA.debugLineNum = 4;BA.debugLine="Public title As String = \"TreeView\"";
_title = "TreeView";
 //BA.debugLineNum = 5;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 6;BA.debugLine="Private tv As VMTreeView";
_tv = new b4j.example.vmtreeview();
 //BA.debugLineNum = 7;BA.debugLine="Private BANano As BANano  'ignore";
_banano = new com.ab.banano.BANano();
 //BA.debugLineNum = 8;BA.debugLine="Private vue As BANanoVue";
_vue = new b4j.example.bananovue();
 //BA.debugLineNum = 9;BA.debugLine="End Sub";
return "";
}
public static String  _tv1_oninput(anywheresoftware.b4a.objects.collections.List _items) throws Exception{
String _scode = "";
 //BA.debugLineNum = 169;BA.debugLine="Sub tv1_oninput(items As List)";
 //BA.debugLineNum = 170;BA.debugLine="Dim sCode As String = BANano.tojson(items)";
_scode = BA.ObjectToString(_banano.ToJson((Object)(_items.getObject())));
 //BA.debugLineNum = 171;BA.debugLine="vm.showsnackbar(\"Selected: \" & sCode)";
_vm._showsnackbar /*String*/ ("Selected: "+_scode);
 //BA.debugLineNum = 172;BA.debugLine="End Sub";
return "";
}
public static String  _tv1codecheckedcopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 175;BA.debugLine="Sub tv1codecheckedcopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 176;BA.debugLine="vue.CopyCode2Clipboard(\"tv1codechecked\")";
_vue._copycode2clipboard /*String*/ ("tv1codechecked");
 //BA.debugLineNum = 177;BA.debugLine="End Sub";
return "";
}
public static String  _tv1codecheckeddownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 179;BA.debugLine="Sub tv1codecheckeddownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 180;BA.debugLine="vue.DownloadCode(\"tv1codechecked\", \"tv1codechecke";
_vue._downloadcode /*String*/ ("tv1codechecked","tv1codechecked.txt");
 //BA.debugLineNum = 181;BA.debugLine="End Sub";
return "";
}
public static String  _tv1codecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 153;BA.debugLine="Sub tv1codecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 154;BA.debugLine="vue.CopyCode2Clipboard(\"tv1code\")";
_vue._copycode2clipboard /*String*/ ("tv1code");
 //BA.debugLineNum = 155;BA.debugLine="End Sub";
return "";
}
public static String  _tv1codedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 157;BA.debugLine="Sub tv1codedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 158;BA.debugLine="vue.DownloadCode(\"tv1code\", \"tv1code.txt\")";
_vue._downloadcode /*String*/ ("tv1code","tv1code.txt");
 //BA.debugLineNum = 159;BA.debugLine="End Sub";
return "";
}
public static String  _tv2_updateactive(anywheresoftware.b4a.objects.collections.List _items) throws Exception{
String _scode = "";
 //BA.debugLineNum = 163;BA.debugLine="Sub tv2_updateactive(items As List)";
 //BA.debugLineNum = 164;BA.debugLine="Dim sCode As String = BANano.tojson(items)";
_scode = BA.ObjectToString(_banano.ToJson((Object)(_items.getObject())));
 //BA.debugLineNum = 165;BA.debugLine="vm.showsnackbar(\"Active: \" & sCode)";
_vm._showsnackbar /*String*/ ("Active: "+_scode);
 //BA.debugLineNum = 166;BA.debugLine="End Sub";
return "";
}
public static String  _tv2codeclickcopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 193;BA.debugLine="Sub tv2codeclickcopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 194;BA.debugLine="vue.CopyCode2Clipboard(\"tv2codeclick\")";
_vue._copycode2clipboard /*String*/ ("tv2codeclick");
 //BA.debugLineNum = 195;BA.debugLine="End Sub";
return "";
}
public static String  _tv2codeclickdownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 197;BA.debugLine="Sub tv2codeclickdownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 198;BA.debugLine="vue.DownloadCode(\"tv2codeclick\", \"tv2codeclick.tx";
_vue._downloadcode /*String*/ ("tv2codeclick","tv2codeclick.txt");
 //BA.debugLineNum = 199;BA.debugLine="End Sub";
return "";
}
public static String  _tv2codecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 184;BA.debugLine="Sub tv2codecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 185;BA.debugLine="vue.CopyCode2Clipboard(\"tv2code\")";
_vue._copycode2clipboard /*String*/ ("tv2code");
 //BA.debugLineNum = 186;BA.debugLine="End Sub";
return "";
}
public static String  _tv2codedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 188;BA.debugLine="Sub tv2codedownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 189;BA.debugLine="vue.DownloadCode(\"tv2code\", \"tv2code.txt\")";
_vue._downloadcode /*String*/ ("tv2code","tv2code.txt");
 //BA.debugLineNum = 190;BA.debugLine="End Sub";
return "";
}
}
