package b4j.example;


import anywheresoftware.b4a.BA;

public class modtimeline extends Object{
public static modtimeline mostCurrent = new modtimeline();

public static BA ba;
static {
		ba = new  anywheresoftware.b4j.objects.FxBA("b4j.example", "b4j.example.modtimeline", null);
		ba.loadHtSubs(modtimeline.class);
        if (ba.getClass().getName().endsWith("ShellBA")) {
			
			ba.raiseEvent2(null, true, "SHELL", false);
			ba.raiseEvent2(null, true, "CREATE", true, "b4j.example.modtimeline", ba);
		}
	}
    public static Class<?> getObject() {
		return modtimeline.class;
	}

 public static anywheresoftware.b4a.keywords.Common __c = null;
public static String _name = "";
public static String _title = "";
public static b4j.example.bananovm _vm = null;
public static b4j.example.bananovue _vue = null;
public static com.ab.banano.BANano _banano = null;
public static b4j.example.main _main = null;
public static b4j.example.pgindex _pgindex = null;
public static b4j.example.moditemgroups _moditemgroups = null;
public static b4j.example.modcalendar _modcalendar = null;
public static b4j.example.modcard _modcard = null;
public static b4j.example.modsparkline _modsparkline = null;
public static b4j.example.modbuttons _modbuttons = null;
public static b4j.example.modchips _modchips = null;
public static b4j.example.moddialog _moddialog = null;
public static b4j.example.modbadges _modbadges = null;
public static b4j.example.modtabs _modtabs = null;
public static b4j.example.modalert _modalert = null;
public static b4j.example.modautocomplete _modautocomplete = null;
public static b4j.example.modavatar _modavatar = null;
public static b4j.example.modbanner _modbanner = null;
public static b4j.example.modbottomnavigation _modbottomnavigation = null;
public static b4j.example.modbottomsheet _modbottomsheet = null;
public static b4j.example.modbreadcrumbs _modbreadcrumbs = null;
public static b4j.example.modcarousel _modcarousel = null;
public static b4j.example.modcheckbox _modcheckbox = null;
public static b4j.example.modcolorpicker _modcolorpicker = null;
public static b4j.example.modcombo _modcombo = null;
public static b4j.example.moddatatable _moddatatable = null;
public static b4j.example.moddatepicker _moddatepicker = null;
public static b4j.example.moddesign _moddesign = null;
public static b4j.example.modexpansionpanels _modexpansionpanels = null;
public static b4j.example.modfileinput _modfileinput = null;
public static b4j.example.modform _modform = null;
public static b4j.example.modgrid _modgrid = null;
public static b4j.example.modicons _modicons = null;
public static b4j.example.modimages _modimages = null;
public static b4j.example.modlists _modlists = null;
public static b4j.example.modloadingskeleton _modloadingskeleton = null;
public static b4j.example.modmenus _modmenus = null;
public static b4j.example.modmessageboard _modmessageboard = null;
public static b4j.example.modoverlay _modoverlay = null;
public static b4j.example.modpagination _modpagination = null;
public static b4j.example.modparallax _modparallax = null;
public static b4j.example.modprogress _modprogress = null;
public static b4j.example.modradiogroups _modradiogroups = null;
public static b4j.example.modrating _modrating = null;
public static b4j.example.modrealtimelogging _modrealtimelogging = null;
public static b4j.example.modselects _modselects = null;
public static b4j.example.modslidegroups _modslidegroups = null;
public static b4j.example.modslider _modslider = null;
public static b4j.example.modsnackbar _modsnackbar = null;
public static b4j.example.modstepper _modstepper = null;
public static b4j.example.modswitch _modswitch = null;
public static b4j.example.modtextarea _modtextarea = null;
public static b4j.example.modtextfield _modtextfield = null;
public static b4j.example.modtimepicker _modtimepicker = null;
public static b4j.example.modtoolbar _modtoolbar = null;
public static b4j.example.modtoolkit _modtoolkit = null;
public static b4j.example.modtreeview _modtreeview = null;
public static b4j.example.modwindow _modwindow = null;
public static b4j.example.pgbrs _pgbrs = null;
public static b4j.example.bananoshared _bananoshared = null;
public static String  _btnx_click(com.ab.banano.BANanoEvent _e) throws Exception{
String _btnid = "";
 //BA.debugLineNum = 277;BA.debugLine="Sub btnx_click(e As BANanoEvent)";
 //BA.debugLineNum = 279;BA.debugLine="Dim btnID As String = vm.GetIDFromEvent(e)";
_btnid = _vm._getidfromevent /*String*/ (_e);
 //BA.debugLineNum = 281;BA.debugLine="vm.ShowSnackBarSuccess(btnID)";
_vm._showsnackbarsuccess /*String*/ (_btnid);
 //BA.debugLineNum = 282;BA.debugLine="End Sub";
return "";
}
public static String  _code() throws Exception{
b4j.example.vmcontainer _cont = null;
b4j.example.vmtimeline _tltimeline1 = null;
b4j.example.vmtimelineitem _tlitemfirstname = null;
b4j.example.vmtimelineitem _tlitemsurname = null;
b4j.example.vmtimelineitem _tl3 = null;
b4j.example.vmlabel _lblx = null;
b4j.example.vmtimelineitem _tl4 = null;
anywheresoftware.b4a.objects.collections.List _tlines = null;
b4j.example.vmtimeline _txtline = null;
b4j.example.vmtimelineitem _titem = null;
b4j.example.vmbutton _btn = null;
 //BA.debugLineNum = 11;BA.debugLine="Sub Code";
 //BA.debugLineNum = 12;BA.debugLine="vm = pgIndex.vm";
_vm = _pgindex._vm /*b4j.example.bananovm*/ ;
 //BA.debugLineNum = 13;BA.debugLine="vue = vm.vue";
_vue = _vm._vue /*b4j.example.bananovue*/ ;
 //BA.debugLineNum = 15;BA.debugLine="Dim cont As VMContainer = vm.CreateContainer(name";
_cont = _vm._createcontainer /*b4j.example.vmcontainer*/ (_name,modtimeline.getObject());
 //BA.debugLineNum = 16;BA.debugLine="cont.AddRows(10).AddColumns12";
_cont._addrows /*b4j.example.vmcontainer*/ ((int) (10))._addcolumns12 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 18;BA.debugLine="cont.Hide";
_cont._hide /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 20;BA.debugLine="Dim tltimeline1 As VMTimeline";
_tltimeline1 = new b4j.example.vmtimeline();
 //BA.debugLineNum = 21;BA.debugLine="tltimeline1.Initialize(vue, \"tltimeline1\", Me)";
_tltimeline1._initialize /*b4j.example.vmtimeline*/ (ba,_vue,"tltimeline1",modtimeline.getObject());
 //BA.debugLineNum = 22;BA.debugLine="tltimeline1.SetVisible(True)";
_tltimeline1._setvisible /*b4j.example.vmtimeline*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 24;BA.debugLine="Dim tlItemfirstname As VMTimelineItem";
_tlitemfirstname = new b4j.example.vmtimelineitem();
 //BA.debugLineNum = 25;BA.debugLine="tlItemfirstname.Initialize(vue, \"tlItemfirstname\"";
_tlitemfirstname._initialize /*b4j.example.vmtimelineitem*/ (ba,_vue,"tlItemfirstname",modtimeline.getObject());
 //BA.debugLineNum = 26;BA.debugLine="tlItemfirstname.SetColorintensity(\"brown\",\"\")";
_tlitemfirstname._setcolorintensity /*b4j.example.vmtimelineitem*/ ("brown","");
 //BA.debugLineNum = 27;BA.debugLine="tlItemfirstname.SetLarge(True)";
_tlitemfirstname._setlarge /*b4j.example.vmtimelineitem*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 28;BA.debugLine="tlItemfirstname.SetAvatar(\"./assets/sponge.png\")";
_tlitemfirstname._setavatar /*b4j.example.vmtimelineitem*/ ("./assets/sponge.png");
 //BA.debugLineNum = 29;BA.debugLine="tlItemfirstname.OppositeText.SetText(\"Anele\")";
_tlitemfirstname._oppositetext /*b4j.example.vmlabel*/ ._settext /*b4j.example.vmlabel*/ ("Anele");
 //BA.debugLineNum = 30;BA.debugLine="tltimeline1.AddTimeLineItem(tlItemfirstname)";
_tltimeline1._addtimelineitem /*String*/ (_tlitemfirstname);
 //BA.debugLineNum = 32;BA.debugLine="Dim tlItemsurname As VMTimelineItem";
_tlitemsurname = new b4j.example.vmtimelineitem();
 //BA.debugLineNum = 33;BA.debugLine="tlItemsurname.Initialize(vue, \"tlItemsurname\", Me";
_tlitemsurname._initialize /*b4j.example.vmtimelineitem*/ (ba,_vue,"tlItemsurname",modtimeline.getObject());
 //BA.debugLineNum = 34;BA.debugLine="tlItemsurname.SetFilldot(True)";
_tlitemsurname._setfilldot /*b4j.example.vmtimelineitem*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 35;BA.debugLine="tlItemsurname.SetIcon(\"mdi-plus\")";
_tlitemsurname._seticon /*b4j.example.vmtimelineitem*/ ("mdi-plus");
 //BA.debugLineNum = 36;BA.debugLine="tlItemsurname.SetIconColorIntensity(vm.COLOR_RED,";
_tlitemsurname._seticoncolorintensity /*b4j.example.vmtimelineitem*/ (_vm._color_red /*String*/ ,_vm._intensity_accent4 /*String*/ );
 //BA.debugLineNum = 37;BA.debugLine="tlItemsurname.SetSmall(True)";
_tlitemsurname._setsmall /*b4j.example.vmtimelineitem*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 38;BA.debugLine="tlItemsurname.OppositeText.SetText(\"Mbanga\")";
_tlitemsurname._oppositetext /*b4j.example.vmlabel*/ ._settext /*b4j.example.vmlabel*/ ("Mbanga");
 //BA.debugLineNum = 39;BA.debugLine="tltimeline1.AddTimeLineItem(tlItemsurname)";
_tltimeline1._addtimelineitem /*String*/ (_tlitemsurname);
 //BA.debugLineNum = 43;BA.debugLine="Dim tl3 As VMTimelineItem";
_tl3 = new b4j.example.vmtimelineitem();
 //BA.debugLineNum = 44;BA.debugLine="tl3.Initialize(vue, \"tl3\", Me)";
_tl3._initialize /*b4j.example.vmtimelineitem*/ (ba,_vue,"tl3",modtimeline.getObject());
 //BA.debugLineNum = 45;BA.debugLine="tl3.SetColor(vm.COLOR_ORANGE)";
_tl3._setcolor /*b4j.example.vmtimelineitem*/ (_vm._color_orange /*String*/ );
 //BA.debugLineNum = 46;BA.debugLine="tl3.SetFilldot(True)";
_tl3._setfilldot /*b4j.example.vmtimelineitem*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 47;BA.debugLine="tl3.SetLeft(True)";
_tl3._setleft /*b4j.example.vmtimelineitem*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 48;BA.debugLine="tl3.UsesCard = True";
_tl3._usescard /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 49;BA.debugLine="tl3.CardTitle.SetColorIntensity(vm.COLOR_purple,";
_tl3._cardtitle /*b4j.example.vmcardtitle*/ ._setcolorintensity /*b4j.example.vmcardtitle*/ (_vm._color_purple /*String*/ ,_vm._intensity_lighten2 /*String*/ );
 //BA.debugLineNum = 50;BA.debugLine="tl3.CardTitle.AddIcon1(\"icx1\", \"mdi-magnify\", Cre";
_tl3._cardtitle /*b4j.example.vmcardtitle*/ ._addicon1 /*b4j.example.vmcardtitle*/ ("icx1","mdi-magnify",anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("dark"),(Object)(anywheresoftware.b4a.keywords.Common.True),(Object)("size"),(Object)(42),(Object)("color"),(Object)("white")}),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("mr-4")}));
 //BA.debugLineNum = 51;BA.debugLine="tl3.CardTitle.AddElement(\"ich1\", \"h2\", \"Uses Card";
_tl3._cardtitle /*b4j.example.vmcardtitle*/ ._addelement /*b4j.example.vmcardtitle*/ ("ich1","h2","Uses Card",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("display-1 white--text font-weight-light")}));
 //BA.debugLineNum = 53;BA.debugLine="tl3.CardContainer.AddRows(1).AddColumns12";
_tl3._cardcontainer /*b4j.example.vmcontainer*/ ._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns12 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 54;BA.debugLine="Dim lblX As VMLabel = vm.CreateLabel(\"\")";
_lblx = _vm._createlabel /*b4j.example.vmlabel*/ ("");
 //BA.debugLineNum = 55;BA.debugLine="lblX.SetParagraph.SetText(BANanoShared.LoremIpsum";
_lblx._setparagraph /*b4j.example.vmlabel*/ ()._settext /*b4j.example.vmlabel*/ (_bananoshared._loremipsum /*String*/ (BA.NumberToString(1)));
 //BA.debugLineNum = 56;BA.debugLine="tl3.CardContainer.AddComponent(1,1,lblX.ToString)";
_tl3._cardcontainer /*b4j.example.vmcontainer*/ ._addcomponent /*String*/ ((int) (1),(int) (1),_lblx._tostring /*String*/ ());
 //BA.debugLineNum = 57;BA.debugLine="tltimeline1.AddTimeLineItem(tl3)";
_tltimeline1._addtimelineitem /*String*/ (_tl3);
 //BA.debugLineNum = 59;BA.debugLine="Dim tl4 As VMTimelineItem";
_tl4 = new b4j.example.vmtimelineitem();
 //BA.debugLineNum = 60;BA.debugLine="tl4.Initialize(vue, \"tl4\", Me)";
_tl4._initialize /*b4j.example.vmtimelineitem*/ (ba,_vue,"tl4",modtimeline.getObject());
 //BA.debugLineNum = 61;BA.debugLine="tl4.SetColor(vm.COLOR_PURPLE)";
_tl4._setcolor /*b4j.example.vmtimelineitem*/ (_vm._color_purple /*String*/ );
 //BA.debugLineNum = 62;BA.debugLine="tl4.SetFilldot(True)";
_tl4._setfilldot /*b4j.example.vmtimelineitem*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 63;BA.debugLine="tl4.SetRight(True)";
_tl4._setright /*b4j.example.vmtimelineitem*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 64;BA.debugLine="tl4.SetSmall(True)";
_tl4._setsmall /*b4j.example.vmtimelineitem*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 65;BA.debugLine="tl4.UsesCard = True";
_tl4._usescard /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 66;BA.debugLine="tl4.CardTitle.SetColorIntensity(vm.COLOR_AMBER, v";
_tl4._cardtitle /*b4j.example.vmcardtitle*/ ._setcolorintensity /*b4j.example.vmcardtitle*/ (_vm._color_amber /*String*/ ,_vm._intensity_lighten1 /*String*/ );
 //BA.debugLineNum = 67;BA.debugLine="tl4.CardTitle.AddClass(\"justify-end\")";
_tl4._cardtitle /*b4j.example.vmcardtitle*/ ._addclass /*b4j.example.vmcardtitle*/ ("justify-end");
 //BA.debugLineNum = 68;BA.debugLine="tl4.CardTitle.AddElement(\"ich2\", \"h2\", \"Uses Card";
_tl4._cardtitle /*b4j.example.vmcardtitle*/ ._addelement /*b4j.example.vmcardtitle*/ ("ich2","h2","Uses Card 1",(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),anywheresoftware.b4a.keywords.Common.ArrayToList(new Object[]{(Object)("display-1 mr-4 white--text font-weight-light")}));
 //BA.debugLineNum = 69;BA.debugLine="tl4.CardTitle.AddIcon1(\"icx2\", \"mdi-home-outline\"";
_tl4._cardtitle /*b4j.example.vmcardtitle*/ ._addicon1 /*b4j.example.vmcardtitle*/ ("icx2","mdi-home-outline",anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("dark"),(Object)(anywheresoftware.b4a.keywords.Common.True),(Object)("size"),(Object)(42),(Object)("color"),(Object)("white")}),(anywheresoftware.b4a.objects.collections.Map) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.Map(), (anywheresoftware.b4a.objects.collections.Map.MyMap)(anywheresoftware.b4a.keywords.Common.Null)),(anywheresoftware.b4a.objects.collections.List) anywheresoftware.b4a.AbsObjectWrapper.ConvertToWrapper(new anywheresoftware.b4a.objects.collections.List(), (java.util.List)(anywheresoftware.b4a.keywords.Common.Null)));
 //BA.debugLineNum = 71;BA.debugLine="tl4.CardContainer.AddRows(1).AddColumns12";
_tl4._cardcontainer /*b4j.example.vmcontainer*/ ._addrows /*b4j.example.vmcontainer*/ ((int) (1))._addcolumns12 /*b4j.example.vmcontainer*/ ();
 //BA.debugLineNum = 72;BA.debugLine="Dim lblX As VMLabel = vm.CreateLabel(\"\")";
_lblx = _vm._createlabel /*b4j.example.vmlabel*/ ("");
 //BA.debugLineNum = 73;BA.debugLine="lblX.SetParagraph.SetText(BANanoShared.LoremIpsum";
_lblx._setparagraph /*b4j.example.vmlabel*/ ()._settext /*b4j.example.vmlabel*/ (_bananoshared._loremipsum /*String*/ (BA.NumberToString(1)));
 //BA.debugLineNum = 74;BA.debugLine="tl4.CardContainer.AddComponent(1,1,lblX.ToString)";
_tl4._cardcontainer /*b4j.example.vmcontainer*/ ._addcomponent /*String*/ ((int) (1),(int) (1),_lblx._tostring /*String*/ ());
 //BA.debugLineNum = 75;BA.debugLine="tltimeline1.AddTimeLineItem(tl4)";
_tltimeline1._addtimelineitem /*String*/ (_tl4);
 //BA.debugLineNum = 77;BA.debugLine="tltimeline1.AddToContainer(cont,1,1)";
_tltimeline1._addtocontainer /*String*/ (_cont,(int) (1),(int) (1));
 //BA.debugLineNum = 80;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 81;BA.debugLine="vue.AddCode($\"Dim tltimeline1 As VMTimeline\"$)";
_vue._addcode /*String*/ (("Dim tltimeline1 As VMTimeline"));
 //BA.debugLineNum = 82;BA.debugLine="vue.AddCode($\"tltimeline1.Initialize(vue, \"tltimel";
_vue._addcode /*String*/ (("tltimeline1.Initialize(vue, \"tltimeline1\", Me)"));
 //BA.debugLineNum = 83;BA.debugLine="vue.AddCode($\"tltimeline1.SetVisible(True)\"$)";
_vue._addcode /*String*/ (("tltimeline1.SetVisible(True)"));
 //BA.debugLineNum = 84;BA.debugLine="vue.AddCode($\"'add each item\"$)";
_vue._addcode /*String*/ (("'add each item"));
 //BA.debugLineNum = 85;BA.debugLine="vue.AddCode($\"Dim tlItemfirstname As VMTimelineIte";
_vue._addcode /*String*/ (("Dim tlItemfirstname As VMTimelineItem"));
 //BA.debugLineNum = 86;BA.debugLine="vue.AddCode($\"tlItemfirstname.Initialize(vue, \"tlI";
_vue._addcode /*String*/ (("tlItemfirstname.Initialize(vue, \"tlItemfirstname\", Me)"));
 //BA.debugLineNum = 87;BA.debugLine="vue.AddCode($\"tlItemfirstname.SetColorintensity(\"b";
_vue._addcode /*String*/ (("tlItemfirstname.SetColorintensity(\"brown\",\"\")"));
 //BA.debugLineNum = 88;BA.debugLine="vue.AddCode($\"tlItemfirstname.SetLarge(True)\"$)";
_vue._addcode /*String*/ (("tlItemfirstname.SetLarge(True)"));
 //BA.debugLineNum = 89;BA.debugLine="vue.AddCode($\"tlItemfirstname.SetAvatar(\"./assets/";
_vue._addcode /*String*/ (("tlItemfirstname.SetAvatar(\"./assets/sponge.png\")"));
 //BA.debugLineNum = 90;BA.debugLine="vue.AddCode($\"tlItemfirstname.OppositeText.SetText";
_vue._addcode /*String*/ (("tlItemfirstname.OppositeText.SetText(\"Anele\")"));
 //BA.debugLineNum = 91;BA.debugLine="vue.AddCode($\"tltimeline1.AddTimeLineItem(tlItemfi";
_vue._addcode /*String*/ (("tltimeline1.AddTimeLineItem(tlItemfirstname)"));
 //BA.debugLineNum = 92;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 93;BA.debugLine="vue.AddCode($\"Dim tlItemsurname As VMTimelineItem\"";
_vue._addcode /*String*/ (("Dim tlItemsurname As VMTimelineItem"));
 //BA.debugLineNum = 94;BA.debugLine="vue.AddCode($\"tlItemsurname.Initialize(vue, \"tlIte";
_vue._addcode /*String*/ (("tlItemsurname.Initialize(vue, \"tlItemsurname\", Me)"));
 //BA.debugLineNum = 95;BA.debugLine="vue.AddCode($\"tlItemsurname.SetFilldot(True)\"$)";
_vue._addcode /*String*/ (("tlItemsurname.SetFilldot(True)"));
 //BA.debugLineNum = 96;BA.debugLine="vue.AddCode($\"tlItemsurname.SetIcon(\"mdi-plus\")\"$)";
_vue._addcode /*String*/ (("tlItemsurname.SetIcon(\"mdi-plus\")"));
 //BA.debugLineNum = 97;BA.debugLine="vue.AddCode($\"tlItemsurname.SetIconColorIntensity(";
_vue._addcode /*String*/ (("tlItemsurname.SetIconColorIntensity(vm.COLOR_RED, vm.INTENSITY_ACCENT4)"));
 //BA.debugLineNum = 98;BA.debugLine="vue.AddCode($\"tlItemsurname.SetSmall(True)\"$)";
_vue._addcode /*String*/ (("tlItemsurname.SetSmall(True)"));
 //BA.debugLineNum = 99;BA.debugLine="vue.AddCode($\"tlItemsurname.OppositeText.SetText(\"";
_vue._addcode /*String*/ (("tlItemsurname.OppositeText.SetText(\"Mbanga\")"));
 //BA.debugLineNum = 100;BA.debugLine="vue.AddCode($\"tltimeline1.AddTimeLineItem(tlItemsu";
_vue._addcode /*String*/ (("tltimeline1.AddTimeLineItem(tlItemsurname)"));
 //BA.debugLineNum = 101;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 102;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 103;BA.debugLine="vue.AddCode($\"'use cards\"$)";
_vue._addcode /*String*/ (("'use cards"));
 //BA.debugLineNum = 104;BA.debugLine="vue.AddCode($\"Dim tl3 As VMTimelineItem\"$)";
_vue._addcode /*String*/ (("Dim tl3 As VMTimelineItem"));
 //BA.debugLineNum = 105;BA.debugLine="vue.AddCode($\"tl3.Initialize(vue, \"tl3\", Me)\"$)";
_vue._addcode /*String*/ (("tl3.Initialize(vue, \"tl3\", Me)"));
 //BA.debugLineNum = 106;BA.debugLine="vue.AddCode($\"tl3.SetColor(vm.COLOR_ORANGE)\"$)";
_vue._addcode /*String*/ (("tl3.SetColor(vm.COLOR_ORANGE)"));
 //BA.debugLineNum = 107;BA.debugLine="vue.AddCode($\"tl3.SetFilldot(True)\"$)";
_vue._addcode /*String*/ (("tl3.SetFilldot(True)"));
 //BA.debugLineNum = 108;BA.debugLine="vue.AddCode($\"tl3.SetLeft(True)\"$)";
_vue._addcode /*String*/ (("tl3.SetLeft(True)"));
 //BA.debugLineNum = 109;BA.debugLine="vue.AddCode($\"tl3.UsesCard = True\"$)";
_vue._addcode /*String*/ (("tl3.UsesCard = True"));
 //BA.debugLineNum = 110;BA.debugLine="vue.AddCode($\"tl3.CardTitle.SetColorIntensity(vm.C";
_vue._addcode /*String*/ (("tl3.CardTitle.SetColorIntensity(vm.COLOR_purple, vm.INTENSITY_lighten2)"));
 //BA.debugLineNum = 111;BA.debugLine="vue.AddCode($\"tl3.CardTitle.AddIcon1(\"icx1\", \"mdi-";
_vue._addcode /*String*/ (("tl3.CardTitle.AddIcon1(\"icx1\", \"mdi-magnify\", CreateMap(\"dark\":True,\"size\":42,\"color\":\"white\"), Null, Array(\"mr-4\"))"));
 //BA.debugLineNum = 112;BA.debugLine="vue.AddCode($\"tl3.CardTitle.AddElement(\"ich1\", \"h2";
_vue._addcode /*String*/ (("tl3.CardTitle.AddElement(\"ich1\", \"h2\", \"Uses Card\", Null, Null, Array(\"display-1 white--text font-weight-light\"))"));
 //BA.debugLineNum = 113;BA.debugLine="vue.AddCode($\"'add 1 row with 1 column\"$)";
_vue._addcode /*String*/ (("'add 1 row with 1 column"));
 //BA.debugLineNum = 114;BA.debugLine="vue.AddCode($\"tl3.CardContainer.AddRows(1).AddColu";
_vue._addcode /*String*/ (("tl3.CardContainer.AddRows(1).AddColumns12"));
 //BA.debugLineNum = 115;BA.debugLine="vue.AddCode($\"Dim lblX As VMLabel = vm.CreateLabel";
_vue._addcode /*String*/ (("Dim lblX As VMLabel = vm.CreateLabel(\"\")"));
 //BA.debugLineNum = 116;BA.debugLine="vue.AddCode($\"lblX.SetParagraph.SetText(BANanoShar";
_vue._addcode /*String*/ (("lblX.SetParagraph.SetText(BANanoShared.LoremIpsum(1))"));
 //BA.debugLineNum = 117;BA.debugLine="vue.AddCode($\"tl3.CardContainer.AddComponent(1,1,l";
_vue._addcode /*String*/ (("tl3.CardContainer.AddComponent(1,1,lblX.ToString)"));
 //BA.debugLineNum = 118;BA.debugLine="vue.AddCode($\"tltimeline1.AddTimeLineItem(tl3)\"$)";
_vue._addcode /*String*/ (("tltimeline1.AddTimeLineItem(tl3)"));
 //BA.debugLineNum = 119;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 120;BA.debugLine="vue.AddCode($\"Dim tl4 As VMTimelineItem\"$)";
_vue._addcode /*String*/ (("Dim tl4 As VMTimelineItem"));
 //BA.debugLineNum = 121;BA.debugLine="vue.AddCode($\"tl4.Initialize(vue, \"tl4\", Me)\"$)";
_vue._addcode /*String*/ (("tl4.Initialize(vue, \"tl4\", Me)"));
 //BA.debugLineNum = 122;BA.debugLine="vue.AddCode($\"tl4.SetColor(vm.COLOR_PURPLE)\"$)";
_vue._addcode /*String*/ (("tl4.SetColor(vm.COLOR_PURPLE)"));
 //BA.debugLineNum = 123;BA.debugLine="vue.AddCode($\"tl4.SetFilldot(True)\"$)";
_vue._addcode /*String*/ (("tl4.SetFilldot(True)"));
 //BA.debugLineNum = 124;BA.debugLine="vue.AddCode($\"tl4.SetRight(True)\"$)";
_vue._addcode /*String*/ (("tl4.SetRight(True)"));
 //BA.debugLineNum = 125;BA.debugLine="vue.AddCode($\"tl4.SetSmall(True)\"$)";
_vue._addcode /*String*/ (("tl4.SetSmall(True)"));
 //BA.debugLineNum = 126;BA.debugLine="vue.AddCode($\"tl4.UsesCard = True\"$)";
_vue._addcode /*String*/ (("tl4.UsesCard = True"));
 //BA.debugLineNum = 127;BA.debugLine="vue.AddCode($\"tl4.CardTitle.SetColorIntensity(vm.C";
_vue._addcode /*String*/ (("tl4.CardTitle.SetColorIntensity(vm.COLOR_AMBER, vm.INTENSITY_lighten1)"));
 //BA.debugLineNum = 128;BA.debugLine="vue.AddCode($\"tl4.CardTitle.AddClass(\"justify-end\"";
_vue._addcode /*String*/ (("tl4.CardTitle.AddClass(\"justify-end\")"));
 //BA.debugLineNum = 129;BA.debugLine="vue.AddCode($\"tl4.CardTitle.AddElement(\"ich2\", \"h2";
_vue._addcode /*String*/ (("tl4.CardTitle.AddElement(\"ich2\", \"h2\", \"Uses Card 1\", Null, Null, Array(\"display-1 mr-4 white--text font-weight-light\"))"));
 //BA.debugLineNum = 130;BA.debugLine="vue.AddCode($\"tl4.CardTitle.AddIcon1(\"icx2\", \"mdi-";
_vue._addcode /*String*/ (("tl4.CardTitle.AddIcon1(\"icx2\", \"mdi-home-outline\", CreateMap(\"dark\":True,\"size\":42,\"color\":\"white\"), Null, Null)"));
 //BA.debugLineNum = 131;BA.debugLine="vue.AddCode($\"'add 1 row with 1 column\"$)";
_vue._addcode /*String*/ (("'add 1 row with 1 column"));
 //BA.debugLineNum = 132;BA.debugLine="vue.AddCode($\"tl4.CardContainer.AddRows(1).AddColu";
_vue._addcode /*String*/ (("tl4.CardContainer.AddRows(1).AddColumns12"));
 //BA.debugLineNum = 133;BA.debugLine="vue.AddCode($\"Dim lblX As VMLabel = vm.CreateLabel";
_vue._addcode /*String*/ (("Dim lblX As VMLabel = vm.CreateLabel(\"\")"));
 //BA.debugLineNum = 134;BA.debugLine="vue.AddCode($\"lblX.SetParagraph.SetText(BANanoShar";
_vue._addcode /*String*/ (("lblX.SetParagraph.SetText(BANanoShared.LoremIpsum(1))"));
 //BA.debugLineNum = 135;BA.debugLine="vue.AddCode($\"tl4.CardContainer.AddComponent(1,1,l";
_vue._addcode /*String*/ (("tl4.CardContainer.AddComponent(1,1,lblX.ToString)"));
 //BA.debugLineNum = 136;BA.debugLine="vue.AddCode($\"tltimeline1.AddTimeLineItem(tl4)\"$)";
_vue._addcode /*String*/ (("tltimeline1.AddTimeLineItem(tl4)"));
 //BA.debugLineNum = 137;BA.debugLine="vue.AddCode($\"'\"$)";
_vue._addcode /*String*/ (("'"));
 //BA.debugLineNum = 138;BA.debugLine="vue.AddCode($\"tltimeline1.AddToContainer(cont,1,1)";
_vue._addcode /*String*/ (("tltimeline1.AddToContainer(cont,1,1)"));
 //BA.debugLineNum = 139;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"timelinex\", \"Timeli";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modtimeline.getObject(),"timelinex","Timeline",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (2),(int) (1));
 //BA.debugLineNum = 144;BA.debugLine="Dim tlines As List = vue.NewList";
_tlines = new anywheresoftware.b4a.objects.collections.List();
_tlines = _vue._newlist /*anywheresoftware.b4a.objects.collections.List*/ ();
 //BA.debugLineNum = 145;BA.debugLine="tlines.Add(CreateMap(\"color\": \"red lighten-2\", \"i";
_tlines.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("color"),(Object)("red lighten-2"),(Object)("icon"),(Object)("mdi-star"),(Object)("title"),(Object)("AD ASTRA"),(Object)("year"),(Object)("2019")}).getObject()));
 //BA.debugLineNum = 146;BA.debugLine="tlines.add(CreateMap(\"color\": \"purple darken-1\",";
_tlines.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("color"),(Object)("purple darken-1"),(Object)("icon"),(Object)("mdi-book-variant"),(Object)("title"),(Object)("WEST WORLD"),(Object)("year"),(Object)("1973")}).getObject()));
 //BA.debugLineNum = 147;BA.debugLine="tlines.add(CreateMap(\"color\": \"green lighten-1\",";
_tlines.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("color"),(Object)("green lighten-1"),(Object)("icon"),(Object)("mdi-airballoon"),(Object)("title"),(Object)("ANNIHILATION"),(Object)("year"),(Object)("2018")}).getObject()));
 //BA.debugLineNum = 148;BA.debugLine="tlines.add(CreateMap(\"color\": \"indigo\", \"icon\": \"";
_tlines.Add((Object)(anywheresoftware.b4a.keywords.Common.createMap(new Object[] {(Object)("color"),(Object)("indigo"),(Object)("icon"),(Object)("mdi-buffer"),(Object)("title"),(Object)("CONTACT"),(Object)("year"),(Object)("1997")}).getObject()));
 //BA.debugLineNum = 150;BA.debugLine="vue.Setdata(\"tlines\", tlines)";
_vue._setdata /*b4j.example.bananovue*/ ("tlines",(Object)(_tlines.getObject()));
 //BA.debugLineNum = 152;BA.debugLine="Dim txtline As VMTimeline";
_txtline = new b4j.example.vmtimeline();
 //BA.debugLineNum = 153;BA.debugLine="txtline.Initialize(vue, \"txline\", Me)";
_txtline._initialize /*b4j.example.vmtimeline*/ (ba,_vue,"txline",modtimeline.getObject());
 //BA.debugLineNum = 155;BA.debugLine="txtline.SetAlignTop(True)";
_txtline._setaligntop /*b4j.example.vmtimeline*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 157;BA.debugLine="Dim titem As VMTimelineItem";
_titem = new b4j.example.vmtimelineitem();
 //BA.debugLineNum = 158;BA.debugLine="titem.Initialize(vue, \"\", Me)";
_titem._initialize /*b4j.example.vmtimelineitem*/ (ba,_vue,"",modtimeline.getObject());
 //BA.debugLineNum = 160;BA.debugLine="titem.Setvfor(\"(item, i)\", \"tlines\")";
_titem._setvfor /*b4j.example.vmtimelineitem*/ ("(item, i)","tlines");
 //BA.debugLineNum = 162;BA.debugLine="titem.SetKey(\"i\")";
_titem._setkey /*b4j.example.vmtimelineitem*/ ("i");
 //BA.debugLineNum = 164;BA.debugLine="titem.Bind(\":color\", \"item.color\")";
_titem._bind /*b4j.example.vmtimelineitem*/ (":color","item.color");
 //BA.debugLineNum = 166;BA.debugLine="titem.Bind(\":icon\", \"item.icon\")";
_titem._bind /*b4j.example.vmtimelineitem*/ (":icon","item.icon");
 //BA.debugLineNum = 168;BA.debugLine="titem.SetFillDot(True)";
_titem._setfilldot /*b4j.example.vmtimelineitem*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 170;BA.debugLine="titem.UsesCard = True";
_titem._usescard /*boolean*/  = anywheresoftware.b4a.keywords.Common.True;
 //BA.debugLineNum = 172;BA.debugLine="titem.Card.Bind(\":color\", \"item.color\")";
_titem._card /*b4j.example.vmcard*/ ._bind /*b4j.example.vmcard*/ (":color","item.color");
 //BA.debugLineNum = 174;BA.debugLine="titem.Card.SetDark(True)";
_titem._card /*b4j.example.vmcard*/ ._setdark /*b4j.example.vmcard*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 176;BA.debugLine="titem.CardTitle.AddClass(\"title\")";
_titem._cardtitle /*b4j.example.vmcardtitle*/ ._addclass /*b4j.example.vmcardtitle*/ ("title");
 //BA.debugLineNum = 178;BA.debugLine="titem.CardTitle.SetText(\"{{ item.title }}\")";
_titem._cardtitle /*b4j.example.vmcardtitle*/ ._settext /*b4j.example.vmcardtitle*/ ("{{ item.title }}");
 //BA.debugLineNum = 180;BA.debugLine="titem.CardText.SetColor(vm.COLOR_WHITE)";
_titem._cardtext /*b4j.example.vmcardtext*/ ._setcolor /*b4j.example.vmcardtext*/ (_vm._color_white /*String*/ );
 //BA.debugLineNum = 182;BA.debugLine="titem.CardText.SetTextColor(vm.COLOR_PRIMARY)";
_titem._cardtext /*b4j.example.vmcardtext*/ ._settextcolor /*b4j.example.vmcardtext*/ (_vm._color_primary /*String*/ );
 //BA.debugLineNum = 184;BA.debugLine="titem.CardText.SetText($\"<p>The movie was release";
_titem._cardtext /*b4j.example.vmcardtext*/ ._settext /*b4j.example.vmcardtext*/ (("<p>The movie was released in {{ item.year }})</p>"));
 //BA.debugLineNum = 186;BA.debugLine="titem.CardText.SetText($\"<p>${BANanoShared.LoremI";
_titem._cardtext /*b4j.example.vmcardtext*/ ._settext /*b4j.example.vmcardtext*/ (("<p>"+anywheresoftware.b4a.keywords.Common.SmartStringFormatter("",(Object)(_bananoshared._loremipsum /*String*/ (BA.NumberToString(1))))+"</p>"));
 //BA.debugLineNum = 188;BA.debugLine="Dim btn As VMButton = vm.CreateButton(\"btnx\", Me)";
_btn = _vm._createbutton /*b4j.example.vmbutton*/ ("btnx",modtimeline.getObject());
 //BA.debugLineNum = 189;BA.debugLine="btn.Bind(\":color\", \"item.color\")";
_btn._bind /*b4j.example.vmbutton*/ (":color","item.color");
 //BA.debugLineNum = 190;BA.debugLine="btn.Bind(\":key\", \"item.title\")";
_btn._bind /*b4j.example.vmbutton*/ (":key","item.title");
 //BA.debugLineNum = 191;BA.debugLine="btn.Bind(\":id\", \"item.title\")";
_btn._bind /*b4j.example.vmbutton*/ (":id","item.title");
 //BA.debugLineNum = 192;BA.debugLine="btn.AddClass(\"mx-0\")";
_btn._addclass /*b4j.example.vmbutton*/ ("mx-0");
 //BA.debugLineNum = 193;BA.debugLine="btn.SetOutlined(True)";
_btn._setoutlined /*b4j.example.vmbutton*/ (anywheresoftware.b4a.keywords.Common.True);
 //BA.debugLineNum = 194;BA.debugLine="btn.SetLabel(\"Watch\")";
_btn._setlabel /*b4j.example.vmbutton*/ ("Watch");
 //BA.debugLineNum = 195;BA.debugLine="titem.CardText.SetText(btn.ToString)";
_titem._cardtext /*b4j.example.vmcardtext*/ ._settext /*b4j.example.vmcardtext*/ (_btn._tostring /*String*/ ());
 //BA.debugLineNum = 198;BA.debugLine="txtline.AddTimeLineItem(titem)";
_txtline._addtimelineitem /*String*/ (_titem);
 //BA.debugLineNum = 200;BA.debugLine="txtline.AddToContainer(cont,3,1)";
_txtline._addtocontainer /*String*/ (_cont,(int) (3),(int) (1));
 //BA.debugLineNum = 204;BA.debugLine="vue.SourceCodeBuilder";
_vue._sourcecodebuilder /*String*/ ();
 //BA.debugLineNum = 205;BA.debugLine="vue.AddCode($\"'add timelines using v-for\"$)";
_vue._addcode /*String*/ (("'add timelines using v-for"));
 //BA.debugLineNum = 206;BA.debugLine="vue.AddCode($\"'create the details that each card w";
_vue._addcode /*String*/ (("'create the details that each card will be created from"));
 //BA.debugLineNum = 207;BA.debugLine="vue.AddCode($\"Dim tlines As List = vue.NewList\"$)";
_vue._addcode /*String*/ (("Dim tlines As List = vue.NewList"));
 //BA.debugLineNum = 208;BA.debugLine="vue.AddCode($\"tlines.Add(CreateMap(\"color\": \"red l";
_vue._addcode /*String*/ (("tlines.Add(CreateMap(\"color\": \"red lighten-2\", \"icon\": \"mdi-star\",\"title\":\"AD ASTRA\",\"year\":\"2019\"))"));
 //BA.debugLineNum = 209;BA.debugLine="vue.AddCode($\"tlines.add(CreateMap(\"color\": \"purpl";
_vue._addcode /*String*/ (("tlines.add(CreateMap(\"color\": \"purple darken-1\", \"icon\": \"mdi-book-variant\",\"title\":\"WEST WORLD\",\"year\":\"1973\"))"));
 //BA.debugLineNum = 210;BA.debugLine="vue.AddCode($\"tlines.add(CreateMap(\"color\": \"green";
_vue._addcode /*String*/ (("tlines.add(CreateMap(\"color\": \"green lighten-1\", \"icon\": \"mdi-airballoon\",\"title\":\"ANNIHILATION\",\"year\":\"2018\"))"));
 //BA.debugLineNum = 211;BA.debugLine="vue.AddCode($\"tlines.add(CreateMap(\"color\": \"indig";
_vue._addcode /*String*/ (("tlines.add(CreateMap(\"color\": \"indigo\", \"icon\": \"mdi-buffer\",\"title\":\"CONTACT\",\"year\":\"1997\"))"));
 //BA.debugLineNum = 212;BA.debugLine="vue.AddCode($\"'save the items to the state\"$)";
_vue._addcode /*String*/ (("'save the items to the state"));
 //BA.debugLineNum = 213;BA.debugLine="vue.AddCode($\"vue.Setdata(\"tlines\", tlines)\"$)";
_vue._addcode /*String*/ (("vue.Setdata(\"tlines\", tlines)"));
 //BA.debugLineNum = 214;BA.debugLine="vue.AddCode($\"'create the timeline\"$)";
_vue._addcode /*String*/ (("'create the timeline"));
 //BA.debugLineNum = 215;BA.debugLine="vue.AddCode($\"Dim txtline As VMTimeline\"$)";
_vue._addcode /*String*/ (("Dim txtline As VMTimeline"));
 //BA.debugLineNum = 216;BA.debugLine="vue.AddCode($\"txtline.Initialize(vue, \"txline\", Me";
_vue._addcode /*String*/ (("txtline.Initialize(vue, \"txline\", Me)"));
 //BA.debugLineNum = 217;BA.debugLine="vue.AddCode($\"'align on topp\"$)";
_vue._addcode /*String*/ (("'align on topp"));
 //BA.debugLineNum = 218;BA.debugLine="vue.AddCode($\"txtline.SetAlignTop(True)\"$)";
_vue._addcode /*String*/ (("txtline.SetAlignTop(True)"));
 //BA.debugLineNum = 219;BA.debugLine="vue.AddCode($\"'create a single timeline item that";
_vue._addcode /*String*/ (("'create a single timeline item that uses a v-for loop"));
 //BA.debugLineNum = 220;BA.debugLine="vue.AddCode($\"Dim titem As VMTimelineItem\"$)";
_vue._addcode /*String*/ (("Dim titem As VMTimelineItem"));
 //BA.debugLineNum = 221;BA.debugLine="vue.AddCode($\"titem.Initialize(vue, \"\", Me)\"$)";
_vue._addcode /*String*/ (("titem.Initialize(vue, \"\", Me)"));
 //BA.debugLineNum = 222;BA.debugLine="vue.AddCode($\"'for each item in tlines state\"$)";
_vue._addcode /*String*/ (("'for each item in tlines state"));
 //BA.debugLineNum = 223;BA.debugLine="vue.AddCode($\"titem.Setvfor(\"(item, i)\", \"tlines\")";
_vue._addcode /*String*/ (("titem.Setvfor(\"(item, i)\", \"tlines\")"));
 //BA.debugLineNum = 224;BA.debugLine="vue.AddCode($\"'the key is the index\"$)";
_vue._addcode /*String*/ (("'the key is the index"));
 //BA.debugLineNum = 225;BA.debugLine="vue.AddCode($\"titem.SetKey(\"i\")\"$)";
_vue._addcode /*String*/ (("titem.SetKey(\"i\")"));
 //BA.debugLineNum = 226;BA.debugLine="vue.AddCode($\"'get the color of each item\"$)";
_vue._addcode /*String*/ (("'get the color of each item"));
 //BA.debugLineNum = 227;BA.debugLine="vue.AddCode($\"titem.Bind(\":color\", \"item.color\")\"$";
_vue._addcode /*String*/ (("titem.Bind(\":color\", \"item.color\")"));
 //BA.debugLineNum = 228;BA.debugLine="vue.AddCode($\"'get the icon for each item\"$)";
_vue._addcode /*String*/ (("'get the icon for each item"));
 //BA.debugLineNum = 229;BA.debugLine="vue.AddCode($\"titem.Bind(\":icon\", \"item.icon\")\"$)";
_vue._addcode /*String*/ (("titem.Bind(\":icon\", \"item.icon\")"));
 //BA.debugLineNum = 230;BA.debugLine="vue.AddCode($\"'fill the dot\"$)";
_vue._addcode /*String*/ (("'fill the dot"));
 //BA.debugLineNum = 231;BA.debugLine="vue.AddCode($\"titem.SetFillDot(True)\"$)";
_vue._addcode /*String*/ (("titem.SetFillDot(True)"));
 //BA.debugLineNum = 232;BA.debugLine="vue.AddCode($\"'each timeline item uses a card\"$)";
_vue._addcode /*String*/ (("'each timeline item uses a card"));
 //BA.debugLineNum = 233;BA.debugLine="vue.AddCode($\"titem.UsesCard = True\"$)";
_vue._addcode /*String*/ (("titem.UsesCard = True"));
 //BA.debugLineNum = 234;BA.debugLine="vue.AddCode($\"'the complete color of the card\"$)";
_vue._addcode /*String*/ (("'the complete color of the card"));
 //BA.debugLineNum = 235;BA.debugLine="vue.AddCode($\"titem.Card.Bind(\":color\", \"item.colo";
_vue._addcode /*String*/ (("titem.Card.Bind(\":color\", \"item.color\")"));
 //BA.debugLineNum = 236;BA.debugLine="vue.AddCode($\"'make it dark\"$)";
_vue._addcode /*String*/ (("'make it dark"));
 //BA.debugLineNum = 237;BA.debugLine="vue.AddCode($\"titem.Card.SetDark(True)\"$)";
_vue._addcode /*String*/ (("titem.Card.SetDark(True)"));
 //BA.debugLineNum = 238;BA.debugLine="vue.AddCode($\"'define the title\"$)";
_vue._addcode /*String*/ (("'define the title"));
 //BA.debugLineNum = 239;BA.debugLine="vue.AddCode($\"titem.CardTitle.AddClass(\"title\")\"$)";
_vue._addcode /*String*/ (("titem.CardTitle.AddClass(\"title\")"));
 //BA.debugLineNum = 240;BA.debugLine="vue.AddCode($\"'use the title per each of the items";
_vue._addcode /*String*/ (("'use the title per each of the items"));
 //BA.debugLineNum = 241;BA.debugLine="vue.AddCode($\"titem.CardTitle.SetText(\"{{ item.tit";
_vue._addcode /*String*/ (("titem.CardTitle.SetText(\"{{ item.title }}\")"));
 //BA.debugLineNum = 242;BA.debugLine="vue.AddCode($\"'the background color of the card te";
_vue._addcode /*String*/ (("'the background color of the card text should be white"));
 //BA.debugLineNum = 243;BA.debugLine="vue.AddCode($\"titem.CardText.SetColor(vm.COLOR_WHI";
_vue._addcode /*String*/ (("titem.CardText.SetColor(vm.COLOR_WHITE)"));
 //BA.debugLineNum = 244;BA.debugLine="vue.AddCode($\"' the color of the text should be pr";
_vue._addcode /*String*/ (("' the color of the text should be prmary"));
 //BA.debugLineNum = 245;BA.debugLine="vue.AddCode($\"titem.CardText.SetTextColor(vm.COLOR";
_vue._addcode /*String*/ (("titem.CardText.SetTextColor(vm.COLOR_PRIMARY)"));
 //BA.debugLineNum = 246;BA.debugLine="vue.AddCode($\"'indicate the year of release\"$)";
_vue._addcode /*String*/ (("'indicate the year of release"));
 //BA.debugLineNum = 247;BA.debugLine="vue.AddCode($\"titem.CardText.SetText(~\"<p>The movi";
_vue._addcode /*String*/ (("titem.CardText.SetText(~\"<p>The movie was released in {{ item.year }})</p>\"~)"));
 //BA.debugLineNum = 248;BA.debugLine="vue.AddCode($\"'use some lorem ipsum\"$)";
_vue._addcode /*String*/ (("'use some lorem ipsum"));
 //BA.debugLineNum = 249;BA.debugLine="vue.AddCode($\"titem.CardText.SetText($\"<p>~{BANano";
_vue._addcode /*String*/ (("titem.CardText.SetText($\"<p>~{BANanoShared.LoremIpsum(1)}</p>\"~)"));
 //BA.debugLineNum = 250;BA.debugLine="vue.AddCode($\"'add a button\"$)";
_vue._addcode /*String*/ (("'add a button"));
 //BA.debugLineNum = 251;BA.debugLine="vue.AddCode($\"Dim btn As VMButton = vm.CreateButto";
_vue._addcode /*String*/ (("Dim btn As VMButton = vm.CreateButton(\"btnx\", Me)"));
 //BA.debugLineNum = 252;BA.debugLine="vue.AddCode($\"btn.Bind(\":color\", \"item.color\")\"$)";
_vue._addcode /*String*/ (("btn.Bind(\":color\", \"item.color\")"));
 //BA.debugLineNum = 253;BA.debugLine="vue.AddCode($\"btn.Bind(\":key\", \"item.title\")\"$)";
_vue._addcode /*String*/ (("btn.Bind(\":key\", \"item.title\")"));
 //BA.debugLineNum = 254;BA.debugLine="vue.AddCode($\"btn.Bind(\":id\", \"item.title\")\"$)";
_vue._addcode /*String*/ (("btn.Bind(\":id\", \"item.title\")"));
 //BA.debugLineNum = 255;BA.debugLine="vue.AddCode($\"btn.AddClass(\"mx-0\")\"$)";
_vue._addcode /*String*/ (("btn.AddClass(\"mx-0\")"));
 //BA.debugLineNum = 256;BA.debugLine="vue.AddCode($\"btn.SetOutlined(True)\"$)";
_vue._addcode /*String*/ (("btn.SetOutlined(True)"));
 //BA.debugLineNum = 257;BA.debugLine="vue.AddCode($\"btn.SetLabel(\"Watch\")\"$)";
_vue._addcode /*String*/ (("btn.SetLabel(\"Watch\")"));
 //BA.debugLineNum = 258;BA.debugLine="vue.AddCode($\"titem.CardText.SetText(btn.ToString)";
_vue._addcode /*String*/ (("titem.CardText.SetText(btn.ToString)"));
 //BA.debugLineNum = 259;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 260;BA.debugLine="vue.AddCode($\"'add the item to the timeline\"$)";
_vue._addcode /*String*/ (("'add the item to the timeline"));
 //BA.debugLineNum = 261;BA.debugLine="vue.AddCode($\"txtline.AddTimeLineItem(titem)\"$)";
_vue._addcode /*String*/ (("txtline.AddTimeLineItem(titem)"));
 //BA.debugLineNum = 262;BA.debugLine="vue.AddCode($\"\"$)";
_vue._addcode /*String*/ ((""));
 //BA.debugLineNum = 263;BA.debugLine="vue.AddCode($\"'Trap button clicks and get the id o";
_vue._addcode /*String*/ (("'Trap button clicks and get the id of the clicked button"));
 //BA.debugLineNum = 264;BA.debugLine="vue.AddCode($\"Sub btnx_click(e As BANanoEvent)\"$)";
_vue._addcode /*String*/ (("Sub btnx_click(e As BANanoEvent)"));
 //BA.debugLineNum = 265;BA.debugLine="vue.AddCode($\"'get the id of the selected button\"$";
_vue._addcode /*String*/ (("'get the id of the selected button"));
 //BA.debugLineNum = 266;BA.debugLine="vue.AddCode($\"Dim btnID As String = vm.GetIDFromEv";
_vue._addcode /*String*/ (("Dim btnID As String = vm.GetIDFromEvent(e)"));
 //BA.debugLineNum = 267;BA.debugLine="vue.AddCode($\"'show the button id\"$)";
_vue._addcode /*String*/ (("'show the button id"));
 //BA.debugLineNum = 268;BA.debugLine="vue.AddCode($\"vm.ShowSnackBarSuccess(btnID)\"$)";
_vue._addcode /*String*/ (("vm.ShowSnackBarSuccess(btnID)"));
 //BA.debugLineNum = 269;BA.debugLine="vue.AddCode($\"End Sub\"$)";
_vue._addcode /*String*/ (("End Sub"));
 //BA.debugLineNum = 270;BA.debugLine="pgIndex.CreateVBCode(vue, Me, \"dynamictimeline\", \"";
_pgindex._createvbcode /*b4j.example.vmprism*/ (_vue,modtimeline.getObject(),"dynamictimeline","Dynamic Timeline",_vue._getsourcecode /*String*/ ())._addtocontainer /*String*/ (_cont,(int) (4),(int) (1));
 //BA.debugLineNum = 273;BA.debugLine="vm.AddContainer(cont)";
_vm._addcontainer /*String*/ (_cont);
 //BA.debugLineNum = 275;BA.debugLine="End Sub";
return "";
}
public static String  _dynamictimelinecopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 294;BA.debugLine="Sub dynamictimelinecopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 295;BA.debugLine="vue.CopyCode2Clipboard(\"dynamictimeline\")";
_vue._copycode2clipboard /*String*/ ("dynamictimeline");
 //BA.debugLineNum = 296;BA.debugLine="End Sub";
return "";
}
public static String  _dynamictimelinedownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 298;BA.debugLine="Sub dynamictimelinedownload_click(e As BANanoEvent";
 //BA.debugLineNum = 299;BA.debugLine="vue.DownloadCode(\"dynamictimeline\", \"dynamictimel";
_vue._downloadcode /*String*/ ("dynamictimeline","dynamictimeline.txt");
 //BA.debugLineNum = 300;BA.debugLine="End Sub";
return "";
}
public static String  _process_globals() throws Exception{
 //BA.debugLineNum = 2;BA.debugLine="Sub Process_Globals";
 //BA.debugLineNum = 3;BA.debugLine="Public name As String = \"timeLineCode\"";
_name = "timeLineCode";
 //BA.debugLineNum = 4;BA.debugLine="Public title As String = \"TimeLine\"";
_title = "TimeLine";
 //BA.debugLineNum = 5;BA.debugLine="Private vm As BANanoVM";
_vm = new b4j.example.bananovm();
 //BA.debugLineNum = 6;BA.debugLine="Private vue As BANanoVue";
_vue = new b4j.example.bananovue();
 //BA.debugLineNum = 7;BA.debugLine="Private BANano As BANano";
_banano = new com.ab.banano.BANano();
 //BA.debugLineNum = 8;BA.debugLine="End Sub";
return "";
}
public static String  _timelinexcopy_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 284;BA.debugLine="Sub timelinexcopy_click(e As BANanoEvent)";
 //BA.debugLineNum = 285;BA.debugLine="vue.CopyCode2Clipboard(\"timelinex\")";
_vue._copycode2clipboard /*String*/ ("timelinex");
 //BA.debugLineNum = 286;BA.debugLine="End Sub";
return "";
}
public static String  _timelinexdownload_click(com.ab.banano.BANanoEvent _e) throws Exception{
 //BA.debugLineNum = 288;BA.debugLine="Sub timelinexdownload_click(e As BANanoEvent)";
 //BA.debugLineNum = 289;BA.debugLine="vue.DownloadCode(\"timelinex\", \"timelinex.txt\")";
_vue._downloadcode /*String*/ ("timelinex","timelinex.txt");
 //BA.debugLineNum = 290;BA.debugLine="End Sub";
return "";
}
}
